import {chromium} from '@playwright/test';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'assets/spyder/evidence/packaged-controls',base=process.env.BASE_URL||'http://127.0.0.1:5214';await mkdir(out,{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']}),p=await b.newPage({viewport:{width:1600,height:1000}}),r={errors:[],missing:[],vehicles:[],cameras:[]};p.on('pageerror',e=>r.errors.push(e.message));p.on('response',x=>{if(x.status()>=400)r.missing.push(x.url())});
const ready=()=>p.waitForFunction(()=>window.__EXPRESS?.ready||window.__SIGNATURE?.ready,null,{timeout:180000});
const step=async(keys,n,raster=10)=>p.evaluate(([keys,n,raster])=>{const h=window.__EXPRESS;h.setDeviceSample({keys,pads:[],focused:true});let s;for(let i=0;i<n;i++){s=h.normalFrame(window.frameNow,i%raster===0||i===n-1);window.frameNow+=1000/60}return s},[keys,n,raster]);
try{
 for(const [visual,id] of [['2026','slingshot-r-2024'],['ryker','can-am-ryker-900'],['spyder','can-am-spyder-f3']].filter(x=>!process.env.ONLY||x[0]===process.env.ONLY)){
  await p.goto(base+`/?scene=signature&screen=build&visual=${visual}&test=1&profile=1`);await ready();const showroom=await p.evaluate(()=>window.__SIGNATURE.inspect());assert.equal(showroom.recipe.vehicleId,id);
  await p.locator('[data-action=test-drive]').click();await p.waitForURL('**/?scene=express**',{timeout:120000});const url=new URL(p.url());url.searchParams.set('test','1');url.searchParams.set('profile','1');url.searchParams.set('clock','controlled');url.searchParams.set('captureBuffer','1');await p.goto(url.href);await ready();await p.evaluate(()=>window.frameNow=0);
  await p.locator('#start-crew').click();if(await p.locator('.film-skip').isVisible())await p.locator('.film-skip').click();const spawn=await step([],180),drive=await step(['ArrowUp'],120),stop=await step(['ArrowDown'],180);await step(['KeyX'],2);await step([],2);const reverse=await step(['ArrowUp'],90);
  assert.ok(drive.telemetry.speed>5);assert.ok(Math.abs(stop.telemetry.speed)<.4);assert.equal(reverse.telemetry.gear,-1);assert.ok(reverse.telemetry.speed<-.5);assert.equal(drive.recipe.vehicleId,id);await p.screenshot({path:`${out}/${visual}-road.png`});
  const item={visual,showroom,spawn,drive,stop,reverse};r.vehicles.push(item);
  if(visual==='spyder'){
   await step(['ArrowDown'],180);for(let i=0;i<4;i++){const s=await step(['KeyC'],1);await step([],30);r.cameras.push(await p.evaluate(()=>window.__EXPRESS.inspect()));if(r.cameras.at(-1).camera.view==='cockpit'){assert.equal(r.cameras.at(-1).visual.driver.headVisible,false);assert.ok(r.cameras.at(-1).mirrors.updates.every(x=>x>0));}await p.screenshot({path:`${out}/camera-${i}.png`});}
   const previous=await p.evaluate(()=>window.__EXPRESS.inspect());item.recovered=await step(['KeyR'],90);await step([],20);assert.notEqual(item.recovered.attemptId,previous.attemptId);assert.ok(Math.abs(item.recovered.telemetry.speed)<.5);
   const png=await p.evaluate(()=>window.__EXPRESS.referenceCamera('player',[0,1.25,.38],[0,.8,-.75]));await writeFile(out+'/instrument.png',Buffer.from(png.split(',')[1],'base64'));
  }
  await step(['Escape'],1);await step([],1);await p.locator('[data-action=bay]').click();await p.waitForURL('**/?scene=signature**',{timeout:120000});const urlBack=new URL(p.url());urlBack.searchParams.set('test','1');urlBack.searchParams.set('profile','1');await p.goto(urlBack.href);await ready();item.returned=await p.evaluate(()=>window.__SIGNATURE.inspect());assert.equal(item.returned.recipe.vehicleId,id);
  await writeFile(out+'/report.json',JSON.stringify(r));console.log(visual+' ordinary controls PASS');
 }
 // The actual challenge judge receives frequent rendered telemetry, without result injection.
 await p.goto(base+'/?scene=express&route=harbor&play=preview&visual=spyder&mode=test&challenge=harbor-sprint&test=1&profile=1&clock=controlled');await ready();await p.addScriptTag({content:await readFile('.tools/ryker-agent/agent.js','utf8')});await p.evaluate(()=>{window.frameNow=0;window.last=0;window.driver=new window.CrewEvidence.EvidenceDriver(window.__EXPRESS.route)});await p.locator('#start-crew').click();if(await p.locator('.film-skip').isVisible())await p.locator('.film-skip').click();
 for(let block=0;block<20;block++){const phase=await p.evaluate(()=>{const h=window.__EXPRESS;for(let i=0;i<300;i++){const s=h.lightweight(),dt=Math.max(0,s.telemetry.time-window.last);window.last=s.telemetry.time;h.setDeviceSample(s.race.phase==='running'?window.driver.sample(s.telemetry,s.field,dt):window.CrewEvidence.toDevice());h.normalFrame(window.frameNow,i%3===0);window.frameNow+=1000/60;const phase=document.querySelector('.gx-chal')?.dataset.phase;if(phase==='done'||phase==='failed')return phase}return document.querySelector('.gx-chal')?.dataset.phase});if(phase==='done'||phase==='failed'){r.challengePhase=phase;break}}
 await p.waitForTimeout(1100);r.challenge={state:await p.evaluate(()=>window.__EXPRESS.inspect()),phase:await p.locator('.gx-chal').getAttribute('data-phase'),text:await p.locator('.gx-chal-result').innerText(),stored:await p.evaluate(()=>Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.includes('challenge'))))};await p.screenshot({path:out+'/challenge.png'});assert.equal(r.challengePhase,'done');assert.match(JSON.stringify(r.challenge.stored),/can-am-spyder-f3/);await p.goto(base+'/?scene=signature&visual=spyder&test=1&profile=1');await ready();await p.locator('[data-gx-log]').first().click();await p.locator('[data-tab=records]').click();r.tourLog=await p.locator('.gx-options').innerText();assert.match(r.tourLog,/Spyder/);await p.screenshot({path:out+'/tour-log.png'});await p.locator('[data-opt=close]').click();
 assert.deepEqual(r.errors,[]);assert.deepEqual(r.missing,[]);r.status='PASS';
}catch(e){r.status='FAIL';r.failure=e.stack;console.error(e);await p.screenshot({path:out+'/failure.png'}).catch(()=>{})}finally{await writeFile(out+'/report.json',JSON.stringify(r));await b.close();console.log(JSON.stringify({status:r.status,failure:r.failure}))}
