import {chromium} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';const out='assets/spyder/evidence/audio';await mkdir(out,{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']}),p=await b.newPage({viewport:{width:1440,height:900}}),r={errors:[],samples:[],method:'Live native-clock game master recording; no microphone or system audio, no injected tones. Browser speaker output muted, graph recording active. Synthesized inline-three, not an OEM recording.'};p.on('pageerror',e=>r.errors.push(e.message));
try{
 await p.goto((process.env.BASE_URL||'http://127.0.0.1:5213')+'/?scene=express&route=harbor&mode=test&play=preview&visual=spyder&test=1&profile=1');await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:180000});await p.locator('#enable-sound').click();await p.waitForFunction(()=>window.__EXPRESS.inspect().audio.enabled);await p.locator('#start-crew').click();if(await p.locator('.film-skip').isVisible())await p.locator('.film-skip').click();await p.waitForTimeout(3300);
 await p.evaluate(()=>window.__EXPRESS.setDeviceSample({keys:[],pads:[],focused:true}));await p.locator('#race-pause').click();await p.locator('#start-crew').waitFor({state:'visible'});await p.keyboard.press('o');await p.locator('[data-mix=audio-music]').press('Home');await p.locator('[data-opt=close]').click();await p.locator('#start-crew').click();await p.evaluate(()=>window.__EXPRESS.startAudioCapture());
 for(const [name,keys,n] of [['idle',[],2],['accelerate',['ArrowUp'],6],['brake',['ArrowDown'],4],['release',[],1],['reverse-switch',['KeyX'],.1],['reverse',['ArrowUp'],3],['stop',['ArrowDown'],3]]){
  await p.evaluate(keys=>window.__EXPRESS.setDeviceSample({keys,pads:[],focused:true}),keys);for(let i=0;i<Math.ceil(n*2);i++){await p.waitForTimeout(n<.5?n*1000:500);r.samples.push({phase:name,state:await p.evaluate(()=>{const s=window.__EXPRESS.inspect();return{telemetry:s.telemetry,audio:s.audio,display:s.display}})});}
 }
 await p.evaluate(()=>window.__EXPRESS.setDeviceSample({keys:[],pads:[],focused:true}));const audio=await p.evaluate(()=>window.__EXPRESS.stopAudioCapture());await writeFile(out+'/spyder-live.webm',Buffer.from(audio.base64,'base64'));delete audio.base64;r.capture=audio;
 await p.evaluate(()=>window.__EXPRESS.setDeviceSample({keys:[],pads:[],focused:true}));await p.locator('#race-pause').click();await p.locator('#start-crew').waitFor({state:'visible'});await p.keyboard.press('o');await p.locator('[data-opt=mute]').click();await p.locator('[data-opt=close]').click();await p.locator('#start-crew').click();await p.waitForTimeout(600);r.muted=await p.evaluate(()=>window.__EXPRESS.inspect().audio);assert.equal(r.muted.graph.masterTarget,0);assert.ok(r.muted.graph.rms<.001);
 await p.evaluate(()=>window.__EXPRESS.setDeviceSample({keys:[],pads:[],focused:true}));await p.locator('#race-pause').click();await p.locator('#start-crew').waitFor({state:'visible'});await p.keyboard.press('o');await p.locator('[data-opt=mute]').click();await p.locator('[data-tab=gameplay]').click();await p.locator('[data-opt=difficulty][data-value=hard]').click();await p.locator('[data-opt=close]').click();await p.locator('#start-crew').click();r.options=await p.evaluate(()=>({difficulty:localStorage.getItem('slingmods-gx-difficulty'),audio:window.__EXPRESS.inspect().audio}));
 assert.ok(r.samples.some(x=>x.state.audio.graph.rms>.005));assert.ok(r.samples.some(x=>x.state.telemetry.gear>=2));assert.ok(r.samples.some(x=>x.state.telemetry.gear===-1));assert.ok(r.samples.every(x=>x.state.audio.soundTreatment==='synthesized-inline-three-SE6'));assert.equal(r.options.difficulty,'hard');assert.deepEqual(r.errors,[]);r.status='PASS';
}catch(e){r.status='FAIL';r.failure=e.stack;console.error(e);await p.screenshot({path:out+'/failure.png'}).catch(()=>{})}finally{await writeFile(out+'/report.json',JSON.stringify(r));await b.close();console.log(JSON.stringify({status:r.status,failure:r.failure}))}
