from pathlib import Path
R=Path(__file__).resolve().parents[2]
def edit(path,changes):
 p=R/path;s=p.read_text(encoding='utf-8')
 for a,b in changes:
  if a not in s:raise ValueError((path,a[:100]))
  s=s.replace(a,b)
 p.write_text(s,encoding='utf-8')
edit('src/signature/config.ts',[("import {validRykerBuild", "import {freshSpyderBuild,validSpyderBuild,SPYDER_PRODUCTS,type SpyderBuild} from './spyder-catalog';\nimport {validRykerBuild"),("{ryker?:RykerBuild;version:1|2;", "{spyder?:SpyderBuild;ryker?:RykerBuild;version:1|2|3;"),("'slingshot-r-2024'|'can-am-ryker-900'","'slingshot-r-2024'|'can-am-ryker-900'|'can-am-spyder-f3'"),("definitionId?:'ryker-900-v1'","definitionId?:'ryker-900-v1'|'spyder-f3-v1'"),("|'ryker-road-v1'", "|'ryker-road-v1'|'spyder-f3-v1'"),("r.version===1&&r.vehicleId", "r.version===1&&r.handlingProfile!=='spyder-f3-v1'&&r.vehicleId"),("Object.keys(r.products??{}).length===0))", "Object.keys(r.products??{}).length===0)||(r.version===3&&r.vehicleId==='can-am-spyder-f3'&&r.definitionId==='spyder-f3-v1'&&r.handlingProfile==='spyder-f3-v1'&&Object.keys(r.products??{}).length===0&&validSpyderBuild(r.spyder)))"),("'slingmods-sport-v5','ryker-road-v1'", "'slingmods-sport-v5','ryker-road-v1','spyder-f3-v1'"),(" if(r.ryker!==undefined", " if(r.spyder!==undefined&&(r.vehicleId!=='can-am-spyder-f3'||!validSpyderBuild(r.spyder)))throw Error('Unsupported Spyder equipment');\n if(r.vehicleId==='can-am-spyder-f3'&&r.ryker!==undefined)throw Error('Ryker equipment cannot fit Spyder');\n if(r.ryker!==undefined"),("export const freshRykerRecipe", "export const freshSpyderRecipe=():BuildRecipe=>({...freshRecipe(),version:3,vehicleId:'can-am-spyder-f3',definitionId:'spyder-f3-v1',handlingProfile:'spyder-f3-v1',spyder:freshSpyderBuild()});\nexport const freshRykerRecipe"),("=>id==='ryker-road-v1'?", "=>id==='spyder-f3-v1'?'Spyder F3 v1 · 6-speed · Auto shift assist':id==='ryker-road-v1'?"),("products:{},...(recipe.ryker?", "products:{},...(recipe.spyder?{spyder:freshSpyderBuild()}:{}),...(recipe.ryker?"),("handlingProfile:recipe.vehicleId==='can-am-ryker-900'?", "handlingProfile:recipe.vehicleId==='can-am-spyder-f3'?'spyder-f3-v1':recipe.vehicleId==='can-am-ryker-900'?"),(" if(r.vehicleId==='can-am-ryker-900')return", " if(r.vehicleId==='can-am-spyder-f3')return ['Can-Am Spyder F3 Custom — 2023 reference',...SPYDER_PRODUCTS.filter(p=>r.spyder?.parts[p.id]).map(p=>p.name+' / '+p.option+'\\n'+p.url)].join('\\n\\n');\n if(r.vehicleId==='can-am-ryker-900')return"),("private vehicle=CURRENT_VEHICLE_CONTEXT.visual==='ryker'?", "private vehicle=CURRENT_VEHICLE_CONTEXT.visual==='spyder'?'spyder':CURRENT_VEHICLE_CONTEXT.visual==='ryker'?"),("const r=validateRecipe(recipe);if(this.vehicle==='ryker')", "const r=validateRecipe(recipe);if(this.vehicle==='spyder'){if(r.vehicleId!=='can-am-spyder-f3')throw Error('Select the matching vehicle to load this build');return r}if(this.vehicle==='ryker')"),("return this.vehicle==='ryker'?freshRykerRecipe()", "return this.vehicle==='spyder'?freshSpyderRecipe():this.vehicle==='ryker'?freshRykerRecipe()"),("return this.vehicle==='ryker'?key+'-ryker':key", "return this.vehicle==='spyder'?key+'-spyder':this.vehicle==='ryker'?key+'-ryker':key")])
edit('src/presentation/suspension.ts',[("if(isRyker(car))","if(isRyker(car)||!!car.getObjectByName('spyder_foundation'))"),("value=value&&!isRyker(this.car)","value=value&&!isRyker(this.car)&&!this.car.getObjectByName('spyder_foundation')")])
edit('src/presentation/product.ts',[("static async load(loader:GLTFLoader,chassis:THREE.Object3D,scene:THREE.Scene){", "static async load(loader:GLTFLoader,chassis:THREE.Object3D,scene:THREE.Scene){if(chassis.getObjectByName('spyder_foundation'))return new ProductPresenter(new THREE.Group(),chassis,scene,{lightOrigins:[],vehicle:'spyder',product:'SM-18631'});")])
edit('src/simulation/index.ts',[("...(this.drivetrain instanceof RykerCVT?", "...(this.drivetrain instanceof SpyderSE6?{vehicleId:this.definition.id,definitionId:this.definition.revision,powertrain:this.definition.powertrain}:{}),...(this.drivetrain instanceof RykerCVT?")])
edit('src/express.ts',[("if((recipe.vehicleId==='can-am-ryker-900')!==(CURRENT_VEHICLE_CONTEXT.visual==='ryker'))", "if((recipe.vehicleId==='can-am-spyder-f3'?'spyder':recipe.vehicleId==='can-am-ryker-900'?'ryker':'2026')!==(CURRENT_VEHICLE_CONTEXT.visual==='spyder'?'spyder':CURRENT_VEHICLE_CONTEXT.visual==='ryker'?'ryker':'2026'))"),("recipe.vehicleId==='can-am-ryker-900'?'ryker':'2026'", "recipe.vehicleId==='can-am-spyder-f3'?'spyder':recipe.vehicleId==='can-am-ryker-900'?'ryker':'2026'"),("vehicle:recipe.vehicleId==='can-am-ryker-900'?'Ryker':'Slingshot'", "vehicle:recipe.vehicleId==='can-am-spyder-f3'?'Spyder':recipe.vehicleId==='can-am-ryker-900'?'Ryker':'Slingshot'")])
edit('src/signature/drive-preparation.ts',[("const shared=recipe.vehicleId==='can-am-ryker-900'?", "const shared=recipe.vehicleId==='can-am-spyder-f3'?['/assets/spyder/spyder-f3.glb','/assets/spyder/driver-attachment.json','/assets/spyder/rear-rig.json',riderAssetURL(),'/assets/brand/slingmods-sign.glb']:recipe.vehicleId==='can-am-ryker-900'?")])
edit('src/signature/ui.ts',[("const ryker=CURRENT", "const spyder=CURRENT_VEHICLE_CONTEXT.visual==='spyder';\nconst ryker=CURRENT"),("const categories=ryker?", "const categories=spyder?['Paint','Build Presets']:ryker?"),("s.recipe.vehicleId!=='can-am-ryker-900'", "s.recipe.vehicleId==='slingshot-r-2024'"),("this.state.recipe.vehicleId!=='can-am-ryker-900'", "this.state.recipe.vehicleId==='slingshot-r-2024'"),("(ryker?RYKER_PRESETS:PRESETS)", "(spyder?[]:ryker?RYKER_PRESETS:PRESETS)")])
# Six-speed synthesis uses its own firing-frequency oscillator and never a CVT/sample or Thermal bed.
edit('src/audio/graph.ts',[("p.powertrain==='cvt'&&!sampledRyker?", "(p.powertrain==='six-speed'||p.powertrain==='cvt'&&!sampledRyker)?"),("p.powertrain==='cvt'&&!sampledRyker&&layer.name.startsWith('engine-')", "(p.powertrain==='six-speed'||p.powertrain==='cvt'&&!sampledRyker)&&layer.name.startsWith('engine-')"),("sportTreatment&&p.powertrain!=='cvt'?", "sportTreatment&&p.powertrain!=='cvt'&&p.powertrain!=='six-speed'?"),("engine:last?.powertrain==='cvt'?", "engine:last?.powertrain==='six-speed'?'Synthesized 1330 inline-three, RPM/load/shift driven':last?.powertrain==='cvt'?"),("if(shift&&!p.reset", "if(shift&&p.powertrain!=='six-speed'&&!p.reset")])
edit('src/audio/game-audio.ts',[("if(enabled)this.director?.play", "if(enabled&&this.last?.powertrain!=='six-speed')this.director?.play"),("beginDeparture(equipped:boolean){this.director?.duck(6);this.director?.play", "beginDeparture(equipped:boolean){this.director?.duck(6);if(this.last?.powertrain!=='six-speed')this.director?.play")])
