from pathlib import Path
R=Path(__file__).resolve().parents[2]
def edit(path,changes):
 p=R/path;s=p.read_text(encoding='utf-8')
 for a,b in changes:
  if a not in s:raise ValueError((path,a[:100]))
  s=s.replace(a,b)
 p.write_text(s,encoding='utf-8')
edit('src/simulation/index.ts',[("import {SpyderSE6}","import {freshSpyderBuild,validSpyderBuild,spyderThrottle,type SpyderBuild} from '../signature/spyder-catalog';\nimport {SpyderSE6}"),("  private elka=false;", "  private spyder:SpyderBuild=freshSpyderBuild();\n  configureSpyder(build:SpyderBuild){if(this.time!==0||this.definition.powertrain!=='six-speed'||!validSpyderBuild(build))throw Error('Valid Spyder configuration required before driving');this.spyder=structuredClone(build)}\n  private elka=false;"),("suspensionConfig(){return this.definition.powertrain==='cvt'?", "suspensionConfig(){return this.definition.powertrain==='six-speed'?{vehicle:this.definition.id,build:structuredClone(this.spyder),calibration:'game-estimated'}:this.definition.powertrain==='cvt'?"),("    const driveState=this.drivetrain.step", "    if(this.definition.powertrain==='six-speed')this.throttle=spyderThrottle(this.throttle,this.spyder);\n    const driveState=this.drivetrain.step"),("      if(this.definition.powertrain==='cvt'){", "      if(this.definition.powertrain==='six-speed'){if(contact&&this.spyder.parts[rear?'rear':'front']){const setup=rear?this.spyder.rear:this.spyder.front,vertical=dot(pointVel,up),d=(rear?3500:2050)*(.8+.4*(vertical>0?setup.rebound:setup.compression));load=clamp(k*(restLength-length+setup.preload*.012)-d*vertical,0,weight*4.5)}if(contact&&length<.035)load+=Math.min(weight*2,(.035-length)*80000)}else if(this.definition.powertrain==='cvt'){"),("this.definition.powertrain==='six-speed'?3600", "this.definition.powertrain==='six-speed'?(this.spyder.parts.sway?5000:3600)"),("fade*(this.definition.powertrain==='cvt'?.40:1)","fade*(this.definition.powertrain==='six-speed'?.55:this.definition.powertrain==='cvt'?.40:1)"),("(this.definition.powertrain==='cvt'?.30:.43)","(this.definition.powertrain==='six-speed'?.36:this.definition.powertrain==='cvt'?.30:.43)")])
edit('src/presentation/vehicle-materials.ts',[("=>car.getObjectByName('vehicle_root')?.userData.materialBindingsVersion===1", "=>car.getObjectByName('vehicle_root')?.userData.materialBindingsVersion===1||!!car.getObjectByName('spyder_foundation')")])
edit('src/presentation/signature-art.ts',[("import {RykerProducts}","import {SpyderProducts} from './spyder-products';\nimport type {SpyderBuild} from '../signature/spyder-catalog';\nimport type {Appearance} from '../career/catalog';\nimport {RykerProducts}"),(" private ryker?:RykerProducts;", " private spyder?:SpyderProducts;private ryker?:RykerProducts;"),("if(car.getObjectByName('spyder_foundation'))return new SignatureProducts(car,new THREE.Group());", "if(car.getObjectByName('spyder_foundation')){const result=new SignatureProducts(car,new THREE.Group());result.spyder=new SpyderProducts(car,(await loader.loadAsync('/assets/spyder/spyder-products.glb')).scene);return result}"),("set(ids:Iterable<string>,ryker?:RykerBuild){if(this.car.getObjectByName('spyder_foundation'))return;", "set(ids:Iterable<string>,ryker?:RykerBuild,spyder?:SpyderBuild,lights?:Appearance){if(this.car.getObjectByName('spyder_foundation')){this.spyder?.set(spyder,lights);return;}"),("inspect(){return{ryker:", "inspect(){return{spyder:this.spyder?.inspect(),ryker:"),("dispose(){if(this.ryker)", "dispose(){this.spyder?.dispose();if(this.ryker)")])
for path in ['src/express.ts','src/signature/scene.ts']:
 p=R/path;s=p.read_text(encoding='utf-8');s=s.replace('accessories.set(Object.keys(recipe.products),recipe.ryker)','accessories.set(Object.keys(recipe.products),recipe.ryker,recipe.spyder,recipe.lights)').replace('accessories.set(Object.keys(shown.products),shown.ryker)','accessories.set(Object.keys(shown.products),shown.ryker,shown.spyder,shown.lights)')
 if path.endswith('express.ts'):s=s.replace("if(recipe.vehicleId==='can-am-ryker-900')world.get('player').configureRykerSuspension(!!recipe.ryker?.shocks);", "if(recipe.vehicleId==='can-am-ryker-900')world.get('player').configureRykerSuspension(!!recipe.ryker?.shocks);if(recipe.spyder)world.get('player').configureSpyder(recipe.spyder);")
 else:
  s=s.replace("simulation.reset({x:0,z:0,y:0,yaw:0});if(recipe.vehicleId", "simulation.reset({x:0,z:0,y:0,yaw:0});if(recipe.spyder)simulation.configureSpyder(recipe.spyder);if(recipe.vehicleId")
  s=s.replace("simulation.configureSuspension(shown.products", "if(shown.spyder)simulation.configureSpyder(shown.spyder);simulation.configureSuspension(shown.products")
  s=s.replace("if(hero.asset.getObjectByName('ryker_foundation')){camera", "if(hero.asset.getObjectByName('spyder_foundation')){camera.position.set(-.65,1.65,.80);controls.target.set(0,1.02,-.2)}else if(hero.asset.getObjectByName('ryker_foundation')){camera")
  s=s.replace("wheelRadius:recipe.vehicleId==='can-am-ryker-900'?.2848:undefined", "wheelRadius:recipe.spyder?.32355:recipe.vehicleId==='can-am-ryker-900'?.2848:undefined").replace("wheelbase:recipe.vehicleId==='can-am-ryker-900'?1.709:undefined", "wheelbase:recipe.vehicleId!=='slingshot-r-2024'?1.709:undefined").replace("if(recipe.vehicleId==='can-am-ryker-900'&&'pose' in hero.rear)","if(recipe.vehicleId!=='slingshot-r-2024'&&'pose' in hero.rear)")
 p.write_text(s,encoding='utf-8')
