"""One-time source edits with exact-match guards; retained as change provenance."""
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def edit(path,changes):
 p=R/path;s=p.read_text(encoding='utf-8')
 for a,b in changes:
  if a not in s:raise ValueError((path,a[:100]))
  s=s.replace(a,b)
 p.write_text(s,encoding='utf-8')
edit('src/simulation/vehicle-definition.ts',[("import slingshot", "import spyder from '../../public/assets/spyder/manifest.json';\nimport slingshot"),("'slingshot-r-2024'|'can-am-ryker-900'","'slingshot-r-2024'|'can-am-ryker-900'|'can-am-spyder-f3'"),("'five-speed'|'cvt'","'five-speed'|'cvt'|'six-speed'"),("export const vehicleDefinition=(id:VehicleId)=>id==='can-am-ryker-900'?RYKER_DEFINITION:SLINGSHOT_DEFINITION;","""export const SPYDER_DEFINITION=immutable<VehicleDefinition>({id:'can-am-spyder-f3',revision:'spyder-f3-v1',powertrain:'six-speed',layout:{wheelbase:spyder.wheelbase,wheels:structuredClone(spyder.wheels)},mass:508,comHeight:.51,inertia:[178,202,88],chassis:[.31,.13,.83],chassisOffset:[0,-.23,0],frontSpring:27000,rearSpring:47000,restLength:.115,rearRestLength:.125,travel:.065});
export function vehicleDefinition(id:VehicleId):VehicleDefinition {switch(id){case 'slingshot-r-2024':return SLINGSHOT_DEFINITION;case 'can-am-ryker-900':return RYKER_DEFINITION;case 'can-am-spyder-f3':return SPYDER_DEFINITION;default:throw Error('Unknown vehicle: '+id)}}""")])
edit('src/simulation/profile.ts',[("|'ryker-road-v1';","|'ryker-road-v1'|'spyder-f3-v1';"),("export const HANDLING_PROFILES={","export const HANDLING_PROFILES={\n 'spyder-f3-v1':{id:'spyder-f3-v1',name:'Spyder F3 Road v1',torqueScale:1,shiftSeconds:.22,steerLock:.60,steerFalloff:.018,lateralSteerLimit:7.8,steerRate:2.9,asphaltGripScale:1.06,tireStiffness:8.5,brakeScale:1,brakeSteerRelief:0,damperFront:2050,damperRear:3500},"),("id==='ryker-road-v1'?","(id==='ryker-road-v1'||id==='spyder-f3-v1')?")])
edit('src/simulation/index.ts',[("import {RykerCVT}","import {SpyderSE6} from './spyder-se6';\nimport {RykerCVT}"),("'five-speed'|'cvt'","'five-speed'|'cvt'|'six-speed'"),("private drivetrain:AutoDrive|RykerCVT;","private drivetrain:AutoDrive|RykerCVT|SpyderSE6;"),("definition.powertrain==='cvt'?new RykerCVT():new AutoDrive(profileId)","definition.powertrain==='six-speed'?new SpyderSE6():definition.powertrain==='cvt'?new RykerCVT():new AutoDrive(profileId)"),("this.definition.powertrain==='cvt'&&setup","this.definition.powertrain!=='five-speed'&&setup"),("||this.profileId==='ryker-road-v1'","||this.profileId==='ryker-road-v1'||this.profileId==='spyder-f3-v1'"),("||profileId==='ryker-road-v1'","||profileId==='ryker-road-v1'||profileId==='spyder-f3-v1'"),("this.definition.powertrain==='cvt'?.25:.18","this.definition.powertrain==='six-speed'?.23:this.definition.powertrain==='cvt'?.25:.18"),("this.definition.powertrain==='cvt'?2600:5500","this.definition.powertrain==='six-speed'?3600:this.definition.powertrain==='cvt'?2600:5500")])
edit('src/presentation/vehicle-context.ts',[("|'ryker';","|'ryker'|'spyder';"),("'R'|'Ryker 900'","'R'|'Ryker 900'|'Spyder F3'"),(" if(visual==='ryker')"," if(visual==='spyder')return {year:2023,model:'Spyder F3',visual,rollHoops:'none',label:'Can-Am Spyder F3 Custom',controls:'1330 inline-three · 6-speed / reverse · auto-shift game assist'};\n if(visual==='ryker')")])
edit('src/presentation/vehicle-asset.ts',[("if(recipe?.version===2", "if(recipe?.version===3&&recipe.vehicleId==='can-am-spyder-f3')requested='spyder';else if(recipe?.version===2"),("||v==='ryker'","||v==='ryker'||v==='spyder'"),("CURRENT_VEHICLE=VEHICLE_VISUAL==='ryker'?","CURRENT_VEHICLE=VEHICLE_VISUAL==='spyder'?'spyder-f3.glb':VEHICLE_VISUAL==='ryker'?"),("CURRENT_REAR_RIG=VEHICLE_VISUAL==='ryker'?","CURRENT_REAR_RIG=VEHICLE_VISUAL==='spyder'?'/assets/spyder/rear-rig.json':VEHICLE_VISUAL==='ryker'?"),("CURRENT_DRIVER_ATTACHMENT=VEHICLE_VISUAL==='ryker'?","CURRENT_DRIVER_ATTACHMENT=VEHICLE_VISUAL==='spyder'?'/assets/spyder/driver-attachment.json':VEHICLE_VISUAL==='ryker'?"),("CURRENT_VEHICLE_URL=VEHICLE_VISUAL==='ryker'?","CURRENT_VEHICLE_URL=VEHICLE_VISUAL==='spyder'?'/assets/spyder/spyder-f3.glb':VEHICLE_VISUAL==='ryker'?")])
edit('src/presentation/hero.ts',[("import {isRyker", "import {isSpyder,SpyderMotion} from './spyder';\nimport {isRyker"),("if(!isRyker(asset.scene))restore", "if(!isRyker(asset.scene)&&!isSpyder(asset.scene))restore"),("if(!isRyker(asset.scene)||!options.rivals)","if((!isRyker(asset.scene)&&!isSpyder(asset.scene))||!options.rivals)"),("const ryker=isRyker(car)?new RykerMotion(car):undefined;","const ryker=isSpyder(car)?new SpyderMotion(car):isRyker(car)?new RykerMotion(car):undefined;")])
edit('src/presentation/ryker-selection.ts',[("['ryker','Can-Am Ryker 900']","['ryker','Can-Am Ryker 900'],['spyder','Spyder F3 Custom']"),("(VEHICLE_VISUAL==='ryker'?'ryker':'2026')","(VEHICLE_VISUAL==='spyder'?'spyder':VEHICLE_VISUAL==='ryker'?'ryker':'2026')")])
edit('src/presentation/powered-display.ts',[("if(car.getObjectByName('ryker_foundation'))","if(car.getObjectByName('ryker_foundation')||car.getObjectByName('spyder_foundation'))")])
edit('src/demo/profile.ts',[("['josh','legacy','2026','ryker']","['josh','legacy','2026','ryker','spyder']")])
edit('src/presentation/signature-art.ts',[("static async load(loader:GLTFLoader,car:THREE.Object3D){if(isRyker(car))", "static async load(loader:GLTFLoader,car:THREE.Object3D){if(car.getObjectByName('spyder_foundation'))return new SignatureProducts(car,new THREE.Group());if(isRyker(car))"),("set(ids:Iterable<string>,ryker?:RykerBuild){", "set(ids:Iterable<string>,ryker?:RykerBuild){if(this.car.getObjectByName('spyder_foundation'))return;"),("isRyker(this.car)&&finish==='blue-orange'", "(isRyker(this.car)||!!this.car.getObjectByName('spyder_foundation'))&&finish==='blue-orange'")])
# Stop Slingshot product loaders from adding irrelevant parts to the new chassis.
edit('src/presentation/suspension.ts',[("if(car.getObjectByName('ryker_foundation'))", "if(car.getObjectByName('ryker_foundation')||car.getObjectByName('spyder_foundation'))")])
