from pathlib import Path
R=Path(__file__).resolve().parents[2]
def edit(path,changes):
 p=R/path;s=p.read_text(encoding='utf-8')
 for a,b in changes:
  if a not in s:raise ValueError((path,a[:100]))
  s=s.replace(a,b)
 p.write_text(s,encoding='utf-8')
edit('src/career-experience/model.ts',[("import {RYKER_PRODUCTS", "import {SPYDER_PRODUCTS,type SpyderPart,type SpyderBuild} from '../signature/spyder-catalog';\nimport {freshSpyderRecipe} from '../signature/config';\nimport {RYKER_PRODUCTS"),("|'can-am-ryker-900'","|'can-am-ryker-900'|'can-am-spyder-f3'"),("export interface OwnBuild {", "export interface OwnBuild {spyder?:{recipe:BuildRecipe;owned:SpyderPart[]};"),("export function careerRecipe(s:Career):BuildRecipe {", "export function careerRecipe(s:Career):BuildRecipe {if(s.ownBuild.vehicle==='can-am-spyder-f3')return validateRecipe(s.ownBuild.spyder?.recipe??freshSpyderRecipe());"),("['slingshot-r-2024','can-am-ryker-900']", "['slingshot-r-2024','can-am-ryker-900','can-am-spyder-f3']"),(" if(s.ryker){", " if(s.spyder){const r=validateRecipe(s.spyder.recipe);if(r.vehicleId!=='can-am-spyder-f3'||!Array.isArray(s.spyder.owned)||new Set(s.spyder.owned).size!==s.spyder.owned.length||s.spyder.owned.some(id=>!SPYDER_PRODUCTS.some(p=>p.id===id))||Object.entries(r.spyder!.parts).some(([id,on])=>on&&!s.spyder!.owned.includes(id as SpyderPart)))return fail()}\n if(s.ryker){"),("export type OwnBuildCommand=", "export type OwnBuildCommand={type:'chapter-spyder-purchase';id:string;part:SpyderPart}|{type:'chapter-spyder-equip';part:SpyderPart;equipped:boolean}|{type:'chapter-spyder-style';finish?:FinishId;lights?:Appearance;settings?:SpyderBuild}|"),("b.vehicle=c.vehicle;if(c.vehicle==='can-am-ryker-900')", "b.vehicle=c.vehicle;if(c.vehicle==='can-am-spyder-f3')b.spyder??={recipe:freshSpyderRecipe(),owned:[]};if(c.vehicle==='can-am-ryker-900')"),(" if(c.type==='chapter-ryker-purchase'", """ if(c.type==='chapter-spyder-purchase'||c.type==='chapter-spyder-equip'||c.type==='chapter-spyder-style'){
  if(b.vehicle!=='can-am-spyder-f3'||!b.spyder)throw Error('Select the Spyder in your career garage');const r=b.spyder;
  if(c.type==='chapter-spyder-style'){const candidate=validateRecipe({...r.recipe,...(c.finish?{finish:c.finish}:{}),...(c.lights?{lights:c.lights}:{}),...(c.settings?{spyder:c.settings}:{})});if(Object.entries(candidate.spyder!.parts).some(([id,on])=>on&&!r.owned.includes(id as SpyderPart)))throw Error('Owned Spyder equipment required');r.recipe=candidate;return {changed:true}}
  const part=SPYDER_PRODUCTS.find(p=>p.id===c.part);if(!part)throw Error('Unknown Spyder part or variant');
  if(c.type==='chapter-spyder-equip'){if(!r.owned.includes(c.part)||typeof c.equipped!=='boolean')throw Error('Owned Spyder part required');r.recipe.spyder!.parts[c.part]=c.equipped;return {changed:true}}
  if(!uuid(c.id))throw Error('Purchase identity required');if(r.owned.includes(c.part))return {changed:false};if(s.receipts[c.id])throw Error('Transaction identity already used');if(s.credits<part.credits)throw Error(`${part.credits} game credits required`);s.credits-=part.credits;r.owned.push(c.part);r.recipe.spyder!.parts[c.part]=true;return {changed:true,receipt:{id:c.id,kind:'spyder-purchase',amount:-part.credits,balance:s.credits,first:true,at,productId:c.part}};
 }
 if(c.type==='chapter-ryker-purchase'""")])
edit('src/career/store.ts',[("import ", "import ",),("export interface Receipt", "import {SPYDER_PRODUCTS} from '../signature/spyder-catalog';\nexport interface Receipt"),("|'ryker-purchase'", "|'ryker-purchase'|'spyder-purchase'"),("'chapter-purchase','ryker-purchase'", "'chapter-purchase','ryker-purchase','spyder-purchase'"),("  if(receipt.kind==='ryker-purchase'", "  if(receipt.kind==='spyder-purchase'){const p=SPYDER_PRODUCTS.find(p=>p.id===receipt.productId);if(!p||receipt.amount!==-p.credits||!s.ownBuild.spyder?.owned.includes(p.id))return fail()}\n  if(receipt.kind==='ryker-purchase'"),(" for(const part of s.ownBuild.ryker?.owned", " for(const part of s.ownBuild.spyder?.owned??[])if(!Object.values(s.receipts).some((r:any)=>r.kind==='spyder-purchase'&&r.productId===part))return fail();\n for(const part of s.ownBuild.ryker?.owned")])
for f in ['src/career-experience/chapter-one-race.ts','src/career-experience/race-adapter.ts']:
 edit(f,[("recipe.vehicleId==='can-am-ryker-900'?'ryker':'2026'", "recipe.vehicleId==='can-am-spyder-f3'?'spyder':"+('attempt.' if f.endswith('race-adapter.ts') else '')+"recipe.vehicleId==='can-am-ryker-900'?'ryker':'2026'")])
edit('src/career-experience/race-adapter.ts',[("attempt!.recipe.vehicleId!=='can-am-ryker-900'", "attempt!.recipe.vehicleId==='slingshot-r-2024'")])
edit('src/career/client.ts',[("visual==='ryker'||visual==='2026'", "visual==='spyder'||visual==='ryker'||visual==='2026'"),("vehicle:visual==='ryker'?", "vehicle:visual==='spyder'?'can-am-spyder-f3':visual==='ryker'?"),("(VEHICLE_VISUAL==='ryker')!==(state.ownBuild.vehicle==='can-am-ryker-900')", "(VEHICLE_VISUAL==='spyder'?'spyder':VEHICLE_VISUAL==='ryker'?'ryker':'2026')!==(state.ownBuild.vehicle==='can-am-spyder-f3'?'spyder':state.ownBuild.vehicle==='can-am-ryker-900'?'ryker':'2026')"),("state.ownBuild.vehicle==='can-am-ryker-900'?'ryker':'2026');", "state.ownBuild.vehicle==='can-am-spyder-f3'?'spyder':state.ownBuild.vehicle==='can-am-ryker-900'?'ryker':'2026');")])
