import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {bindDrivingHero} from '../../src/presentation/hero';import {disposeGraph} from '../../src/presentation/scene-lifetime';import {RaceWorld} from '../../src/simulation';import {SLINGSHOT_DEFINITION,RYKER_DEFINITION,SPYDER_DEFINITION} from '../../src/simulation/vehicle-definition';
const scene=new THREE.Scene();scene.background=new THREE.Color('#252a33');const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(1);document.body.append(renderer.domElement);const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,100);camera.position.set(8,5,-9);camera.lookAt(0,.8,0);scene.add(new THREE.HemisphereLight(0xffffff,0x596477,3));const sun=new THREE.DirectionalLight(0xffeedd,3);sun.position.set(3,7,-4);scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshStandardMaterial({color:0x444851,roughness:.8}));ground.rotation.x=-Math.PI/2;ground.position.y=-.01;scene.add(ground);
const report:any={cycles:[],errors:[]},loader=new GLTFLoader();
async function cycle(n:number){const world=await RaceWorld.create({ground:{center:[0,-.5,0],size:[100,1,100]},obstacles:[],ramps:[],surfaceAt:()=>({id:'asphalt',mu:1.05,rolling:.014})}),heroes:any[]=[];const configs=[['/assets/model02/slingshot-2026.glb','/assets/model02','/assets/drivers/tour-rider/tour-rider.glb',SLINGSHOT_DEFINITION,'slingmods-sport-v5'],['/assets/ryker/complete/ryker-900-complete.glb','/assets/ryker','/assets/drivers/tour-rider/tour-rider.glb',RYKER_DEFINITION,'ryker-road-v1'],['/assets/spyder/spyder-f3.glb','/assets/spyder','/assets/spyder/spyder-rider.glb',SPYDER_DEFINITION,'spyder-f3-v1']] as const;
 for(let i=0;i<3;i++){const [url,dir,rider,definition,tune]=configs[i];const [car,person,attachment,rig]=await Promise.all([loader.loadAsync(url),loader.loadAsync(rider),fetch(dir+'/driver-attachment.json').then(r=>r.json()),fetch(dir+'/rear-rig.json').then(r=>r.json())]);car.scene.userData.assetURL=url;const hero=bindDrivingHero(car.scene,person.scene,attachment,rig);heroes.push(hero);scene.add(hero.root);world.addVehicle(String(i),{x:(i-1)*3.4,z:0},definition,tune);}
 const coast={throttle:0,brake:0,steer:0,reverse:false};for(let i=0;i<180;i++)world.step({'0':coast,'1':coast,'2':coast});heroes.forEach((h,i)=>h.pose(world.get(String(i)).telemetry(),1/60,false,true));renderer.render(scene,camera);const entry={resident:{...renderer.info.memory},visuals:heroes.map(h=>h.inspectVisual()),definitions:configs.map(c=>c[3].id),png:n===0?renderer.domElement.toDataURL():undefined};
 // Different controls in a shared physical world must not drive another instance's rig.
 for(let i=0;i<120;i++){world.step({'0':coast,'1':{...coast,throttle:.6},'2':{...coast,throttle:.3,steer:.2}});heroes.forEach((h,j)=>h.pose(world.get(String(j)).telemetry(),1/60,false));}renderer.render(scene,camera);(entry as any).moving=heroes.map(h=>h.inspectVisual());(entry as any).field=world.telemetry();
 for(const h of heroes){scene.remove(h.root);disposeGraph(h.root)}world.dispose();renderer.renderLists.dispose();renderer.render(scene,camera);(entry as any).disposed={...renderer.info.memory};report.cycles.push(entry);
}
try{for(let i=0;i<3;i++)await cycle(i);report.status='PASS'}catch(e){report.status='FAIL';report.failure=String(e)}(window as any).__MIXED=report;
