import {chromium} from '@playwright/test';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'assets/spyder/evidence/roads';await mkdir(out,{recursive:true});const source=await readFile('.tools/ryker-agent/agent.js','utf8'),assembled=JSON.parse(await readFile(process.env.ASSEMBLED_REPORT||'assets/spyder/evidence/assembled-final/report.json','utf8'));
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']}),p=await b.newPage({viewport:{width:1600,height:1000}}),report={errors:[],missing:[],runs:[],method:'Actual controls, frozen validated recipes and complete production laps. Controlled simulation clock accelerates evidence only; this is not a performance test.'};p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.missing.push({url:r.url(),status:r.status()})});
try{
 for(const build of ['stock','equipped'])for(const route of ['harbor','express','ridge']){
  const recipe=structuredClone(assembled[build].recipe);const url=(process.env.BASE_URL||'http://127.0.0.1:5213')+`/?scene=express&route=${route}&play=preview&visual=spyder&mode=race&trial=1&test=1&profile=1&clock=controlled&captureBuffer=1#build=`+encodeURIComponent(JSON.stringify(recipe));
  await p.goto(url);await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:180000});await p.addScriptTag({content:source});await p.evaluate(()=>{window.driver=new window.CrewEvidence.EvidenceDriver(window.__EXPRESS.route);window.frameNow=0;window.last=0});await p.locator('#start-crew').click();if(await p.locator('.film-skip').isVisible())await p.locator('.film-skip').click();
  let state;for(let block=0;block<42;block++){state=await p.evaluate(()=>{const h=window.__EXPRESS;let s;for(let i=0;i<600;i++){const b=h.lightweight(),dt=Math.max(0,b.telemetry.time-window.last);window.last=b.telemetry.time;h.setDeviceSample(b.race.phase==='running'?window.driver.sample(b.telemetry,b.field,dt):window.CrewEvidence.toDevice());s=h.normalFrame(window.frameNow,i===599);window.frameNow+=1000/60;if(s.race.playerResult)break}return s});if(block===1)await p.screenshot({path:`${out}/${build}-${route}.png`});if(state.race.playerResult)break}
  await p.evaluate(()=>{window.__EXPRESS.setDeviceSample(window.CrewEvidence.toDevice());window.__EXPRESS.normalFrame(window.frameNow,true);window.frameNow+=1000/60});assert.ok(state.race.playerResult?.valid,`${build} ${route} must finish validly`);assert.deepEqual(state.recipe,recipe);const stored=await p.evaluate(()=>JSON.parse(localStorage.getItem('slingmods-gx-time-attack-v1')??'{}'));assert.ok(Object.entries(stored).some(([k,v])=>k.startsWith(route+':can-am-spyder-f3|')&&v.ghost?.length>8),'saved build-specific ghost required');report.runs.push({build,route,state,stored});console.log(JSON.stringify({build,route,result:state.race.playerResult}));await writeFile(out+'/report.json',JSON.stringify(report));
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.missing,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);await p.screenshot({path:out+'/failure.png'}).catch(()=>{})}finally{await writeFile(out+'/report.json',JSON.stringify(report));await b.close()}

