import pathlib,json,hashlib,datetime,re
R=pathlib.Path(__file__).resolve().parents[2];E=R/'assets/spyder/evidence'
def read(p):return json.loads((E/p).read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
build=json.loads((R/'demo-current.json').read_text());checks=[]
def check(id,evidence,observed,limitations=None):
 for p in evidence:assert (R/p).exists(),p
 checks.append({'id':id,'status':'PASS','evidence':evidence,'observed':observed,'limitations':limitations or []})
def ep(*names):return ['assets/spyder/evidence/'+n for n in names]
for n in ['assembled-final/report.json','packaged-controls/report.json','packaged-roads-final/report.json','career-final/report.json','mixed/report.json','audio/report.json','departure/report.json','delivery-smoke/report.json','delivery-smoke/package-server.json','build-equivalence.json']:assert read(n)['status']=='PASS',n
assert 'pass 457' in (E/'full-tests-final.log').read_text(encoding='utf-8-sig');assert (E/'typecheck.log').stat().st_size==0
performance=read('performance-final/report.json');assert len(performance['runs'])==3 and all(r['status']=='PASS' for r in performance['runs'])
validator=read('gltf-validator.json');assert all(r['issues']['numErrors']==0 for r in validator.values())
check('S01',ep('source-hashes-final.log','source-preflight.json'),{'sourceHashesMatched':14,'kitHashesMatched':53,'servedPrivateFiles':0,'packagingEnforcesExclusion':True})
check('S02',ep('source-import.json','source-import.log','components.json'),{'nativeBlender':'4.5.2 LTS','autoexecDisabled':True,'sourceObjects':36,'sourceTriangleEquivalents':4923405,'removed':'Only two-triangle Plane02 floor','processing':'Uniform metric calibration, semantic island partition, selective decimation; staged tire material dependency fix; UV artwork retained'},['Legacy reflection/alpha interpretation was repaired for PBR.'])
check('S03',ep('matched'),{'views':['hero','left','right','rear','cockpit','seat','wheel'],'modes':['clay','pbr'],'sourceFinalImages':28,'actualBlenderGeometry':True,'visualInspection':'All matched views inspected; final cockpit and assembled in-game views also inspected.'})
check('S04',['public/assets/spyder/manifest.json','assets/spyder/PHYSICS.md']+ep('reimport.json'),{'units':'metres','frame':'Y up, -Z forward','uniformScale':.008541972297919004,'wheelbase':1.709,'frontTrack':1.371638,'tireRadius':.323549837},['Custom donor dimensions differ from nominal OEM tires; visual year unverified.'])
check('S05',['tests/spyder-rig.test.ts','public/assets/spyder/rear-rig.json']+ep('rig-tests.log','assembled-final/report.json'),{'steeringExtremes':[-.6,.6],'spins':'Forward and reverse','travel':'Independent left/right/front/rear','rig':'Calipers, fenders and stationary light rings steer but do not spin; rims and rotors spin; bars follow steering; stock returns on removal'},['Suspension linkage presentation is approximate, not CAD kinematics.'])
check('S06',ep('basic-glb.json','gltf-validator.json','reimport.json'),{'validatorErrors':{n:r['issues']['numErrors'] for n,r in validator.items()},'validatorWarnings':{n:r['issues']['numWarnings'] for n,r in validator.items()},'cleanNativeReimport':'PASS','vehicleTriangles':957915,'productTriangles':31892,'riderTriangles':44595},['124 rider tangent/non-root skin warnings retained; actual runtime pose and render tested.'])
check('R01',ep('packaged-controls/report.json'),{'normalGXSelectionAndRoadFlow':'All three vehicles','Spyder':'Throttle, braking, complete stop, safe reverse, recovery and garage return PASS'})
check('R02',['src/simulation/spyder-se6.ts','tests/spyder-physics.test.ts']+ep('full-tests-final.log','cockpit/report.json'),{'powertrain':'Independent six-speed + reverse','redlineRPM':8100,'reverse':'Speed/brake interlock','display':'Actual telemetry gear/RPM/speed; two live dials'},['Automatic shifting is a game assist; gear ratios are explicit estimates.'])
check('R03',['tests/spyder-physics.test.ts','tests/spyder-suspension.test.ts']+ep('full-tests-final.log','packaged-controls/report.json'),{'fixtures':['spawn','slalom','trail brake','stop','2.4 m corridor','7 cm one-wheel bump','12 cm ramp','barrier/reverse recovery'],'forces':'Finite nonnegative loaded contact channels; upright checks and actual fixture engagement asserted'},['Keyboard/controller-input automation and physics fixtures, not human handling evaluation.'])
check('R04',ep('assembled-final/report.json','cockpit/report.json','departure/report.json','rider-background-check.png'),{'hands':'Sub-millimetre tall-grip contact at both extremes and travel','feet':'Anchored','gloves':'Visually intact','cockpit':'Head and fittings hidden; actual mirrors, LCD and speed/RPM needles','departure':'Ordinary animated bay exit reaches existing road'},['Two background wall rings were checked with rider hidden; no floating helmet geometry defect.'])
check('P01',['src/signature/spyder-catalog.ts','tests/spyder-physics.test.ts','assets/spyder/PRODUCT-REFERENCES.md']+ep('full-tests-final.log'),{'responseOnly':True,'modes':['Eco','City','Sport','Sport+'],'endpointsInvariant':True,'noPeakPowerBonus':True})
check('P02',['tests/spyder-suspension.test.ts','public/assets/spyder/product-mounts.json']+ep('assembled-final/front-shock.png','full-tests-final.log'),{'frontStage4':'Manual preload/rebound/low-speed compression; black/red geometry','rearIsolation':'PASS'})
check('P03',['tests/spyder-suspension.test.ts','public/assets/spyder/product-mounts.json']+ep('assembled-final/rear-shock.png','full-tests-final.log'),{'rearStage4':'Independent manual preload/rebound/low-speed compression','frontIsolation':'PASS','hydraulicOrHighSpeedControls':False})
check('P04',['src/simulation/index.ts','tests/spyder-suspension.test.ts','assets/spyder/PRODUCT-REFERENCES.md']+ep('full-tests-final.log'),{'assembly':'ULTRA bar and required compatible links form one dependency bundle','effect':'Conservative bounded front support redistribution, total unchanged, rear unchanged, no tire-grip bonus'},['Visible bars/links approximate the purchased assembly; not a CAD linkage solver.'])
check('P05',['assets/spyder/PRODUCT-REFERENCES.md','public/assets/spyder/product-mounts.json']+ep('surface-mounts.json','assembled-final/lights.png','full-tests-final.log'),{'mountedStrips':8,'locations':['inner grilles','above headlamp pods','side tubes','lower arms'],'patterns':['steady','pulse'],'physicsEffect':0},['Custom fit uses measured donor surfaces; documented year/trim conditions do not certify real installation.'])
check('P06',ep('ring-clearance.json','assembled-final/ring.png','rig-tests.log','full-tests-final.log'),{'option':'Standalone front wheel-light kit','stationary':True,'supportsSteeringTravel':True,'physicsEffect':0,'sampledClearanceMetresApproximately':.0301},['Sampled rigid mesh clearance, not physical fit or deformation certification.'])
check('P07',ep('assembled-final/report.json','packaged-roads-final/report.json')+['assets/spyder/PRODUCT-REFERENCES.md'],{'eachProduct':'Install/remove/reinstall and stock restoration','savedCombinedRecipe':'Reload identical','combinedBuildRoads':3,'actualCatalogURLs':6})
check('G01',['tests/spyder-state.test.ts']+ep('full-tests-final.log','packaged-controls/report.json'),{'namespaces':'Independent three-vehicle draft/build and ownership','invalidCrossVehicleProduct':'Rejected','oldSaves':'Preserved by additive migration tests; owner profiles never touched'})
check('G02',ep('packaged-roads-final/report.json'),{'runs':6,'routes':['Harbor','Harbor Express','Ridge'],'builds':['stock','all six upgrades'],'validFullLaps':6,'sameRendererAndAsset':True})
check('G03',ep('career-final/report.json'),{'event':'harbor-shakedown-standing-lap-v1','validLapMs':78312.79374498046,'legitimateReward':800,'pedalCommanderCost':550,'remainingCredits':250,'onceOnlyAndReload':'PASS','injectedCreditsOrFinish':False})
check('G04',ep('packaged-controls/report.json','performance-final/report.json','audio/report.json')+['tests/spyder-state.test.ts'],{'challenge':'Genuine Harbor Sprint completion recorded in Tour Log','timeAttack':'Dense native-rate Spyder ghost persisted/reloaded','identity':'Vehicle, definition, tune, assist and functional build settings separated','difficultyOptions':'Hard applied','achievementCompatibility':'Additive Spyder records preserve established progress'},['Conservative driver did not earn Harbor Sprint bronze; shared Tour targets retained, every top medal/chapter/build/device not exhaustively completed.'])
check('G05',ep('mixed/report.json','mixed/three-vehicles.png','packaged-controls/report.json'),{'mixedWorld':'Three definitions and separate actual vehicle/rider rigs','cycles':3,'resident':{'geometries':499,'textures':45},'disposedEachCycle':{'geometries':1,'textures':1},'controls':'Different simultaneous inputs and independent motion'})
check('G06',ep('full-tests-final.log','packaged-controls/report.json','performance-final/report.json'),{'testsPassed':457,'existingVehicles':'Ordinary road drive/brake/reverse/garage-return smokes and full native Harbor laps','RykerProducts':'Existing assembly/mod/career/lighting tests preserved','SlingshotRykerPhysicsInputChanges':'None intended; independent Spyder branch'})
check('A01',ep('audio/report.json','audio/spyder-live.webm','audio/astats.log','departure/report.json'),{'engine':'Original inline-three synthesis','follows':['RPM','load','shift','reverse'],'options':['mute','unmute','music level','difficulty'],'peakDBFS':-8.201240,'rmsDBFS':-17.926332,'nan':0,'inf':0,'captureSecondsApproximately':19.74},['No authentic engine recording or human listening approval claimed.'])
check('B01',ep('delivery-smoke/report.json','delivery-smoke/package-server.json','build-equivalence.json','full-tests-final.log','typecheck.log','build-final.log','packaged-controls/report.json','packaged-roads-final/report.json','performance-final/report.json'),{'tests':'457/457','typecheck':'PASS','productionBuild':'PASS','packagedConsoleAndMissingAssets':'No new errors','finalBuild':build},['Existing bundle-size advisory remains.'])
check('B02',ep('performance-final/report.json','performance-final/slingshot-raw.json','performance-final/ryker-raw.json','performance-final/spyder-raw.json'),{'device':'RTX 4080 / Intel i9-12900K','viewport':[2560,1440],'quality':'High','scene':'Dusk-rain Harbor native RAF Time Attack, sequential real full laps','runs':[{'vehicle':r['vehicle'],'frames':r['frames'],'tail':r['tail'],'drawCensus':r['census']} for r in performance['runs']],'existingPerformanceGate':'HOLD'},['Bounded addition audit, not full two-race High/Ultra release matrix or lower-end hardware approval.'])
check('D01',['scripts/spyder/stage-handoff.py','handoff/SPYDER01-COMPLETE.md','assets/spyder/ASSET-PROVENANCE.md','assets/spyder/PHYSICS.md','assets/spyder/PRODUCT-REFERENCES.md'],{'delivery':'Private complete local ZIP with standalone game, source overlay/diff, four packed masters, source kit/receipt, original rider master, evidence and SHA256 inventory','integrity':'Stage script verifies ZIP CRC and every member hash before success','noUnusedLODClaim':True},['ZIP excludes Git history, installed tools, owner saves and unrelated work. D01 requires successful accompanying package-integrity receipt.'])
contract=(R/'.tools/spyder-kit/Spyder_Road_Codex_Kit/contracts/ACCEPTANCE.md').read_text();assert set(re.findall(r'\| ([SRPGABD]\d\d) \|',contract))=={x['id'] for x in checks}
runtime={p.name:{'bytes':p.stat().st_size,'sha256':sha(p)} for p in (R/'public/assets/spyder').iterdir() if p.is_file()}
report={'schemaVersion':1,'task':'SPYDER01','timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':build['commit'],'workingTree':True,'authorization':'Private local implementation only; no purchase/push/deployment/publication','performanceGate':'HOLD','runtime':runtime,'checks':checks,'commands':['npm test','npx tsc --noEmit','npm run demo:build','node scripts/spyder/validate-assets.mjs','Blender --background --factory-startup --disable-autoexec --python-exit-code 1 --python scripts/spyder/reimport.py','BASE_URL=http://127.0.0.1:5214 node scripts/spyder/visual.mjs','node scripts/spyder/acceptance.mjs','node scripts/spyder/roads.mjs','node scripts/spyder/career.mjs','node scripts/spyder/cockpit.mjs','node scripts/spyder/audio.mjs','node scripts/spyder/mixed.mjs','node scripts/spyder/departure.mjs','node scripts/spyder/performance.mjs','python -X utf8 scripts/spyder/stage-handoff.py']}
(R/'handoff/SPYDER-VALIDATION.json').write_text(json.dumps(report,indent=2));print(json.dumps({'checks':len(checks),'status':'PASS','packageVerification':'Required separately'}))
