import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RIDGE_ROUTE,RIDGE_DESIGN,RIDGE_SURFACES,ridgePoint,ridgeRibbon,ridgeCrossHeight,type RidgeMeshData} from './route';
import {sampleRoad,projectRoad} from '../course/environment';
import {RIDGE_ASSETS} from './assets';
import {loadRidgeForest} from './forest';
import type {GraphicsQuality} from '../presentation/graphics-settings';
export {RIDGE_ASSETS} from './assets';
const noise=(x:number,z:number)=>Math.sin(x*.021+Math.cos(z*.018))*Math.cos(z*.027)+.37*Math.sin(x*.093-z*.063);
export function ridgeScenicHeight(x:number,z:number){const p=projectRoad(RIDGE_ROUTE,x,z),offset=(x-p.x)*-p.dz+(z-p.z)*p.dx,near=ridgeCrossHeight(p.progress,Math.sign(offset)*Math.min(60,Math.abs(offset))),far=-25+50*Math.exp(-(((x-400)/600)**2)-((z+750)/900)**2)+12*Math.sin(x*.006)*Math.cos(z*.006),raw=Math.max(0,Math.min(1,(p.distance-60)/160)),blend=raw*raw*(3-2*raw);return near*(1-blend)+far*blend}

function geometry(data:RidgeMeshData){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(data.vertices,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(data.uv,2));g.setIndex(data.indices);g.computeVertexNormals();return g}
/** Dedicated low afternoon / blue-hour sky. Reuses the one-sun, two-headlight budget. */
export function loadRidgeAtmosphere(scene:THREE.Scene,renderer:THREE.WebGLRenderer,preset:'day'|'night'){
 const night=preset==='night',w=512,h=256,data=new Float32Array(w*h*4),sun=new THREE.Vector3(-.74,.29,-.60).normalize();
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const lat=(.5-(y+.5)/h)*Math.PI,lng=((x+.5)/w-.5)*Math.PI*2,dir=new THREE.Vector3(Math.cos(lat)*Math.cos(lng),Math.sin(lat),Math.cos(lat)*Math.sin(lng)),t=Math.pow(Math.max(0,dir.y),.45),haze=Math.exp(-Math.abs(dir.y)*9),warm=Math.max(0,dir.dot(sun));let c:THREE.Color;if(night)c=new THREE.Color().setRGB(.095+.20*haze,.15+.15*haze,.26+.10*haze);else c=new THREE.Color().setRGB(.65-.32*t+.27*haze*warm,.62-.15*t+.06*haze,.62-.03*t-.12*haze*warm);if(dir.y<0)c.multiplyScalar(.4);if(!night&&dir.angleTo(sun)<.008)c.setRGB(4,3.3,2.3);data.set([c.r,c.g,c.b,1],(y*w+x)*4)}
 const tex=new THREE.DataTexture(data,w,h,THREE.RGBAFormat,THREE.FloatType);tex.mapping=THREE.EquirectangularReflectionMapping;tex.flipY=true;tex.needsUpdate=true;const pmrem=new THREE.PMREMGenerator(renderer),probe=pmrem.fromEquirectangular(tex);pmrem.dispose();scene.background=tex;scene.environment=probe.texture;scene.environmentIntensity=night?1.0:1.2;renderer.toneMappingExposure=night?1.15:1.0;scene.userData.outdoorSunDirection=sun.toArray();scene.userData.outdoorEnvironment={source:'Original procedural Appalachian atmosphere',preset:night?'blue-hour':'late-afternoon',sunElevationDegrees:Math.asin(sun.y)*180/Math.PI};
 return{inspect:()=>scene.userData.outdoorEnvironment,dispose(){if(scene.background===tex)scene.background=null;if(scene.environment===probe.texture)scene.environment=null;tex.dispose();probe.dispose()}};
}
/** Call after harborLighting to retain its exact lighting budget and dynamic follow. */
export function configureRidgeLighting(scene:THREE.Scene,preset:'day'|'night') {const night=preset==='night';scene.fog=new THREE.Fog(night?'#71859e':'#c9bda6',night?320:440,night?2100:2900);scene.traverse(o=>{if(o instanceof THREE.DirectionalLight){o.color.set(night?'#9fbde9':'#ffce91');o.intensity=night?.85:3.0}else if(o instanceof THREE.HemisphereLight){o.color.set(night?'#a4bddd':'#d7e8f2');o.groundColor.set(night?'#434d57':'#806743');o.intensity=night?.95:1.1}})}
export async function loadRidgePresentation(scene:THREE.Scene,preset:'day'|'night'='day',forestOptions?:{renderer:THREE.WebGLRenderer;enabled:boolean}){
 const root=new THREE.Group();root.name='Smoky_Ridge_layout_v1';const loader=new GLTFLoader(),tl=new THREE.TextureLoader();
 // Wait for every decode before rejecting, then release successful partial loads.
 const loaded=await Promise.allSettled([loader.loadAsync(RIDGE_ASSETS[0]),fetch(RIDGE_ASSETS[1]).then(r=>{if(!r.ok)throw Error("Ridge land load failed");return r.json()}),...RIDGE_ASSETS.slice(2).map(url=>tl.loadAsync(url))]);
 const failed=loaded.find(r=>r.status==='rejected');
 if(failed){const gs=new Set<THREE.BufferGeometry>(),ms=new Set<THREE.Material>(),ts=new Set<THREE.Texture>();for(const r of loaded){if(r.status!=='fulfilled')continue;const value=r.value;if(value instanceof THREE.Texture)ts.add(value);else if(value?.scene instanceof THREE.Object3D)value.scene.traverse((o:THREE.Object3D)=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m)}})}for(const m of ms){for(const v of Object.values(m))if(v instanceof THREE.Texture)ts.add(v);m.dispose()}gs.forEach(g=>g.dispose());ts.forEach(t=>t.dispose());throw failed.reason}
 const [kit,land,...textures]=loaded.map(r=>(r as PromiseFulfilledResult<any>).value);
 const [asphalt,normal,rough,grass,grassNormal,planks,bark,stone]=textures as THREE.Texture[];for(const t of textures as THREE.Texture[]){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=4}for(const t of[asphalt,grass,planks,bark,stone])t.colorSpace=THREE.SRGBColorSpace;for(const t of[asphalt,normal,rough])t.repeat.set(2.5,2.5);
 const materials={road:new THREE.MeshStandardMaterial({map:asphalt,normalMap:normal,roughnessMap:rough,roughness:.93,normalScale:new THREE.Vector2(.35,.35)}),shoulder:new THREE.MeshStandardMaterial({map:grass,color:'#aa9b77',roughness:1}),terrain:new THREE.MeshStandardMaterial({map:grass,normalMap:grassNormal,color:'#8c8e69',normalScale:new THREE.Vector2(.55,.55),roughness:1}),white:new THREE.MeshStandardMaterial({color:'#eee7d5',roughness:.85}),yellow:new THREE.MeshStandardMaterial({color:'#d1ac4b',roughness:.8}),rail:new THREE.MeshStandardMaterial({color:'#9a9e99',metalness:.5,roughness:.53}),dark:new THREE.MeshStandardMaterial({color:'#353c3a',roughness:.9}),stone:new THREE.MeshStandardMaterial({map:stone,color:'#777a71',roughness:1})};
 const add=(g:THREE.BufferGeometry,m:THREE.Material,name:string)=>{const mesh=new THREE.Mesh(g,m);mesh.name=name;mesh.receiveShadow=true;root.add(mesh);return mesh};
 add(geometry(RIDGE_SURFACES.road),materials.road,'Ridge_road_EXACT_support_vertices');for(const [name,data]of [['left',RIDGE_SURFACES.leftShoulder],['right',RIDGE_SURFACES.rightShoulder]]as const)add(geometry(data),materials.shoulder,'Ridge_gravel_'+name);RIDGE_SURFACES.terrain.forEach((data,i)=>add(geometry(data),materials.terrain,'Ridge_physical_terrain_'+i));
 for(const side of[-1,1])add(geometry(ridgeRibbon(side*5.75,side*5.90,.018)),materials.white,'Ridge_edge_'+side);
 const dashes:THREE.BufferGeometry[]=[];for(let s=15;s<3200;s+=21){const a=ridgePoint(s),b=ridgePoint(s+6),v:number[]=[];for(const p of[a,b])for(const o of[-.055,.055])v.push(p.x-p.dz*o,p.y+.026,p.z+p.dx*o);dashes.push(geometry({vertices:v,indices:[0,1,2,1,3,2],uv:[0,0,1,0,0,1,1,1]}))}add(mergeGeometries(dashes)!,materials.yellow,'Ridge_center_dashes');dashes.forEach(g=>g.dispose());
 // Scenic terrain connects the 60m physical verge to distant wooded land. No hidden support plane.
 add(geometry(land as RidgeMeshData),materials.terrain,'Ridge_scenic_land_exact_bank_boundary');
 // Five true 3D silhouette layers; wooded profiles with atmospheric separation.
 for(let layer=0;layer<5;layer++){const v:number[]=[],uv:number[]=[],idx:number[]=[],radius=1100+layer*410;for(let j=0;j<=384;j++){const a=j/384*Math.PI*2,r=radius+90*Math.sin(a*7+layer),y=95+layer*30+65*Math.sin(a*3+layer*.8)+35*Math.sin(a*8+layer)+2.5*Math.sin(a*89+layer)+1.5*Math.sin(a*137-layer);v.push(340+Math.cos(a)*r,-250,-350+Math.sin(a)*r,340+Math.cos(a)*r,y,-350+Math.sin(a)*r);uv.push(j,0,j,1);if(j<384){const k=j*2;idx.push(k,k+1,k+2,k+1,k+3,k+2)}}const m=new THREE.MeshBasicMaterial({color:new THREE.Color().setHSL(preset==='night'?.57:.37+layer*.015,preset==='night'?.18:.24,preset==='night'?.14+layer*.045:.19+layer*.042),side:THREE.DoubleSide});add(geometry({vertices:v,indices:idx,uv}),m,'Ridge_distant_wooded_layer_'+layer)}
 const box=new THREE.BoxGeometry(1,1,1),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),euler=new THREE.Euler();const rails=new THREE.InstancedMesh(box,materials.rail,RIDGE_ROUTE.colliders.length);RIDGE_ROUTE.colliders.forEach((b,i)=>{q.setFromEuler(euler.set(b.pitch??0,b.yaw??0,0,'YXZ'));matrix.compose(new THREE.Vector3().fromArray(b.center as number[]),q,new THREE.Vector3().fromArray(b.size as number[]));rails.setMatrixAt(i,matrix)});rails.name='Ridge_rails_EXACT_collision_boxes';rails.computeBoundingSphere();root.add(rails);
 const posts:number[]=[];for(let s=450;s<3140;s+=12)for(const side of[-1,1]){if(side===1&&s<1400||s>1790&&s<1885)continue;const p=ridgePoint(s,side*10.4);posts.push(p.x,p.y+.30,p.z)}const postMesh=new THREE.InstancedMesh(box,materials.dark,posts.length/3);for(let i=0;i<posts.length;i+=3){matrix.makeScale(.15,.85,.15);matrix.setPosition(posts[i],posts[i+1],posts[i+2]);postMesh.setMatrixAt(i/3,matrix)}postMesh.computeBoundingSphere();root.add(postMesh);
 kit.scene.updateMatrixWorld(true);const library=new Map<string,Map<THREE.Material,THREE.BufferGeometry[]>>();kit.scene.traverse((o:THREE.Object3D)=>{if(!(o instanceof THREE.Mesh))return;const module=o.name.match(/^ridge_(tree\d_(?:near|far))_/)?.[1]??o.name.match(/^ridge_(pavilion|gantry|table|crate|rock\d)/)?.[1];if(!module)return;const m=(Array.isArray(o.material)?o.material[0]:o.material)as THREE.MeshStandardMaterial;if(m.name==='Ridge_bark'){m.map=bark;m.color.set('#777369')}if(m.name==='Ridge_warm_timber')m.map=planks;if(m.name==='Ridge_layered_stone')m.map=stone;if(m.name==='Ridge_broadleaf')m.side=THREE.DoubleSide;const by=library.get(module)??new Map(),gs=by.get(m)??[];gs.push(o.geometry.clone().applyMatrix4(o.matrixWorld));by.set(m,gs);library.set(module,by)});
 const modules=new Map<string,{geometry:THREE.BufferGeometry;material:THREE.Material}[]>();for(const[module,by]of library){const list=[];for(const[material,gs]of by){const geometry=gs.length===1?gs[0]:mergeGeometries(gs)!;if(gs.length>1)gs.forEach(g=>g.dispose());list.push({geometry,material})}modules.set(module,list)}
 type Placement={x:number;y:number;z:number;yaw:number;scale:number;variant:number};const trees:Placement[]=[];let seed=718;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 for(let s=120;s<3180;s+=10)for(const side of[-1,1]){if(s>1460&&s<2100&&side===-1)continue;if(s>2140&&s<2740&&side===-1&&rand()>.18)continue;for(let row=0;row<3;row++){const offset=side*(15+row*16+rand()*10),p=ridgePoint(s+rand()*8,offset);trees.push({...p,y:p.y-.14,yaw:rand()*Math.PI*2,scale:row===2?.40+rand()*.45:.72+rand()*.46,variant:Math.floor(rand()*4)})}}
 // Small clustered saplings break regular mature-tree spacing outside the gravel verge.
 for(let s=200;s<1350;s+=55)for(let j=0;j<3;j++){const side=s%110===0?-1:1,p=ridgePoint(s+rand()*18,side*(20+rand()*13));trees.push({...p,y:p.y-.15,yaw:rand()*Math.PI*2,scale:.18+rand()*.20,variant:Math.floor(rand()*4)})}
 for(let x=-240;x<990;x+=28)for(let z=-1150;z<410;z+=28){const px=x+rand()*16,pz=z+rand()*16,p=projectRoad(RIDGE_ROUTE,px,pz);if(p.distance<62||p.distance>245||p.distance<120&&p.progress>1480&&p.progress<2190&&(px-p.x)*-p.dz+(pz-p.z)*p.dx<0)continue;trees.push({x:px,y:ridgeScenicHeight(px,pz)-1.2,z:pz,yaw:rand()*Math.PI*2,scale:.68+rand()*.55,variant:Math.floor(rand()*4)})}
 let forest:Awaited<ReturnType<typeof loadRidgeForest>>|undefined,forestFailure='disabled';
 if(forestOptions?.enabled)try{forest=await loadRidgeForest(forestOptions.renderer,trees,new THREE.Vector3().fromArray(scene.userData.outdoorSunDirection??[-.74,.29,-.60]).normalize(),preset==='night');root.add(forest.group)}catch(error){forestFailure=String(error);console.warn('P11 forest unavailable; retaining the original Ridge trees.',error)}
 const cells=new Map<string,Placement[]>();for(const p of trees){const key=Math.floor(p.x/100)+':'+Math.floor(p.z/100),list=cells.get(key)??[];list.push(p);cells.set(key,list)}const lodCells:{near:THREE.Group;far:THREE.Group;center:THREE.Vector3}[]=[];
 function instances(module:string,list:Placement[],parent:THREE.Object3D,shadow=false){for(const part of modules.get(module)??[]){const mesh=new THREE.InstancedMesh(part.geometry,part.material,list.length);list.forEach((p,i)=>{matrix.compose(new THREE.Vector3(p.x,p.y,p.z),q.setFromAxisAngle(THREE.Object3D.DEFAULT_UP,p.yaw),new THREE.Vector3().setScalar(p.scale));mesh.setMatrixAt(i,matrix)});mesh.name='Ridge_'+module;mesh.castShadow=shadow;mesh.receiveShadow=true;mesh.computeBoundingSphere();parent.add(mesh)}}
 if(!forest)for(const[key,list]of cells){const near=new THREE.Group(),far=new THREE.Group();near.name='Ridge_near_chunk_'+key;far.name='Ridge_far_chunk_'+key;for(let v=0;v<4;v++){const selected=list.filter(p=>p.variant===v);if(selected.length){instances('tree'+v+'_near',selected,near,true);instances('tree'+v+'_far',selected,far)}}root.add(near,far);const [cx,cz]=key.split(':').map(Number);lodCells.push({near,far,center:new THREE.Vector3(cx*100+50,0,cz*100+50)})}
 function fixture(module:string,s:number,offset:number,yaw=0,scale=1){const p=ridgePoint(s,offset);instances(module,[{...p,yaw,scale,variant:0}],root,true)}
 fixture('gantry',35,0,0,1);fixture('pavilion',90,-24,.08,1.2);fixture('pavilion',1850,-24,Math.PI*.5,.8);for(let i=0;i<5;i++){fixture('table',55+i*12,-20,.1,.8);fixture('crate',90+i*3,-17,0,.9)}for(let s=1380;s<1760;s+=18)fixture('rock'+Math.floor(s/18)%3,s,16+Math.sin(s)*1.4,s*.032,1.0+Math.sin(s*.11)*.15);
 // The start gantry's painted SlingMods board is authored in the kit (scripts/author-p10a-ridge.py); no runtime logo plane.
 function board(text:string,sub:string,s:number,offset:number,width=3){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle='#e6dfc9';c.fillRect(0,0,512,256);c.fillStyle='#34423a';c.fillRect(0,0,512,15);c.textAlign='center';c.fillStyle='#243b34';c.font='bold 68px sans-serif';c.fillText(text,256,115);c.font='bold 28px sans-serif';c.fillText(sub,256,182);const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;const mesh=add(new THREE.PlaneGeometry(width,width/2),new THREE.MeshStandardMaterial({map,roughness:.8,side:THREE.DoubleSide}),'Ridge_board_'+text),p=ridgePoint(s,offset);mesh.position.set(p.x,p.y+1.9,p.z);mesh.rotation.y=Math.atan2(-p.dx,-p.dz);const post=add(new THREE.BoxGeometry(.12,1.9,.12),materials.dark,'Ridge_signpost');post.position.set(p.x,p.y+.95,p.z)}
 board('SMOKY RIDGE','CLOSED COURSE · 3.2 KM',120,-13,4);board('SUMMIT','OVERLOOK  →',1790,-12,3);for(const m of[200,150,100,50])board(String(m),'BRAKE · DESCENT',2540-m,-11.9,1.6);board('PIT RETURN','KEEP RIGHT',3080,12,2.8);
 // Turnout stays outside race line and supported by existing shoulder/terrain mesh.
 const turnoutData=ridgeRibbon(-24,-9,.018);const trimmed=turnoutData.indices.filter((_,i)=>{const start=Math.floor(i/6)*6,vertex=turnoutData.indices[start],station=turnoutData.uv[vertex*2+1]*5;return station>=1800&&station<=1860});add(geometry({...turnoutData,indices:trimmed}),materials.shoulder,'Ridge_overlook_turnout');
 if(forest)root.traverse(o=>{if(o instanceof THREE.Mesh&&/^Ridge_(gravel_|physical_terrain_|scenic_land|overlook_turnout)/.test(o.name))o.material=forest!.ground});
 scene.add(root);let disposed=false,activeNear=0,activeFar=0;return{root,update(camera:THREE.Vector3,_time:number,quality:GraphicsQuality='high',reduced=false){forest?.update(camera,_time,quality,reduced);activeNear=activeFar=0;for(const cell of lodCells){const d=Math.hypot(camera.x-cell.center.x,camera.z-cell.center.z);cell.near.visible=d<180;cell.far.visible=d>=180&&d<520;activeNear+=Number(cell.near.visible);activeFar+=Number(cell.far.visible)}},inspect:()=>({forest:forest?.inspect()??{fallback:true,reason:forestFailure},route:RIDGE_DESIGN,trees:trees.length,chunks:lodCells.length,activeNear,activeFar,nearDistance:180,farDistance:520,assets:RIDGE_ASSETS,source:'assets/blender/ridge/ridge-district-kit.blend; src/ridge/route.ts',terrain:'Physical road/shoulders/60m bank exact support data, distant slopes scenic only',light:preset==='day'?'late-afternoon':'blue-hour'}),dispose(){if(disposed)return;disposed=true;forest?.dispose();root.removeFromParent();const gs=new Set<THREE.BufferGeometry>(),ms=new Set<THREE.Material>(),ts=new Set<THREE.Texture>(textures as THREE.Texture[]);for(const tree of[root,kit.scene])tree.traverse((o:THREE.Object3D)=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m)}});for(const material of Object.values(materials))ms.add(material);for(const list of modules.values())for(const p of list){gs.add(p.geometry);ms.add(p.material)}for(const g of gs)g.dispose();for(const m of ms){for(const v of Object.values(m))if(v instanceof THREE.Texture)ts.add(v);m.dispose()}for(const t of ts)t.dispose()}};
}
