import {perfLegacy} from './perf-switches';
import {RiderMotion,type RiderGesture} from './rider-motion';
let riderSequence=0;
import * as THREE from 'three';import type{VehicleTelemetry}from'../simulation';
type V3=[number,number,number];
/** restPose: every rig node's local TRS for this vehicle's seat, applied before the IK records its rests (biker fits). */
export type DriverAttachment={restPose?:Record<string,{t:V3;r:[number,number,number,number];s?:V3}>;handlebar?:boolean;handlebarPose?:{lean:number;extraLean:number;twist:number};eye:V3;rootOffset?:V3;headVisualNode:string;headVisualNodes?:string[];arms:Record<string,{upperBone:string;lowerBone:string;handBone:string;shoulder:V3;elbow:V3;contact:V3;upperLength:number;lowerLength:number;poleHint:V3;wheelGripLocal:V3}>;feet:Record<string,{bone:string;anchor:V3}>;legs?:Record<string,{upperBone:string;lowerBone:string;footBone:string;ankle:V3;pole:V3;upperLength:number;lowerLength:number;footPitch:number}>};
export function solveElbow(shoulder:THREE.Vector3,target:THREE.Vector3,pole:THREE.Vector3,upper:number,lower:number){const direction=target.clone().sub(shoulder),actual=direction.length(),distance=THREE.MathUtils.clamp(actual,.015,upper+lower-.0001);direction.normalize();const across=pole.clone().sub(shoulder).addScaledVector(direction,-pole.clone().sub(shoulder).dot(direction));if(across.lengthSq()<1e-8)across.set(1,0,0).cross(direction);across.normalize();const along=(upper*upper-lower*lower+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,upper*upper-along*along));return shoulder.clone().addScaledVector(direction,along).addScaledVector(across,height)}
export class GripMotion {
 private offset=0;private phase=1;private start=0;
 update(wheelAngle:number,dt:number,reset=false,allowRelease=true){if(reset){this.offset=-wheelAngle;this.phase=1}let angle=wheelAngle+this.offset;if(this.phase>=1&&Math.abs(angle)>1.0&&!allowRelease){angle=THREE.MathUtils.clamp(angle,-1,1);this.offset=angle-wheelAngle}
 if(this.phase>=1&&Math.abs(angle)>1.0&&allowRelease){this.start=THREE.MathUtils.clamp(angle,-1.15,1.15);this.phase=0}
 let release=0;if(this.phase<1){this.phase=Math.min(1,this.phase+Math.max(0,dt)/.24);const smooth=this.phase*this.phase*(3-2*this.phase);angle=this.start*(1-smooth);release=.05*Math.sin(Math.PI*this.phase);if(this.phase===1)this.offset=-wheelAngle}
 return{angle,release,regripping:this.phase<1,offset:angle-wheelAngle};
 }
}
/** Alternating hand-over-hand: supporting glove stays on the rim and may slide within its reachable sector. */
export class GripPair {
 private motions={left:new GripMotion(),right:new GripMotion()};private active:string|undefined;
 update(angle:number,dt:number,reset=false){if(reset)this.active=undefined;const result:any={};for(const side of ['left','right'] as const){const motion=this.motions[side].update(angle,dt,reset,!this.active||this.active===side);if(motion.regripping)this.active=side;else if(this.active===side)this.active=undefined;result[side]=motion}return result as Record<'left'|'right',ReturnType<GripMotion['update']>>}
}
/** Same skinned rig in all modes; grip targets derive from the displayed wheel's world matrix. */
/** One rider asset serves several vehicles: a fit's pose fully replaces whatever pose the (possibly cloned) rig carried. */
export function applyRestPose(root:THREE.Object3D,pose:DriverAttachment['restPose']){if(!pose)return;for(const[name,p]of Object.entries(pose)){const node=root.getObjectByName(name);if(!node)continue;node.position.fromArray(p.t);node.quaternion.fromArray(p.r);if(p.s)node.scale.fromArray(p.s);else node.scale.set(1,1,1)}root.updateMatrixWorld(true)}
export class DriverPresenter {
 // After the vehicle/control path and rider are current, IK can read their matrices directly.
 // Each changed joint updates its descendants before the next solve. Rewalking its ancestors is redundant.
 private legacy=false;private decomposePosition=new THREE.Vector3();private decomposeScale=new THREE.Vector3();private inverse=new THREE.Matrix4();
 private position(node:THREE.Object3D){const out=new THREE.Vector3();return this.legacy?node.getWorldPosition(out):out.setFromMatrixPosition(node.matrixWorld)}
 private orientation(node:THREE.Object3D){const out=new THREE.Quaternion();if(this.legacy)return node.getWorldQuaternion(out);node.matrixWorld.decompose(this.decomposePosition,out,this.decomposeScale);return out}
 private point(node:THREE.Object3D,out:THREE.Vector3){return this.legacy?node.localToWorld(out):out.applyMatrix4(node.matrixWorld)}
 private localPoint(node:THREE.Object3D,out:THREE.Vector3){return this.legacy?node.worldToLocal(out):out.applyMatrix4(this.inverse.copy(node.matrixWorld).invert())}
 private nodes=new Map<string,THREE.Object3D|undefined>();
 private node(name:string){if(this.legacy)return this.root.getObjectByName(name);if(!this.nodes.has(name))this.nodes.set(name,this.root.getObjectByName(name));return this.nodes.get(name)}
 private authoredGrip:boolean;private motion:RiderMotion;private rests=new Map<THREE.Object3D,THREE.Quaternion>();private grips=new GripPair();private handRest=new Map<string,THREE.Quaternion>();private footRest=new Map<string,THREE.Quaternion>();private wheelBase:THREE.Quaternion;private speed:number|undefined;private bodyPitch=0;private report:any={};
 constructor(readonly root:THREE.Object3D,readonly vehicle:THREE.Object3D,readonly wheel:THREE.Object3D,readonly config:DriverAttachment){applyRestPose(root,config.restPose);this.authoredGrip=root.getObjectByName('driver_root')?.userData.gripPoseVersion===1;this.motion=new RiderMotion(root,(riderSequence++%11)*.57);root.traverse(o=>{if(o instanceof THREE.Bone)this.rests.set(o,o.quaternion.clone());if(o instanceof THREE.Mesh){o.castShadow=false;o.receiveShadow=true}});vehicle.updateWorldMatrix(true,true);this.wheelBase=wheel.quaternion.clone();const inverse=vehicle.getWorldQuaternion(new THREE.Quaternion()).invert();for(const[side,a]of Object.entries(config.arms)){this.handRest.set(side,inverse.clone().multiply(root.getObjectByName(a.handBone)!.getWorldQuaternion(new THREE.Quaternion())))}for(const [side,leg]of Object.entries(config.legs??{}))this.footRest.set(side,inverse.clone().multiply(root.getObjectByName(leg.footBone)!.getWorldQuaternion(new THREE.Quaternion())))}
 update(t:VehicleTelemetry,dt:number,cockpit:boolean,reset=false){this.legacy=perfLegacy('rider');for(const[o,q]of this.rests)o.quaternion.copy(q);const acceleration=reset||this.speed===undefined||dt<=0?0:THREE.MathUtils.clamp((t.speed-this.speed)/dt,-12,12);this.speed=t.speed;this.bodyPitch=reset?0:THREE.MathUtils.lerp(this.bodyPitch,acceleration*.001,1-Math.exp(-10*dt));const spine=this.node('driver_spine');if(spine){spine.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),(this.config.handlebar?(this.config.handlebarPose?.lean??-.35)+(this.config.handlebarPose?.extraLean??-.23)*Math.min(1,Math.abs(t.steer)/.62):0)+this.bodyPitch));if(this.config.handlebar)spine.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),t.steer*(this.config.handlebarPose?.twist??.65)))}
 // Biker fits: the full-lock lean into the outside grip keeps the eyes level (neck extends), so the helmet does not dip into the bars.
 const lockLean=this.config.handlebar&&this.config.restPose?(this.config.handlebarPose?.extraLean??-.23)*Math.min(1,Math.abs(t.steer)/.62):0,head=lockLean?this.node('driver_head'):undefined;if(spine&&head)head.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),-lockLean));this.motion.update(t,dt,reset);const heads=(this.config.headVisualNodes??[this.config.headVisualNode]).map(n=>(this.node(n)??this.node(THREE.PropertyBinding.sanitizeNodeName(n)))).filter((n):n is THREE.Object3D=>!!n);for(const head of heads)head.visible=!cockpit;
 // Tour glove curl centres sit 23 mm ahead of the semantic pivot. The Ryker
 // attachment is only 3 mm behind its bar, so move that glove pivot back 20 mm.
 if(this.legacy)this.vehicle.updateWorldMatrix(true,true);else{this.vehicle.updateWorldMatrix(true,false);this.wheel.updateWorldMatrix(true,false);this.root.updateWorldMatrix(true,true)}const delta=this.wheelBase.clone().invert().multiply(this.wheel.quaternion),wheelAngle=this.config.handlebar?0:2*Math.atan2(delta.z,delta.w),axis=new THREE.Vector3(0,0,1).transformDirection(this.wheel.matrixWorld),vehicleQ=this.orientation(this.vehicle);const arms:any={},grips=this.grips.update(wheelAngle,dt,reset);
 for(const[side,a]of Object.entries(this.config.arms)){const motion=grips[side as 'left'|'right'],grip=new THREE.Vector3().fromArray(a.wheelGripLocal).add(new THREE.Vector3(0,0,this.authoredGrip&&this.config.handlebar?.020:0)).applyAxisAngle(new THREE.Vector3(0,0,1),motion.offset);const rim=this.point(this.wheel,grip.clone());grip.z+=motion.release;const target=this.point(this.wheel,grip),upper=this.node(a.upperBone)!,lower=this.node(a.lowerBone)!,hand=this.node(a.handBone)!;const shoulder=this.position(upper),pole=this.point(this.vehicle,new THREE.Vector3().fromArray(a.poleHint)),elbow=solveElbow(shoulder,target,pole,a.upperLength,a.lowerLength);this.aim(upper,lower,elbow);this.aim(lower,hand,target);const desiredQ=this.authoredGrip?this.orientation(this.wheel).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),this.config.handlebar?(side==='left'?-Math.PI/2:Math.PI/2):motion.offset)).multiply(this.handRest.get(side)!):this.config.handlebar?vehicleQ.clone().multiply(delta).multiply(this.handRest.get(side)!):new THREE.Quaternion().setFromAxisAngle(axis,motion.angle).multiply(vehicleQ.clone().multiply(this.handRest.get(side)!));hand.quaternion.copy(this.orientation(hand.parent!).invert().multiply(desiredQ));hand.updateWorldMatrix(this.legacy,true);const actual=this.position(hand);arms[side]={gap:actual.distanceTo(target),rimGap:actual.distanceTo(rim),regripping:motion.regripping,release:motion.release,angle:motion.angle,target:target.toArray(),contact:actual.toArray(),elbow:this.position(lower).toArray()}}
 const feet:Record<string,{gap:number;ankle:number[]}>= {};
 for(const [side,leg]of Object.entries(this.config.legs??{})){const upper=this.node(leg.upperBone)!,lower=this.node(leg.lowerBone)!,foot=this.node(leg.footBone)!,target=this.point(this.vehicle,new THREE.Vector3().fromArray(leg.ankle)),hip=this.position(upper),pole=this.point(this.vehicle,new THREE.Vector3().fromArray(leg.pole));const knee=solveElbow(hip,target,pole,leg.upperLength,leg.lowerLength);this.aim(upper,lower,knee);this.aim(lower,foot,target);const desired=vehicleQ.clone().multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),leg.footPitch)).multiply(this.footRest.get(side)!);foot.quaternion.copy(this.orientation(foot.parent!).invert().multiply(desired));foot.updateWorldMatrix(this.legacy,true);feet[side]={gap:this.position(foot).distanceTo(target),ankle:this.localPoint(this.vehicle,this.position(foot)).toArray()}}
 for(const[side,f]of Object.entries(this.config.feet)){const bone=this.node(f.bone);if(bone)bone.quaternion.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),-.035*(side==='right'?t.throttle:t.brake)))}this.root.updateWorldMatrix(this.legacy,true);this.report={motion:this.motion.report,arms,feet,headVisible:heads.length?heads.some(h=>h.visible):undefined,bodyPitch:this.bodyPitch,wheelAngle,eye:this.config.eye};return this.report;
 }
 private aim(bone:THREE.Object3D,child:THREE.Object3D,target:THREE.Vector3){const from=this.position(bone),current=this.position(child).sub(from).normalize(),direction=target.clone().sub(from).normalize(),world=new THREE.Quaternion().setFromUnitVectors(current,direction).multiply(this.orientation(bone));bone.quaternion.copy(this.orientation(bone.parent!).invert().multiply(world));bone.updateWorldMatrix(this.legacy,true)}
 triggerGesture(gesture:RiderGesture){return this.motion.trigger(gesture)}
 inspect(){return this.report}
}
