/** Original game rendition of the reference Driver home. No OEM artwork or service data. */
import * as THREE from 'three';
import type {VehicleTelemetry} from '../simulation';
import {fitInspectionCamera} from './inspection';
export const DISPLAY_MOUNT={width:.202,height:.133,position:[0,.665,-.1735] as const,pixels:[512,336] as const};
import {displayValues} from './instrument-values';
export {displayValues} from './instrument-values';
import {NativeCluster} from './native-cluster';
export class PoweredDisplay {
 private cluster:NativeCluster;
 private mount:{width:number;height:number;position:number[];pixels:number[]}={...DISPLAY_MOUNT,position:[...DISPLAY_MOUNT.position],pixels:[...DISPLAY_MOUNT.pixels]};
 readonly canvas=document.createElement('canvas');readonly texture:THREE.CanvasTexture;readonly mesh:THREE.Mesh;private ctx:CanvasRenderingContext2D;
 private power=true;private dirty=true;private lastUpload=-Infinity;private lastKey='';private uploads=0;private thumbnailCaptures=0;private thumbnailKey='';private thumbnail?:HTMLCanvasElement;private value={speed:0,units:'mph',rpm:900,gear:'1'};private disposed=false;private world=new THREE.Vector3();private projected=new THREE.Vector3();private normal=new THREE.Vector3();private direction=new THREE.Vector3();
 constructor(private car:THREE.Object3D){this.cluster=new NativeCluster(car);this.canvas.width=512;this.canvas.height=336;this.ctx=this.canvas.getContext('2d')!;this.texture=new THREE.CanvasTexture(this.canvas);this.texture.colorSpace=THREE.SRGBColorSpace;this.texture.generateMipmaps=false;this.texture.minFilter=THREE.LinearFilter;const material=new THREE.MeshBasicMaterial({map:this.texture,toneMapped:false});const anchor=car.getObjectByName('display_mount');if(anchor)this.mount={width:anchor.userData.width,height:anchor.userData.height,position:anchor.position.toArray(),pixels:[512,336]};this.mesh=new THREE.Mesh(new THREE.PlaneGeometry(this.mount.width,this.mount.height),material);this.mesh.name='signature_powered_display';this.mesh.renderOrder=1;this.mesh.visible=!car.getObjectByName('ryker_foundation');if(anchor)anchor.add(this.mesh);else{this.mesh.position.fromArray(DISPLAY_MOUNT.position);car.add(this.mesh)}this.draw()}
 setPower(on:boolean){if(this.power===on)return;this.power=on;this.cluster.setPower(on);this.dirty=true;this.draw()}
 /** One small render/readback only when the validated build changes; never per frame. */
 snapshot(renderer:THREE.WebGLRenderer,environment:THREE.Texture|null,key:string){if(this.disposed||key===this.thumbnailKey)return;this.thumbnailKey=key;const clone=this.car.clone(true);clone.getObjectByName(this.mesh.name)?.removeFromParent();clone.position.set(0,0,0);clone.quaternion.identity();const scene=new THREE.Scene();scene.add(clone);scene.background=new THREE.Color('#20272c');scene.environment=environment;scene.environmentIntensity=1;scene.add(new THREE.HemisphereLight(0xffffff,0x616973,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(2,4,-4);scene.add(light);const camera=new THREE.PerspectiveCamera(36,256/160,.05,20);clone.updateMatrixWorld(true);const bounds=new THREE.Box3();clone.traverseVisible(o=>{if(o instanceof THREE.Mesh){o.geometry.computeBoundingBox();if(o.geometry.boundingBox)bounds.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld))}});fitInspectionCamera(camera,bounds,new THREE.Vector3(4,1.1,-2),.94);const rt=new THREE.WebGLRenderTarget(256,160,{depthBuffer:true});rt.texture.colorSpace=THREE.SRGBColorSpace;const prior=renderer.getRenderTarget(),shadow=renderer.shadowMap.enabled;try{renderer.shadowMap.enabled=false;renderer.setRenderTarget(rt);renderer.render(scene,camera);const pixels=new Uint8Array(256*160*4);renderer.readRenderTargetPixels(rt,0,0,256,160,pixels);const image=document.createElement('canvas');image.width=256;image.height=160;const c=image.getContext('2d')!,data=c.createImageData(256,160);for(let y=0;y<160;y++)data.data.set(pixels.subarray((159-y)*256*4,(160-y)*256*4),y*256*4);c.putImageData(data,0,0);this.thumbnail=image;this.thumbnailCaptures++;this.dirty=true}finally{renderer.setRenderTarget(prior);renderer.shadowMap.enabled=shadow;rt.dispose();clone.removeFromParent()}this.draw()}
 update(t:VehicleTelemetry,camera:THREE.Camera,now:number){if(!this.disposed)this.cluster.update(t);if(this.disposed||!this.power)return;this.mesh.updateWorldMatrix(true,false);this.mesh.getWorldPosition(this.world);camera.getWorldPosition(this.direction);this.direction.sub(this.world);this.normal.set(0,0,1).transformDirection(this.mesh.matrixWorld);this.projected.copy(this.world).project(camera);if(this.direction.lengthSq()>16||this.normal.dot(this.direction)<=0||Math.abs(this.projected.x)>1.05||Math.abs(this.projected.y)>1.05||this.projected.z>1||this.projected.z< -1)return;if(now-this.lastUpload<100)return;this.lastUpload=now;const value=displayValues(t),key=JSON.stringify(value);if(key!==this.lastKey){this.value=value;this.lastKey=key;this.dirty=true}if(this.dirty){this.lastUpload=now;this.draw()}}
 private draw(){if(this.disposed)return;const c=this.ctx;c.fillStyle=this.power?'#151c22':'#080c0f';c.fillRect(0,0,512,336);if(this.power){const text=(s:string,x:number,y:number,size=18,color='#e9edf0')=>{c.fillStyle=color;c.font=`500 ${size}px Arial`;c.fillText(s,x,y)};c.fillStyle='#29343e';c.fillRect(0,0,512,34);text('DRIVER',16,24,17);text('PHONE —    GPS —',263,24,13,'#aebbc4');text('—:—',458,24,14);c.fillStyle='#26313a';c.fillRect(333,42,1,255);text('VEHICLE OVERVIEW',16,64,17);if(this.thumbnail)c.drawImage(this.thumbnail,8,82,316,198);else{text('SLINGSHOT',54,175,28);text(this.car.getObjectByName('model02_2026_foundation')?'2026 R':'2024 R',115,203,18,'#adbac4')};text('SLINGSHOT R',16,300,16);text('Fuel —   Voltage —   Temp —',16,323,13,'#8b9aa6');text('SPEED',354,67,15,'#a5b5c1');text(String(this.value.speed),353,113,40);text(this.value.units,432,113,16);c.fillStyle='#33414c';c.fillRect(350,128,146,1);text('ENGINE',354,157,15,'#a5b5c1');text(String(this.value.rpm),354,194,30);text('RPM',443,194,14);c.fillRect(350,210,146,1);text('GEAR',354,241,15,'#a5b5c1');text(this.value.gear,354,283,36);text('HOME',434,318,13,'#a5b5c1')}this.texture.needsUpdate=true;this.uploads++;this.dirty=false}
 inspect(){return{cluster:this.cluster.inspect(),power:this.power,values:{...this.value},pixels:[512,336],uploads:this.uploads,thumbnailCaptures:this.thumbnailCaptures,thumbnailKey:this.thumbnailKey,mount:this.mount,method:'Original Driver-home approximation; game-rendered selected-build thumbnail. Speed/RPM/gear use actual telemetry. Unsimulated fields unavailable. At most10Hz changed-value upload, only nearby/front-facing/in-view; no rival displays.'}}
 dispose(){if(this.disposed)return;this.disposed=true;this.cluster.dispose();this.mesh.removeFromParent();this.mesh.geometry.dispose();(this.mesh.material as THREE.Material).dispose();this.texture.dispose();this.thumbnail=undefined}
}
