import * as THREE from 'three';
import {freshSpyderBuild,type SpyderBuild} from '../signature/spyder-catalog';
import {COLORS,defaultAppearance,type Appearance} from '../career/catalog';
export class SpyderProducts {
 private emitters:THREE.PointLight[]=[];private ledMaterials=new Set<THREE.MeshStandardMaterial>();private state=freshSpyderBuild();private lights=defaultAppearance();private carriers:THREE.Object3D[]=[];
 constructor(private car:THREE.Object3D,readonly root:THREE.Group){car.add(root);for(const side of [-1,1]){const light=new THREE.PointLight(0xff2222,0,1.15,2);light.position.set(side*.33,.22,-.78);root.add(light);this.emitters.push(light)}car.updateWorldMatrix(true,true);for(let i=0;i<2;i++){const ring=root.getObjectByName('spyder_wheel_light_'+i)!;car.getObjectByName((i===0?'front_left':'front_right')+'_steer')!.attach(ring);this.carriers.push(ring)}car.userData.spyderRevision=(car.userData.spyderRevision??0)+1;this.set()}
 set(state:SpyderBuild=freshSpyderBuild(),lights:Appearance=defaultAppearance()){this.state=structuredClone(state);this.lights={...lights};this.car.userData.spyderLights={enabled:lights.enabled,brightness:lights.brightness,pattern:state.pattern};for(const [id,on] of Object.entries({...freshSpyderBuild().parts,...Object.fromEntries(['throttle','front','rear','sway','underglow','wheels'].map(id=>[id,!!state.parts[id as keyof typeof state.parts]]))})){const n=this.root.getObjectByName('spyder_mod_'+id);if(n)n.visible=on;}
  for(const [i,name] of ['front_left','front_right','rear'].entries())for(const part of ['spring','shock']){const stock=this.car.getObjectByName('stock_'+name+'_'+part);if(stock)stock.visible=!state.parts[i===2?'rear':'front']}
  this.carriers.forEach(r=>r.visible=!!state.parts.wheels);
  for(const tree of [this.root,...this.carriers])tree.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=!o.name.includes('LED');o.receiveShadow=true;for(const m of Array.isArray(o.material)?o.material:[o.material])if(m instanceof THREE.MeshStandardMaterial&&m.name==='Spyder LED diffuser'){this.ledMaterials.add(m);m.color.set(COLORS[lights.color]);m.emissive.set(lights.enabled?COLORS[lights.color]:0);m.emissiveIntensity=lights.enabled?lights.brightness*3:0}}});
 }
 /** Showroom install ignition multiplier (src/presentation/install-motion.ts); 1 = normal. */
 glow=1;
 update(time:number){const gain=(this.lights.enabled?this.lights.brightness*(this.state.pattern==='pulse'?.68+.32*Math.sin(time*3):1):0)*this.glow;for(const m of this.ledMaterials)m.emissiveIntensity=gain*3;for(const light of this.emitters){light.color.set(COLORS[this.lights.color]);light.intensity=this.state.parts.underglow?gain*1.8:0}}
 inspect(){return {selected:structuredClone(this.state),appearance:this.lights,stationaryRings:this.carriers.map(r=>({name:r.name,parent:r.parent?.name,visible:r.visible,bounds:new THREE.Box3().setFromObject(r).min.toArray(),boundsMax:new THREE.Box3().setFromObject(r).max.toArray()})),stock:['front_left','front_right','rear'].map(n=>({name:n,spring:this.car.getObjectByName('stock_'+n+'_spring')?.visible,shock:this.car.getObjectByName('stock_'+n+'_shock')?.visible})),fitment:'2023 F3 reference; custom physical fit unverified',requiredEndLinks:this.state.parts.sway?2:0}}
 dispose(){for(const n of ['front_left','front_right','rear'])for(const p of ['spring','shock']){const o=this.car.getObjectByName('stock_'+n+'_'+p);if(o)o.visible=true}const gs=new Set<THREE.BufferGeometry>(),ms=new Set<THREE.Material>();for(const root of [this.root,...this.carriers]){root.traverse(o=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m)}});root.removeFromParent()}gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose())}
}
