import {RYKER_PRODUCTS} from '../signature/ryker-catalog';
import {setCareerSource} from '../game/options';
import {announceAchievements,announce} from '../game/toast';
import {retailFitment} from '../signature/fitment';
import {GameAudio} from '../audio/game-audio';
import type {CueId} from '../audio/interface';
import {loadRouteGraphics} from '../signature/route-data';
import {PRODUCT} from '../career/catalog';
import {SUSPENSION} from '../career/suspension';
import {careerClient} from '../career/client';
import {BuildMenuInput} from '../career/menu';
import {PRODUCTS,type ProductId} from '../signature/catalog';
import {FINISHES,driveTuneLabel,recipeFragment,type FinishId} from '../signature/config';
import {CREDIT_TABLE,EVENTS,ALL_EVENTS,RIDGE_EVENTS,ridgeAvailable,chapterAvailable,eventAvailable,productOwned,productEquipped,productUnlocked,careerRecipe,cupStandings,nextCareerStep,type ChapterEvent,type CoastlineEvent,type RidgeEvent} from './model';
import {gameHeader} from '../signature/header';
import {beginCareerEvent,careerRaceHref} from './race-adapter';
import {evidenceEnabled} from '../demo/profile';
import '../signature/tokens.css';
import '../signature/ui.css';
import './hub.css';
import '../game/career.css';
import '../game/menu.css';
import {tourProgress} from '../game/progress';
import {speakerOf,portraitMarkup} from '../game/crew';
import {playerCard} from '../signature/header';

const app=document.querySelector('#app')!;document.body.className='career-experience';
// Same persistent header as the showroom and garage; chapter tabs switch between the garage and this hub.
app.innerHTML=`<main class="career-shell">${gameHeader({current:'career',career:{label:'Career',detail:'Chapters 02–03',returning:false,returnLabel:''}})}<nav class="career-chapters" aria-label="Career chapters"><a href="?scene=bay&play=career"><span>01</span>Build Matters</a><a href="?scene=career&play=career" aria-current="page"><span>02–03</span>Own the build · Ridge Run</a></nav><div id="career-content"></div><p id="career-message" role="status"></p></main>`;
const client=await careerClient();setCareerSource(()=>client.state);const root=app.querySelector<HTMLElement>('.career-shell')!,content=app.querySelector<HTMLElement>('#career-content')!,message=app.querySelector<HTMLElement>('#career-message')!;
const graphics=await loadRouteGraphics();const audio=new GameAudio(root);const audioFocus=()=>audio.lifecycle(document.hidden||!document.hasFocus());addEventListener('blur',audioFocus);addEventListener('focus',audioFocus);document.addEventListener('visibilitychange',audioFocus);
const partCue:Record<ProductId,CueId>={'SM-133':'part.lights.attach','SM-3223':'part.shocks.attach','SM-7720':'part.exhaust.attach','SM-26801':'part.aero.attach','SM-28919':'part.storage.attach'};
let pending=false,notice='',dialog:ChapterEvent|null=null,dialogMenu:BuildMenuInput|undefined;const menu=new BuildMenuInput(root,()=>{if(dialog){dialog=null;render()}else client.navigate('?scene=signature')});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function disabled(value:boolean){return value?'disabled':''}
function nextUp(){const step=nextCareerStep(client.state);if(step.kind==='event'&&step.event){const e=ALL_EVENTS[step.event];return `<aside class="career-next" data-chapter="${step.chapter}"><div><span class="career-kicker">NEXT UP · CHAPTER 0${step.chapter}</span><strong>${esc(e.title)}</strong><p>${esc(e.description)}</p></div><button data-focus="next-up" data-action="event" data-value="${step.event}" ${disabled(pending)}>Continue · ${esc(e.title)}</button></aside>`}if(step.kind==='complete')return '<aside class="career-next is-complete"><div><span class="career-kicker">CAREER COMPLETE</span><strong>Every chapter finished.</strong><p>Rematch any event below, or take your earned build for a free drive.</p></div></aside>';return ''}
function headerAction(action:string){audio.cue('ui.nav');if(action==='home'){client.navigate(location.pathname);return}if(action==='career'){scrollTo({top:0,behavior:'smooth'});content.querySelector<HTMLElement>('[data-focus=next-up],.career-callout a,.career-resume button')?.focus({preventScroll:true});return}client.navigate(`?scene=signature&screen=${action==='quick-race'?'events':action}&from=career${recipeFragment(careerRecipe(client.state))}`)}
/** Personal best for an event from the career's own race records (place first, then time). */
function bestOf(event:string){const rows=client.state.ownBuild.records.filter(r=>r.competitionId.includes(`-${event}-`));if(!rows.length)return '';const best=rows.slice().sort((a,b)=>a.place-b.place||a.timeMs-b.timeMs)[0],solo=best.standings.length<=1,sec=best.timeMs/1000,m=Math.floor(sec/60),time=`${m}:${(sec-m*60).toFixed(3).padStart(6,'0')}`;return `<p class="gx-best"><span>YOUR BEST</span>${solo?'':`<b>P${best.place}</b>`}${event==='coastline-cup'?'':`<b>${time}</b>`}</p>`}
/** First sight of a newly unlocked workshop part gets its own toast (remembered locally, once per part). */
function announceUnlocks(s:typeof client.state){let seen:string[]=[];try{seen=JSON.parse(localStorage.getItem('slingmods-gx-seen-unlocks')??'[]')}catch{}const earned=new Set<string>(Object.values(EVENTS).map(e=>e.unlock)),fresh=PRODUCTS.filter(p=>earned.has(p.id)&&productUnlocked(s,p.id)&&!productOwned(s,p.id)&&!seen.includes(p.id));if(!fresh.length)return;for(const p of fresh.slice(0,2))announce('🔓',`${p.brand} ${p.id}`,'New part unlocked · buy it in your workshop','PART UNLOCKED');try{localStorage.setItem('slingmods-gx-seen-unlocks',JSON.stringify([...seen,...fresh.map(p=>p.id)]))}catch{}}
function progressBlock(){const p=tourProgress(client.state);return `<div class="gx-career-progress"><div><b>${p.completed}<i>/${p.total}</i></b><span>EVENTS COMPLETE</span></div><div><b>LV ${p.level}</b><span>${esc(p.title.toUpperCase())}</span></div><span class="gx-career-meter"><i style="--gx-fill:${(p.completed/p.total).toFixed(3)}"></i></span></div>`}
function render(){
 const s=client.state,b=s.ownBuild,cup=b.activeCupId?b.cups[b.activeCupId]:undefined,latestCup=Object.values(b.cups).filter(c=>c.status==='completed').at(-1),shownCup=cup??latestCup;
 const focus=document.activeElement instanceof HTMLElement?document.activeElement.dataset.focus:undefined;
 content.innerHTML=`<section class="career-intro"><div><p class="career-kicker">CAREER / CHAPTERS 02 + 03</p><h1>Own the build.</h1><p>Race the coastline. Earn your parts. Take your build to the ridge. Every supported mod stays free to try in the showroom.</p>${progressBlock()}</div><div class="career-wallet"><strong>${s.credits.toLocaleString('en-US')}<i>CR</i></strong><span>GAME CREDITS · NOT REAL MONEY</span><small>${client.durable?'Career saved on this browser':'Temporary career · this tab only'}</small></div></section>
 ${nextUp()}
 ${!chapterAvailable(s)?'<aside class="career-callout"><strong>Finish Build Matters first.</strong><p>Complete a clean Harbor lap, Maya’s duel and the crew event. Earlier earned crew access is retained.</p><a href="?scene=bay&play=career">Continue Chapter 01 →</a></aside>':''}
 ${b.active?`<aside class="career-callout career-resume"><strong>Your race entry is saved.</strong><p>${ALL_EVENTS[b.active.event].title} · ${b.active.route==='ridge'?'Smoky Ridge':b.active.route==='harbor'?'Original Harbor':'Express'}. Drive tune: ${esc(driveTuneLabel(b.active.recipe.handlingProfile))}. Resume restarts this lap with your saved equipment and current driving; no unfinished-lap reward.</p><button data-action="resume">Resume saved entry</button><button data-action="abandon">Abandon entry${cup?' and Cup':''}</button></aside>`:cup?`<aside class="career-callout career-resume"><strong>Coastline Cup · Event ${cup.stages.length+1} / 2</strong><p>Your first result and build are saved. Continue on Express or abandon the Cup. No completed-Cup reward until both valid finishes.</p><button data-action="event" data-value="coastline-cup">Continue Cup</button><button data-action="abandon">Abandon Cup</button></aside>`:''}
 <section aria-label="Chapter events"><div class="career-section-title"><h2>The next coastline</h2><span>STOCK BUILDS WELCOME · ${driveTuneLabel(careerRecipe(s).handlingProfile)}</span></div><div class="career-events">${(Object.keys(EVENTS) as CoastlineEvent[]).map((id,i)=>{const e=EVENTS[id],available=eventAvailable(s,id);return `<article data-event-state="${b.completed[id]?'completed':available?'next':'locked'}" data-route="${id==='coastline-cup'?'harbor':'express'}" style="--gx-i:${i}"><div class="career-event-route"><svg viewBox="0 0 240 130" aria-label="${id==='coastline-cup'?'Harbor':'Express'} course"><path d="${graphics.routePaths[id==='coastline-cup'?'harbor':'express']}"/></svg><span>0${i+1} / ${id==='coastline-cup'?'HARBOR + EXPRESS':'EXPRESS'}</span></div><div class="career-event-body"><span class="career-kicker">${b.completed[id]?'✓ COMPLETED':available?'NEXT UP':'LOCKED'}</span><h3>${e.title}</h3><p>${e.description}</p><p class="career-reward"><b>+${e.first} CR</b> first finish · ${e.repeat} repeat${id!=='open-it-up'?' · win +100':''}</p>${bestOf(id)}<small>Unlocks ${PRODUCTS.find(p=>p.id===e.unlock)!.brand} ${e.unlock}</small><button data-focus="event-${id}" data-action="event" data-value="${id}" ${disabled(!available||pending||!!cup&&id!=='coastline-cup')}>${!available?'Complete the previous chapter step':b.completed[id]?'Race again':cup&&id==='coastline-cup'?'Continue Cup':'Meet the crew'}</button></div></article>`}).join('')}</div></section>
 <section aria-label="Ridge Run chapter"><div class="career-section-title"><h2>Chapter 03 · Ridge Run</h2><span>SMOKY RIDGE · FINISH TO ADVANCE</span></div>${!ridgeAvailable(s)?'<aside class="career-callout"><strong>Complete the Coastline Cup to earn the ridge invitation.</strong><p>Both Cup results must be saved. Free mountain test drives and Quick Race are already open.</p><a href="?scene=signature&screen=events&from=career">Preview Smoky Ridge →</a></aside>':''}<div class="career-events">${(Object.keys(RIDGE_EVENTS) as RidgeEvent[]).map((id,i)=>{const e=RIDGE_EVENTS[id],available=eventAvailable(s,id),complete=b.ridge.completed[id];return `<article data-event-state="${complete?'completed':available?'next':'locked'}" data-route="ridge" data-look="${e.preset}" style="--gx-i:${i}"><div class="career-event-route"><svg viewBox="0 0 240 130" aria-label="Smoky Ridge course"><path d="${graphics.routePaths.ridge}"/></svg><span>0${i+1} / ${e.laps} LAP${e.laps===1?'':'S'} · ${e.preset==='day'?'LATE AFTERNOON':'BLUE HOUR'}</span></div><div class="career-event-body"><span class="career-kicker">${complete?'✓ COMPLETED':available?'NEXT UP':'LOCKED'}${b.ridge.won[id]?' · FIRST PLACE':''}</span><h3>${e.title}</h3><p>${e.description}</p><p class="career-reward"><b>+${e.first} CR</b> first finish · ${e.repeat} repeat</p>${bestOf(id)}<small>No purchase required · First place is an achievement</small><button data-focus="event-${id}" data-action="event" data-value="${id}" ${disabled(!available||pending||!!cup)}>${!available?'Complete the previous chapter step':complete?'Race again':'Meet the crew'}</button></div></article>`}).join('')}</div>${b.ridge.completed['summit-invitational']?'<aside class="career-callout"><strong>Ridge Run complete.</strong><p>Your finishes, achievements and build are saved. Return for a rematch or a free drive.</p></aside>':''}</section>
 ${shownCup?`<section class="career-cup"><div><p class="career-kicker">${shownCup.status==='completed'?'CUP COMPLETE':'CUP IN PROGRESS'}</p><h2>Coastline standings</h2><p>${shownCup.stages.length} / 2 events · 10 / 7 / 5 / 3 points per finish; ties use combined time, then driver ID.</p>${shownCup.status==='completed'?`<p>Lower bags unlocked. Your Cup build: ${esc(FINISHES.find(f=>f.id===shownCup.recipe.finish)!.name)} · ${Object.keys(shownCup.recipe.products).length} installed products.</p>`:''}</div><ol>${cupStandings(shownCup).map(x=>`<li><strong>${x.id==='player'?'YOU':x.id.toUpperCase()}</strong><span>${x.points} pts</span></li>`).join('')}</ol></section>`:''}
 ${s.ownBuild.vehicle==='can-am-ryker-900'?`<section aria-label="Ryker career workshop"><div class="career-section-title"><h2>Your Ryker workshop</h2><span>OWNERSHIP SURVIVES REMOVAL</span></div><p>Stock Ryker 900 · CVT · ready for every chapter. Your Slingshot and its earned equipment are preserved.</p><a class="chapter-next" href="?scene=bay&play=career&visual=ryker&shop=build">Open the Ryker workshop →</a><div class="career-products">${RYKER_PRODUCTS.map(p=>`<article><div><span class="career-kicker">${p.brand}</span><h3>${p.name}</h3><p>${s.ownBuild.ryker?.recipe.ryker?.[p.id]?'Installed':s.ownBuild.ryker?.owned.includes(p.id)?'Owned · removed':'Available in the Ryker workshop'}</p><p>${p.option}</p><a href="?scene=bay&play=career&visual=ryker&shop=build">Inspect & configure →</a></div></article>`).join('')}</div></section>`:` <section aria-label="Career workshop"><div class="career-section-title"><h2>Your earned workshop</h2><span>OWNERSHIP SURVIVES REMOVAL</span></div><div class="career-finish"><label for="career-finish">Career finish</label><select id="career-finish" ${disabled(pending)}>${FINISHES.map(f=>`<option value="${f.id}" ${b.finish===f.id?'selected':''}>${f.name}</option>`).join('')}</select><a href="?scene=signature&screen=build&from=career${esc(recipeFragment(careerRecipe(s)))}">Inspect this build in free showroom →</a><a href="?scene=bay&play=career&shop=build">Lighting / suspension setup →</a></div><div class="career-products">${PRODUCTS.map(p=>{const retail=retailFitment(p.id),owned=productOwned(s,p.id),equipped=productEquipped(s,p.id),unlocked=productUnlocked(s,p.id),unlock=Object.values(EVENTS).find(e=>e.unlock===p.id),preview=careerRecipe(s);preview.products[p.id]=p.option;return `<article data-product="${p.id}" data-owned="${owned}" data-equipped="${equipped}"><img src="/assets/p08b/thumbnails/${p.id}.png" alt="${esc(p.brand+' '+p.name)}"><div><span class="career-kicker">${p.brand} / ${p.id}</span><h3>${p.name}</h3><p class="career-product-state">${equipped?'Installed':owned?'Owned · removed':unlocked?'Available to purchase':'Locked in career'}</p><p class="career-price">${CREDIT_TABLE[p.id]} game credits · ${esc(retail.label)}</p><p>${esc(retail.condition)}</p><p>${p.effect}</p>${!unlocked?`<p class="career-lock">Complete ${unlock?.title} to unlock ownership.</p>`:''}<div class="career-product-actions"><a href="?scene=signature&screen=build&from=career${esc(recipeFragment(preview))}">Preview in showroom</a><button data-focus="product-${p.id}" data-action="${owned?'equip':'purchase'}" data-value="${p.id}" ${disabled(pending||!owned&&(!unlocked||s.credits<CREDIT_TABLE[p.id]))}>${owned?equipped?'Remove':'Equip':`Purchase · ${CREDIT_TABLE[p.id]}`}</button></div><a class="career-external" href="${p.shopUrl}" target="_blank" rel="noopener noreferrer">${esc(retail.linkLabel)}</a></div></article>`}).join('')}</div></section>`}
 <details class="career-records"><summary>Race records and reward receipts</summary><p>Records are separated by route, event and handling tune. Earlier Chapter 01 receipts remain below; no previous time is relabeled as the current tune.</p>${b.records.length?`<ul>${b.records.slice(-12).reverse().map(r=>`<li>${r.route.toUpperCase()} · ${esc(r.competitionId)} · ${esc(r.handlingProfile)} · ${(r.timeMs/1000).toFixed(2)}s · P${r.place} · +${s.receipts[r.attemptId]?.amount??0} credits</li>`).join('')}</ul>`:'<p>No Chapter 02 record yet.</p>'}<p>Earlier receipts: ${Object.values(s.receipts).filter(r=>!r.kind.startsWith('chapter-')).map(r=>`${r.kind} ${r.amount>0?'+':''}${r.amount} (${r.handlingProfile??'legacy-p08a'})`).join(' · ')||'None yet'}</p></details>
 ${dialog?`<div class="career-dialog-backdrop"><section class="career-dialog" role="dialog" aria-modal="true" aria-labelledby="career-dialog-title"><span class="career-kicker">CREW INVITATION</span><h2 id="career-dialog-title">${ALL_EVENTS[dialog].title}</h2>${(()=>{const who=speakerOf(ALL_EVENTS[dialog].line);return who?`<div class="gx-dialog-line">${portraitMarkup(who)}<p>${ALL_EVENTS[dialog].line.replace(/^\s*[A-Z]+\s*:\s*/,'')}</p></div>`:`<p>${ALL_EVENTS[dialog].line}</p>`})()}<p>${dialog==='summit-invitational'?'Two clean laps':'One clean lap'}${dialog==='coastline-cup'?' per event. Your build stays fixed across both Cup races': ''}. No part purchase is required.</p><button data-action="start" ${disabled(pending)}>Skip dialogue · Start event</button><button data-action="later" ${disabled(pending)}>Later</button></section></div>`:''}`;
 message.textContent=notice;announceAchievements(s);announceUnlocks(s);const prog=tourProgress(s);document.body.dataset.gxChapter=String(prog.chapter);const card=root.querySelector('.gx-player'),nextCard=playerCard(prog);if(card)card.outerHTML=nextCard;else root.querySelector('.sig-header')?.insertAdjacentHTML('beforeend',nextCard);root.setAttribute('aria-busy',String(pending));for(const child of Array.from(content.children))if(child instanceof HTMLElement&&!child.classList.contains('career-dialog-backdrop'))child.inert=!!dialog;
 root.querySelector<HTMLElement>('.sig-header')!.inert=!!dialog;root.querySelector<HTMLElement>('.career-chapters')!.inert=!!dialog;
 if(dialog){dialogMenu=new BuildMenuInput(content.querySelector<HTMLElement>('.career-dialog')!,()=>{dialog=null;render()});content.querySelector<HTMLButtonElement>('[data-action=start]')?.focus()}else{dialogMenu=undefined;if(focus)content.querySelector<HTMLElement>(`[data-focus="${focus}"]`)?.focus()}
}
async function task(fn:()=>Promise<unknown>){if(pending||client.stale)return;pending=true;render();try{await fn()}catch(e){notice=(e as Error).message}finally{pending=false;render()}}
root.addEventListener('click',event=>{const button=(event.target as Element).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;const action=button.dataset.action,value=button.dataset.value;if(['home','build','quick-race','shop','career'].includes(action!)&&button.closest('.sig-header')){headerAction(action!);return}if(action==='event'){dialog=value as ChapterEvent;audio.cue('ui.nav');render();return}if(action==='later'){dialog=null;audio.cue('ui.back');render();return}void task(async()=>{
 if(action==='start'&&dialog){const attempt=await beginCareerEvent(client,dialog);client.navigate(careerRaceHref(attempt));return}
 if(action==='resume'&&client.state.ownBuild.active){client.navigate(careerRaceHref(client.state.ownBuild.active));return}
 if(action==='abandon'){await client.execute({type:'chapter-abandon'});notice='Entry abandoned. Completed receipts and owned parts are kept.';return}
 const id=value as ProductId,p=PRODUCTS.find(p=>p.id===id);if(!p)return;
 if(action==='purchase'){const result=await client.execute(id==='SM-133'?{type:'purchase',id:crypto.randomUUID(),productId:PRODUCT.id,vehicleId:p.saveVehicleId}:id==='SM-3223'?{type:'suspension-purchase',id:crypto.randomUUID(),productId:SUSPENSION.id,vehicleId:p.saveVehicleId}:{type:'chapter-purchase',id:crypto.randomUUID(),productId:id,vehicleId:p.saveVehicleId,option:p.option});if(result.changed)audio.cue(partCue[id],`career:${result.state.revision}`);notice=`${p.brand} purchased and installed. Ownership is saved.`}
 if(action==='equip'){const equipped=!productEquipped(client.state,id);const result=await client.execute(id==='SM-133'?{type:'equip',equipped}:id==='SM-3223'?{type:'suspension-equip',equipped}:{type:'chapter-equip',productId:id,equipped});notice=`${p.brand} ${equipped?'installed':'removed — still owned'}.`}
 })});
root.addEventListener('change',event=>{const select=event.target as HTMLSelectElement;if(select.id==='career-finish')void task(async()=>{const result=await client.execute({type:'chapter-finish',finish:select.value as FinishId});if(result.changed)audio.cue('finish.apply',`career:${result.state.revision}`)})});
root.addEventListener('keydown',event=>{if(dialog&&event.key==='Escape'){event.preventDefault();dialog=null;render()}if(dialog&&event.key==='Tab'){const buttons=[...content.querySelectorAll<HTMLButtonElement>('.career-dialog button')];event.preventDefault();buttons[(buttons.indexOf(document.activeElement as HTMLButtonElement)+(event.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus()}});
const unsubscribe=client.subscribe(render);render();let disposed=false;function frame(){if(disposed)return;(dialogMenu??menu).frame({keys:new Set(),pads:Array.from(navigator.getGamepads?.()??[]),focused:document.hasFocus()&&!document.hidden});requestAnimationFrame(frame)}requestAnimationFrame(frame);
if(evidenceEnabled())(window as any).__CAREER_HUB={ready:true,audioInspect:()=>audio.inspect(),startAudioCapture:()=>audio.startEvidenceCapture(),audioMarker:(id:string)=>audio.evidenceMarker(id),stopAudioCapture:()=>audio.stopEvidenceCapture(),inspect:()=>({state:structuredClone(client.state),durable:client.durable,pending,notice,dialog,recipe:careerRecipe(client.state)})};
addEventListener('pagehide',()=>{disposed=true;audio.dispose();removeEventListener('blur',audioFocus);removeEventListener('focus',audioFocus);document.removeEventListener('visibilitychange',audioFocus);unsubscribe();client.close()},{once:true});
