import type {Career} from '../career/store';
import {PRODUCTS} from '../signature/catalog';
import {RYKER_PRODUCTS} from '../signature/ryker-catalog';
import {SPYDER_PRODUCTS} from '../signature/spyder-catalog';
import {FINISHES,recipeFragment} from '../signature/config';
import {retailFitment} from '../signature/fitment';
import {careerRecipe,CREDIT_TABLE,EVENTS,productOwned,productEquipped,productUnlocked} from './model';

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

/** Render only the current vehicle's catalog. Preview links never mutate the saved career. */
export function careerWorkshop(s:Career,pending=false){
 const recipe=careerRecipe(s),b=s.ownBuild,disabled=pending?'disabled':'';
 if(recipe.vehicleId==='can-am-spyder-f3')return `<section aria-label="Spyder career workshop"><div class="career-section-title"><h2>Your Spyder workshop</h2><span>OWNERSHIP SURVIVES REMOVAL</span></div><p>Spyder F3 Custom · 1330 inline-three · ready for every chapter.</p><a class="chapter-next" href="?scene=bay&play=career&visual=spyder&shop=build">Open the Spyder workshop →</a><div class="career-products">${SPYDER_PRODUCTS.map(p=>`<article data-product="${p.id}"><div><span class="career-kicker">${esc(p.brand)} / ${esc(p.sku)}</span><h3>${esc(p.name)}</h3><p class="career-product-state">${recipe.spyder!.parts[p.id]?'Installed':b.spyder?.owned.includes(p.id)?'Owned · removed':'Available in the Spyder workshop'}</p><p>${esc(p.option)}</p><a href="?scene=bay&play=career&visual=spyder&shop=build">Inspect & configure →</a></div></article>`).join('')}</div></section>`;
 if(recipe.vehicleId==='can-am-ryker-900')return `<section aria-label="Ryker career workshop"><div class="career-section-title"><h2>Your Ryker workshop</h2><span>OWNERSHIP SURVIVES REMOVAL</span></div><p>Stock Ryker 900 · CVT · ready for every chapter. Your Slingshot and its earned equipment are preserved.</p><a class="chapter-next" href="?scene=bay&play=career&visual=ryker&shop=build">Open the Ryker workshop →</a><div class="career-products">${RYKER_PRODUCTS.map(p=>`<article><div><span class="career-kicker">${p.brand}</span><h3>${p.name}</h3><p>${recipe.ryker?.[p.id]?'Installed':b.ryker?.owned.includes(p.id)?'Owned · removed':'Available in the Ryker workshop'}</p><p>${p.option}</p><a href="?scene=bay&play=career&visual=ryker&shop=build">Inspect & configure →</a></div></article>`).join('')}</div></section>`;
 return `<section aria-label="Career workshop"><div class="career-section-title"><h2>Your earned workshop</h2><span>OWNERSHIP SURVIVES REMOVAL</span></div><div class="career-finish"><label for="career-finish">Career finish</label><select id="career-finish" ${disabled}>${FINISHES.map(f=>`<option value="${f.id}" ${b.finish===f.id?'selected':''}>${f.name}</option>`).join('')}</select><a href="?scene=signature&screen=build&from=career${esc(recipeFragment(recipe))}">Inspect this build in free showroom →</a><a href="?scene=bay&play=career&shop=build">Lighting / suspension setup →</a></div><div class="career-products">${PRODUCTS.map(p=>{const retail=retailFitment(p.id),owned=productOwned(s,p.id),equipped=productEquipped(s,p.id),unlocked=productUnlocked(s,p.id),unlock=Object.values(EVENTS).find(e=>e.unlock===p.id),preview=structuredClone(recipe);preview.products[p.id]=p.option;return `<article data-product="${p.id}" data-owned="${owned}" data-equipped="${equipped}"><img src="/assets/p08b/thumbnails/${p.id}.png" alt="${esc(p.brand+' '+p.name)}"><div><span class="career-kicker">${p.brand} / ${p.id}</span><h3>${p.name}</h3><p class="career-product-state">${equipped?'Installed':owned?'Owned · removed':unlocked?'Available to purchase':'Locked in career'}</p><p class="career-price">${CREDIT_TABLE[p.id]} game credits · ${esc(retail.label)}</p><p>${esc(retail.condition)}</p><p>${p.effect}</p>${!unlocked?`<p class="career-lock">Complete ${unlock?.title} to unlock ownership.</p>`:''}<div class="career-product-actions"><a href="?scene=signature&screen=build&from=career${esc(recipeFragment(preview))}">Preview in showroom</a><button data-focus="product-${p.id}" data-action="${owned?'equip':'purchase'}" data-value="${p.id}" ${pending||!owned&&(!unlocked||s.credits<CREDIT_TABLE[p.id])?'disabled':''}>${owned?equipped?'Remove':'Equip':`Purchase · ${CREDIT_TABLE[p.id]}`}</button></div><a class="career-external" href="${p.shopUrl}" target="_blank" rel="noopener noreferrer">${esc(retail.linkLabel)}</a></div></article>`}).join('')}</div></section>`;
}
