import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
// Isolated browser-only IndexedDB tests: synthetic fixtures, no user profile, no desktop input.
test('real IndexedDB migration, old-tab closure, concurrent tabs, aborted write/retry and corrupt protection',async()=>{
 const temp=await mkdtemp(path.join(tmpdir(),'p05-career-'));
 const entry=path.join(temp,'entry.ts');await writeFile(entry,`export * from ${JSON.stringify(process.cwd().replaceAll('\\','/')+'/src/career/store.ts')};export * from ${JSON.stringify(process.cwd().replaceAll('\\','/')+'/src/career/crew-result.ts')};`);
 const joint=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es'],fileName:'joint'}}});
 const source=(Array.isArray(joint)?joint[0]:joint).output.find(x=>x.type==='chunk').code;await rm(entry);await import('node:fs/promises').then(fs=>fs.rmdir(temp));
 const browser=await chromium.launch({headless:true});try{
 const context=await browser.newContext();await context.route('http://career.test/**',route=>route.fulfill({contentType:route.request().url().endsWith('.js')?'text/javascript':'text/html',body:route.request().url().endsWith('.js')?source:'<!doctype html><title>Isolated career test</title>'}));
 const a=await context.newPage(),b=await context.newPage();await Promise.all([a.goto('http://career.test/'),b.goto('http://career.test/')]);
 await a.evaluate(async()=>{window.mod=await import('/career.js');const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(window.mod.CAREER_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('career');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});window.oldDb=db;window.oldClosed=false;db.onversionchange=()=>{window.oldClosed=true;db.close()};const s=window.mod.freshCareer();s.version=1;delete s.crew;s.credits=300;s.owned=s.equipped=true;s.appearance={color:'cyan',brightness:.7,enabled:true};s.chapters={entry:true,firstCompletion:true,firstBuild:true};s.receipts={'11111111-1111-4111-8111-111111111111':{id:'11111111-1111-4111-8111-111111111111',kind:'award',amount:800,balance:800,first:true,at:'2026-09-11T10:00:00.000Z'}};window.oldFixture=structuredClone(s);await new Promise((resolve,reject)=>{const tx=db.transaction('career','readwrite');tx.objectStore('career').put(s,'current');tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error)});window.store=await window.mod.openCareer();});
 assert.equal(await a.evaluate(()=>window.oldClosed),true);assert.equal(await a.evaluate(()=>{try{window.oldDb.transaction('career','readwrite');return false}catch{return true}}),true);
 const migrated=await a.evaluate(async()=>{const s=await window.store.read(),old=structuredClone(s);old.version=1;delete old.crew;return {version:s.version,preserved:JSON.stringify(old)===JSON.stringify(window.oldFixture)}});assert.deepEqual(migrated,{version:2,preserved:true});
 await b.evaluate(async()=>{window.mod=await import('/career.js');window.store=await window.mod.openCareer()});
 const submit=(page,id,place)=>page.evaluate(async({id,place})=>{const result=window.mod.certifyCrewFinish({event:window.mod.CREW_EVENT,attemptId:id,participantId:'player',status:'finished',valid:true,laps:2,timeMs:160000,place});return window.store.execute({type:'crew-award',result})},{id,place});
 const id1='22222222-2222-4222-8222-222222222222',id2='33333333-3333-4333-8333-333333333333';await Promise.all([submit(a,id1,3),submit(b,id2,1)]);await Promise.all([submit(a,id1,3),submit(b,id2,1)]);const concurrent=await a.evaluate(()=>window.store.read());assert.equal(concurrent.credits,1150);assert.equal(Object.values(concurrent.receipts).filter(r=>r.chapterBonus===400).length,1);
 const failed=await a.evaluate(async()=>{window.failedProof=window.mod.certifyCrewFinish({event:window.mod.CREW_EVENT,attemptId:'44444444-4444-4444-8444-444444444444',participantId:'player',status:'finished',valid:true,laps:2,timeMs:160000,place:4});const prior=await window.store.read(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Injected failed transaction','QuotaExceededError')};let error;try{await window.store.execute({type:'crew-award',result:window.failedProof})}catch(e){error=e.message}finally{IDBObjectStore.prototype.put=put}return {error,unchanged:JSON.stringify(await window.store.read())===JSON.stringify(prior)}});assert.match(failed.error,/Injected/);assert.equal(failed.unchanged,true);await a.evaluate(()=>window.store.execute({type:'crew-award',result:window.failedProof}));await a.evaluate(()=>window.store.execute({type:'crew-award',result:window.failedProof}));assert.equal((await a.evaluate(()=>window.store.read())).credits,1250);
 // Corrupt persisted state is rejected and untouched; no fallback silently replaces it.
 await b.evaluate(()=>window.store.close());const protectedRecord=await a.evaluate(async()=>{window.store.close();const db=await new Promise(resolve=>{const r=indexedDB.open(window.mod.CAREER_DB,2);r.onsuccess=()=>resolve(r.result)});const bad={version:99,credits:1250,sentinel:'preserve me'};await new Promise(resolve=>{const tx=db.transaction('career','readwrite');tx.objectStore('career').put(bad,'current');tx.oncomplete=resolve});let error;try{await window.mod.openCareer()}catch(e){error=e.name}const raw=await new Promise(resolve=>{const r=db.transaction('career','readonly').objectStore('career').get('current');r.onsuccess=()=>resolve(r.result)});db.close();return {error,raw}});assert.equal(protectedRecord.error,'CareerDataError');assert.deepEqual(protectedRecord.raw,{version:99,credits:1250,sentinel:'preserve me'});
 const denied=await context.newPage();await denied.goto('http://career.test/');const fallback=await denied.evaluate(async()=>{const mod=await import('/career.js');Object.defineProperty(window,'indexedDB',{configurable:true,get(){throw new DOMException('Denied','SecurityError')}});const fixture=mod.freshCareer();fixture.credits=800;fixture.chapters.firstCompletion=true;const store=await mod.openCareer(fixture);await store.execute({type:'crew-award',result:mod.certifyCrewFinish({event:mod.CREW_EVENT,attemptId:'55555555-5555-4555-8555-555555555555',participantId:'player',status:'finished',valid:true,laps:2,timeMs:160000,place:2})});return {durable:store.durable,state:await store.read()}});assert.equal(fallback.durable,false);assert.equal(fallback.state.credits,1400);assert.equal(fallback.state.crew.cleared,true);
 await context.close();
 }finally{await browser.close()}
});
