import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID}from'node:crypto';
import {freshCareer,transition,MemoryCareerStore,type Command}from'../src/career/store';import{PRODUCT}from'../src/career/catalog';
const award=(id=randomUUID(),valid=true):Command=>({type:'award',id,valid,timeMs:78719.2,event:'harbor'});
const purchase=():Command=>({type:'purchase',id:randomUUID(),productId:PRODUCT.id,vehicleId:PRODUCT.vehicleId});
test('fresh unique valid awards pay 800 then100; duplicate ignores extra claimed amount and chapter never repeats',()=>{const id=randomUUID(),first=transition(freshCareer(),award(id));assert.equal(first.state.credits,800);assert.equal(first.story,'firstCompletion');const repeat=transition(first.state,{...award(id),amount:99999}as unknown as Command);assert.equal(repeat.changed,false);assert.equal(repeat.state.credits,800);assert.equal(repeat.story,undefined);const next=transition(repeat.state,award());assert.equal(next.state.credits,900);assert.equal(next.receipt?.amount,100);assert.equal(next.story,undefined)});
test('invalid, incomplete and corrupt finish payloads cannot create credits',()=>{for(const c of[award(randomUUID(),false),{...award(),timeMs:0},{...award(),timeMs:NaN},{...award(),event:'pad'}])assert.equal(transition(freshCareer(),c as Command).state.credits,0)});
test('purchase validates fitment and fixed price, atomically installs once; first loop0 800 200 300',()=>{assert.throws(()=>transition(freshCareer(),purchase()),/600/);const won=transition(freshCareer(),award()).state;assert.throws(()=>transition(won,{...purchase(),vehicleId:'other'}as Command),/fit/);assert.throws(()=>transition(won,{...purchase(),productId:'phantom'}as Command),/fit/);const bought=transition(won,{...purchase(),price:0}as unknown as Command);assert.equal(bought.state.credits,200);assert.ok(bought.state.owned&&bought.state.equipped);assert.equal(bought.story,'firstBuild');assert.deepEqual(transition(bought.state,purchase()).state,bought.state);assert.equal(transition(bought.state,award()).state.credits,300)});
test('appearance/equip mutations preserve latest credits/receipts; unowned appearance rejected',()=>{assert.throws(()=>transition(freshCareer(),{type:'appearance',patch:{color:'cyan'}}));let s=transition(transition(freshCareer(),award()).state,purchase()).state;s=transition(s,{type:'appearance',patch:{color:'cyan',brightness:.7,enabled:false}}).state;s=transition(s,{type:'equip',equipped:false}).state;s=transition(s,award()).state;s=transition(s,{type:'equip',equipped:true}).state;assert.equal(s.credits,300);assert.deepEqual(s.appearance,{color:'cyan',brightness:.7,enabled:false});assert.equal(Object.keys(s.receipts).length,3)});
test('session contract serializes concurrent awards/purchases and chapter entry claims',async()=>{const db=new MemoryCareerStore();await Promise.all([db.execute(award()),db.execute(award())]);assert.equal((await db.read()).credits,900);await Promise.all([db.execute(purchase()),db.execute(purchase())]);assert.equal((await db.read()).credits,300);const a=await db.execute({type:'entry'}),b=await db.execute({type:'entry'});assert.equal(a.story,'entry');assert.equal(b.changed,false);assert.equal(db.durable,false)});
