import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID}from 'node:crypto';
import {CrewRace,createCrewGrid,RivalController}from '../src/competition';import {sampleRoad,type CourseRoute}from '../src/course/environment';import type{VehicleTelemetry}from '../src/simulation';import routeData from '../public/assets/harbor/route.json';
const route:CourseRoute={id:'test',version:'1',name:'Test',width:11,runoff:3,length:600,centerline:[[0,0],[0,-100],[-100,-100],[-100,100],[0,100]],start:{x:0,z:5,y:.025,yaw:0},ground:{center:[0,-.15,0],size:[500,.3,500]},colliders:[],lamps:[],checkpoints:[]};route.checkpoints=[0,50,150,250,350,450,550].map((d,i)=>({...sampleRoad(route,d),id:String(i),distance:d,halfWidth:8.5}));
const ids=['maya','jett','nico','player'];
function at(d:number,offset=0):VehicleTelemetry{const p=sampleRoad(route,d);return {position:{x:p.x+offset,z:p.z,y:.48},quaternion:{x:0,y:0,z:0,w:1},velocity:{x:p.dx*60,y:0,z:p.dz*60},speed:60,wheels:[-.8,.8,0].map(x=>({localCenter:{x,y:.3,z:0},contact:true}))}as VehicleTelemetry}
const field=(d:number)=>Object.fromEntries(ids.map(id=>[id,at(d)]));
function go(r=new CrewRace(route)){r.restart(randomUUID());for(let i=0;i<180;i++)r.tick(field(-5),field(-5),1/60);return r}
function run(r:CrewRace,start=-5,end=1200){for(let d=start;d<end;d++)r.tick(field(d),field(d+1),1/60)}
test('grid fits physical full footprints, all behind line and player fourth; rejects narrow corridor',()=>{const g=createCrewGrid(routeData as CourseRoute);assert.ok(g.player.z>g.nico.z&&g.nico.z>g.jett.z);assert.throws(()=>createCrewGrid({...routeData,width:4}as CourseRoute),/Unsafe/);assert.throws(()=>createCrewGrid(route,['player','player','jett','maya']),/unique/)});
test('one countdown, freeze on pause, two ordered laps, fresh attempt IDs, terminal award proof stable',()=>{const r=new CrewRace(route);r.restart(randomUUID());r.setPaused(true);for(let i=0;i<200;i++)r.tick(field(-5),field(-5),1/60);assert.equal(r.snapshot().countdown,3);assert.equal(r.control('player',{throttle:1,brake:0,steer:1,reverse:true}).throttle,0);r.setPaused(false);for(let i=0;i<180;i++)r.tick(field(-5),field(-5),1/60);run(r,-5,600);assert.equal(r.snapshot().playerResult,null);assert.equal(r.snapshot().standings[0].lap,2);run(r,600,1200);const result=r.snapshot().playerResult;assert.equal(result?.valid,true);assert.equal(result?.laps,2);assert.ok(r.awardProof());const proof=r.awardProof();for(let i=0;i<10;i++)r.tick(field(1199),field(1201),1/60);assert.deepEqual(r.snapshot().playerResult,result);assert.equal(r.awardProof(),proof);assert.throws(()=>r.restart(result!.attemptId),/fresh/);r.restart(randomUUID());assert.equal(r.awardProof(),null);assert.equal(r.snapshot().elapsedMs,0)});
test('close finishes sort true fractions across all participants rather than insertion order; exact tie lexical',()=>{const r=go(new CrewRace(route,['player','nico','maya','jett']));run(r,-5,1199);const before=field(1199),after={player:at(1200.2),nico:at(1201),maya:at(1203),jett:at(1202)};r.tick(before,after,1/60);assert.deepEqual(r.snapshot().standings.map(s=>s.id),['maya','jett','nico','player']);assert.ok(r.snapshot().standings[0].timeMs!<r.snapshot().standings[1].timeMs!);const tie=go();run(tie);assert.deepEqual(tie.snapshot().standings.map(s=>s.id),['jett','maya','nico','player'])});
test('reverse, skipped gates, relocation and sustained tire cut invalidate only their own car with no proof',()=>{for(const mode of ['reverse','skip','relocate','cut']){const r=go(),a=field(-5),b=field(-5);if(mode==='reverse'){a.player=at(1);b.player=at(-1)}if(mode==='skip'){a.player=at(149);b.player=at(151)}if(mode==='relocate')b.player=at(300);if(mode==='cut')a.player=b.player=at(-5,15);for(let i=0;i<(mode==='cut'?22:1);i++)r.tick(a,b,1/60);assert.equal(r.snapshot().playerResult?.valid,false,mode);assert.equal(r.snapshot().playerResult?.timeMs,null,mode);assert.equal(r.awardProof(),null);assert.equal(r.snapshot().standings.find(s=>s.id==='maya')?.status,'running')}});
test('lap wrap and lapped cars rank by validated progress; postfinish rivals remain running then explicit DNF',()=>{const r=go();for(let d=-5;d<1200;d++){const a=field(-5),b=field(-5);a.player=at(d);b.player=at(d+1);if(d>=600){a.maya=at(d-605);b.maya=at(d-604)}r.tick(a,b,1/60);if(d===601)assert.equal(r.snapshot().standings[0].id,'player')}assert.equal(r.snapshot().playerResult?.place,1);assert.equal(r.snapshot().standings.find(s=>s.id==='maya')?.status,'running');for(let i=0;i<1800;i++)r.tick(field(-5),field(-5),1/60);assert.equal(r.snapshot().standings.find(s=>s.id==='nico')?.status,'dnf');assert.equal(r.snapshot().standings.find(s=>s.id==='nico')?.timeMs,null)});
test('aborted and stranded statuses never synthesize finish times or awards',()=>{const r=go();r.retire('maya','Blocked');assert.equal(r.snapshot().standings.find(s=>s.id==='maya')?.status,'dnf');r.abort();assert.equal(r.snapshot().playerResult?.status,'unfinished');assert.equal(r.awardProof(),null)});
function straight(z:number,speed=15,x=0){const t=at(-z);t.position={x,y:.48,z};t.velocity={x:0,y:0,z:-speed};t.speed=speed;return t}
test('control-only rivals brake for blockers, hold a passing side, and leave occupied adjacent corridors',()=>{const r=new RivalController(routeData as CourseRoute,'nico',11),v=straight(-50),front=straight(-59,5),left=straight(-49,15,-2.7),right=straight(-49,15,2.7),peers={nico:v,player:front,maya:left,jett:right},copy=structuredClone(peers);let c=r.control(v,peers);assert.ok(c.brake>.5);for(let i=0;i<60;i++)c=r.control(v,peers);assert.notEqual(r.inspect().mode,'pass');assert.deepEqual(peers,copy);const open={nico:v,player:front};for(let i=0;i<70;i++)r.control(v,open);assert.equal(r.inspect().mode,'pass');const held=r.inspect().targetLane;for(let i=0;i<90;i++)r.control(v,open);assert.equal(r.inspect().targetLane,held);assert.ok(Math.abs(held)<=2.7)});
test('physically stuck controller tries reverse then retires rather than writing poses',()=>{const r=new RivalController(routeData as CourseRoute,'jett',8),v=straight(-70,0),peers={jett:v};let reverse=false;for(let i=0;i<60*40;i++){const c=r.control(v,peers);reverse ||=c.reverse}assert.equal(reverse,true);assert.match(r.inspect().retiredReason!,/Stranded/);assert.equal(v.position.z,-70)});

