import test from 'node:test';import assert from 'node:assert/strict';
import {CrewUI} from '../src/crew-ui';import type{DeviceSample,PadSample}from'../src/driving/input';
const pad=(id:string,held:number[]=[],index=0):PadSample=>({index,id,connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},(_,i)=>({value:held.includes(i)?1:0,pressed:held.includes(i)}))});
const sample=(pads:PadSample[],focused=true,keys:string[]=[]):DeviceSample=>({pads,focused,keys:new Set(keys)});
function harness(){const priorElement=Object.getOwnPropertyDescriptor(globalThis,'Element'),priorDocument=Object.getOwnPropertyDescriptor(globalThis,'document');class ElementStub{closest(){return null}}Object.defineProperty(globalThis,'Element',{configurable:true,value:ElementStub});Object.defineProperty(globalThis,'document',{configurable:true,value:{activeElement:null}});const actions:string[]=[];
 // Exercise the actual production menu method without creating a WebGL renderer or browser.
 const ui=Object.assign(Object.create(CrewUI.prototype),{armed:false,padKey:'',confirm:false,back:false,action:(a:string)=>actions.push(a)})as CrewUI;
 return{ui,actions,run:(s:DeviceSample)=>ui.menuInput(s,{phase:'ready',paused:true}as any),restore(){if(priorElement)Object.defineProperty(globalThis,'Element',priorElement);else delete(globalThis as any).Element;if(priorDocument)Object.defineProperty(globalThis,'document',priorDocument);else delete(globalThis as any).document}};
}
test('crew menu rejects held replacement controller after disconnect until focused neutral',()=>{const h=harness();try{h.run(sample([pad('old')]));h.run(sample([]));h.run(sample([pad('replacement',[1])]));h.run(sample([pad('replacement',[1])]));assert.deepEqual(h.actions,[]);h.run(sample([pad('replacement')]));h.run(sample([pad('replacement',[1])]));assert.deepEqual(h.actions,['bay'])}finally{h.restore()}});
test('controller identity change without an empty frame cannot inherit old menu arming',()=>{const h=harness();try{h.run(sample([pad('old')]));h.run(sample([pad('replacement',[0],1)]));assert.deepEqual(h.actions,[]);h.run(sample([pad('replacement',[],1)]));h.run(sample([pad('replacement',[0],1)]));assert.deepEqual(h.actions,['resume']);h.run(sample([pad('replacement',[0],1)]));assert.deepEqual(h.actions,['resume'])}finally{h.restore()}});
test('unfocused neutral does not arm the menu; focus return with held control stays blocked',()=>{const h=harness();try{h.run(sample([pad('pad')]));h.run(sample([pad('pad')],false));h.run(sample([pad('pad',[1])],true));assert.deepEqual(h.actions,[]);h.run(sample([pad('pad')],true));h.run(sample([pad('pad',[1])],true));assert.deepEqual(h.actions,['bay'])}finally{h.restore()}});
test('explicit lifecycle suspension catches same-identity reconnect between render samples',()=>{const h=harness();try{h.run(sample([pad('same')]));h.ui.suspendInput();h.run(sample([pad('same',[0])]));assert.deepEqual(h.actions,[]);h.run(sample([pad('same')]));h.run(sample([pad('same',[0])]));assert.deepEqual(h.actions,['resume'])}finally{h.restore()}});
test('bare keyboard confirmation still works with absent or held unarmed controller',()=>{const h=harness();try{h.run(sample([],true,['Enter']));assert.deepEqual(h.actions,['resume']);h.run(sample([]));h.run(sample([pad('new',[1])],true,['Enter']));assert.deepEqual(h.actions,['resume','resume'])}finally{h.restore()}});
