import {test} from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {Simulation} from '../src/simulation';import {DrivingSession,PRACTICE_START} from '../src/driving/session';import {ChaseCamera} from '../src/presentation/chase';import {practiceSample} from './fixtures/practice-trace';
import {writeFileSync} from 'node:fs';
test('ordinary session: direction request goes through retained braking interlock; reset/pause do not latch throttle',async()=>{const sim=await Simulation.create();try{let sample=practiceSample(0);const s=new DrivingSession(sim,()=>sample);s.reset();for(let i=0;i<=300;i++){sample=practiceSample(i/60);s.frame(i*1000/60)}assert.ok(s.current.speed>5);sample=practiceSample(23.05);sample.pads[0]!.buttons[7].value=.8;const pending=s.frame(301*1000/60);assert.equal(pending.current.reversePending,true);assert.ok(pending.current.gear>0);assert.equal(pending.current.throttle,0);assert.ok(pending.current.brake>=.6);for(let i=302;i<540;i++)s.frame(i*1000/60);assert.equal(s.current.gear,-1);s.reset();assert.equal(s.current.position.x,PRACTICE_START.x);assert.equal(s.input.armed,false);assert.equal(s.input.reverse,false)}finally{sim.dispose()}});
test('camera: same fixed-physics maneuver across 30/60/120/144Hz presentation, finite horizon and continuous switches',async()=>{
 const sim=await Simulation.create();const trace:{p:THREE.Vector3;q:THREE.Quaternion;speed:number;far:boolean;lookBack:boolean;reset:boolean}[]=[];
 try{let sample=practiceSample(0);const session=new DrivingSession(sim,()=>sample);session.reset();let far=false;
 for(let i=0;i<=1800;i++){sample=practiceSample(i/60);const r=session.frame(i*1000/60);if(r.camera)far=!far;trace.push({p:new THREE.Vector3(r.current.position.x,r.current.position.y,r.current.position.z),q:new THREE.Quaternion(r.current.quaternion.x,r.current.quaternion.y,r.current.quaternion.z,r.current.quaternion.w),speed:r.current.speed,far,lookBack:r.lookBack,reset:r.reset})}
 const runs=[];for(const hz of [30,60,120,144]){const camera=new THREE.PerspectiveCamera(38,1.5,.05,700),chase=new ChaseCamera(camera),samples=[];let previous=new THREE.Vector3(),maximumStep=0,resetTime=-10;
 for(let f=0;f<=30*hz;f++){const time=f/hz,index=Math.min(1800,Math.floor(time*60+1e-8)),a=trace[index],b=trace[Math.min(index+1,1800)],alpha=Math.max(0,time*60-index);if(a.reset)resetTime=time;const p=a.p.clone().lerp(b.p,alpha),q=a.q.clone().slerp(b.q,alpha);const r=chase.update(p,q,a.speed,1/hz,a.far,a.lookBack,f===0||a.reset);assert.ok([...r.position,...r.target,r.fov,...camera.quaternion.toArray()].every(Number.isFinite));assert.deepEqual(camera.up.toArray(),[0,1,0]);if(f>0&&Math.abs(time-29.2)>.15&&time-resetTime>.15)maximumStep=Math.max(maximumStep,previous.distanceTo(camera.position));previous.copy(camera.position);if(f%hz===0)samples.push({time,...r})}
 assert.ok(maximumStep<1.5,`ordinary ${hz}Hz camera step ${maximumStep}`);runs.push({hz,maximumStep,samples})}
 const baseline=runs[1];const deviations=runs.map(run=>{let position=0,target=0,fov=0;run.samples.forEach((s,i)=>{if(s.time>=29)return;position=Math.max(position,new THREE.Vector3().fromArray(s.position).distanceTo(new THREE.Vector3().fromArray(baseline.samples[i].position)));target=Math.max(target,new THREE.Vector3().fromArray(s.target).distanceTo(new THREE.Vector3().fromArray(baseline.samples[i].target)));fov=Math.max(fov,Math.abs(s.fov-baseline.samples[i].fov))});assert.ok(position<.45&&target<.15&&fov<.15,JSON.stringify({hz:run.hz,position,target,fov}));return{hz:run.hz,position,target,fov}});
 // After look-back releases at16.5s, the18s view is behind the moving chassis again.
 for(const run of runs){const c=run.samples[18],body=trace[18*60],offset=new THREE.Vector3().fromArray(c.position).sub(body.p),back=new THREE.Vector3(0,0,1).applyQuaternion(body.q);assert.ok(offset.dot(back)>4);assert.equal(c.lookBack,false)}
 if(process.env.CAMERA_REPORT)writeFileSync(process.env.CAMERA_REPORT,JSON.stringify({method:'One input/session trace at60Hz authoritative physics; interpolated same chassis poses at30/60/120/144 presentation schedules; no hardware FPS claim',tolerances:{positionM:.45,targetM:.15,fovDeg:.15,ordinaryMaxStepM:1.5},deviations,runs},null,2));
 }finally{sim.dispose()}
});
