import test from 'node:test';import assert from 'node:assert/strict';
import {RaceAttempt,crossGate}from'../src/race/attempt';import {sampleRoad,type CourseRoute}from'../src/course/environment';import type {VehicleTelemetry}from'../src/simulation';
const route:CourseRoute={id:'test',version:'1',name:'Test',width:11,runoff:3,length:600,centerline:[[0,0],[0,-100],[-100,-100],[-100,100],[0,100]],start:{x:0,z:5,y:.025,yaw:0},ground:{center:[0,-.15,0],size:[500,.3,500]},colliders:[],lamps:[],checkpoints:[]};
route.checkpoints=[0,50,150,250,350,450,550].map((d,i)=>({...sampleRoad(route,d),id:String(i),distance:d,halfWidth:8.5}));
const at=(distance:number,offset=0):VehicleTelemetry=>{const p=sampleRoad(route,distance);return {position:{x:p.x+offset,z:p.z,y:.025},quaternion:{x:0,y:0,z:0,w:1},speed:60,wheels:[-.8,.8,0].map(x=>({localCenter:{x,y:.3,z:0},contact:true}))}as VehicleTelemetry};
function go(r:RaceAttempt){r.start();for(let i=0;i<180;i++)r.tick(at(-5),at(-5),1/60);assert.equal(r.snapshot().phase,'running')}
function lap(r:RaceAttempt,start=-5,end=601){for(let d=start;d<end;d++)r.tick(at(d),at(d+1),1/60)}
test('countdown holds normal controls, initial crossing is not finish; ordered lap interpolates and commits once',()=>{const r=new RaceAttempt(route,'day');r.start();assert.deepEqual(r.control({throttle:1,brake:0,steer:1,reverse:true}),{throttle:0,brake:1,steer:0,reverse:false,tractionControl:true});for(let i=0;i<180;i++)r.tick(at(-5),at(-5),1/60);lap(r,-5,1);assert.equal(r.snapshot().phase,'running');lap(r,1,599);r.tick(at(599),at(601),1/60);const result=r.snapshot().result!;assert.equal(result.valid,true);assert.equal(result.firstRecord,true);assert.ok(Math.abs(result.timeMs-(604+.5)*1000/60)<1e-7);r.tick(at(599),at(601),1/60);assert.deepEqual(r.snapshot().result,result);r.restart();assert.equal(r.snapshot().elapsedMs,0);assert.equal(r.snapshot().checkpoint,0);assert.equal(r.snapshot().attempt,2)});
test('backward finish, missing gate, teleport and interior shortcut cannot earn a best',()=>{const backward=new RaceAttempt(route,'day');go(backward);backward.tick(at(1),at(-1),1/60);assert.match(backward.snapshot().invalidReason!,/backward/);const skip=new RaceAttempt(route,'day');go(skip);lap(skip,-5,20);skip.tick(at(20),at(151),1/60);lap(skip,151,601);assert.equal(skip.snapshot().result,null);assert.notEqual(skip.snapshot().invalidReason,null);const short=new RaceAttempt(route,'day');go(short);lap(short,-5,10);short.tick(at(10),at(590),1/60);lap(short,590,601);assert.notEqual(short.snapshot().invalidReason,null);assert.equal(short.snapshot().result,null)});
test('two tires beyond runoff require over .35 seconds; invalid retains practice clock, never records',()=>{const r=new RaceAttempt(route,'day');go(r);for(let i=0;i<21;i++)r.tick(at(-5,15),at(-5,15),1/60);assert.equal(r.snapshot().invalidReason,null);r.tick(at(-5,15),at(-5,15),1/60);assert.match(r.snapshot().invalidReason!,/Track limits/);const before=r.snapshot().elapsedMs;lap(r);assert.equal(r.snapshot().result?.valid,false);assert.ok(r.snapshot().elapsedMs>before);assert.equal(r.snapshot().result?.newBest,false)});
test('pause freezes countdown and lap clock; retry clears invalid and retains prior compatible best',()=>{const r=new RaceAttempt(route,'night',12000);r.start();r.setPaused(true);for(let i=0;i<120;i++)r.tick(at(-5),at(-5),1/60);assert.equal(r.snapshot().countdown,3);r.setPaused(false);for(let i=0;i<180;i++)r.tick(at(-5),at(-5),1/60);r.setPaused(true);lap(r);assert.equal(r.snapshot().elapsedMs,0);r.setPaused(false);lap(r);assert.equal(r.snapshot().result?.previousBestMs,12000);r.restart();assert.equal(r.snapshot().invalidReason,null);assert.equal(r.snapshot().result,null)});
test('directed plane test spans a whole tick and rejects crossing beyond the gate width',()=>{const g=route.checkpoints[0];assert.deepEqual(crossGate(g,{x:0,z:2},{x:0,z:-6}),{fraction:.25,forward:true});assert.equal(crossGate(g,{x:9,z:2},{x:9,z:-6}),null);assert.equal(crossGate(g,{x:0,z:-2},{x:0,z:6})?.forward,false)});
