import {test} from 'node:test';import assert from 'node:assert/strict';
import {InputResolver,KeyboardBuffer,stickSteering,type PadSample} from '../src/driving/input';
const pad=(axis=0,throttle=0,brake=0,buttons:number[]=[],id='test'):PadSample=>({index:0,id,mapping:'standard',connected:true,axes:[axis],buttons:Array.from({length:17},(_,i)=>({value:i===7?throttle:i===6?brake:buttons.includes(i)?1:0,pressed:buttons.includes(i)}))});
function rig(){const input=new InputResolver();let now=0;return {input,poll:(keys:string[]=[],pads:(PadSample|null)[]=[pad()],dt=16,focused=true)=>input.poll(now+=dt,{keys:new Set(keys),pads,focused})}}
test('input: signed fractional stick, rescaled deadzone, analog triggers and finite sanitation',()=>{const r=rig();r.poll();let s=r.poll([],[pad(-.4,.37,.18)]);assert.equal(s.control.steer,stickSteering(-.4));assert.ok(s.control.steer>0&&s.control.steer<1);assert.equal(s.control.throttle,.37);assert.equal(s.control.brake,.18);s=r.poll([],[pad(.4,NaN,Infinity)]);assert.ok(s.control.steer<0);assert.equal(s.control.throttle,0);assert.equal(s.control.brake,0);assert.equal(stickSteering(.08),0);assert.equal(stickSteering(NaN),0)});
test('input: changed meaningful ownership, noisy drift and unsupported mappings',()=>{const r=rig();r.poll();assert.equal(r.poll(['KeyW'],[pad(.04)]).activeDevice,'keyboard');assert.ok(r.poll(['KeyW'],[pad(-.4)]).activeDevice.startsWith('pad:'));assert.equal(r.poll(['KeyW'],[pad(-.4)]).control.throttle,0);assert.equal(r.poll(['KeyD'],[pad(-.4)]).activeDevice,'keyboard');const p=pad();p.mapping='';const x=r.poll(['KeyW'],[null,p]);assert.match(x.status,/Unrecognized/);assert.equal(x.control.throttle,1)});
test('input: rising camera/direction edges and continuous monotonic reset hold fires once',()=>{const r=rig();r.poll();assert.equal(r.poll(['KeyC']).camera,true);assert.equal(r.poll(['KeyC']).camera,false);r.poll();assert.equal(r.poll(['KeyX']).control.reverse,true);assert.equal(r.poll(['KeyX']).control.reverse,true);r.poll();assert.equal(r.poll(['KeyR']).reset,false);assert.equal(r.poll(['KeyR'],[pad()],999).reset,false);assert.equal(r.poll(['KeyR'],[pad()],1).reset,true);assert.equal(r.poll(['KeyR'],[pad()],2000).reset,false);assert.equal(r.poll(['KeyR']).control.throttle,0);r.poll();assert.equal(r.input.armed,true);assert.equal(r.input.reverse,false)});
test('input: pause/menu poll, neutral resume, interrupted hold, blur and held-button quarantine',()=>{const r=rig();r.poll();r.poll(['KeyR']);r.poll(['KeyR'],[pad()],800);assert.equal(r.poll(['Escape']).paused,true);assert.equal(r.poll(['Escape'],[pad()],2000).paused,true);r.poll();assert.equal(r.poll(['Escape','KeyW']).paused,false);assert.equal(r.poll(['KeyW']).control.throttle,0);r.poll();assert.equal(r.poll(['KeyW']).control.throttle,1);r.poll(['KeyR']);assert.equal(r.poll(['KeyR'],[pad()],300).reset,false);r.poll([],[],16,false);assert.equal(r.poll(['KeyW']).paused,true);r.poll();assert.equal(r.poll(['Escape']).paused,false);r.poll();assert.equal(r.poll(['KeyR']).reset,false);assert.equal(r.poll(['KeyR'],[pad()],999).reset,false)});
test('input: disconnect/index reuse and held throttle require neutral plus deliberate resume',()=>{const r=rig();r.poll();r.poll([],[pad(0,.5)]);let s=r.poll([],[null]);assert.equal(s.paused,true);assert.equal(s.control.throttle,0);s=r.poll([],[pad(0,.9,0,[],'replacement')]);assert.equal(s.control.throttle,0);r.poll(['Escape'],[pad(0,.9,0,[],'replacement')]);assert.equal(r.poll([],[pad(0,.9,0,[],'replacement')]).control.throttle,0);r.poll([],[pad(0,0,0,[],'replacement')]);assert.equal(r.poll([],[pad(0,.3,0,[],'replacement')]).control.throttle,.3)});
test('input: held new controller gesture does not trigger camera/throttle on scene entry',()=>{const r=rig();assert.equal(r.poll([],[pad(0,.8,0,[3])]).camera,false);assert.equal(r.poll([],[pad(0,.8,0,[3])]).control.throttle,0);r.poll();assert.equal(r.poll([],[pad(0,.4,0,[3])]).camera,true)});

test('input: a deliberate slow analog ramp takes ownership without per-frame threshold starvation',()=>{const r=rig();r.poll();for(let i=1;i<=100;i++)r.poll([],[pad(0,i/100)]);assert.ok(r.input.activeDevice.startsWith('pad:'));assert.equal(r.poll([],[pad(0,1)]).control.throttle,1);const k=rig();k.poll();for(let i=1;i<=40;i++)k.poll([],[pad(-i/100)]);assert.ok(k.input.activeDevice.startsWith('pad:'));assert.ok(k.poll([],[pad(-.4)]).control.steer>0)});

test('input: a fresh menu edge can reclaim keyboard while another key remains held',()=>{const r=rig();r.poll();r.poll(['KeyW','KeyC']);r.poll(['KeyW']);assert.ok(r.poll(['KeyW'],[pad(-.4)]).activeDevice.startsWith('pad:'));const c=r.poll(['KeyW','KeyC'],[pad(-.4)]);assert.equal(c.activeDevice,'keyboard');assert.equal(c.camera,true)});

test('keyboard event buffer: short released taps survive a frame and held repeats do not retoggle',()=>{const k=new KeyboardBuffer(),input=new InputResolver();const poll=(now:number)=>input.poll(now,{...k.read(),pads:[],focused:true});poll(0);k.down('Escape',10);k.up('Escape');assert.equal(poll(100).paused,true);assert.equal(poll(120).paused,true);k.down('Escape',130);k.up('Escape');assert.equal(poll(200).paused,false);k.down('KeyC',210);k.up('KeyC');assert.equal(poll(250).camera,true);k.down('KeyC',260);assert.equal(poll(280).camera,true);k.down('KeyC',290,true);assert.equal(poll(310).camera,false)});
test('keyboard reset uses monotonic down time and a fresh hold after interruption',()=>{const k=new KeyboardBuffer(),input=new InputResolver();const poll=(now:number)=>input.poll(now,{...k.read(),pads:[],focused:true});poll(0);k.down('KeyR',10);assert.equal(poll(900).reset,false);assert.equal(poll(1010).reset,true);assert.equal(poll(2500).reset,false);k.up('KeyR');poll(2520);k.down('KeyR',2600);poll(2700);k.up('KeyR');poll(2900);k.down('KeyR',3000);assert.equal(poll(3900).reset,false);assert.equal(poll(4000).reset,true)});

test('keyboard release and repress between rendered frames restarts continuous reset hold',()=>{const r=new InputResolver(),k=new KeyboardBuffer();const poll=(t:number)=>r.poll(t,{...k.read(),pads:[],focused:true});poll(0);k.down('KeyR',10);poll(500);k.up('KeyR');k.down('KeyR',700);assert.equal(poll(1010).reset,false);assert.equal(poll(1699).reset,false);assert.equal(poll(1700).reset,true)});
