import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm,rmdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
test('suspension writes block parent navigation; failed write keeps credits; controller buttons tune and stock comparison is reversible',async()=>{
 const root=process.cwd().replaceAll('\\','/'),temp=await mkdtemp(path.join(tmpdir(),'p08-ui-')),entry=path.join(temp,'entry.ts');await writeFile(entry,`export {BuildUI} from ${JSON.stringify(root+'/src/career/build-ui.ts')};export {MemoryCareerStore,freshCareer} from ${JSON.stringify(root+'/src/career/store.ts')};`);
 let js,css;try{const result=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es']}}}),o=(Array.isArray(result)?result[0]:result).output;js=o.find(x=>x.type==='chunk').code;css=o.filter(x=>x.type==='asset'&&x.fileName.endsWith('.css')).map(x=>x.source).join('\n')}finally{await rm(entry);await rmdir(temp)}
 const html=`<!doctype html><style>body{margin:0}#app{height:100vh}${css}</style><div id="app"></div><script type="module">import{BuildUI,MemoryCareerStore,freshCareer}from'/ui.js';let fixture=freshCareer();fixture.credits=1800;const store=new MemoryCareerStore(fixture);let state=await store.read();const listeners=new Set();window.client={get state(){return state},stale:false,durable:false,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},async execute(c){if(c.type==='suspension-purchase'&&window.hold)await new Promise((resolve,reject)=>{window.resolveWrite=resolve;window.rejectWrite=reject});const r=await store.execute(c);state=r.state;listeners.forEach(f=>f());return r}};window.ui=new BuildUI(client,{open(){},appearance(){},previewNight(){},suspension(value){window.visible=value}});ui.open();window.ready=true;</script>`;
 const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1280,height:720}}),p=await c.newPage();p.on('pageerror',e=>console.log('P08 UI error:',e.message));try{await c.route('http://127.0.0.1:42972/**',r=>r.fulfill({contentType:r.request().url().endsWith('ui.js')?'text/javascript':'text/html',body:r.request().url().endsWith('ui.js')?js:html}));await p.goto('http://127.0.0.1:42972/');await p.waitForFunction(()=>window.ready);await p.evaluate(()=>window.hold=true);await p.locator('#buy-suspension').click();await p.waitForFunction(()=>window.ui.inspect().pending);assert.deepEqual(await p.evaluate(()=>{ui.close();document.querySelector('#drive-kit-night').click();return{open:ui.inspect().open,pending:ui.inspect().pending,credits:client.state.credits,disabled:document.querySelector('#close-build').disabled}}),{open:true,pending:true,credits:1800,disabled:true});assert.equal(p.url(),'http://127.0.0.1:42972/');await p.evaluate(()=>window.rejectWrite(Error('Deliberate suspension write failure')));await p.waitForFunction(()=>!window.ui.inspect().pending);assert.equal(await p.evaluate(()=>client.state.credits),1800);assert.match(await p.locator('#suspension-feedback').textContent(),/Deliberate/);
 await p.evaluate(()=>window.hold=false);await p.locator('#buy-suspension').click();await p.waitForFunction(()=>client.state.suspension.owned&&!ui.inspect().pending);assert.equal(await p.evaluate(()=>client.state.credits),800);
 await p.getByRole('button',{name:'Increase Front compression',exact:true}).focus();await p.evaluate(()=>{const sample=held=>({focused:true,keys:new Set(),pads:[{id:'P08 controller test',index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},(_,i)=>({value:held===i?1:0,pressed:held===i}))}]});ui.frame(sample(-1));ui.frame(sample(0));ui.frame(sample(-1))});await p.waitForFunction(()=>client.state.suspension.setup.frontCompression===3&&!ui.inspect().pending);await p.locator('#compare-suspension').click();assert.equal(await p.evaluate(()=>window.visible),false);assert.equal(await p.evaluate(()=>client.state.suspension.equipped),true);await p.locator('#close-build').click();assert.equal(await p.evaluate(()=>window.visible),true);
 }finally{await c.close();await b.close()}
});


