import {test} from 'node:test';import assert from 'node:assert/strict';
import {InputResolver,type PadSample} from '../src/driving/input';import {Simulation,steeringLimit,HANDLING_PROFILES} from '../src/simulation';
import {streetSetup} from '../src/career/suspension';
const pad=(throttle=0,brake=0):PadSample=>({index:0,id:'test',mapping:'standard',connected:true,axes:[0],buttons:Array.from({length:17},(_,i)=>({value:i===7?throttle:i===6?brake:0}))});
function rig(){const input=new InputResolver('slingmods-sport-v1');let now=0;return {input,poll:(keys:string[]=[],speed=0,pads:PadSample[]=[])=>input.poll(now+=17,{keys:new Set(keys),pads,focused:true},speed)}}
test('Sport brake to stop stays forward until release and fresh brake; forward uses the same deliberate transition',()=>{const r=rig();r.poll();r.poll(['KeyW'],12);let s=r.poll(['KeyS'],8);assert.equal(s.direction,'D');assert.equal(s.control.brake,1);s=r.poll(['KeyS'],0);assert.equal(s.direction,'D');r.poll([],0);s=r.poll(['KeyS'],0);assert.equal(s.direction,'R');assert.equal(s.control.throttle,1);assert.equal(s.control.brake,0);s=r.poll(['KeyW'],-3);assert.equal(s.direction,'R');assert.equal(s.control.brake,1);s=r.poll(['KeyW'],0);assert.equal(s.direction,'R');r.poll([],0);s=r.poll(['KeyW'],0);assert.equal(s.direction,'D');assert.equal(s.control.throttle,1)});
test('Sport analog reverse works on first fresh controller ownership and keeps analog magnitude',()=>{const r=rig();r.poll([],0,[pad()]);const reverse=r.poll([],0,[pad(0,.37)]);assert.equal(reverse.direction,'R');assert.equal(reverse.control.throttle,.37);assert.equal(reverse.control.brake,0);r.poll([],0,[pad()]);const forward=r.poll([],0,[pad(.42)]);assert.equal(forward.direction,'D');assert.equal(forward.control.throttle,.42)});
test('Sport explicit direction keeps established explicit pedal mapping and reset clears reverse',()=>{const r=rig();r.poll();r.poll(['KeyX']);let s=r.poll(['KeyW']);assert.equal(s.direction,'R');assert.equal(s.control.throttle,1);s=r.poll(['KeyS']);assert.equal(s.control.brake,1);r.input.reset();r.poll();s=r.poll(['KeyW']);assert.equal(s.direction,'D');assert.equal(s.control.throttle,1)});
test('Sport pause cannot inherit held pedals into a direction change',()=>{const r=rig();r.poll();r.poll(['KeyW'],10);r.poll(['Escape'],8);r.poll(['KeyS'],0);r.poll(['Escape','KeyS'],0);assert.equal(r.poll(['KeyS'],0).control.throttle,0);r.poll([],0);assert.equal(r.poll(['KeyS'],0).direction,'R')});
test('Sport direction stays deliberate with simultaneous pedals, disconnect and focus loss',()=>{const r=rig();r.poll([],0,[pad()]);assert.equal(r.poll(['KeyW','KeyS'],0,[pad()]).direction,'D');r.poll([],0,[pad()]);r.poll([],0,[pad(0,.7)]);assert.equal(r.input.reverse,true);r.poll([],0,[]);assert.equal(r.input.paused,true);assert.equal(r.poll([],0,[pad(0,.7)]).control.throttle,0);r.poll(['Escape'],0,[pad(0,.7)]);assert.equal(r.poll([],0,[pad(0,.7)]).control.throttle,0);r.poll([],0,[pad()]);assert.equal(r.poll([],0,[pad(0,.4)]).control.throttle,.4);r.input.poll(1000,{keys:new Set(),pads:[pad(0,.4)],focused:false},-2);assert.equal(r.input.paused,true);assert.equal(r.poll([],0,[pad(0,.4)]).control.throttle,0)});
test('Sport brake-reverse produces negative displacement and steering follows reverse orientation',async()=>{const environment={ground:{center:[0,-.15,0],size:[300,.3,300]},obstacles:[],ramps:[],surfaceAt:()=>({id:'asphalt',mu:1.05,rolling:.014})};for(const direction of[1,-1]){const sim=await Simulation.create(environment,'slingmods-sport-v1'),r=rig();sim.reset({x:0,y:.025,z:0});r.poll();for(let i=0;i<120;i++){const s=r.poll([direction<0?'KeyS':'KeyW','KeyA'],sim.telemetry().speed);sim.step(s.control)}const t=sim.telemetry(),q=t.quaternion,yaw=Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z));assert.ok(t.speed*direction>1);assert.ok(yaw*direction>.2,JSON.stringify({direction,yaw,t}));assert.ok(t.wheels.every(w=>w.contact));if(direction<0)assert.ok(t.position.z>1);sim.dispose()}});
test('Legacy remains default and explicit legacy telemetry is exactly equal for stock driving',async()=>{const a=await Simulation.create(),b=await Simulation.create(undefined,'legacy-p08a');for(let i=0;i<1200;i++){const c={throttle:i<480?.7:0,brake:i>=900?.5:0,steer:i>300&&i<650?.15:0,reverse:false};a.step(c);b.step(c);assert.deepEqual(a.telemetry(),b.telemetry())}a.dispose();b.dispose();assert.equal(HANDLING_PROFILES['legacy-p08a'].damperFront,HANDLING_PROFILES['slingmods-sport-v1'].damperFront)});
test('Sport steering requests more medium-speed authority while retaining a falling high-speed cap',()=>{assert.ok(steeringLimit(20,'slingmods-sport-v1')>steeringLimit(20));assert.ok(steeringLimit(45,'slingmods-sport-v1')<steeringLimit(20,'slingmods-sport-v1'));assert.throws(()=>steeringLimit(0,'invented' as any),/Unknown/)})
test('Sport street estimate and uninstalled suspension restore active Sport stock tick for tick',async()=>{const stock=await Simulation.create(undefined,'slingmods-sport-v1'),street=await Simulation.create(undefined,'slingmods-sport-v1'),removed=await Simulation.create(undefined,'slingmods-sport-v1');street.configureSuspension(streetSetup());removed.configureSuspension({...streetSetup(),frontCompression:12,rideHeightMm:10});removed.configureSuspension(null);for(let i=0;i<1200;i++){const c={throttle:i<650?.7:0,brake:i>=900?.5:0,steer:i>350&&i<700?.15:0,reverse:false};stock.step(c);street.step(c);removed.step(c);assert.deepEqual(street.telemetry(),stock.telemetry());assert.deepEqual(removed.telemetry(),stock.telemetry())}stock.dispose();street.dispose();removed.dispose()});
