import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm,rmdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
test('Signature UI preserves state, pending interlocks, fitment, focus and controller setup at three desktop sizes',async()=>{
 const root=process.cwd().replaceAll('\\','/'),temp=await mkdtemp(path.join(tmpdir(),'p08b-ui-')),entry=path.join(temp,'entry.ts');await writeFile(entry,`export {SignatureUI} from ${JSON.stringify(root+'/src/signature/ui.ts')};export {freshRecipe} from ${JSON.stringify(root+'/src/signature/config.ts')};`);
 let js,css;try{const r=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es']}}}),o=(Array.isArray(r)?r[0]:r).output;js=o.find(x=>x.type==='chunk').code;css=o.filter(x=>x.type==='asset'&&x.fileName.endsWith('.css')).map(x=>x.source).join('\n')}finally{await rm(entry);await rmdir(temp)}
 const html=`<!doctype html><style>body{margin:0;background:#414142}#app{height:100vh}${css}</style><main id="app"></main><script type="module">import{SignatureUI,freshRecipe}from'/ui.js';window.state={recipe:freshRecipe(),pending:false,status:'',screen:'entry',lighting:'studio',driverVisible:true,compare:false,canUndo:false,savedRecipes:[]};window.actions=[];window.ui=new SignatureUI(document.querySelector('#app'),{onChange(recipe){state.recipe=recipe;state.canUndo=true;ui.update(state)},onAction(action,value){actions.push({action,value});if(action==='build')state.screen='build';if(action==='quick-race')state.screen='events';if(action==='shop')state.screen='shop';if(action==='compare')state.compare=!state.compare;if(action==='reset')state.recipe=freshRecipe();ui.update(state)},onSave(name){state.savedRecipes.push({id:'saved',name});ui.update(state)}});ui.update(state);window.ready=true;</script>`;
 const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1280,height:720}}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));try{
  await c.route('http://127.0.0.1:42973/**',r=>r.fulfill({contentType:r.request().url().endsWith('ui.js')?'text/javascript':'text/html',body:r.request().url().endsWith('ui.js')?js:html}));await p.goto('http://127.0.0.1:42973/');await p.waitForFunction(()=>window.ready);
  await p.getByRole('button',{name:'Build Your Slingshot'}).click();await p.locator('[data-action=finish][data-value=black-red]').click();assert.equal(await p.evaluate(()=>state.recipe.finish),'black-red');
  await p.locator('[data-action=inspector]').click();assert.equal(await p.locator('.sig-detail').isHidden(),true);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'inspector');await p.locator('.sig-restore button').click();assert.equal(await p.locator('.sig-detail').isVisible(),true);
  await p.locator('[data-action=advanced]').click();await p.locator('[data-action=ignition]').click();await p.locator('[data-action=advanced]').click();assert.equal(await p.evaluate(()=>actions.at(-1).action),'ignition');assert.equal(await p.evaluate(()=>actions.at(-1).value),'true');
  await p.evaluate(()=>{const a=document.createElement('div');a.id='game-audio';a.innerHTML='<details open><summary>Sound mix</summary><input type="range" min="0" max="1" step=".05" value=".5"></details>';document.body.append(a);const input=a.querySelector('input');input.focus();let inputEvents=0;input.oninput=()=>window.audioInputEvents=++inputEvents;const sample=held=>({focused:true,keys:new Set(),pads:[{id:'P09B audio controls',index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},(_,i)=>({value:held===i?1:0,pressed:held===i}))}]});ui.frame(sample(-1));ui.frame(sample(15));ui.frame(sample(-1))});assert.equal(await p.locator('#game-audio input').inputValue(),'0.55');assert.equal(await p.evaluate(()=>window.audioInputEvents),1);await p.locator('#game-audio').evaluate(e=>e.remove());
  await p.locator('[data-action=category][data-value=Suspension]').click();await p.getByRole('button',{name:'Preview part',exact:true}).click();assert.equal(await p.evaluate(()=>state.recipe.products['SM-3223']),'silver');
  await p.getByRole('button',{name:'Increase Front compression',exact:true}).focus();await p.evaluate(()=>{const sample=held=>({focused:true,keys:new Set(),pads:[{id:'P08B focus test',index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},(_,i)=>({value:held===i?1:0,pressed:held===i}))}]});ui.frame(sample(-1));ui.frame(sample(0));ui.frame(sample(-1))});assert.equal(await p.evaluate(()=>state.recipe.suspension.frontCompression),3);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Increase Front compression');
  await p.evaluate(()=>{state.pending=true;ui.update(state)});assert.equal(await p.locator('button:not(:disabled)').count(),0);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>actions.some(a=>a.action==='back')),false);await p.evaluate(()=>{state.pending=false;ui.update(state)});assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Increase Front compression');
  await p.getByRole('button',{name:'Remove',exact:true}).click();assert.equal(await p.evaluate(()=>state.recipe.products['SM-3223']),undefined);assert.equal(await p.evaluate(()=>state.recipe.suspension.frontCompression),3);
  await p.locator('[data-action=category][data-value=Lighting]').click();await p.getByRole('button',{name:'Preview part',exact:true}).click();await p.locator('[data-action=light-color][data-value=blue]').click();await p.getByRole('button',{name:'Increase brightness'}).click();assert.deepEqual(await p.evaluate(()=>({color:state.recipe.lights.color,brightness:state.recipe.lights.brightness})),{color:'blue',brightness:.65});
  await p.getByRole('button',{name:'Reset',exact:true}).click();assert.equal(await p.locator('[role=alertdialog]').count(),1);await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'confirm-reset');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'cancel-reset');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>state.recipe.finish),'black-red');assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'reset');
  await p.locator('[data-action=category][data-value="Build Presets"]').click();await p.getByLabel('Save your build recipe').fill('<script>long named build & safe markup</script>');await p.getByLabel('Save your build recipe').press('Enter');assert.equal(await p.locator('[data-action=load-recipe]').textContent(),'<script>long named build & safe markup</script>');
  await p.locator('[data-action=category][data-value=Aero]').click();await p.evaluate(()=>{state.recipe.vehicleId='wrong-vehicle';ui.update(state)});assert.equal(await p.getByRole('button',{name:'Preview part',exact:true}).isDisabled(),true);assert.match(await p.locator('.sig-fitment').textContent(),/does not fit/);await p.evaluate(()=>{state.recipe.vehicleId='slingshot-r-2024';ui.update(state)});
  for(const width of [1280,1920,2560]){await p.setViewportSize({width,height:width===1280?720:width===1920?1080:1440});for(const screen of ['entry','build','events','shop']){await p.evaluate(screen=>{state.screen=screen;ui.update(state)},screen);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${screen} overflow ${width}`);const bad=await p.locator('button:visible').evaluateAll(es=>es.filter(e=>getComputedStyle(e).fontSize.replace('px','')<13||e.getBoundingClientRect().height<44).map(e=>e.textContent));assert.deepEqual(bad,[],`${screen} readable controls ${width}`)}}
  await p.evaluate(()=>{state.screen='shop';ui.update(state)});for(const a of await p.locator('.sig-shop-list a').all()){assert.equal(await a.getAttribute('target'),'_blank');assert.match(await a.getAttribute('rel'),/noopener/);assert.match(await a.getAttribute('href'),/^https:\/\/www.slingmods.com\//)}assert.deepEqual(errors,[]);
 }finally{await c.close();await b.close()}
});
