import assert from 'node:assert/strict';import test from 'node:test';import * as THREE from 'three';import fs from 'node:fs';import{SignatureFinishPresenter,SignatureProducts}from'../src/presentation/signature-art.ts';
test('signature finishes isolate shared materials and restore their original identity',async()=>{
 const paint=new THREE.MeshStandardMaterial({color:'#234466',roughness:.31});paint.name='P03A_Radar_Blue';const rubber=new THREE.MeshStandardMaterial({color:'#171717'});rubber.name='P03A_Rubber';const car=new THREE.Group(),rival=new THREE.Mesh(new THREE.BoxGeometry(),paint);const body=new THREE.Mesh(new THREE.BoxGeometry(),[paint,rubber]);body.name='body_static__Radar_Blue';car.add(body);const presenter=new SignatureFinishPresenter(car),originalLoad=THREE.TextureLoader.prototype.loadAsync;THREE.TextureLoader.prototype.loadAsync=async()=>new THREE.Texture();
 try{await presenter.set('black-red');assert.notEqual(body.material[0],paint);assert.equal(body.material[1],rubber);assert.equal(rival.material,paint);assert.equal(paint.color.getHexString(),'234466');await presenter.set('blue-orange');assert.equal((body.material[0]as THREE.MeshStandardMaterial).color.getHexString(),'234466');presenter.dispose();assert.equal(body.material[0],paint);assert.equal(body.material[1],rubber)}finally{THREE.TextureLoader.prototype.loadAsync=originalLoad}
});
test('catalog removal preserves stock and storage inspection restores exact prior visibility and pose',()=>{
 const car=new THREE.Group(),source=new THREE.Group(),stock=new THREE.Group();stock.name='stock_exhaust';car.add(stock);for(const id of ['SM-7720','SM-26801','SM-28919']){const x=new THREE.Group();x.name='product_'+id;source.add(x)}
 for(const n of ['signature_storage_door_left','signature_storage_door_right','signature_seat_driver','signature_seat_passenger']){const x=new THREE.Group();x.name=n;x.rotation.x=.12;car.add(x)}const hidden=car.getObjectByName('signature_seat_driver')!;hidden.visible=false;const p=new SignatureProducts(car,source);p.set(['SM-7720','SM-28919']);assert.equal(stock.visible,false);p.inspectStorage(true);assert.equal(car.getObjectByName('signature_seat_passenger')!.visible,false);p.set([]);assert.equal(stock.visible,true);assert.equal(hidden.visible,false);assert.equal(car.getObjectByName('signature_seat_passenger')!.visible,true);assert.equal(car.getObjectByName('signature_storage_door_left')!.rotation.x,.12);p.dispose();assert.equal(source.parent,null)
});
function glb(path:string){const raw=fs.readFileSync(path);return JSON.parse(raw.subarray(20,20+raw.readUInt32LE(12)).toString())}
test('canonical repaired export carries live rig nodes, independent compartment doors, and packed maps',()=>{
 const g=glb('public/assets/p08b/slingshot-signature.glb'),names=new Set(g.nodes.map((x:{name:string})=>x.name));for(const n of ['front_left_steer','front_right_steer','rear_spin','steering_control','shock_upper','shock_lower','signature_storage_door_left','signature_storage_door_right','signature_seat_driver','signature_seat_passenger'])assert.ok(names.has(n),n);assert.ok(g.images.length>=16);assert.ok(g.images.every((i:{bufferView:number;uri?:string})=>typeof i.bufferView==='number'&&!i.uri));
});
test('new product groups are stable and room is independently loadable',()=>{const p=glb('public/assets/p08b/signature-products.glb');for(const id of ['SM-7720','SM-26801','SM-28919'])assert.ok(p.nodes.some((n:{name:string})=>n.name==='product_'+id));const room=glb('public/assets/p08b/signature-showroom.glb');assert.ok(room.nodes.some((n:{name:string})=>n.name==='signature_showroom'));assert.equal(room.buffers.length,1);assert.ok(!JSON.stringify(room).includes('harbor'))});
