import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm,rmdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
test('Departure modal keeps recovery focus, cancels constructor failure and completes once',async()=>{
 const root=process.cwd().replaceAll('\\','/'),temp=await mkdtemp(path.join(tmpdir(),'departure-ui-')),entry=path.join(temp,'entry.ts');await writeFile(entry,`export {ShowroomDeparture} from ${JSON.stringify(root+'/src/signature/departure.ts')};export * as THREE from ${JSON.stringify(root+'/node_modules/three/build/three.module.js')};`);
 let js,css;try{const r=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es']}}}),o=(Array.isArray(r)?r[0]:r).output;js=o.find(x=>x.type==='chunk').code;css=o.filter(x=>x.type==='asset'&&x.fileName.endsWith('.css')).map(x=>x.source).join('\n')}finally{await rm(entry);await rmdir(temp)}
 const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();try{
  await context.route('http://127.0.0.1:42972/**',r=>r.fulfill({contentType:r.request().url().endsWith('.js')?'text/javascript':'text/html',body:r.request().url().endsWith('.js')?js:`<style>${css}</style><button id="launch">Test build</button><main id="app"></main><button id="recovery">Recovery</button><script type="module">import {ShowroomDeparture,THREE} from '/test.js';window.completed=0;window.stopped=0;window.make=(fail=false)=>{const room=new THREE.Group(),car=new THREE.Group(),door=new THREE.Group();door.name='bay_door_curtain';room.add(door);return new ShowroomDeparture({parent:document.querySelector('#app'),room,car,camera:new THREE.PerspectiveCamera(),target:new THREE.Vector3(),onComplete:()=>completed++,onSoundStart:()=>{if(fail)throw Error('Cue unavailable')},onSoundStop:()=>stopped++})};window.ready=true;</script>`}));await page.goto('http://127.0.0.1:42972/');await page.waitForFunction(()=>window.ready);
  await page.locator('#launch').focus();assert.equal(await page.evaluate(()=>{try{make(true)}catch(e){return e.message}}),'Cue unavailable');assert.equal(await page.locator('.sig-departure').count(),0);await page.locator('#recovery').focus();assert.equal(await page.evaluate(()=>document.activeElement.id),'recovery');
  await page.locator('#launch').focus();await page.evaluate(()=>window.departure=make());await page.locator('[data-departure=skip]').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.dataset.departure),'pause');
  await page.evaluate(()=>{document.querySelector('#app').inert=true;document.querySelector('#recovery').focus()});assert.equal(await page.evaluate(()=>document.activeElement.id),'recovery');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>completed),0);await page.evaluate(()=>document.querySelector('#app').inert=false);
  await page.evaluate(()=>{departure.finish();departure.finish()});assert.equal(await page.evaluate(()=>completed),1);assert.equal(await page.evaluate(()=>stopped),1);await page.locator('#recovery').focus();assert.equal(await page.evaluate(()=>document.activeElement.id),'recovery');
 }finally{await context.close();await browser.close()}
});
