import {PRODUCT} from '../src/career/catalog';
import {SUSPENSION} from '../src/career/suspension';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {freshCareer,migrateCareer,transition,MemoryCareerStore,CareerDataError,type Career} from '../src/career/store';
import {EVENTS,CREDIT_TABLE,careerRecipe,certifyCareerFinish,eventAvailable,productUnlocked,productOwned,productEquipped,cupStandings,type ChapterEvent,type Attempt} from '../src/career-experience/model';
import {PRODUCTS} from '../src/signature/catalog';
import {routeVersion} from '../src/career-experience/race-adapter';
import type {CrewRace} from '../src/competition';
const earned=()=>{const s=freshCareer();s.chapters.firstCompletion=true;s.buildMatters.legacyCrewAccess=true;return s};
const begin=(s:Career,event:ChapterEvent)=>transition(s,{type:'chapter-begin',event,id:randomUUID(),cupId:randomUUID(),routeVersion:routeVersion(event,s.ownBuild.activeCupId?s.ownBuild.cups[s.ownBuild.activeCupId].stages.length:0)}).state;
function snapshot(a:Attempt,place=a.participants.length){const ids=[...a.participants.filter(x=>x!=='player')];ids.splice(place-1,0,'player');return {event:a.competitionId,handlingProfileId:a.handlingProfile,laps:1,phase:'finished',paused:false,countdown:0,elapsedMs:90000,attemptId:a.id,standings:ids.map((id,i)=>({id,place:i+1,status:'finished',lap:1,nextGate:16,progress:2500,timeMs:80000+i*1000,invalidReason:null,valid:true})),playerResult:{event:a.competitionId,attemptId:a.id,participantId:'player',status:'finished',valid:true,laps:1,timeMs:80000+(place-1)*1000,place,invalidReason:null},allFinished:true} as ReturnType<CrewRace['snapshot']>}
function finish(s:Career,place?:number){const a=s.ownBuild.active!;return transition(s,{type:'chapter-result',result:certifyCareerFinish(a,snapshot(a,place))})}
function full(){let s=earned();for(const event of ['open-it-up','hold-your-nerve','coastline-cup','coastline-cup'] as ChapterEvent[])s=finish(begin(s,event)).state;return s}
test('v3 migration retains exact prior fields and mints no chapter credits, wins or ownership',()=>{const current=earned(),old:any=structuredClone(current);old.version=3;delete old.ownBuild;old.credits=1234;old.equipped=old.owned=true;const before=structuredClone(old),s=migrateCareer(old);assert.equal(s.version,4);const stripped:any=structuredClone(s);delete stripped.ownBuild;stripped.version=3;assert.deepEqual(stripped,before);assert.deepEqual(old,before);assert.equal(s.credits,1234);assert.deepEqual(s.ownBuild.products,{});assert.equal(s.ownBuild.completed['open-it-up'],false);assert.deepEqual(migrateCareer(s),s)});
test('chapter order preserves old crew access while new careers complete existing chapter',()=>{assert.equal(eventAvailable(freshCareer(),'open-it-up'),false);assert.equal(eventAvailable(earned(),'open-it-up'),true);assert.throws(()=>begin(earned(),'hold-your-nerve'),/locked/);assert.throws(()=>begin(earned(),'coastline-cup'),/locked/);const s=finish(begin(earned(),'open-it-up')).state;assert.equal(eventAvailable(s,'hold-your-nerve'),true);assert.equal(productUnlocked(s,'SM-7720'),true);assert.equal(productUnlocked(s,'SM-26801'),false)});
test('ordinary finishes fund all three new products without a win or grind',()=>{let s=full();assert.equal(s.credits,2400);for(const p of PRODUCTS.filter(p=>['SM-7720','SM-26801','SM-28919'].includes(p.id))){s=transition(s,{type:'chapter-purchase',id:randomUUID(),productId:p.id,vehicleId:p.vehicleId,option:p.option}).state;assert.equal(productOwned(s,p.id),true);assert.equal(productEquipped(s,p.id),true)}assert.equal(s.credits,600);assert.equal(Object.keys(careerRecipe(s).products).length,3);assert.deepEqual(Object.values(s.ownBuild.completed),[true,true,true]);assert.equal(s.ownBuild.records.length,4)});
test('all five ownership uses existing lighting and shock fields, equipment survives remove/reload',()=>{let s=full();s.credits+=1600;for(const p of PRODUCTS){s=transition(s,p.id==='SM-133'?{type:'purchase',id:randomUUID(),productId:PRODUCT.id,vehicleId:p.vehicleId}:p.id==='SM-3223'?{type:'suspension-purchase',id:randomUUID(),productId:SUSPENSION.id,vehicleId:p.vehicleId}:{type:'chapter-purchase',id:randomUUID(),productId:p.id,vehicleId:p.vehicleId,option:p.option}).state}assert.equal(Object.keys(careerRecipe(s).products).length,5);s=transition(s,{type:'chapter-equip',productId:'SM-7720',equipped:false}).state;const loaded=migrateCareer(JSON.parse(JSON.stringify(s)));assert.equal(productOwned(loaded,'SM-7720'),true);assert.equal(productEquipped(loaded,'SM-7720'),false);assert.equal(loaded.suspension.owned,true);assert.equal(loaded.owned,true)});
test('proofs bind attempt, competition, recipe, route version and tune; cloned or foreign proof rejected',()=>{const s=begin(earned(),'open-it-up'),a=s.ownBuild.active!,snap=snapshot(a),proof=certifyCareerFinish(a,snap);assert.throws(()=>transition(s,{type:'chapter-result',result:structuredClone(proof)}),/verified/);assert.throws(()=>certifyCareerFinish(a,{...snap,handlingProfileId:'legacy-p08a'}),/matching/);assert.throws(()=>certifyCareerFinish(a,{...snap,allFinished:false}),/matching/);assert.throws(()=>certifyCareerFinish(a,{...snap,playerResult:{...snap.playerResult!,valid:false}}),/matching/);assert.throws(()=>certifyCareerFinish(a,{...snap,playerResult:{...snap.playerResult!,timeMs:NaN}}));assert.throws(()=>{(proof.recipe.products as any)['SM-7720']='brushed-silver'});assert.equal(a.recipe.handlingProfile,'slingmods-sport-v2')});
test('every result has one receipt and duplicate callbacks after reload pay exactly once',()=>{const s=begin(earned(),'open-it-up'),a=s.ownBuild.active!,proof=certifyCareerFinish(a,snapshot(a)),first=transition(s,{type:'chapter-result',result:proof}),reloaded=migrateCareer(JSON.parse(JSON.stringify(first.state))),repeat=transition(reloaded,{type:'chapter-result',result:proof});assert.equal(first.receipt?.amount,800);assert.equal(repeat.changed,false);assert.equal(repeat.state.credits,800);assert.equal(repeat.state.ownBuild.records.length,1)});
test('retry supersedes old attempt identity, abandoned callbacks cannot pay',()=>{const first=begin(earned(),'open-it-up'),a=first.ownBuild.active!,proof=certifyCareerFinish(a,snapshot(a)),retry=begin(first,'open-it-up');assert.notEqual(retry.ownBuild.active!.id,a.id);assert.equal(retry.ownBuild.attempts[a.id].status,'abandoned');assert.throws(()=>transition(retry,{type:'chapter-result',result:proof}),/abandoned/);const abandoned=transition(retry,{type:'chapter-abandon'}).state;assert.equal(abandoned.ownBuild.active,null);assert.equal(abandoned.credits,0)});
test('Cup partial result, crash/reload, next event, retry and aggregate pay atomically once',()=>{let s=earned();s=finish(begin(s,'open-it-up')).state;s=finish(begin(s,'hold-your-nerve')).state;s=begin(s,'coastline-cup');const cupId=s.ownBuild.activeCupId!,recipe=structuredClone(s.ownBuild.active!.recipe);s=finish(s).state;assert.equal(s.credits,1500);assert.equal(s.ownBuild.cups[cupId].stages.length,1);assert.equal(Object.values(s.receipts).at(-1)?.amount,0);s=migrateCareer(JSON.parse(JSON.stringify(s)));s=transition(s,{type:'chapter-finish',finish:'black-red'}).state;s=begin(s,'coastline-cup');assert.equal(s.ownBuild.active!.route,'express');assert.deepEqual(s.ownBuild.active!.recipe,recipe);const retry=begin(s,'coastline-cup');assert.equal(retry.ownBuild.active!.stage,1);assert.equal(retry.ownBuild.activeCupId,cupId);s=finish(retry).state;assert.equal(s.credits,2400);assert.equal(s.ownBuild.activeCupId,null);assert.equal(s.ownBuild.cups[cupId].status,'completed');assert.equal(cupStandings(s.ownBuild.cups[cupId]).at(-1)?.id,'player')});
test('abandoning a partial Cup preserves results, no bonus or bag unlock; restart begins Harbor',()=>{let s=full();s.ownBuild.completed['coastline-cup']=false;s=begin(s,'coastline-cup');s=finish(s).state;const before=s.credits,oldCup=s.ownBuild.activeCupId!;s=transition(s,{type:'chapter-abandon'}).state;assert.equal(s.credits,before);assert.equal(s.ownBuild.cups[oldCup].status,'abandoned');assert.equal(productUnlocked(s,'SM-28919'),false);s=begin(s,'coastline-cup');assert.equal(s.ownBuild.active!.route,'harbor');assert.notEqual(s.ownBuild.activeCupId,oldCup)});
test('first win is modest and only paid once; ordinary repeats have transparent reward',()=>{let s=finish(begin(earned(),'open-it-up')).state;let r=finish(begin(s,'hold-your-nerve'),1);assert.equal(r.receipt?.amount,800);r=finish(begin(r.state,'hold-your-nerve'),1);assert.equal(r.receipt?.amount,100);assert.equal(r.receipt?.chapterBonus,0);assert.equal(r.state.ownBuild.won['hold-your-nerve'],true)});
test('invalid options, URL-like product IDs, locked parts and unsupported fitment never charge',()=>{const s=earned(),p=PRODUCTS.find(p=>p.id==='SM-7720')!,base={type:'chapter-purchase' as const,id:randomUUID(),productId:p.id,vehicleId:p.vehicleId,option:p.option};for(const patch of [{},{option:'touring'},{vehicleId:'spyder'},{productId:'https://evil.test/'},{id:'invalid'}])assert.throws(()=>transition(s,{...base,...patch} as any));assert.equal(s.credits,0);assert.deepEqual(s.ownBuild.products,{})});
test('future and corrupt chapter save is rejected without replacing the original',()=>{const s=full();for(const patch of [{version:99},{ownBuild:{...s.ownBuild,version:2}},{ownBuild:{...s.ownBuild,finish:'pink'}},{ownBuild:{...s.ownBuild,activeCupId:randomUUID()}},{ownBuild:{...s.ownBuild,products:{'SM-7720':{owned:false,equipped:true}}}}]){const bad={...s,...patch},copy=structuredClone(bad);assert.throws(()=>migrateCareer(bad),CareerDataError);assert.deepEqual(bad,copy)}});
test('memory fallback serializes simultaneous purchases and reward duplicates without partial credits',async()=>{const s=begin(earned(),'open-it-up'),proof=certifyCareerFinish(s.ownBuild.active!,snapshot(s.ownBuild.active!)),store=new MemoryCareerStore(s);await Promise.all([store.execute({type:'chapter-result',result:proof}),store.execute({type:'chapter-result',result:proof})]);const p=PRODUCTS.find(p=>p.id==='SM-7720')!;await Promise.all([1,2].map(()=>store.execute({type:'chapter-purchase',id:randomUUID(),productId:p.id,vehicleId:p.vehicleId,option:p.option})));assert.equal((await store.read()).credits,100);assert.equal(store.durable,false)});
