import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
test('Chapter02 real IndexedDB atomic Cup award, duplicate retry, concurrent purchase, corruption and denied storage',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'p09-career-')),entry=path.join(dir,'entry.ts');await writeFile(entry,`export * from ${JSON.stringify(process.cwd().replaceAll('\\','/')+'/src/career/store.ts')};export * from ${JSON.stringify(process.cwd().replaceAll('\\','/')+'/src/career-experience/model.ts')};`);
 const bundled=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es']}}}),source=(Array.isArray(bundled)?bundled[0]:bundled).output.find(x=>x.type==='chunk').code;await rm(entry);await import('node:fs/promises').then(fs=>fs.rmdir(dir));
 const browser=await chromium.launch({headless:true});try{const c=await browser.newContext();await c.route('https://p09-career.test/**',route=>route.fulfill({contentType:route.request().url().endsWith('.js')?'text/javascript':'text/html',body:route.request().url().endsWith('.js')?source:'<!doctype html><title>Isolated Chapter02 transaction tests</title>'}));const p=await c.newPage();await p.goto('https://p09-career.test/');
 const result=await p.evaluate(async()=>{const m=await import('/model.js');window.m=m;const initial=m.freshCareer();initial.credits=0;initial.chapters.firstCompletion=true;initial.buildMatters.legacyCrewAccess=true;const db=await new Promise(resolve=>{const r=indexedDB.open(m.CAREER_DB,2);r.onupgradeneeded=()=>r.result.createObjectStore('career');r.onsuccess=()=>resolve(r.result)});await new Promise(resolve=>{const tx=db.transaction('career','readwrite');tx.objectStore('career').put(initial,'current');tx.oncomplete=resolve});db.close();const store=await m.openCareer();window.store=store;
  function proof(a){const ids=a.participants,standings=ids.map((id,i)=>({id,place:i+1,status:'finished',lap:1,nextGate:16,progress:2500,timeMs:80000+i*1000,invalidReason:null,valid:true})),player=standings.find(s=>s.id==='player');return m.certifyCareerFinish(a,{event:a.competitionId,handlingProfileId:a.handlingProfile,laps:1,phase:'finished',paused:false,countdown:0,elapsedMs:90000,attemptId:a.id,standings,playerResult:{event:a.competitionId,attemptId:a.id,participantId:'player',status:'finished',valid:true,laps:1,timeMs:player.timeMs,place:player.place,invalidReason:null},allFinished:true})}
  for(const event of ['open-it-up','hold-your-nerve','coastline-cup']){const s=await store.execute({type:'chapter-begin',event,id:crypto.randomUUID(),cupId:crypto.randomUUID(),routeVersion:event==='coastline-cup'?'1':'express-layout-v1'});await store.execute({type:'chapter-result',result:proof(s.state.ownBuild.active)})}
  const prepared=await store.execute({type:'chapter-begin',event:'coastline-cup',id:crypto.randomUUID(),routeVersion:'express-layout-v1'}),finish=proof(prepared.state.ownBuild.active),before=await store.read(),put=IDBObjectStore.prototype.put;let error;
  IDBObjectStore.prototype.put=function(){throw new DOMException('Injected interrupted Cup write','QuotaExceededError')};try{await store.execute({type:'chapter-result',result:finish})}catch(e){error=e.message}finally{IDBObjectStore.prototype.put=put}
  const unchanged=JSON.stringify(await store.read())===JSON.stringify(before);await store.execute({type:'chapter-result',result:finish});await store.execute({type:'chapter-result',result:finish});const complete=await store.read();const second=await m.openCareer();await Promise.all([store,second].map(s=>s.execute({type:'chapter-purchase',id:crypto.randomUUID(),productId:'SM-7720',vehicleId:'slingshot-r-2024',option:'brushed-silver'})));second.close();const purchased=await store.read();store.close();return {error,unchanged,complete,purchased};});
 assert.match(result.error,/interrupted Cup write/);assert.equal(result.unchanged,true);assert.equal(result.complete.credits,2400);assert.equal(result.purchased.credits,1700);assert.equal(Object.values(result.complete.receipts).filter(r=>r.kind==='chapter-award').length,4);assert.equal(Object.values(result.purchased.receipts).filter(r=>r.kind==='chapter-purchase').length,1);
 const corrupt=await p.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open(window.m.CAREER_DB,2);r.onsuccess=()=>resolve(r.result)}),raw=await new Promise(resolve=>{const r=db.transaction('career').objectStore('career').get('current');r.onsuccess=()=>resolve(r.result)});raw.ownBuild.version=99;await new Promise(resolve=>{const tx=db.transaction('career','readwrite');tx.objectStore('career').put(raw,'current');tx.oncomplete=resolve});let error;try{await window.m.openCareer()}catch(e){error=e.name}const after=await new Promise(resolve=>{const r=db.transaction('career').objectStore('career').get('current');r.onsuccess=()=>resolve(r.result)});db.close();return {error,unchanged:JSON.stringify(raw)===JSON.stringify(after)}});assert.deepEqual(corrupt,{error:'CareerDataError',unchanged:true});
 const denied=await p.evaluate(async()=>{Object.defineProperty(window,'indexedDB',{configurable:true,get(){throw new DOMException('Denied','SecurityError')}});const state=window.m.freshCareer();state.chapters.firstCompletion=true;state.buildMatters.legacyCrewAccess=true;const store=await window.m.openCareer(state),result=await store.execute({type:'chapter-begin',event:'open-it-up',id:crypto.randomUUID(),routeVersion:'express-layout-v1'});return {durable:store.durable,active:result.state.ownBuild.active?.event,credits:result.state.credits}});assert.deepEqual(denied,{durable:false,active:'open-it-up',credits:0});await c.close();
 }finally{await browser.close()}
});

