import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import fs from 'node:fs';
import {Simulation,type HandlingProfileId} from '../src/simulation';import {streetSetup} from '../src/career/suspension';import {InputResolver} from '../src/driving/input';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/p09a-baseline-digests.json',import.meta.url),'utf8'));
const flat={ground:{center:[0,-.15,0],size:[3000,.3,3000]},obstacles:[],ramps:[],surfaceAt:()=>({id:'asphalt',mu:1.05,rolling:.014})};
const yaw=(q:any)=>Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z));
for(const item of fixture.cases)test('reviewed '+item.profile+' '+item.scenario+' full telemetry remains byte equivalent',async()=>{const sim=await Simulation.create(undefined,item.profile),hash=createHash('sha256');for(let i=0;i<item.ticks;i++){const t=i/60,c=item.scenario==='long-throttle-brake-pad'?{throttle:t<21?1:0,brake:t>=21?1:0,steer:0,reverse:false}:{throttle:t<10?.7:t<16?.2:0,brake:t>=18?.7:0,steer:t>5&&t<16?Math.sin(t)*.4:0,reverse:t>24};sim.step(c);hash.update(JSON.stringify(sim.telemetry())+'\n')}assert.equal(hash.digest('hex'),item.telemetrySha256);sim.dispose()});
for(const [mph,target]of[[60,40],[110,140]])test('Sport v2 matched '+mph+' mph stop meets distance, yaw and path goals inside three tire channels',async()=>{const sim=await Simulation.create(flat,'slingmods-sport-v2');sim.reset({x:0,y:.025,z:35});let entry:any=null,last=sim.telemetry(),path=0,stopped=false;for(let i=0;i<40*60;i++){if(!entry&&last.speed>=mph*.44704-.05)entry=last;sim.step({throttle:entry?0:1,brake:entry?1:0,steer:0,reverse:false});const t=sim.telemetry();if(entry)path+=Math.hypot(t.position.x-last.position.x,t.position.z-last.position.z);for(const w of t.wheels)assert.ok(Math.hypot(w.longitudinalForce,w.lateralForce)<=w.gripLimit+1e-7);assert.equal(t.wheels.length,3);assert.ok(t.wheels.every(w=>w.contact));last=t;if(entry&&Math.abs(t.speed)<.2){stopped=true;break}}assert.ok(stopped);assert.ok(path<=target,JSON.stringify({mph,path}));assert.ok(Math.abs(yaw(last.quaternion)-yaw(entry.quaternion))*180/Math.PI<=2);assert.ok(Math.abs(last.position.x-entry.position.x)<=.5);assert.equal(last.gear>0,true);sim.dispose()});
test('Sport v2 unchanged launch and steering, street estimate and removed product remain exactly stock',async()=>{const v1=await Simulation.create(flat,'slingmods-sport-v1'),stock=await Simulation.create(flat,'slingmods-sport-v2'),street=await Simulation.create(flat,'slingmods-sport-v2'),removed=await Simulation.create(flat,'slingmods-sport-v2');street.configureSuspension(streetSetup());removed.configureSuspension({...streetSetup(),frontCompression:12,rideHeightMm:10});removed.configureSuspension(null);let launch:number|null=null;for(let i=0;i<1100;i++){const c={throttle:i<300?1:i<550?.25:0,brake:i>=700?1:0,steer:i>=320&&i<650?.3:0,reverse:false};for(const sim of[v1,stock,street,removed])sim.step(c);assert.deepEqual(street.telemetry(),stock.telemetry());assert.deepEqual(removed.telemetry(),stock.telemetry());if(i<550)assert.deepEqual(stock.telemetry(),v1.telemetry());if(!launch&&stock.telemetry().speed>=26.8224)launch=(i+1)/60}assert.equal(launch,4.733333333333333);for(const sim of[v1,stock,street,removed])sim.dispose()});
test('Sport v2 preserves wall collision and chassis landing while guards omit only planar floor',async()=>{const wall={...flat,obstacles:[{id:'wall',center:[0,1,0],size:[10,2,.5]}]},sim=await Simulation.create(wall,'slingmods-sport-v2');sim.reset({x:0,z:12,y:.025});sim.enableDiagnostics();let guardContact=false;for(let i=0;i<420;i++){sim.step({throttle:i<300?1:0,brake:i>=300?1:0,steer:0,reverse:false});assert.ok(sim.telemetry().position.z>1);guardContact ||=sim.diagnostics().contacts.some(c=>c.kind==='guard')}assert.ok(guardContact);sim.reset({x:15,z:15,y:2});for(let i=0;i<360;i++)sim.step({throttle:0,brake:0,steer:0,reverse:false});assert.ok(sim.telemetry().position.y>-.05);assert.ok(sim.telemetry().wheels.every(w=>w.contact));sim.dispose()});
test('Sport v2 release/repress reverse, explicit selector and focus cancellation use existing input lifecycle',()=>{const input=new InputResolver('slingmods-sport-v2');let now=0;const poll=(keys:string[]=[],speed=0,focused=true)=>input.poll(now+=17,{keys:new Set(keys),pads:[],focused},speed);poll();poll(['KeyW'],10);assert.equal(poll(['KeyS'],8).direction,'D');assert.equal(poll(['KeyS'],0).direction,'D');poll();assert.equal(poll(['KeyS']).direction,'R');assert.equal(poll(['KeyS']).control.throttle,1);poll([],0,false);assert.equal(poll(['KeyS']).control.throttle,0);const explicit=new InputResolver('slingmods-sport-v2');explicit.poll(0,{keys:new Set(),pads:[],focused:true});assert.equal(explicit.poll(17,{keys:new Set(['KeyX']),pads:[],focused:true}).direction,'R');assert.equal(explicit.poll(34,{keys:new Set(['KeyW']),pads:[],focused:true}).control.throttle,1)});

for(const brake of[.5,1])for(const steer of[-1,1])test('Sport v2 matched fast brake-turn '+brake+' / '+steer+' stops with secure support',async()=>{const sim=await Simulation.create(flat,'slingmods-sport-v2');sim.reset({x:0,y:.025,z:35});let entry=false,stopped=false,last=sim.telemetry(),turn=0,path=0;for(let i=0;i<30*60;i++){if(last.speed>=34.95)entry=true;sim.step({throttle:entry?0:1,brake:entry?brake:0,steer:entry?steer:0,reverse:false});const t=sim.telemetry();assert.ok(t.wheels.every(w=>w.contact));assert.ok(1-2*(t.quaternion.x**2+t.quaternion.z**2)>.95);if(entry){const delta=yaw(t.quaternion)-yaw(last.quaternion);turn+=Math.atan2(Math.sin(delta),Math.cos(delta));path+=Math.hypot(t.position.x-last.position.x,t.position.z-last.position.z)}last=t;if(entry&&Math.abs(t.speed)<.2){stopped=true;break}}assert.ok(stopped);assert.ok(turn*steer>.5&&turn*steer<Math.PI);assert.ok(path<120);sim.dispose()});
test('Sport v2 analog magnitude, pause and disconnect cannot inherit held reverse pedals',()=>{const input=new InputResolver('slingmods-sport-v2');let now=0;const pad=(value=0)=>({index:0,id:'P09A standard simulated controller',mapping:'standard',connected:true,axes:[0],buttons:Array.from({length:17},(_,i)=>({value:i===6?value:0}))});const poll=(value=0,keys:string[]=[],connected=true)=>input.poll(now+=17,{keys:new Set(keys),pads:connected?[pad(value)]:[],focused:true},0);poll();let r=poll(.37);assert.equal(r.direction,'R');assert.equal(r.control.throttle,.37);poll(.37,['Escape']);assert.equal(poll(.37).control.throttle,0);poll(.37,['Escape']);assert.equal(poll(.37).control.throttle,0);poll();assert.equal(poll(.42).control.throttle,.42);poll(0,[],false);assert.equal(input.paused,true);assert.equal(poll(.42).control.throttle,0);poll(.42,['Escape']);assert.equal(poll(.42).control.throttle,0);poll();assert.equal(poll(.31).control.throttle,.31)});
import {RivalController} from '../src/competition/rival';
import {EXPRESS_ROUTE} from '../src/express/route';
import {sampleRoad} from '../src/course/environment';
test('Sport v2 preserves v1 rival planner pace and controls across wide/narrow routes; legacy stays distinct',async()=>{
 const sim=await Simulation.create(),template=sim.telemetry();sim.dispose();
 for(const width of[15,12])for(const id of['maya','jett','nico','player']){
  const route={...EXPRESS_ROUTE,width},v1=new RivalController(route,id,11,'slingmods-sport-v1'),v2=new RivalController(route,id,11,'slingmods-sport-v2'),legacy=new RivalController(route,id,11,'legacy-p08a');let legacyDiffers=false;
  for(const progress of[100,220,600,735,900,1250]){
   const point=sampleRoad(route,progress),heading=Math.atan2(-point.dx,-point.dz),speed=35;
   const telemetry={...structuredClone(template),position:{x:point.x,y:.025,z:point.z},quaternion:{x:0,y:Math.sin(heading/2),z:0,w:Math.cos(heading/2)},velocity:{x:point.dx*speed,y:0,z:point.dz*speed},speed};
   for(let tick=0;tick<12;tick++){
    const before=structuredClone(telemetry),a=v1.control(telemetry,{[id]:telemetry}),b=v2.control(telemetry,{[id]:telemetry});legacy.control(telemetry,{[id]:telemetry});
    assert.equal(v2.inspect().targetSpeed,v1.inspect().targetSpeed,`${id}, width${width}, progress${progress}`);assert.deepEqual(b,a);assert.deepEqual(telemetry,before,'planner must not mutate vehicle state');
    legacyDiffers ||= Math.abs(legacy.inspect().targetSpeed-v1.inspect().targetSpeed)>1;
   }
  }
  assert.ok(legacyDiffers,`${id} width${width}: legacy must retain its historical pace`);
 }
});
