import {test} from 'node:test';import assert from 'node:assert/strict';
import {recoveryReason,freeRecoveryPose} from '../src/driving/recovery';
import {Simulation,type VehicleTelemetry} from '../src/simulation';import {scenarios} from '../src/simulation/scenarios';
import {EXPRESS_ROUTE} from '../src/express/route';import {projectRoad,type CourseRoute} from '../src/course/environment';
const route:CourseRoute={id:'recovery-test',version:'1',name:'Recovery test',width:10,runoff:2,length:400,centerline:[[0,0],[0,-100],[-100,-100],[-100,0]],start:{x:0,y:.025,z:8,yaw:0},checkpoints:[],colliders:[],ground:{center:[-50,-.15,-50],size:[400,.3,400]},lamps:[]};
async function telemetry(){const sim=await Simulation.create();const result=sim.telemetry();sim.dispose();return {...result,position:{x:0,y:0,z:-40},velocity:{x:0,y:0,z:0},quaternion:{x:0,y:0,z:0,w:1},wheels:result.wheels.map(w=>({...w,contact:true}))}}
test('recovery prioritizes below-road and overturned state, without interrupting moving upright driving',async()=>{const t=await telemetry();assert.equal(recoveryReason(t,route),'');assert.equal(recoveryReason({...t,position:{...t.position,y:-3.01},velocity:{x:0,y:-20,z:0}},route),'Below the road');assert.equal(recoveryReason({...t,quaternion:{x:0,y:0,z:1,w:0},velocity:{x:7,y:0,z:0}},route),'Car overturned');assert.equal(recoveryReason({...t,quaternion:{x:0,y:0,z:1,w:0},velocity:{x:9,y:0,z:0}},route),'');assert.equal(recoveryReason({...t,velocity:{x:0,y:0,z:-45}},route),'')});
test('stranded prompt requires slow motion beyond runoff, while unsupported prompt does not intercept ordinary airborne motion',async()=>{const t=await telemetry(),off={...t,position:{x:14,y:0,z:-40}};assert.equal(recoveryReason(off,route),'Stranded off the course');assert.equal(recoveryReason({...off,velocity:{x:0,y:0,z:-2}},route),'');assert.equal(recoveryReason({...t,position:{x:10,y:0,z:-40}},route),'');const air={...t,wheels:t.wheels.map(w=>({...w,contact:false}))};assert.equal(recoveryReason(air,route),'Car stuck without tire support');assert.equal(recoveryReason({...air,velocity:{x:0,y:-3,z:0}},route),'');assert.equal(recoveryReason({...air,wheels:air.wheels.map((w,i)=>({...w,contact:i===0}))},route),'')});
test('free recovery returns six metres behind on road, heading forward, without mutating telemetry or route',async()=>{const t={...await telemetry(),position:{x:5,y:-4,z:-40}},before=structuredClone(t),routeBefore=structuredClone(route),pose=freeRecoveryPose(route,t);assert.deepEqual({x:pose.x,y:pose.y,z:pose.z},{x:0,y:.025,z:-34});assert.ok(Math.abs(pose.yaw)<1e-12);assert.deepEqual(t,before);assert.deepEqual(route,routeBefore);assert.equal(projectRoad(route,pose.x,pose.z).distance,0);const heading={x:-Math.sin(pose.yaw),z:-Math.cos(pose.yaw)};assert.ok(heading.z<-.99)});
test('free recovery wraps behind the start line onto the previous road segment instead of advancing a lap',async()=>{const t={...await telemetry(),position:{x:1,y:0,z:-1}},pose=freeRecoveryPose(route,t);assert.ok(Math.abs(pose.x+5)<1e-8);assert.equal(pose.z,0);assert.equal(projectRoad(route,pose.x,pose.z).distance,0);assert.ok(-Math.sin(pose.yaw)>.99);assert.equal(pose.y,.025)});
test('actual Sport v2 high-speed-curb overturn is detected and explicit free recovery restores supported upright state',async()=>{const scenario=scenarios.find(s=>s.name==='high-speed-curb')!,sim=await Simulation.create(undefined,'slingmods-sport-v2');sim.reset(scenario.pose);let detected:VehicleTelemetry|undefined,minUpright=1;for(let tick=0;tick<scenario.seconds*60;tick++){sim.step(scenario.control(tick/60,sim.telemetry()));const t=sim.telemetry(),up=1-2*(t.quaternion.x**2+t.quaternion.z**2);minUpright=Math.min(minUpright,up);if(recoveryReason(t,EXPRESS_ROUTE)==='Car overturned')detected=t}assert.ok(minUpright<0,'Stress case must actually overturn, not inject a mocked quaternion');assert.ok(detected,'Actual slow overturn must offer recovery');const pose=freeRecoveryPose(EXPRESS_ROUTE,detected!);sim.reset(pose);for(let i=0;i<180;i++)sim.step({throttle:0,brake:0,steer:0,reverse:false});const t=sim.telemetry();assert.ok(1-2*(t.quaternion.x**2+t.quaternion.z**2)>.99);assert.ok(t.wheels.every(w=>w.contact));assert.equal(recoveryReason(t,EXPRESS_ROUTE),'');assert.ok(projectRoad(EXPRESS_ROUTE,t.position.x,t.position.z).distance<.05);assert.ok(Math.abs(t.speed)<.05);sim.dispose()});
