import test from 'node:test';
import assert from 'node:assert/strict';
import {CueGate} from '../src/audio/interface';
import {ThermalDepartureAudio} from '../src/audio/thermal-departure';
import {decodeSave,writeSave,loadSave} from '../src/save';
import {mapAudio} from '../src/audio/mapper';
import {Simulation} from '../src/simulation';

test('P09B cue gate rejects transaction duplicates, bounds key cache and detent repeats',()=>{const gate=new CueGate();assert.equal(gate.accept('build.preset',0,'preset:1'),true);assert.equal(gate.accept('build.preset',1,'preset:1'),false);assert.equal(gate.accept('build.preset',1,'preset:2'),true);assert.equal(gate.accept('ui.nav',2),true);assert.equal(gate.accept('ui.nav',2.02),false);assert.equal(gate.accept('ui.nav',2.2),true);for(let i=0;i<300;i++)assert.equal(gate.accept('build.save',i+3,`save:${i}`),true)});
test('P09B old saves gain independent mix defaults without changing master or records',()=>{const prior={version:1,vehicleId:'slingshot-r-2024',settings:{camera:'near',mute:true,volume:.23},records:{abc:{timeMs:5000,recordedAt:'today'}}};const save=decodeSave(JSON.stringify(prior));assert.equal(save.settings.volume,.23);assert.equal(save.settings.interfaceVolume,1);assert.equal(save.settings.engineVolume,1);save.settings.interfaceVolume=.2;save.settings.engineVolume=.7;let raw='';const storage={getItem:()=>raw,setItem:(_k:string,v:string)=>{raw=v}};assert.equal(writeSave(storage,save),true);assert.deepEqual(loadSave(storage),save);assert.deepEqual(save.records,prior.records)});
class Param{value=0;setTargetAtTime(v:number){this.value=v}}
class Node{gain=new Param();connect(){}disconnect(){}}
class Source extends Node{buffer?:{duration:number};onended?:()=>void;startOffset?:number;stopped=false;start(_time:number,offset:number){this.startOffset=offset}stop(){this.stopped=true}}
class Context{currentTime=0;sources:Source[]=[];createGain(){return new Node()}createBufferSource(){const s=new Source();this.sources.push(s);return s}decodeAudioData(){return Promise.resolve({duration:5.8})}}
test('P09B Thermal obeys equipped eligibility, cinematic sample offsets, pause, removal and late unlock',async()=>{const original=globalThis.fetch;globalThis.fetch=(async(url:unknown)=>({ok:true,json:async()=>({files:[{name:'thermal',file:'thermal.wav'}]}),arrayBuffer:async()=>new ArrayBuffer(0)})) as typeof fetch;try{const context=new Context();const audio=new ThermalDepartureAudio(context as unknown as AudioContext,new Node() as unknown as AudioNode);await audio.prepare();audio.begin(false,true);audio.update(1,false,true,1);assert.equal(context.sources.length,0);audio.begin(true,false);audio.update(2,false,true,1);assert.equal(context.sources.length,0,'late unlock must not arm old departure');audio.begin(true,true);audio.update(.2,false,true,1);assert.equal(context.sources[0].startOffset,.2);audio.update(1.3,true,true,1);assert.equal(context.sources[0].stopped,true);context.currentTime=20;audio.update(1.3,false,true,1);assert.equal(context.sources[1].startOffset,1.3,'pause resumes cinematic offset, not elapsed wall time');audio.stop();assert.equal(context.sources[1].stopped,true);audio.update(3,false,true,1);assert.equal(context.sources.length,2);audio.begin(true,true);audio.update(0,false,true,1);audio.update(.2,false,false,1);audio.update(.5,false,true,1);assert.equal(context.sources.length,3,'mute stops and cannot leave a late tail');audio.dispose()}finally{globalThis.fetch=original}});
test('P09B adjacent source crossfades keep active pitch spans bounded and load follows telemetry',async()=>{const sim=await Simulation.create();try{const t=sim.telemetry(),life={enabled:true,paused:false,mute:false,volume:.5,cockpit:false};for(let rpm=950;rpm<=8500;rpm+=50){t.rpm=rpm;const p=mapAudio(t,life),active=p.layers.filter(l=>l.name.startsWith('engine')&&l.gain>1e-5);assert.ok(active.length<=4);assert.ok(active.every(l=>l.rate>=.72&&l.rate<=1.4));const weights=p.layers.filter(l=>l.name.endsWith('load')).map(l=>l.gain/.055);assert.ok(Math.abs(weights.reduce((a,x)=>a+x*x,0)-1)<1e-5)}t.rpm=3600;t.throttle=1;const load=mapAudio(t,life);t.throttle=0;const lift=mapAudio(t,life);assert.ok(load.layers.find(l=>l.name==='engine-4000-load')!.gain>lift.layers.find(l=>l.name==='engine-4000-load')!.gain)}finally{sim.dispose()}});
