import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {BuildRepository,BUILD_KEY,DRAFT_KEY,DRIVE_KEY,freshRecipe,validateRecipe,PRESETS,stockRecipe,recipeFragment,fragmentRecipe,previewSnapshot} from '../src/signature/config';
import {CURRENT_HANDLING_PROFILE} from '../src/simulation/profile';
import {freshCareer,migrateCareer,transition,type Career} from '../src/career/store';
import {careerRecipe,certifyCareerFinish,type Attempt,type ChapterEvent} from '../src/career-experience/model';
import {freshDemo} from '../src/demo/store';
import {recordKey,decodeSave,freshSave} from '../src/save';
import type {CrewRace} from '../src/competition';
const storage=()=>{const data=new Map<string,string>();return {data,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)}}};
const earned=()=>{const s=freshCareer();s.chapters.firstCompletion=true;s.buildMatters.legacyCrewAccess=true;return s};
function begin(s:Career,event:ChapterEvent,retryOf?:string){const cup=s.ownBuild.activeCupId?s.ownBuild.cups[s.ownBuild.activeCupId]:null;return transition(s,{type:'chapter-begin',event,id:randomUUID(),cupId:randomUUID(),retryOf,routeVersion:event==='coastline-cup'&&!cup?.stages.length?'1':'express-layout-v1'}).state}
function finish(s:Career){const a=s.ownBuild.active!,standings=a.participants.map((id,i)=>({id,place:i+1,status:'finished',timeMs:80000+i*1000,valid:true,lap:1,nextGate:16,progress:2500,invalidReason:null})),p=standings.find(v=>v.id==='player')!;const snap={event:a.competitionId,handlingProfileId:a.handlingProfile,laps:1,phase:'finished',paused:false,countdown:0,elapsedMs:90000,attemptId:a.id,allFinished:true,standings,playerResult:{...p,participantId:'player',attemptId:a.id,event:a.competitionId,laps:1}} as ReturnType<CrewRace['snapshot']>;return transition(s,{type:'chapter-result',result:certifyCareerFinish(a,snap)})}
function historicalActive(s:Career,profile:'slingmods-sport-v1'|'slingmods-sport-v2'){const a=s.ownBuild.active!;a.handlingProfile=a.recipe.handlingProfile=profile;s.ownBuild.attempts[a.id]=structuredClone(a);if(a.cupId){const c=s.ownBuild.cups[a.cupId];c.handlingProfile=c.recipe.handlingProfile=profile}return migrateCareer(s)}

test('P09C every fresh ordinary route, showroom preset and prepared demo resolves current; explicit recipe keeps its tune',()=>{
 const repo=new BuildRepository(storage(),storage());assert.equal(repo.draft().handlingProfile,CURRENT_HANDLING_PROFILE);
 for(const route of ['harbor','express'] as const)for(const mode of ['test','race'] as const){const snapshot=repo.drive(route,mode);assert.equal(snapshot.route,route);assert.equal(snapshot.mode,mode);assert.equal(snapshot.recipe.handlingProfile,CURRENT_HANDLING_PROFILE);for(const profile of ['slingmods-sport-v1','slingmods-sport-v2','slingmods-sport-v3'] as const){const r={...freshRecipe(),handlingProfile:profile};assert.equal(previewSnapshot(fragmentRecipe(recipeFragment(r))!,route,mode).recipe.handlingProfile,profile)}}
 for(const p of PRESETS)assert.equal(p.recipe.handlingProfile,CURRENT_HANDLING_PROFILE);assert.equal(careerRecipe(freshDemo()).handlingProfile,CURRENT_HANDLING_PROFILE);
 for(const file of ['harbor','crew']){const code=readFileSync(`src/${file}.ts`,'utf8');assert.match(code,/const handlingProfile=CURRENT_HANDLING_PROFILE/);assert.match(code,/profileId:handlingProfile/);assert.match(code,/DrivingCamera\(camera,handlingProfile\)/);if(file==='crew'){assert.match(code,/RaceWorld.create\(createCourseEnvironment\(route\),handlingProfile\)/);assert.match(code,/new RivalController\(route,id,Number\(params.get\('seed'\)\?\?1\),handlingProfile\)/);assert.match(code,/handlingProfileId:handlingProfile/)}}
});
test('P09C current-driving action preserves the original named or unsaved build, all options and career bytes',()=>{
 for(const historical of ['slingmods-sport-v1','slingmods-sport-v2'] as const){const durable=storage(),session=storage(),repo=new BuildRepository(durable,session),r={...PRESETS[1].recipe,handlingProfile:historical};durable.data.set('career-sentinel',JSON.stringify(earned()));repo.save('My exact old build',r);const before=JSON.stringify(repo.recipes()[0]),career=durable.data.get('career-sentinel');const copy=repo.useCurrentDriving(r);assert.equal(copy.handlingProfile,CURRENT_HANDLING_PROFILE);assert.deepEqual({...copy,handlingProfile:historical},r);assert.equal(JSON.stringify(repo.recipes()[0]),before);assert.equal(durable.data.get('career-sentinel'),career);assert.deepEqual(repo.draft(),copy);repo.beginDrive(copy,'harbor','test');assert.deepEqual(repo.drive().recipe,copy);assert.deepEqual(new BuildRepository(durable,session).draft(),copy);assert.deepEqual(repo.recipes()[0].recipe,r)}
 const d=storage(),s=storage(),repo=new BuildRepository(d,s),old={...freshRecipe(),handlingProfile:'slingmods-sport-v1' as const};repo.useCurrentDriving(old);assert.deepEqual(repo.recipes()[0].recipe,old);assert.deepEqual([...d.data.keys()],[BUILD_KEY]);assert.deepEqual([...s.data.keys()],[DRAFT_KEY]);
});
test('P09C product-only stock comparison retains finish and historical/current profile; corrupt upgrade retains original bytes',()=>{
 for(const handlingProfile of ['slingmods-sport-v1','slingmods-sport-v2','slingmods-sport-v3'] as const){const r={...PRESETS[1].recipe,handlingProfile};const before=structuredClone(r),stock=stockRecipe(r);assert.equal(stock.handlingProfile,handlingProfile);assert.equal(stock.finish,r.finish);assert.deepEqual(stock.products,{});assert.deepEqual(stock.lights,r.lights);assert.deepEqual(r,before)}
 const d=storage(),s=storage(),repo=new BuildRepository(d,s);d.data.set(BUILD_KEY,'future-invalid');const before=[...d.data];assert.throws(()=>repo.useCurrentDriving({...freshRecipe(),handlingProfile:'slingmods-sport-v1'}));assert.deepEqual([...d.data],before);assert.equal(s.data.has(DRAFT_KEY),false);assert.throws(()=>validateRecipe({...freshRecipe(),handlingProfile:'future-v99'}));
});
test('P09C historical in-progress attempts survive migration and retry; a genuinely new event uses current',()=>{
 for(const profile of ['slingmods-sport-v1','slingmods-sport-v2'] as const){let s=historicalActive(begin(earned(),'open-it-up'),profile);const a=structuredClone(s.ownBuild.active!);s=migrateCareer(JSON.parse(JSON.stringify(s)));assert.deepEqual(s.ownBuild.active,a);s=begin(s,'open-it-up',a.id);assert.equal(s.ownBuild.active!.handlingProfile,profile);assert.deepEqual(s.ownBuild.active!.recipe,a.recipe);assert.equal(s.ownBuild.attempts[a.id].status,'abandoned');const result=finish(s);assert.equal(result.receipt?.handlingProfile,profile);assert.equal(result.receipt?.amount,800);s=begin(result.state,'open-it-up');assert.equal(s.ownBuild.active!.handlingProfile,CURRENT_HANDLING_PROFILE);assert.equal(s.credits,800)}
});
test('P09C historical Cup keeps both frozen legs, retry and receipts; next Cup is current without rewriting records',()=>{
 let s=finish(begin(earned(),'open-it-up')).state;s=finish(begin(s,'hold-your-nerve')).state;s=historicalActive(begin(s,'coastline-cup'),'slingmods-sport-v2');const cup=s.ownBuild.activeCupId!,recipe=structuredClone(s.ownBuild.active!.recipe);s=finish(s).state;s=migrateCareer(JSON.parse(JSON.stringify(s)));s=begin(s,'coastline-cup');assert.equal(s.ownBuild.active!.stage,1);assert.deepEqual(s.ownBuild.active!.recipe,recipe);s=begin(s,'coastline-cup',s.ownBuild.active!.id);s=finish(s).state;assert.equal(s.credits,2400);assert.equal(s.ownBuild.cups[cup].status,'completed');assert.ok(s.ownBuild.cups[cup].stages.every(r=>r.handlingProfile==='slingmods-sport-v2'));const old=structuredClone(s.ownBuild.records);s=begin(s,'coastline-cup');assert.equal(s.ownBuild.active!.handlingProfile,CURRENT_HANDLING_PROFILE);assert.deepEqual(s.ownBuild.records,old);
});
test('P09C time-trial keys keep old records incomparable with current and recipe validation never rewrites them',()=>{
 const save=freshSave(),route={id:'harbor',version:'1'};for(const profile of ['legacy-p08a','slingmods-sport-v1','slingmods-sport-v2'])save.records[recordKey(route,'day',`slingshot-r-2024-${profile}`)]={timeMs:80000,recordedAt:'2026-09-15'};const reloaded=decodeSave(JSON.stringify(save));assert.deepEqual(reloaded.records,save.records);assert.equal(reloaded.records[recordKey(route,'day',`slingshot-r-2024-${CURRENT_HANDLING_PROFILE}`)],undefined);
});
