import {InputResolver} from '../src/driving/input';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {Simulation,steeringLimit,steeringRequest,steeringDemandForAngle,CURRENT_HANDLING_PROFILE} from '../src/simulation';
import {createSweeper,MOTION_PAD,yaw} from '../scripts/p09c-motion-protocol';import {streetSetup} from '../src/career/suspension';
const profile=CURRENT_HANDLING_PROFILE;
test('v3 request preserves left/right symmetry, meaningful analog magnitude, continuous speed change, brake reserve and inverse controller mapping',()=>{
 for(const speed of[0,4.4704,13.4112,22.352,31.2928,49.1744])for(const brake of[0,.25,.5,1])for(const d of[.25,.5,.75,1]){const request=steeringRequest(d,speed,profile,brake);assert.equal(request,-steeringRequest(-d,speed,profile,brake));assert.equal(request,steeringRequest(d,speed,profile,0));assert.ok(Math.abs(steeringDemandForAngle(request,speed,profile,brake)-d)<1e-12);assert.ok(Math.abs(steeringLimit(speed+.0001,profile)-steeringLimit(speed-.0001,profile))<.0001)}
 assert.ok(steeringLimit(49.1744,profile)<.02,'110 mph is bounded below 1.15 degrees, not parking lock');
 assert.ok(steeringLimit(22.352,profile)>steeringLimit(22.352,'slingmods-sport-v2'));
});
for(const [mph,radius]of[[50,90],[65,150]])for(const direction of[-1,1] as const)test(`v3 physical ${mph} mph / ${radius} m sweeper ${direction} has useful headroom`,async()=>{
 const {sim,protocol}=await createSweeper(profile,{mph,radius,direction});let count=0,sum=0,peak=0,saturation=0;for(let i=0;i<2400&&!protocol.finished;i++){const c=protocol.control(sim.telemetry());sim.step(c);const s=protocol.sample(sim.telemetry(),c);assert.ok(s.telemetry.wheels.every(w=>w.contact));for(const w of s.telemetry.wheels)assert.ok(Math.hypot(w.longitudinalForce,w.lateralForce)<=w.gripLimit+1e-7);if(s.scored){count++;sum+=s.error*s.error;peak=Math.max(peak,Math.abs(s.error));saturation+=Number(s.command.saturated);assert.ok(Math.abs(s.speedErrorFraction)<=.05)}}assert.ok(count>=360);assert.ok(Math.sqrt(sum/count)<=1.5);assert.ok(peak<=3);assert.ok(saturation/count<.1);sim.dispose();
});
for(const [mph,target]of[[60,40],[110,140]])test(`v3 ${mph} mph stop retains v2 entry/stop definitions and force bounds`,async()=>{const sim=await Simulation.create(MOTION_PAD,profile);sim.reset({x:0,y:.025,z:35});let entry:ReturnType<Simulation['telemetry']>|null=null,last=sim.telemetry(),distance=0,stopped=false;for(let i=0;i<2400;i++){if(!entry&&last.speed>=mph*.44704-.05)entry=last;sim.step({throttle:entry?0:1,brake:entry?1:0,steer:0,reverse:false});const t=sim.telemetry();if(entry)distance+=Math.hypot(t.position.x-last.position.x,t.position.z-last.position.z);assert.ok(t.wheels.every(w=>w.contact));for(const w of t.wheels)assert.ok(Math.hypot(w.longitudinalForce,w.lateralForce)<=w.gripLimit+1e-7);last=t;if(entry&&Math.abs(t.speed)<.2){stopped=true;break}}assert.ok(stopped&&entry);assert.ok(distance<=target);assert.ok(Math.abs(yaw(last.quaternion)-yaw(entry.quaternion))<=2*Math.PI/180);assert.ok(Math.abs(last.position.x-entry.position.x)<=.5);sim.dispose()});
test('v3 exact v2 launch and stock/removed/street suspension equivalence',async()=>{const old=await Simulation.create(MOTION_PAD,'slingmods-sport-v2'),stock=await Simulation.create(MOTION_PAD,profile),street=await Simulation.create(MOTION_PAD,profile),removed=await Simulation.create(MOTION_PAD,profile);street.configureSuspension(streetSetup());removed.configureSuspension({...streetSetup(),rideHeightMm:10});removed.configureSuspension(null);let launch=0;for(let i=0;i<1000;i++){const c={throttle:i<400?1:.3,brake:i>800?.5:0,steer:i<400?0:Math.sin(i/50)*.4,reverse:false};for(const s of[old,stock,street,removed])s.step(c);assert.deepEqual(stock.telemetry(),street.telemetry());assert.deepEqual(stock.telemetry(),removed.telemetry());if(i<400)assert.deepEqual(stock.telemetry(),old.telemetry());if(!launch&&stock.telemetry().speed>=26.8224)launch=(i+1)/60}assert.equal(launch,4.733333333333333);for(const s of[old,stock,street,removed])s.dispose()});

test('Sport v3 preserves wall collision and chassis landing while guards omit only planar floor',async()=>{const wall={...MOTION_PAD,obstacles:[{id:'wall',center:[0,1,0],size:[10,2,.5]}]},sim=await Simulation.create(wall,'slingmods-sport-v3');sim.reset({x:0,z:12,y:.025});sim.enableDiagnostics();let guardContact=false;for(let i=0;i<420;i++){sim.step({throttle:i<300?1:0,brake:i>=300?1:0,steer:0,reverse:false});assert.ok(sim.telemetry().position.z>1);guardContact ||=sim.diagnostics().contacts.some(c=>c.kind==='guard')}assert.ok(guardContact);sim.reset({x:15,z:15,y:2});for(let i=0;i<360;i++)sim.step({throttle:0,brake:0,steer:0,reverse:false});assert.ok(sim.telemetry().position.y>-.05);assert.ok(sim.telemetry().wheels.every(w=>w.contact));sim.dispose()});
test('Sport v3 release/repress reverse, explicit selector and focus cancellation use existing input lifecycle',()=>{const input=new InputResolver('slingmods-sport-v3');let now=0;const poll=(keys:string[]=[],speed=0,focused=true)=>input.poll(now+=17,{keys:new Set(keys),pads:[],focused},speed);poll();poll(['KeyW'],10);assert.equal(poll(['KeyS'],8).direction,'D');assert.equal(poll(['KeyS'],0).direction,'D');poll();assert.equal(poll(['KeyS']).direction,'R');assert.equal(poll(['KeyS']).control.throttle,1);poll([],0,false);assert.equal(poll(['KeyS']).control.throttle,0);const explicit=new InputResolver('slingmods-sport-v3');explicit.poll(0,{keys:new Set(),pads:[],focused:true});assert.equal(explicit.poll(17,{keys:new Set(['KeyX']),pads:[],focused:true}).direction,'R');assert.equal(explicit.poll(34,{keys:new Set(['KeyW']),pads:[],focused:true}).control.throttle,1)});

for(const brake of[.5,1])for(const steer of[-1,1])test('Sport v3 matched fast brake-turn '+brake+' / '+steer+' stops with secure support',async()=>{const sim=await Simulation.create(MOTION_PAD,'slingmods-sport-v3');sim.reset({x:0,y:.025,z:35});let entry=false,stopped=false,last=sim.telemetry(),turn=0,path=0;for(let i=0;i<30*60;i++){if(last.speed>=34.95)entry=true;sim.step({throttle:entry?0:1,brake:entry?brake:0,steer:entry?steer:0,reverse:false});const t=sim.telemetry();assert.ok(t.wheels.every(w=>w.contact));assert.ok(1-2*(t.quaternion.x**2+t.quaternion.z**2)>.95);if(entry){const delta=yaw(t.quaternion)-yaw(last.quaternion);turn+=Math.atan2(Math.sin(delta),Math.cos(delta));path+=Math.hypot(t.position.x-last.position.x,t.position.z-last.position.z)}last=t;if(entry&&Math.abs(t.speed)<.2){stopped=true;break}}assert.ok(stopped);assert.ok(turn*steer>.5&&turn*steer<Math.PI);assert.ok(path<120);sim.dispose()});
test('Sport v3 analog magnitude, pause and disconnect cannot inherit held reverse pedals',()=>{const input=new InputResolver('slingmods-sport-v3');let now=0;const pad=(value=0)=>({index:0,id:'P09A standard simulated controller',mapping:'standard',connected:true,axes:[0],buttons:Array.from({length:17},(_,i)=>({value:i===6?value:0}))});const poll=(value=0,keys:string[]=[],connected=true)=>input.poll(now+=17,{keys:new Set(keys),pads:connected?[pad(value)]:[],focused:true},0);poll();let r=poll(.37);assert.equal(r.direction,'R');assert.equal(r.control.throttle,.37);poll(.37,['Escape']);assert.equal(poll(.37).control.throttle,0);poll(.37,['Escape']);assert.equal(poll(.37).control.throttle,0);poll();assert.equal(poll(.42).control.throttle,.42);poll(0,[],false);assert.equal(input.paused,true);assert.equal(poll(.42).control.throttle,0);poll(.42,['Escape']);assert.equal(poll(.42).control.throttle,0);poll();assert.equal(poll(.31).control.throttle,.31)});

import {recoveryReason,freeRecoveryPose} from '../src/driving/recovery';
import {scenarios} from '../src/simulation/scenarios';
import {EXPRESS_ROUTE} from '../src/express/route';
import {projectRoad} from '../src/course/environment';
import type {VehicleTelemetry} from '../src/simulation';
test('actual Sport v3 high-speed-curb overturn is detected and explicit free recovery restores supported upright state',async()=>{const scenario=scenarios.find(s=>s.name==='high-speed-curb')!,sim=await Simulation.create(undefined,'slingmods-sport-v3');sim.reset(scenario.pose);let detected:VehicleTelemetry|undefined,minUpright=1;for(let tick=0;tick<scenario.seconds*60;tick++){sim.step(scenario.control(tick/60,sim.telemetry()));const t=sim.telemetry(),up=1-2*(t.quaternion.x**2+t.quaternion.z**2);minUpright=Math.min(minUpright,up);if(recoveryReason(t,EXPRESS_ROUTE)==='Car overturned')detected=t}assert.ok(minUpright<0,'Stress case must actually overturn, not inject a mocked quaternion');assert.ok(detected,'Actual slow overturn must offer recovery');const pose=freeRecoveryPose(EXPRESS_ROUTE,detected!);sim.reset(pose);for(let i=0;i<180;i++)sim.step({throttle:0,brake:0,steer:0,reverse:false});const t=sim.telemetry();assert.ok(1-2*(t.quaternion.x**2+t.quaternion.z**2)>.99);assert.ok(t.wheels.every(w=>w.contact));assert.equal(recoveryReason(t,EXPRESS_ROUTE),'');assert.ok(projectRoad(EXPRESS_ROUTE,t.position.x,t.position.z).distance<.05);assert.ok(Math.abs(t.speed)<.05);sim.dispose()});

import fs from 'node:fs';import {createHash} from 'node:crypto';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/p09c-v2-baseline-digests.json',import.meta.url),'utf8'));
for(const item of fixture.cases)test('reviewed '+item.profile+' '+item.scenario+' full telemetry remains byte equivalent',async()=>{const sim=await Simulation.create(undefined,item.profile),hash=createHash('sha256');for(let i=0;i<item.ticks;i++){const t=i/60,c=item.scenario==='long-throttle-brake-pad'?{throttle:t<21?1:0,brake:t>=21?1:0,steer:0,reverse:false}:{throttle:t<10?.7:t<16?.2:0,brake:t>=18?.7:0,steer:t>5&&t<16?Math.sin(t)*.4:0,reverse:t>24};sim.step(c);hash.update(JSON.stringify(sim.telemetry())+'\n')}assert.equal(hash.digest('hex'),item.telemetrySha256);sim.dispose()});
