import test from 'node:test';import assert from 'node:assert/strict';
import {build} from 'vite';import {chromium} from '@playwright/test';import {mkdtemp,writeFile,rm,rmdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
test('Showcase build controls scroll into reach at 720/1080, and pending/failed purchases preserve navigation and state',async()=>{
 const root=process.cwd().replaceAll('\\','/'),temp=await mkdtemp(path.join(tmpdir(),'p06-ui-')),entry=path.join(temp,'entry.ts');let js,css;
 await writeFile(entry,`export {BuildUI} from ${JSON.stringify(root+'/src/career/build-ui.ts')};export {CrewUI} from ${JSON.stringify(root+'/src/crew-ui.ts')};export {MemoryCareerStore,freshCareer} from ${JSON.stringify(root+'/src/career/store.ts')};`);
 try{const result=await build({configFile:false,logLevel:'silent',build:{write:false,minify:false,lib:{entry,formats:['es'],fileName:'ui'}}}),output=(Array.isArray(result)?result[0]:result).output;js=output.find(x=>x.type==='chunk').code;css=output.filter(x=>x.type==='asset'&&x.fileName.endsWith('.css')).map(x=>x.source).join('\n')}finally{await rm(entry);await rmdir(temp)}
 const html=`<!doctype html><style>*{box-sizing:border-box}body{margin:0;background:#303640}#app{min-height:100vh}${css}</style><div id="app"><button id="chapter-build">Build</button><button id="open-build" style="visibility:hidden">Legacy Build</button></div><script type="module">import {BuildUI,CrewUI,MemoryCareerStore,freshCareer} from '/ui.js';const fixture=freshCareer();fixture.credits=800;window.store=new MemoryCareerStore(fixture);let state=await store.read();const listeners=new Set();window.client={get state(){return state},stale:false,durable:false,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},async execute(c){if(c.type==='purchase'&&window.holdPurchase)await new Promise((resolve,reject)=>{window.releasePurchase=resolve;window.rejectPurchase=reject});const result=await store.execute(c);state=result.state;listeners.forEach(fn=>fn());return result}};window.CrewUI=CrewUI;window.buildUI=new BuildUI(client,{open(){},previewNight(){},appearance(){}});buildUI.open();window.ready=true;</script>`;
 const browser=await chromium.launch({headless:true});try{for(const viewport of[{width:1280,height:720},{width:1920,height:1080}]){const context=await browser.newContext({viewport});await context.route('http://127.0.0.1:42971/**',r=>r.fulfill({contentType:r.request().url().endsWith('/ui.js')?'text/javascript':'text/html',body:r.request().url().endsWith('/ui.js')?js:html}));const page=await context.newPage();await page.goto('http://127.0.0.1:42971/');await page.waitForFunction(()=>window.ready);
 await page.locator('#preview-kit').click();for(const selector of['#close-build','#preview-kit','#buy-kit','[data-color="cyan"]','#brightness-down','#brightness-up','#kit-power','#bay-night','#drive-kit-night','#real-product','summary']){const reachable=await page.locator(selector).evaluate(el=>{el.focus();el.scrollIntoView({block:'nearest'});const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))});assert.equal(reachable,true,`${viewport.width} ${selector} receives input`)}
 const link=await page.locator('#real-product').evaluate(a=>({href:a.href,target:a.target,rel:a.rel}));assert.match(link.href,/slingmods\.com/);assert.equal(link.target,'_blank');assert.match(link.rel,/noopener/);
 await page.locator('[data-color="cyan"]').click();await page.locator('#close-build').click();assert.deepEqual(await page.evaluate(()=>({open:buildUI.inspect().open,preview:buildUI.inspect().preview,focus:document.activeElement.id,color:client.state.appearance.color,entryToast:!document.querySelector('#rae-card').hidden})),{open:false,preview:false,focus:'chapter-build',color:'red',entryToast:false});await page.evaluate(()=>buildUI.open());await page.evaluate(()=>{window.holdPurchase=true});await page.locator('#buy-kit').click();await page.waitForFunction(()=>window.buildUI.inspect().pending);const blocked=await page.evaluate(()=>{buildUI.close();document.querySelector('#drive-kit-night').click();return {open:buildUI.inspect().open,pending:buildUI.inspect().pending,disabled:document.querySelector('#close-build').disabled,linkDisabled:document.querySelector('#drive-kit-night').getAttribute('aria-disabled'),credits:client.state.credits,owned:client.state.owned}});assert.deepEqual(blocked,{open:true,pending:true,disabled:true,linkDisabled:'true',credits:800,owned:false});assert.equal(page.url(),'http://127.0.0.1:42971/');
 await page.evaluate(()=>window.rejectPurchase(Error('Deliberate transaction failure')));await page.waitForFunction(()=>!window.buildUI.inspect().pending);assert.match(await page.locator('#build-feedback').textContent(),/Deliberate transaction failure.*No transaction committed/);assert.deepEqual(await page.evaluate(()=>({credits:client.state.credits,owned:client.state.owned})),{credits:800,owned:false});
 await page.evaluate(()=>window.holdPurchase=false);await page.locator('#buy-kit').click();await page.waitForFunction(()=>window.client.state.owned&&!window.buildUI.inspect().pending);assert.equal(await page.evaluate(()=>window.client.state.credits),200);await page.locator('[data-color="cyan"]').click();await page.waitForFunction(()=>!window.buildUI.inspect().pending&&window.client.state.appearance.color==='cyan');await page.locator('#stock-compare').click();assert.equal(await page.evaluate(()=>window.buildUI.inspect().compare),true);await page.locator('#stock-compare').click();assert.equal(await page.evaluate(()=>window.client.state.appearance.color),'cyan');const crewCheck=await page.evaluate(()=>{buildUI.close();const actions=[];const ui=new CrewUI(document.querySelector('#app'),a=>actions.push(a));const state={phase:'ready',paused:false,elapsedMs:0,standings:['player','maya','jett','nico'].map((id,i)=>({id,place:i+1,lap:1,status:'running'}))};const t={speed:0,rpm:950,gear:1};ui.update(state,t,true,'near',null,'','',false);const audio=document.createElement('div');audio.id='game-audio';audio.innerHTML='<button>Mute</button>';let muted=false;audio.firstChild.onclick=()=>muted=!muted;document.body.append(audio);const sample=(held=[])=>({focused:true,keys:new Set(),pads:[{id:'ui-test',index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},(_,i)=>({value:held.includes(i)?1:0,pressed:held.includes(i)}))}]});const press=i=>{ui.menuInput(sample(),state);ui.menuInput(sample([i]),state)};document.activeElement.blur();press(13);press(13);press(13);const summaryFocused=document.activeElement.tagName==='SUMMARY';press(0);const helpOpen=ui.root.querySelector('details').open;press(13);press(0);const audioWorked=muted;ui.update(state,t,true,'near',null,'','',true);ui.menuInput({focused:true,keys:new Set(['Enter']),pads:[]},state);const order=ui.root.querySelector('#crew-order').firstElementChild;ui.update(state,{...t,rpm:1000},true,'near',null,'','',true);return{summaryFocused,helpOpen,audioWorked,actions,orderStable:order===ui.root.querySelector('#crew-order').firstElementChild}});assert.deepEqual(crewCheck,{summaryFocused:true,helpOpen:true,audioWorked:true,actions:[],orderStable:true});await context.close()}}finally{await browser.close()}
});
