import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {SpyderMotion} from '../src/presentation/spyder';import {SpyderProducts} from '../src/presentation/spyder-products';import {SPYDER_DEFINITION} from '../src/simulation/vehicle-definition';import {freshSpyderBuild} from '../src/signature/spyder-catalog';import type {VehicleTelemetry} from '../src/simulation';
// Structural motion test only. Browser and Blender evidence separately validate actual textures.
async function load(name:string){const bytes=await readFile('public/assets/spyder/'+name+'.glb'),n=bytes.readUInt32LE(12),j=JSON.parse(bytes.subarray(20,20+n).toString());delete j.images;delete j.textures;for(const m of j.materials??[]){if(m.pbrMetallicRoughness){delete m.pbrMetallicRoughness.baseColorTexture;delete m.pbrMetallicRoughness.metallicRoughnessTexture}delete m.normalTexture;delete m.occlusionTexture;delete m.emissiveTexture;}const str=JSON.stringify(j),padded=Buffer.from(str+' '.repeat((4-Buffer.byteLength(str)%4)%4)),bin=bytes.subarray(20+n),out=Buffer.alloc(20+padded.length+bin.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(padded.length,12);out.writeUInt32LE(0x4e4f534a,16);padded.copy(out,20);bin.copy(out,20+padded.length);return(await new GLTFLoader().parseAsync(out.buffer.slice(out.byteOffset,out.byteOffset+out.byteLength),'')).scene;}
test('actual GLB rings/calipers/fenders steer without spinning; travel and opposite spin remain independent',async()=>{
 const car=await load('spyder-f3'),products=new SpyderProducts(car,await load('spyder-products')),motion=new SpyderMotion(car),build=freshSpyderBuild();build.parts={front:true,rear:true,sway:true,wheels:true,underglow:true,throttle:true};products.set(build);
 const t=(steer:number,spin:number,travel:number[])=>({steer,wheels:SPYDER_DEFINITION.layout.wheels.map((w,i)=>({steer:i<2?steer:0,spin,localCenter:{x:w.center[0],y:w.center[1]+travel[i],z:w.center[2]}}))}) as VehicleTelemetry;
 for(const steer of [-.6,.6]){
  motion.pose(t(steer,0,[.04,-.04,.06]));car.updateWorldMatrix(true,true);const stationary=['spyder_wheel_light_0','spyder_wheel_light_1','spyder_front_left_steer_mesh','spyder_front_right_steer_mesh'];const before=stationary.map(n=>{const o=car.getObjectByName(n);assert.ok(o,n);return o.matrixWorld.toArray()});
  for(const spin of [-2,2]){motion.pose(t(steer,spin,[.04,-.04,.06]));car.updateWorldMatrix(true,true);stationary.forEach((n,i)=>assert.deepEqual(car.getObjectByName(n)!.matrixWorld.toArray(),before[i]));assert.equal(car.getObjectByName('front_left_spin')!.rotation.x,-spin);assert.equal(car.getObjectByName('rear_spin')!.rotation.x,-spin);assert.ok(Math.abs(car.getObjectByName('steering_control')!.rotation.y-steer)<1e-6);}
  const report=products.inspect();assert.deepEqual(report.stationaryRings.map(x=>x.parent),['front_left_steer','front_right_steer']);assert.ok(report.stock.every(x=>!x.spring&&!x.shock));assert.equal(report.requiredEndLinks,2);
 }
 products.set();assert.ok(products.inspect().stock.every(x=>x.spring&&x.shock));assert.ok(products.inspect().stationaryRings.every(x=>!x.visible));products.dispose();assert.equal(car.getObjectByName('spyder_wheel_light_0'),undefined);
});
