import {pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';import {writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {Simulation,FIXED_DT, type VehicleControl} from '../../src/simulation';
import {RYKER_DEFINITION} from '../../src/simulation/vehicle-definition';import type {EnvironmentDefinition} from '../../src/course/environment';
const out='assets/ryker/evidence/complete/dynamics';await mkdir(out,{recursive:true});
const baseline=execFileSync('git',['show','7b041ac:src/simulation/index.ts'],{encoding:'utf8'}).replace(/from\s*(['"])(\.[^'"]+)\1/g,(_all,q,ref)=>'from '+q+pathToFileURL(path.resolve('src/simulation',ref)).href+q);
await writeFile('.tools/ryker-slingshot-baseline.ts',baseline);const {Simulation:Original}=await import('../../.tools/ryker-slingshot-baseline');
const coast:VehicleControl={throttle:0,brake:0,steer:0,reverse:false};
const flat:EnvironmentDefinition={ground:{center:[0,-.15,0],size:[800,.3,800]},obstacles:[],ramps:[],surfaceAt:()=>({id:'asphalt',mu:1.05,rolling:.014})};
const baselineReport=[];
for(const profile of ['slingmods-sport-v1','slingmods-sport-v4','slingmods-sport-v5'] as const){const a=await Original.create(flat,profile),b=await Simulation.create(flat,profile);try{for(let tick=0;tick<1200;tick++){const control={...coast,throttle:tick<360?.8:tick>900?.45:0,brake:tick>=480&&tick<800?.7:0,steer:tick>=300&&tick<660?.35:0,reverse:tick>900};a.step(control);b.step(control);const {vehicleId,definitionId,powertrain,cvtRatio,...actual}=b.telemetry();assert.deepEqual(actual,a.telemetry(),`${profile} tick ${tick}`)}baselineReport.push({profile,ticks:1200,allTelemetryFields:'exact equality'})}finally{a.dispose();b.dispose()}}
const environment={...flat,obstacles:[{center:[-.52,.04,-8],size:[.34,.08,1.2]}],ramps:[{center:[0,0,-20],width:3,length:5,rise:.12}]};
const report:{baseline:unknown;scenarios:any[];provenance:string}={baseline:baselineReport,scenarios:[],provenance:'Baseline simulator from immutable audit 7b041ac; unchanged dependencies. Separate worlds, same fixed controls, strict numerical equality. Ryker runs use real Rapier tire rays, rigid contacts and bounded controls; no teleport after start.'};
for(const side of [-1,1])for(const elka of [false,true]){environment.obstacles[0].center[0]=side<0?-.52:.54;const sim=await Simulation.create(environment,'ryker-road-v1',RYKER_DEFINITION),rows=[];sim.configureRykerSuspension(elka);sim.reset({x:0,z:10,y:0});for(let tick=0;tick<900;tick++){const t=sim.telemetry(),target=tick<600?10:0,control={...coast,throttle:Math.max(0,Math.min(.65,(target-t.speed)*.4)),brake:tick>=600?.65:Math.max(0,(t.speed-target)*.3)};sim.step(control);rows.push(sim.telemetry())}const finite=rows.every(t=>Number.isFinite(t.speed)&&t.wheels.every(w=>Number.isFinite(w.load)&&Number.isFinite(w.travel))),roll=Math.max(...rows.map(t=>Math.abs(Math.atan2(2*(t.quaternion.w*t.quaternion.z+t.quaternion.x*t.quaternion.y),1-2*(t.quaternion.x**2+t.quaternion.z**2))))),travel=[0,1,2].map(i=>({min:Math.min(...rows.map(t=>t.wheels[i].travel)),max:Math.max(...rows.map(t=>t.wheels[i].travel))}));assert.ok(finite);assert.ok(roll<.25);assert.ok(rows.at(-1)!.speed<.15);assert.ok(Math.max(...rows.map(t=>Math.abs(t.wheels[0].travel-t.wheels[1].travel)))>.02,'single wheel bump must articulate independently');report.scenarios.push({side,elka,peakRollRadians:roll,travel,finalSpeed:rows.at(-1)!.speed,rows});sim.dispose()}
const clearance={...flat,obstacles:[-1,1].map(sign=>({center:[sign*.775,.4,-8],size:[.2,.8,32]}))};
const narrow=await Simulation.create(clearance,'ryker-road-v1',RYKER_DEFINITION);narrow.reset({x:0,y:0,z:12});let minimumSpeed=Infinity,maxLateral=0;for(let tick=0;tick<1200;tick++){narrow.step({...coast,throttle:Math.max(0,Math.min(.7,(4-narrow.telemetry().speed)*.4+.2))});const t=narrow.telemetry();if(tick>90)minimumSpeed=Math.min(minimumSpeed,t.speed);maxLateral=Math.max(maxLateral,Math.abs(t.position.x))}console.log(JSON.stringify({narrowPosition:narrow.telemetry().position,narrowSpeed:narrow.telemetry().speed,maxLateral}));assert.ok(narrow.telemetry().position.z < -24);assert.ok(maxLateral<.1);report.scenarios.push({kind:'1.35m clear corridor',minimumSpeed,maxLateral,final:narrow.telemetry()});narrow.dispose();
await writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({baseline:baselineReport,bumps:report.scenarios.map(({rows,...summary})=>summary)}));
