import {chromium} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'assets/ryker/evidence/complete/preview';await mkdir(out,{recursive:true});const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],report={errors};p.on('pageerror',e=>errors.push(e.message));
const ready=async()=>{const u=new URL(p.url());if(u.searchParams.get('test')!=='1'||u.searchParams.get('profile')!=='1'){u.searchParams.set('test','1');u.searchParams.set('profile','1');u.searchParams.set('captureBuffer','1');await p.goto(u.href)}await p.waitForFunction(()=>window.__SIGNATURE?.ready||window.__EXPRESS?.ready,null,{timeout:120000})};const snap=()=>p.evaluate(()=>window.__SIGNATURE?window.__SIGNATURE.inspect():window.__EXPRESS.inspect());const shot=name=>p.screenshot({path:out+'/'+name+'.png'});
try{
 await p.goto((process.env.BASE_URL||'http://127.0.0.1:5198')+'/?profile=1&scene=signature&screen=build&visual=ryker&test=1&captureBuffer=1');await ready();
 for(const [category,part]of [['Suspension','shocks'],['Body Kit','body'],['Exhaust','exhaust'],['Lighting','underglow']]){await p.locator(`[data-action=category][data-value="${category}"]`).click();await p.locator(`[data-action=ryker-toggle][data-value="${part}"]`).click();await p.waitForTimeout(150)}
 await p.locator('[data-action=category][data-value=Paint]').click();await p.locator('[data-action=finish][data-value=graphite-red]').click();await p.waitForTimeout(300);report.showroom=await snap();await shot('showroom-graphite');
 await p.locator('[data-action=advanced]').click();await p.locator('[data-action=view][data-value=route-relief]').click();await p.waitForTimeout(900);await shot('wall-relief');await p.locator('[data-action=view][data-value=hero]').click();await p.waitForTimeout(900);
 await p.locator('[data-action=test-drive]').click();await p.waitForFunction(()=>window.__SIGNATURE?.inspect().departure?.active,null,{timeout:90000});await p.waitForTimeout(3100);report.departure=await snap();await shot('departure-graphite');assert.deepEqual(report.departure.recipe,report.showroom.recipe);
 await p.waitForURL('**/?scene=express**',{timeout:30000});await ready();report.road=await snap();assert.deepEqual(report.road.recipe,report.showroom.recipe);assert.equal(report.road.telemetry.powertrain,'cvt');
 await p.locator('#start-crew').click();await p.keyboard.down('ArrowUp');await p.waitForTimeout(1600);await p.keyboard.up('ArrowUp');await p.locator('#race-pause').click();await shot('road-graphite');
 await p.locator('[data-action=resume]').click();await p.keyboard.down('KeyR');await p.waitForTimeout(1400);await p.keyboard.up('KeyR');await p.waitForTimeout(400);report.retry=await snap();assert.deepEqual(report.retry.recipe,report.showroom.recipe);await p.locator('#race-pause').click();await p.locator('[data-action=bay]').click();await ready();report.returned=await snap();assert.equal(report.returned.mode,'free-preview');assert.deepEqual(report.returned.recipe,report.showroom.recipe);await shot('returned-graphite');
 await p.locator('[data-vehicle="2026"]').click();await ready();report.slingshot=await snap();assert.equal(report.slingshot.recipe.vehicleId,'slingshot-r-2024');assert.deepEqual(report.slingshot.recipe.products,{});
 await p.locator('[data-vehicle=ryker]').click();await ready();report.switchedBack=await snap();assert.deepEqual(report.switchedBack.recipe,report.showroom.recipe);for(const state of [report.departure,report.road,report.retry,report.returned,report.switchedBack]){assert.deepEqual(state.finish.paintedSurfaces,report.showroom.finish.paintedSurfaces);assert.deepEqual(state.finish.paintedAccents,report.showroom.finish.paintedAccents)}report.method='Ordinary UI navigation; test/profile flags restored after navigation by reload to expose packaged evidence hooks. Material colors and immutable recipe compared through the full trip.';assert.deepEqual(errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;await shot('failure').catch(()=>{});throw e}finally{await writeFile(out+'/report.json',JSON.stringify(report,null,2));await b.close()}
