import {chromium} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.RYKER_WORK??'.tools/ryker-work';const base=process.env.BASE_URL??'http://127.0.0.1:5198';
await mkdir(out+'/browser',{recursive:true});const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']}),p=await b.newPage({viewport:{width:1440,height:1000}});const report={errors:[]};p.on('pageerror',e=>report.errors.push(e.message));
const ready=key=>p.waitForFunction(k=>window[k]?.ready,key,{timeout:180000});
try{
 await p.goto(base+'/?scene=signature&visual=ryker&screen=events&test=1&profile=1');await ready('__SIGNATURE');
 await p.locator('[data-action=test-drive]').first().click();await ready('__EXPRESS');report.showroomDeparture={url:p.url(),asset:await p.evaluate(()=>window.__EXPRESS.inspect().visual.asset)};assert.match(report.showroomDeparture.asset,/ryker/);
 await p.locator('#start-crew').click();await p.waitForFunction(()=>window.__EXPRESS.inspect().race.phase==='running');await p.keyboard.press('x');await p.keyboard.down('w');await p.waitForTimeout(2000);await p.keyboard.up('w');report.reverse=await p.evaluate(()=>({t:window.__EXPRESS.inspect().telemetry,input:window.__EXPRESS.inspect().input,visual:window.__EXPRESS.inspect().visual}));assert.ok(report.reverse.t.speed<-.5,'actual reverse driving');
 await p.goto(base+'/?scene=express&route=harbor&mode=race&visual=ryker&test=1&profile=1');await ready('__EXPRESS');const race=await p.evaluate(()=>window.__EXPRESS.inspect());report.rivalAssets=Object.fromEntries(Object.entries(race.rivals).map(([k,v])=>[k,v.visual.asset]));assert.ok(Object.values(report.rivalAssets).every(x=>x.includes('model02')),'Slingshot rivals retained');
 await p.goto(base+'/?scene=bay&play=career&visual=ryker&test=1&profile=1');await ready('__SIGNATURE');report.garage=await p.evaluate(()=>({visual:window.__SIGNATURE.inspect().vehicleContext,state:window.__SIGNATURE.inspect().career.state}));console.log('garage buttons',await p.locator('button').allTextContents());
 await p.locator('#continue-chapter').click();await p.locator('#start-shakedown').click();await ready('__EXPRESS');report.career=await p.evaluate(()=>{const i=window.__EXPRESS.inspect();return {asset:i.visual.asset,event:i.eventId,career:!!i.career,profile:i.handlingProfile,state:i.career.state}});assert.match(report.career.asset,/ryker/);assert.ok(report.career.career);await p.screenshot({path:out+'/browser/ryker-career.png'});
 assert.deepEqual(report.errors,[]);report.pass=true;
}catch(e){report.failure=e.stack;report.url=p.url();report.text=await p.locator('body').innerText();throw e}finally{await writeFile(out+'/browser/flows.json',JSON.stringify(report,null,2));await b.close()}
