import {chromium} from '@playwright/test';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.RYKER_URL??'http://127.0.0.1:5199';
const out=process.env.RYKER_WORK??'C:/Users/SM - Dan/Documents/GitHub/slingmods game/ryker-purchased/work';const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']}),p=await b.newPage({viewport:{width:1440,height:1000}});const report={errors:[],assetFailures:[]};p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&r.url().includes('/assets/'))report.assetFailures.push({url:r.url(),status:r.status()})});
try{
 await p.goto(base+'/?scene=signature&visual=ryker&test=1&profile=1');await p.waitForFunction(()=>window.__SIGNATURE?.ready,null,{timeout:120000});report.showroom=await p.evaluate(()=>{const i=window.__SIGNATURE.inspect();return {build:i.build,visual:i.visual,context:i.vehicleContext}});assert.match(report.showroom.visual.asset,/ryker/);await p.screenshot({path:out+'/browser/final-showroom.png'});
 await p.locator('.sig-navigation [data-action=build]').click();assert.equal(await p.locator('.vehicle-appearance-picker').isVisible(),false);await p.screenshot({path:out+'/browser/final-build.png'});
 await p.goto(base+'/?scene=express&visual=ryker&route=harbor&mode=test&test=1&profile=1&look=night');await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:120000});await p.locator('#start-crew').click();await p.waitForFunction(()=>window.__EXPRESS.inspect().race.phase==='running');await p.keyboard.down('w');await p.waitForTimeout(1500);await p.keyboard.up('w');report.drive=await p.evaluate(()=>{const i=window.__EXPRESS.inspect();return {build:i.build,asset:i.visual.asset,driver:i.visual.driver,speed:i.telemetry.speed,profile:i.handlingProfile}});assert.ok(report.drive.speed>1);assert.ok(Object.values(report.drive.driver.arms).every(a=>a.gap<.01));await p.screenshot({path:out+'/browser/final-night-drive.png'});
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.assetFailures,[]);report.pass=true;
}catch(e){report.failure=e.stack;throw e}finally{await writeFile(out+'/static-smoke.json',JSON.stringify(report,null,2));await b.close()}
