import {chromium} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.RYKER_WORK??'C:/Users/SM - Dan/Documents/GitHub/slingmods game/ryker-purchased/work';await mkdir(out+'/browser',{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist','--mute-audio']});
const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const report={browser:await b.version(),viewport:[1440,1000],method:'Isolated headless Chromium, ANGLE D3D11, same viewport and fixed reference camera; short RAF samples include whole scene/post passes. Not sustained FPS certification.',showrooms:{},errors};
async function save(){await writeFile(out+'/browser/runtime-validation.json',JSON.stringify(report,null,2))}
async function bench(){return p.evaluate(()=>new Promise(done=>{let last=performance.now();const ms=[];let draws=0,triangles=0;const calls=[],tris=[],gl=document.querySelector('canvas').getContext('webgl2'),originals={};for(const name of ['drawElements','drawArrays','drawElementsInstanced','drawArraysInstanced']){const f=gl[name].bind(gl);originals[name]=f;gl[name]=(...a)=>{draws++;triangles+=(name.startsWith('drawElements')?a[1]:a[2])/3*(name.endsWith('Instanced')?a[name==='drawElementsInstanced'?4:3]:1);return f(...a)}}function frame(now){ms.push(now-last);last=now;calls.push(draws);tris.push(triangles);draws=triangles=0;if(ms.length<180)requestAnimationFrame(frame);else{for(const [name,f]of Object.entries(originals))gl[name]=f;const sorted=[...ms].sort((a,b)=>a-b);done({frameMs:ms,medianMs:sorted[90],p95Ms:sorted[171],maxMs:sorted.at(-1),meanDraws:calls.reduce((a,b)=>a+b)/calls.length,meanSubmittedTriangles:tris.reduce((a,b)=>a+b)/tris.length,renderer:gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info')?.UNMASKED_RENDERER_WEBGL??gl.RENDERER)})}}requestAnimationFrame(frame)}))}
try{
 for(const visual of ['2026','ryker']){
  await p.goto(`http://127.0.0.1:5198/?scene=signature&visual=${visual}&test=1&profile=1`);await p.waitForFunction(()=>window.__SIGNATURE?.ready,null,{timeout:120000});
  await p.evaluate(()=>window.__SIGNATURE.referenceCamera([3.4,1.7,-3.8],[0,.6,0]));await p.waitForTimeout(1000);
  report.showrooms[visual]={inspection:await p.evaluate(()=>window.__SIGNATURE.inspect()),performance:await bench()};await p.screenshot({path:out+`/browser/${visual}-showroom.png`});await save();
 }
 for(const [name,pos,target]of [['left',[-3,1.1,0],[0,.55,0]],['right',[3,1.1,0],[0,.55,0]],['rear',[2.3,1.5,3],[0,.6,.2]],['cockpit',[.65,1.9,.8],[0,.9,-.12]],['wheel',[-1.5,.6,-1.6],[-.52,.28,-.85]]]){await p.evaluate(([pos,target])=>window.__SIGNATURE.referenceCamera(pos,target),[pos,target]);await p.screenshot({path:out+`/browser/ryker-${name}.png`})}
 report.motion=[];for(const [name,steer,spin]of [['forward',0,1],['reverse',0,-1],['left',.35,0],['right',-.35,0]]){report.motion.push({name,visual:await p.evaluate(([s,r])=>window.__SIGNATURE.poseVisual(s,0,r),[steer,spin])})}
 await p.locator('[data-action=build]').first().click();await p.waitForTimeout(500);console.log('buttons',await p.locator('button').allTextContents());
 const driver=p.locator('[data-action=driver]');if(await driver.count()){await driver.first().click();await p.evaluate(()=>window.__SIGNATURE.referenceCamera([2.5,1.5,2.5],[0,.75,0]));await p.screenshot({path:out+'/browser/ryker-rider.png'});report.rider=await p.evaluate(()=>window.__SIGNATURE.inspect().visual.driver)}
 await p.goto('http://127.0.0.1:5198/?scene=signature&visual=ryker&test=1&profile=1');await p.waitForFunction(()=>window.__SIGNATURE?.ready);
 await p.locator('[aria-label="Vehicle appearance"]').selectOption('2026');await p.waitForFunction(()=>window.__SIGNATURE?.inspect().vehicleContext.visual==='2026',null,{timeout:120000});report.switchedBack=true;
 await p.locator('[aria-label="Vehicle appearance"]').selectOption('ryker');await p.waitForFunction(()=>window.__SIGNATURE?.inspect().vehicleContext.visual==='ryker',null,{timeout:120000});report.switchedRyker=true;
 await save();
 await p.goto('http://127.0.0.1:5198/?scene=express&visual=ryker&route=harbor&mode=test&test=1&profile=1&look=day');await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:180000});
 report.drivingInitial=await p.evaluate(()=>window.__EXPRESS.inspect());await p.locator('#start-crew').click();await p.waitForFunction(()=>window.__EXPRESS.inspect().race.phase==='running');await p.keyboard.down('w');await p.waitForTimeout(3500);await p.keyboard.down('a');await p.waitForTimeout(500);await p.keyboard.up('a');await p.keyboard.up('w');report.drivingMoving=await p.evaluate(()=>window.__EXPRESS.inspect());assert.ok(report.drivingMoving.telemetry.speed>1,'Actual forward motion');
 const shot=await p.evaluate(()=>window.__EXPRESS.referenceCamera('player',[2.5,1.5,-3],[0,.65,0]));await writeFile(out+'/browser/ryker-driving.png',Buffer.from(shot.split(',')[1],'base64'));await save();
 await p.goto('http://127.0.0.1:5198/?scene=express&visual=ryker&route=harbor&mode=test&test=1&profile=1&look=night');await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:180000});report.night=await p.evaluate(()=>window.__EXPRESS.inspect());const night=await p.evaluate(()=>window.__EXPRESS.referenceCamera('player',[2.5,1.5,-3],[0,.65,0]));await writeFile(out+'/browser/ryker-night.png',Buffer.from(night.split(',')[1],'base64'));
 assert.deepEqual(errors,[]);report.pass=true;
}catch(e){report.failure=e.stack;throw e}finally{await save();await b.close()}
