"""Build the portable listening room from the mastered asset manifest."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'public/assets/audio/tour-audition';OUT.mkdir(parents=True,exist_ok=True)
rows=json.loads((ROOT/'assets/audio-redesign/mastering-report.json').read_text())
cards=[]
titles={'music-garage':'01 / Built for the journey','music-race':'02 / Find your line','music-ridge':'03 / Beyond the ridge'}
for r in rows:
    group='Score' if r['name'].startswith('music-') else 'Vehicles' if r['bank']=='tour-engine-v1' else 'Interface & workshop' if r['bank']=='tour-cues-v1' else 'World & contact'
    label=titles.get(r['name'],r['name'].replace('-',' ').replace('.',' / '))
    cards.append(f'<article data-group="{group}"><div><small>{group} · {r["duration"]:.1f}s'+(' · loop' if r['loop'] else '')+f'</small><h3>{html.escape(label)}</h3></div><audio controls preload="none" src="../{r["bank"]}/{r["file"]}"></audio></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Three-Wheel Tour / Sound room</title>
<style>*{box-sizing:border-box}body{margin:0;background:#111416;color:#f1f1ed;font:16px/1.5 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:48px 24px}header{max-width:760px;margin-bottom:36px}small{color:#adb6bb;font-size:12px;text-transform:uppercase;letter-spacing:.1em}h1{font-size:clamp(36px,6vw,68px);line-height:1.06;letter-spacing:-.04em;margin:16px 0}h2{margin:32px 0 12px}h3{font-size:17px;font-weight:550;margin:6px 0}p{color:#b8c0c4;max-width:680px}nav{display:flex;flex-wrap:wrap;gap:8px;margin:28px 0}button{color:#fff;background:#242b2f;border:1px solid #465056;border-radius:6px;padding:10px 16px;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#b91321;border-color:#ed4b58}button:focus-visible,a:focus-visible{outline:3px solid #ffc466;outline-offset:4px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}article{display:grid;gap:16px;background:#1b2125;border:1px solid #343d42;border-radius:10px;padding:20px}audio{width:100%;height:40px}a{color:#f2c17d}.note{border-left:3px solid #ca2533;padding-left:20px;margin:28px 0}footer{margin-top:40px;color:#9da8ad;font-size:13px}[hidden]{display:none!important}</style>
<main><header><small>SlingMods / Three-Wheel Tour / Audio candidate</small><h1>A world you can hear.</h1><p>Cinematic electronica, tangible workshop details, two distinct vehicles and room for the road. This listening room is independent of the game's other worktrees.</p></header>
<div class="note"><strong>Start with the full mix.</strong><p>The walkthrough below records the actual game audio service after its master limiter. It uses a scripted telemetry fixture to move from showroom to wet Harbor driving, then the Ryker and a result. It is an audio demonstration, not a completed race.</p><audio controls preload="none" src="runtime-audio-tour.mp3"></audio></div>
<p>Individual files below play at their authored asset level; the game balances them more quietly and dynamically. Only one preview plays at a time. In the game, <strong>Sound mix → Music off</strong> disables the score while retaining vehicle and world sound.</p>
<nav aria-label="Sound categories"><button aria-pressed="true" data-filter="Score">Score</button><button aria-pressed="false" data-filter="Vehicles">Vehicles</button><button aria-pressed="false" data-filter="World & contact">World & contact</button><button aria-pressed="false" data-filter="Interface & workshop">Interface & workshop</button><button id="stop">Stop playback</button></nav>
<section aria-label="Audio previews">'''+''.join(cards)+'''</section><footer>Original generated sound design and local editing, September 2026. Vehicle sounds are artistic approximations, not measured OEM or aftermarket exhaust recordings. Historical owner recordings remain separate and unchanged. No streaming service or API key is needed for playback.</footer></main>
<script>const players=[...document.querySelectorAll('audio')];for(const player of players){player.volume=.5;player.addEventListener('play',()=>players.forEach(p=>{if(p!==player)p.pause()}))}function filter(group){document.querySelectorAll('article').forEach(a=>a.hidden=a.dataset.group!==group);document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===group)))}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>filter(b.dataset.filter));document.querySelector('#stop').onclick=()=>players.forEach(p=>p.pause());filter('Score');</script></html>'''
(OUT/'index.html').write_text(page,encoding='utf-8')
from manifest import append_assets
append_assets(ROOT/'demo-assets.json',['assets/audio/tour-audition/index.html','assets/audio/tour-audition/runtime-audio-tour.mp3'])
print('Listening room:',OUT/'index.html')
