/** Explicit profile identity; an absent/unknown profile always means the real career. */
export type Profile = 'career'|'demo';
export const DEMO_NAMESPACE='slingmods-twt-demo-v1:';
export const DEMO_CAREER_KEY=DEMO_NAMESPACE+'career';
export const DEMO_SETTINGS_KEY=DEMO_NAMESPACE+'settings';
export function profileFrom(search:string):Profile{return new URLSearchParams(search).get('play')==='demo'?'demo':'career'}
export function activeProfile():Profile{return typeof location==='undefined'?'career':profileFrom(location.search)}
export function profileHref(url:string,profile:Profile=activeProfile(),base=location.href){const target=new URL(url,base);if(target.origin!==new URL(base).origin)return target.href;target.searchParams.set('play',profile);return target.pathname+target.search+target.hash}
export function sceneHref(scene:'bay'|'crew'|'harbor',extra='',profile:Profile=activeProfile()){return profileHref('?scene='+scene+extra,profile)}
/** Allowlisted visitors never select historical fixtures/assets in the staged demo. */
export function visitorSearch(search:string){const input=new URLSearchParams(search),out=new URLSearchParams();for(const [key,values]of Object.entries({visual:['josh','legacy','2026','ryker'],scene:['bay','crew','harbor','signature','express','career','ridge'],play:['demo','career','preview'],screen:['entry','build','events','shop'],route:['express','harbor','ridge'],lighting:['day','night'],mode:['test','race'],trial:['1'],series:['1'],attract:['1'],reel:['0','1','2','3','4','5'],preset:['day','night'],quality:['standard','low','medium','high','ultra'],look:['day','golden-hour','dusk','night','after-rain','dusk-rain','night-rain'],effects:['off','on'],contact:['off','on'],cinematic:['arrival','grid','victory'],forest:['off','on'],surfaces:['off','on'],shop:['build'],event:['duel'],from:['career','bay'],back:['garage']})){const value=input.get(key);if(value&&values.includes(value))out.set(key,value)}if(/^(harbor|express|ridge)-(brake|sprint|trap)$/.test(input.get('challenge')??''))out.set('challenge',input.get('challenge')!);if(['harbor','crew'].includes(input.get('scene')??'')&&/^[0-9a-f-]{36}$/i.test(input.get('entry')??''))out.set('entry',input.get('entry')!);if(['express','ridge'].includes(input.get('scene')??'')&&input.get('play')==='career'&&/^[0-9a-f-]{36}$/i.test(input.get('attempt')??''))out.set('attempt',input.get('attempt')!);if(input.get('test')==='1'&&input.get('profile')==='1'){out.set('test','1');out.set('profile','1');for(const key of ['clock','captureBuffer','seed','perf']){const value=input.get(key);if(value&&((key==='clock'&&value==='controlled')||(key==='captureBuffer'&&value==='1')||(key==='seed'&&/^\d{1,6}$/.test(value))||(key==='perf'&&/^legacy(-[a-z]+)?(,legacy-[a-z]+)*$/.test(value))))out.set(key,value)}}return out.toString()}
export function resetDemo(storage:Pick<Storage,'removeItem'>){storage.removeItem(DEMO_CAREER_KEY);storage.removeItem(DEMO_SETTINGS_KEY)}
/** Match the destination after the staged entry canonicalizes its allowed query. */
export function transferTarget(target:URL,visitor:boolean){if(!visitor)return target.pathname+target.search;const search=visitorSearch(target.search);return target.pathname+(search?'?'+search:'')}

export function evidenceEnabled(){if(import.meta.env.MODE!=='demo')return true;const query=new URLSearchParams(location.search);return query.get('test')==='1'&&query.get('profile')==='1'}
