import {retailFitment} from '../signature/fitment';
import type {CueId} from '../audio/interface';
import {SuspensionUI} from './suspension-ui';
import {sceneHref} from "../demo/profile";
import './build.css';import {PRODUCT,COLORS,defaultAppearance,type Appearance,type KitColor}from'./catalog';import{RAE,type CareerClient}from'./client';import{BuildMenuInput}from'./menu';import type{DeviceSample}from'../driving/input';
export interface BuildHooks {cue?(id:CueId,key?:string):void;suspension?(equipped:boolean):void;inspectHardware?(rear:boolean|null):void;open(value:boolean):void;previewNight(value:boolean):void;appearance(equipped:boolean,appearance:Appearance):void}
export class BuildUI {
 private suspensionUI:SuspensionUI;
 readonly root=document.createElement('section');readonly menu:BuildMenuInput;private opened=false;private preview=false;private compare=false;private pending=false;private night=false;private temporary=defaultAppearance();private unsubscribe:()=>void;private story=document.createElement('aside');private status='';
 constructor(private client:CareerClient,private hooks:BuildHooks){
  this.root.id='build-panel';this.root.hidden=true;this.root.setAttribute('aria-label','Build your Slingshot');
  this.root.innerHTML='<div class="build-heading"><span>SLINGMODS / YOUR BUILD</span><button id="close-build" aria-label="Close Build">Done</button></div><h2>Your Slingshot</h2><div class="wallet"><strong id="credit-balance">0</strong> <span>game credits</span></div><small id="career-storage"></small><article class="product-card"><span class="part-number">TRICLED · SM-133</span><h3>RGB Underglow</h3><p>Base Kit #1 · RF remote<br><span id="lighting-retail-fitment"></span></p><p class="cosmetic">Appearance only · driving stays stock</p><strong id="kit-state">Not owned</strong><div class="build-actions"><button id="preview-kit">Preview kit</button><button id="buy-kit" class="primary">Buy & install · 600 credits</button><button id="equip-kit" hidden>Unequip</button><button id="stock-compare" hidden>Compare stock</button></div><fieldset><legend>Solid color</legend><div id="kit-colors"></div></fieldset><div class="brightness"><button id="brightness-down" aria-label="Dim underglow">−</button><span id="brightness-value">60%</span><button id="brightness-up" aria-label="Brighten underglow">+</button><button id="kit-power">Lights on</button></div><button id="bay-night" aria-pressed="false">Night preview</button><p id="build-feedback" role="status" aria-live="polite"></p></article><a id="drive-kit-night" class="primary" href="?scene=harbor&preset=night">Drive at night →</a><a id="real-product" target="_blank" rel="noopener noreferrer">View on SlingMods ↗</a><details><summary>About this visualization</summary><p id="product-exclusions"></p><p>Game credits are virtual. Real products are purchased separately on SlingMods. Check the live page for options and fitment.</p><p id="product-limits"></p></details><small>Tab / arrows / D-pad navigate · Enter / bottom face confirm · Esc / right face back</small>';
  this.root.querySelector('h2')!.textContent='Shop This Build';
  const official=document.createElement('p');official.className='product-official-title';official.textContent=PRODUCT.officialTitle;this.root.querySelector('.product-card h3')!.after(official);
  this.root.querySelector('#lighting-retail-fitment')!.textContent=retailFitment(PRODUCT.part).label;
  const fitment=document.createElement('p');fitment.textContent=retailFitment(PRODUCT.part).condition;this.root.querySelector('details')!.append(fitment);
  this.root.querySelector<HTMLAnchorElement>('#drive-kit-night')!.href=sceneHref('harbor','&preset=night');
  this.root.querySelector<HTMLAnchorElement>('#real-product')!.href=PRODUCT.url;this.text('#product-exclusions',PRODUCT.exclusions);this.text('#product-limits',PRODUCT.limitation);
  for(const [name,color]of Object.entries(COLORS)){const b=document.createElement('button');b.dataset.color=name;b.title=name;b.setAttribute('aria-label',name+' underglow');b.style.setProperty('--swatch',color);b.onclick=()=>this.color(name as KitColor);this.root.querySelector('#kit-colors')!.append(b)}
  document.querySelector('#app')!.append(this.root);this.story.id='rae-card';this.story.hidden=true;this.story.setAttribute('aria-live','polite');document.querySelector('#app')!.append(this.story);
  this.menu=new BuildMenuInput(this.root,()=>this.back());
  this.button('#close-build',()=>this.close());this.button('#preview-kit',()=>{this.preview=!this.preview;this.compare=false;this.temporary=defaultAppearance();this.status='';this.update();if(this.preview)this.hooks.cue?.('part.lights.attach')});
  this.button('#buy-kit',()=>{void this.mutate({type:'purchase',id:crypto.randomUUID(),productId:PRODUCT.id,vehicleId:PRODUCT.vehicleId})});
  this.button('#equip-kit',()=>{void this.mutate({type:'equip',equipped:!this.client.state.equipped})});
  this.button('#stock-compare',()=>{this.compare=!this.compare;this.update()});
  this.button('#kit-power',()=>this.appearance({enabled:!this.activeAppearance().enabled}));
  this.button('#brightness-down',()=>this.appearance({brightness:Math.max(.15,this.activeAppearance().brightness-.1)}));this.button('#brightness-up',()=>this.appearance({brightness:Math.min(.85,this.activeAppearance().brightness+.1)}));
  this.button('#bay-night',()=>{this.night=!this.night;this.hooks.previewNight(this.night);this.update()});
  this.root.addEventListener('click',e=>{if(this.pending||this.client.stale){e.preventDefault();e.stopImmediatePropagation()}},true);this.root.querySelector('#drive-kit-night')!.addEventListener('click',e=>{if(this.pending||this.client.stale)e.preventDefault();else this.close()});
  this.root.addEventListener('keydown',e=>{if(e.code==='Escape'||e.code==='Backspace'){e.preventDefault();e.stopPropagation();this.back()}else if(e.target instanceof HTMLInputElement)return;else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();this.menu.move(['ArrowUp','ArrowLeft'].includes(e.code)?-1:1)}});
  this.suspensionUI=new SuspensionUI(client,this.root,hooks.suspension??(()=>{}),hooks.inspectHardware??(()=>{}),value=>{this.pending=value;this.update()},hooks.cue);
  this.unsubscribe=client.subscribe(()=>this.update());this.update();void client.execute({type:'entry'}).then(r=>{if(r.story&&r.story!=='entry')this.showStory(r.story)}).catch(()=>{});
 }
 private text(selector:string,value:string){this.root.querySelector(selector)!.textContent=value}
 private button(selector:string,fn:()=>void){this.root.querySelector(selector)!.addEventListener('click',()=>{if(!this.pending&&!this.client.stale)fn()})}
 private activeAppearance(){return this.preview?this.temporary:this.client.state.appearance}
 private color(color:KitColor){this.appearance({color})}
 private appearance(patch:Partial<Appearance>){if(this.pending||this.client.stale)return;if(this.preview){const before=JSON.stringify(this.temporary);Object.assign(this.temporary,patch);this.update();if(before!==JSON.stringify(this.temporary))this.hooks.cue?.('ui.detent')}else if(this.client.state.owned)void this.mutate({type:'appearance',patch})}
 private async mutate(command:Parameters<CareerClient['execute']>[0]){if(this.pending||this.client.stale)return;this.pending=true;this.status='Saving…';this.update();try{const r=await this.client.execute(command);if(r.changed){const cue:CueId=command.type==='purchase'||command.type==='equip'&&command.equipped?'part.lights.attach':command.type==='equip'?'part.remove':'ui.detent';this.hooks.cue?.(cue,`legacy:${r.state.revision}`)}this.preview=false;this.compare=false;this.status=r.changed?'Build saved'+(this.client.durable?'':' for this session'):'Already owned — no charge';if(r.story)this.showStory(r.story)}catch(e){this.status=(e as Error).message+' · No transaction committed.'}finally{this.pending=false;this.update()}}
 private showStory(key:keyof typeof RAE){this.story.replaceChildren();const name=document.createElement('strong'),p=document.createElement('p'),button=document.createElement('button');name.textContent='RAE / WORKSHOP';p.textContent=RAE[key];button.textContent='Got it';button.onclick=()=>this.story.hidden=true;this.story.append(name,p,button);this.story.hidden=false}
 open(){this.opened=true;this.root.hidden=false;document.body.classList.add('build-open');this.hooks.open(true);this.menu.reset();this.update();this.root.querySelector<HTMLButtonElement>('#close-build')!.focus()}
 close(){if(this.pending||this.client.stale)return;this.hooks.inspectHardware?.(null);this.suspensionUI.close();this.opened=false;this.preview=false;this.compare=false;this.night=false;this.hooks.previewNight(false);this.hooks.open(false);this.root.hidden=true;document.body.classList.remove('build-open');this.update();[...document.querySelectorAll<HTMLButtonElement>('#chapter-build,#open-build')].find(button=>!!button.getClientRects().length&&getComputedStyle(button).visibility!=='hidden')?.focus()}
 back(){if(this.pending||this.client.stale)return;if(this.preview||this.compare){this.preview=false;this.compare=false;this.status='Preview cancelled — saved build unchanged';this.update()}else this.close()}
 frame(sample:DeviceSample){if(this.opened)this.menu.frame(sample)}
 update(){const s=this.client.state;this.text('#credit-balance',String(s.credits));this.text('#career-storage',this.client.stale?'Refreshing shared career…':this.client.profile==='demo'?'Demo build · separate from your career':this.client.durable?'Saved on this browser':'Session only — progress cannot be saved');this.text('#kit-state',this.preview?'PREVIEW · not owned':this.compare?'STOCK COMPARISON · saved build unchanged':s.owned?s.equipped?(this.client.profile==='demo'?'Demo kit · installed':'Owned · installed'):(this.client.profile==='demo'?'Demo kit · not installed':'Owned · unequipped'):'Not owned');this.text('#build-feedback',this.status||(!s.owned&&s.credits<600?'One clean Harbor lap earns your first 800 credits.':''));
  this.root.setAttribute('aria-busy',String(this.pending));for(const button of this.root.querySelectorAll<HTMLButtonElement>('button'))button.disabled=this.pending||this.client.stale;for(const link of this.root.querySelectorAll<HTMLAnchorElement>('a')){link.setAttribute('aria-disabled',String(this.pending||this.client.stale));link.tabIndex=this.pending||this.client.stale?-1:0}
  const buy=this.root.querySelector<HTMLButtonElement>('#buy-kit')!,equip=this.root.querySelector<HTMLButtonElement>('#equip-kit')!,preview=this.root.querySelector<HTMLButtonElement>('#preview-kit')!,compare=this.root.querySelector<HTMLButtonElement>('#stock-compare')!;buy.hidden=s.owned;buy.disabled=this.pending||this.client.stale;equip.hidden=!s.owned;equip.disabled=this.pending||this.client.stale;equip.textContent=s.equipped?'Unequip':'Equip';preview.hidden=s.owned;preview.textContent=this.preview?'Cancel preview':'Preview kit';compare.hidden=!s.owned;compare.textContent=this.compare?'Show installed':'Compare stock';compare.disabled=this.pending||this.client.stale||!s.equipped;
  for(const id of ['#brightness-down','#brightness-up','#kit-power'])(this.root.querySelector(id)as HTMLButtonElement).disabled=this.pending||this.client.stale||(!this.preview&&!s.owned);
  const a=this.activeAppearance();for(const b of this.root.querySelectorAll<HTMLButtonElement>('[data-color]')){b.setAttribute('aria-pressed',String(b.dataset.color===a.color));b.disabled=this.pending||this.client.stale||(!this.preview&&!s.owned)}this.text('#brightness-value',Math.round(a.brightness*100)+'%');this.text('#kit-power',a.enabled?'Lights on':'Lights off');this.root.querySelector('#kit-power')!.setAttribute('aria-pressed',String(a.enabled));this.root.querySelector('#bay-night')!.setAttribute('aria-pressed',String(this.night));this.text('#bay-night',this.night?'Exit night preview':'Night preview');
  this.suspensionUI?.update();
  this.hooks.appearance(this.opened&&this.compare?false:this.opened&&this.preview?true:s.equipped,a);
 }
 inspect(){return {open:this.opened,preview:this.preview,compare:this.compare,night:this.night,pending:this.pending,career:this.client.state,durable:this.client.durable}}
 dispose(){this.unsubscribe();this.root.remove();this.story.remove()}
}
