import {retailFitment} from '../signature/fitment';
import type {CueId} from '../audio/interface';
import {SUSPENSION,streetSetup,suspensionParameters,type SuspensionSetup} from './suspension';
import type {CareerClient} from './client';
export class SuspensionUI {
 readonly root=document.createElement('article');private pending=false;private compare=false;private status='';
 constructor(private client:CareerClient,parent:HTMLElement,private present:(equipped:boolean)=>void,private inspectHardware:(rear:boolean|null)=>void,private busy:(value:boolean)=>void,private cue?:(id:CueId,key?:string)=>void){
  this.root.id='suspension-card';this.root.className='product-card';
  this.root.innerHTML=`<span class="part-number">DDMWORKS · SM-3223 / DDM-18-2</span><h3>Adjustable Sport Shocks</h3><p>Set of 3 · Silver (Standard)<br>${retailFitment(SUSPENSION.part).label} · 1000 game credits</p><strong id="suspension-state"></strong><div class="build-actions"><button id="buy-suspension" class="primary">Buy & install · 1000</button><button id="equip-suspension">Remove suspension</button><button id="compare-suspension">Compare stock hardware</button></div><div class="build-actions"><button id="inspect-front-shock">Inspect front</button><button id="inspect-rear-shock">Inspect rear</button><button id="inspect-full-vehicle">Full vehicle</button></div><p id="hardware-inspection-status"></p><fieldset id="suspension-controls"><legend>Setup · saved for your next drive</legend></fieldset><button id="street-suspension">Manufacturer street starting clicks</button><p>Full soft = 0. Independent compression and rebound, front pair / rear. Higher damping resists suspension motion more; it can also make the ride harsher.</p><table id="suspension-comparison"><caption>Stock → saved setup · simulation estimates</caption><thead><tr><th scope="col">Parameter</th><th scope="col">Stock</th><th scope="col">Setup</th></tr></thead><tbody></tbody></table><p id="suspension-feedback" role="status"></p><details><summary>Product facts & simulation limits</summary><p>${retailFitment(SUSPENSION.part).condition}</p><p>Separate compression / rebound: 19 clicks from full soft, modeled as 0–19. Street starts front C2/R6, rear C1/R3. Ride-height offset is bounded to ±20 mm in this game.</p><p>${SUSPENSION.limitation} Spring rates remain stock estimates: front 28,000 / rear 48,000 N/m. Tire friction, power, mass and anti-roll remain unchanged.</p><a href="${SUSPENSION.url}" target="_blank" rel="noopener noreferrer">View SM-3223 on SlingMods ↗</a><a href="${SUSPENSION.instructions}" target="_blank" rel="noopener noreferrer">Manufacturer instructions ↗</a></details>`;
  const fields:[keyof SuspensionSetup,string,number,number][]=[['frontCompression','Front compression',0,19],['frontRebound','Front rebound',0,19],['rearCompression','Rear compression',0,19],['rearRebound','Rear rebound',0,19],['rideHeightMm','Ride height offset (mm)',-20,20]];
  for(const [key,label,min,max]of fields){const row=document.createElement('label');row.className='setup-row';row.innerHTML=`<span>${label}</span><input id="setup-${key}" type="number" min="${min}" max="${max}" step="1" aria-label="${label}">`;const input=row.querySelector('input')!;input.addEventListener('change',()=>void this.mutate({type:'suspension-setup',setup:{...client.state.suspension.setup,[key]:input.valueAsNumber}}));for(const direction of [-1,1]){const button=document.createElement('button');button.type='button';button.textContent=direction<0?'−':'+';button.setAttribute('aria-label',(direction<0?'Decrease ':'Increase ')+label);button.dataset.setup=key;button.onclick=()=>{if(!this.pending&&!client.stale&&client.state.suspension.owned)void this.mutate({type:'suspension-setup',setup:{...client.state.suspension.setup,[key]:Math.max(min,Math.min(max,client.state.suspension.setup[key]+direction))}})};row.append(button)}this.root.querySelector('#suspension-controls')!.append(row)}
  const button=(id:string,fn:()=>void)=>this.root.querySelector(id)!.addEventListener('click',()=>{if(!this.pending&&!client.stale)fn()});
  button('#buy-suspension',()=>void this.mutate({type:'suspension-purchase',id:crypto.randomUUID(),productId:SUSPENSION.id,vehicleId:SUSPENSION.vehicleId}));
  button('#equip-suspension',()=>void this.mutate({type:'suspension-equip',equipped:!client.state.suspension.equipped}));
  button('#compare-suspension',()=>{this.compare=!this.compare;this.update()});
  button('#street-suspension',()=>void this.mutate({type:'suspension-setup',setup:streetSetup()}));
  button('#inspect-front-shock',()=>{inspectHardware(false);this.root.querySelector('#hardware-inspection-status')!.textContent='Front hardware inspection · body hidden temporarily'});button('#inspect-rear-shock',()=>{inspectHardware(true);this.root.querySelector('#hardware-inspection-status')!.textContent='Rear hardware inspection · body hidden temporarily'});button('#inspect-full-vehicle',()=>{inspectHardware(null);this.root.querySelector('#hardware-inspection-status')!.textContent='Full vehicle · body restored'});
  parent.querySelector('.product-card')!.before(this.root);this.update();
 }
 private async mutate(command:Parameters<CareerClient['execute']>[0]){if(this.pending||this.client.stale)return;this.pending=true;this.busy(true);this.status='Saving…';this.update();try{const r=await this.client.execute(command);if(r.changed)this.cue?.(command.type==='suspension-setup'?'ui.detent':command.type==='suspension-equip'&&!command.equipped?'part.remove':'part.shocks.attach',`legacy:${r.state.revision}`);this.compare=false;this.status=r.changed?'Build saved. Setup applies on next drive.':'Already owned — no charge.'}catch(e){this.status=(e as Error).message}finally{this.pending=false;this.busy(false);this.update()}}
 update(){const s=this.client.state.suspension,p=suspensionParameters(s.setup);this.root.querySelector('#suspension-state')!.textContent=this.compare?'Stock comparison · saved setup retained':s.owned?s.equipped?'Owned · installed':'Owned · stored in workshop':'Not owned';
  for(const el of this.root.querySelectorAll<HTMLInputElement|HTMLButtonElement>('button,input'))el.disabled=this.pending||this.client.stale;
  this.root.querySelector<HTMLButtonElement>('#buy-suspension')!.hidden=s.owned;const equip=this.root.querySelector<HTMLButtonElement>('#equip-suspension')!;equip.hidden=!s.owned;equip.textContent=s.equipped?'Remove · keep ownership':'Install owned suspension';
  const compare=this.root.querySelector<HTMLButtonElement>('#compare-suspension')!;compare.disabled ||=!s.equipped;compare.textContent=this.compare?'Show installed hardware':'Compare stock hardware';compare.setAttribute('aria-pressed',String(this.compare));
  for(const [key,value]of Object.entries(s.setup)){const input=this.root.querySelector<HTMLInputElement>('#setup-'+key)!;input.value=String(value);input.disabled ||=!s.owned}
  for(const button of this.root.querySelectorAll<HTMLButtonElement>('[data-setup]'))button.disabled ||=!s.owned;
  this.root.querySelector<HTMLButtonElement>('#street-suspension')!.disabled ||=!s.owned;
  this.root.querySelector('tbody')!.innerHTML=[['Front C / R','3800 / 3800',`${Math.round(p.frontCompression)} / ${Math.round(p.frontRebound)}`],['Rear C / R','6500 / 6500',`${Math.round(p.rearCompression)} / ${Math.round(p.rearRebound)}`],['Height offset','0 mm',`${s.setup.rideHeightMm} mm`]].map(([name,stock,setup])=>`<tr><th scope="row">${name}</th><td>${stock}</td><td>${setup}</td></tr>`).join('');
  this.root.querySelector('#suspension-feedback')!.textContent=this.status||'Damping values in N·s/m. Street baseline matches stock coefficients; tune to change the response.';
  this.present(s.equipped&&!this.compare);
 }
 close(){this.compare=false;this.update()}
}
