import {OpponentAudio} from './opponents';
import {LiveGameCapture} from './evidence';
import type{VehicleTelemetry}from'../simulation';import{loadSave,writeSave,browserStorage}from'../save';import{mapAudio,ShiftEvents,type AudioLife}from'./mapper';import{createAudioGraph,loadAudioBank}from'./graph';
export type AudioTimelineFrame={time:number;telemetry:VehicleTelemetry;life:AudioLife};
export class GameAudio {
 private mix:GainNode|undefined;private capture:LiveGameCapture|undefined;
 private opponents:OpponentAudio|undefined;private bank:Awaited<ReturnType<typeof loadAudioBank>>|undefined;
 private context:AudioContext|undefined;private graph:ReturnType<typeof createAudioGraph>|undefined;private shifts=new ShiftEvents();private last:VehicleTelemetry|undefined;private paused=false;private cockpit=false;private enabled=false;private failure='';private loading=false;private disposed=false;
 readonly settings=loadSave(browserStorage()).settings;readonly ui=document.createElement('div');private enable=document.createElement('button');private mute=document.createElement('button');private volume=document.createElement('input');
 constructor(parent:Element){this.ui.id='game-audio';this.enable.id='enable-sound';this.enable.textContent='Enable sound';this.mute.id='mute-sound';this.mute.textContent=this.settings.mute?'Unmute':'Mute';this.volume.type='range';this.volume.min='0';this.volume.max='1';this.volume.step='.05';this.volume.value=String(this.settings.volume);this.volume.setAttribute('aria-label','Game volume');this.ui.append(this.enable,this.mute,this.volume);parent.append(this.ui);this.enable.onclick=()=>void this.unlock();this.mute.onclick=()=>{this.settings.mute=!this.settings.mute;this.persist();this.refresh()};this.volume.oninput=()=>{this.settings.volume=Number(this.volume.value);this.persist();this.refresh()}}
 private persist(){const save=loadSave(browserStorage());save.settings.mute=this.settings.mute;save.settings.volume=this.settings.volume;writeSave(browserStorage(),save)}
 private stateChanged(){if(this.disposed)return;this.enabled=this.context?.state==='running'&&!!this.graph;this.enable.hidden=this.enabled;this.enable.textContent=this.failure||'Enable sound';this.refresh()}
 async unlock(){if(this.loading||this.disposed)return;this.loading=true;try{if(!this.context||this.context.state==='closed'){this.capture?.abort();this.capture=undefined;this.opponents?.dispose();this.opponents=undefined;this.graph?.dispose();this.mix?.disconnect();this.graph=undefined;this.context=new AudioContext();this.context.onstatechange=()=>this.stateChanged()}await this.context.resume();if(this.disposed)return;if(!this.graph){const bank=await loadAudioBank(this.context);if(this.disposed||this.context.state==='closed')return;this.mix=this.context.createGain();this.mix.gain.value=1;this.mix.connect(this.context.destination);this.graph=createAudioGraph(this.context,bank,this.mix);this.bank=bank}this.failure='';this.stateChanged()}catch{if(!this.disposed){this.failure='Sound unavailable — retry';this.enabled=false;this.enable.hidden=false;this.enable.textContent=this.failure}}finally{this.loading=false}}
 async suspendContext(){await this.context?.suspend()}

 updateOpponents(player:VehicleTelemetry,peers:Record<string,VehicleTelemetry>){if(!this.opponents&&this.context&&this.bank)this.opponents=new OpponentAudio(this.context,this.bank,this.mix);this.opponents?.update(player,peers,this.life())}
 startEvidenceCapture(){if(this.capture)throw Error('Evidence recording already active');if(!this.context||!this.mix||!this.enabled)throw Error('Activate game sound first');this.capture=new LiveGameCapture(this.context,this.mix);return{sampleRate:this.context.sampleRate}}
 evidenceMarker(id:string){if(!this.capture)throw Error('No evidence recording');return this.capture.marker(id)}
 async stopEvidenceCapture(){if(!this.capture)throw Error('No evidence recording');const active=this.capture;this.capture=undefined;return active.stop()}
 lifecycle(paused:boolean){this.paused=paused;this.opponents?.silence();this.refresh()}
 private refresh(){this.mute.textContent=this.settings.mute?'Unmute':'Mute';if(this.last)this.graph?.apply(mapAudio(this.last,this.life()),false)}
 life(reset=false):AudioLife{return{enabled:this.enabled,paused:this.paused,mute:this.settings.mute,volume:this.settings.volume,cockpit:this.cockpit,reset}}
 update(t:VehicleTelemetry,paused:boolean,cockpit:boolean,reset=false){this.last=t;this.paused=paused;this.cockpit=cockpit;const life=this.life(reset),parameters=mapAudio(t,life),shift=this.shifts.update(t,reset);this.graph?.apply(parameters,shift);return{life,parameters,shift}}
 inspect(){return{enabled:this.enabled,loading:this.loading,failure:this.failure,life:this.life(),opponents:this.opponents?.inspect(),graph:this.graph?.inspect()}}
 dispose(){this.disposed=true;this.capture?.abort();this.opponents?.dispose();this.graph?.dispose();this.mix?.disconnect();void this.context?.close();this.ui.remove()}
}
export async function renderOfflineGameAudio(timeline:AudioTimelineFrame[],duration:number){const ctx=new OfflineAudioContext(2,Math.round(duration*48000),48000),bank=await loadAudioBank(ctx),graph=createAudioGraph(ctx,bank),events=new ShiftEvents();for(const f of timeline)graph.apply(mapAudio(f.telemetry,f.life),events.update(f.telemetry,!!f.life.reset),f.time);const rendered=await ctx.startRendering();const pcm=new ArrayBuffer(44+rendered.length*4),v=new DataView(pcm);const text=(offset:number,s:string)=>[...s].forEach((x,i)=>v.setUint8(offset+i,x.charCodeAt(0)));text(0,'RIFF');v.setUint32(4,pcm.byteLength-8,true);text(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,48000,true);v.setUint32(28,192000,true);v.setUint16(32,4,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,rendered.length*4,true);let peak=0,nonfinite=0,clipped=0;for(let i=0;i<rendered.length;i++)for(let ch=0;ch<2;ch++){const x=rendered.getChannelData(ch)[i];if(!Number.isFinite(x))nonfinite++;peak=Math.max(peak,Math.abs(x));if(Math.abs(x)>=1)clipped++;v.setInt16(44+(i*2+ch)*2,Math.round(Math.max(-1,Math.min(1,x))*32767),true)}let binary='';const bytes=new Uint8Array(pcm);for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return{wavBase64:btoa(binary),samplePeak:peak,nonfinite,clipped,duration,method:'OfflineAudioContext using identical runtime graph factory, source buffers, mapper and full logical timeline; not live hardware capture'}}
