import type{AudioParameters}from'./mapper';
export type AudioBank=Record<string,AudioBuffer>;
export async function loadAudioBank(ctx:BaseAudioContext):Promise<AudioBank>{const response=await fetch('/assets/audio/p03b2/provenance.json');if(!response.ok)throw new Error('Audio bank unavailable');const manifest=await response.json();return Object.fromEntries(await Promise.all(manifest.files.map(async(f:{name:string;file:string})=>{const r=await fetch('/assets/audio/p03b2/'+f.file);if(!r.ok)throw new Error('Audio sample unavailable');return[f.name,await ctx.decodeAudioData(await r.arrayBuffer())]})))}
/** One factory for realtime and OfflineAudioContext. Persistent loops; bounded one-shot ownership. */
export function createAudioGraph(ctx:BaseAudioContext,bank:AudioBank,output:AudioNode=ctx.destination){
 const master=ctx.createGain(),filter=ctx.createBiquadFilter(),analyser=ctx.createAnalyser();master.gain.value=0;filter.type='lowpass';filter.frequency.value=6500;filter.Q.value=.5;filter.connect(master);master.connect(analyser);analyser.connect(output);analyser.fftSize=512;
 const loops=Object.entries(bank).filter(([name])=>name!=='shift').map(([name,buffer])=>{const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;source.loopStart=0;source.loopEnd=buffer.duration;gain.gain.value=0;source.connect(gain);gain.connect(filter);source.start(0);return{name,source,gain}});let shot:AudioBufferSourceNode|undefined;let disposed=false,shiftCount=0,last:AudioParameters|undefined;
 const ramp=(p:AudioParam,value:number,time:number)=>{p.setTargetAtTime(value,time,.025)};
 return{master,analyser,loops,apply(p:AudioParameters,shift=false,time=ctx.currentTime){if(disposed)return;last=p;if(p.reset&&shot){shot.stop(time);shot=undefined}for(const layer of p.layers){const loop=loops.find(x=>x.name===layer.name)!;ramp(loop.gain.gain,layer.gain,time);ramp(loop.source.playbackRate,layer.rate,time)}ramp(filter.frequency,p.cutoff,time);ramp(master.gain,p.master,time);
 if(shift&&!p.reset&&p.master>0){if(shot)shot.stop(time);const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=bank.shift;gain.gain.setValueAtTime(p.shiftGain,time);source.connect(gain);gain.connect(filter);source.start(time);source.onended=()=>{source.disconnect();gain.disconnect();if(shot===source)shot=undefined};shot=source;shiftCount++}},
 inspect(){const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);return{contextState:ctx.state,contextTime:ctx.currentTime,persistentLoops:loops.length,shiftCount,masterTarget:last?.master??0,rms:Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length),parameters:last}},
 dispose(){if(disposed)return;disposed=true;for(const l of loops){l.source.stop();l.source.disconnect();l.gain.disconnect()}shot?.stop();filter.disconnect();master.disconnect();analyser.disconnect()}}
}
