import type{AudioParameters}from'./mapper';
export type AudioBank=Record<string,AudioBuffer>;
const bankCache=new Map<string,Promise<AudioBank>>();
/** AudioBuffers can be shared by contexts; promises dedupe concurrent scene preparation. */
export function loadAudioBank(ctx:BaseAudioContext,version='p09b'):Promise<AudioBank>{const old=bankCache.get(version);if(old)return old;const pending=(async()=>{const root='/assets/audio/'+version+'/';const response=await fetch(root+'provenance.json');if(!response.ok)throw new Error('Audio bank unavailable');const manifest=await response.json();return Object.fromEntries(await Promise.all(manifest.files.map(async(f:{name:string;file:string})=>{const r=await fetch(root+f.file);if(!r.ok)throw new Error('Audio sample unavailable');return[f.name,await ctx.decodeAudioData(await r.arrayBuffer())]})))} )();bankCache.set(version,pending);pending.catch(()=>bankCache.delete(version));return pending}
/** One factory for realtime and OfflineAudioContext. Persistent loops; bounded one-shot ownership. */
export function createAudioGraph(ctx:BaseAudioContext,bank:AudioBank,output:AudioNode=ctx.destination){
 const master=ctx.createGain(),filter=ctx.createBiquadFilter(),analyser=ctx.createAnalyser();master.gain.value=0;filter.type='lowpass';filter.frequency.value=6500;filter.Q.value=.5;filter.connect(master);master.connect(analyser);analyser.connect(output);analyser.fftSize=512;
 const loops=Object.entries(bank).filter(([name])=>name!=='shift').map(([name,buffer])=>{const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;source.loopStart=0;source.loopEnd=buffer.duration;gain.gain.value=0;source.connect(gain);gain.connect(filter);source.start(0);return{name,source,gain}});let shot:AudioBufferSourceNode|undefined;let disposed=false,shiftCount=0,last:AudioParameters|undefined;
 // Original three-cylinder game synthesis: 3 firing events per two crank revolutions.
 const rykerOsc=ctx.createOscillator(),rykerGain=ctx.createGain();const real=new Float32Array(25),imag=new Float32Array(25);for(let i=1;i<25;i++)imag[i]=Math.pow(.72,i)/i;rykerOsc.setPeriodicWave(ctx.createPeriodicWave(real,imag));rykerGain.gain.value=0;rykerOsc.connect(rykerGain);rykerGain.connect(filter);rykerOsc.start();
 const ramp=(p:AudioParam,value:number,time:number)=>{p.setTargetAtTime(value,time,.025)};
 let sportTreatment=false;
 return{master,analyser,loops,setTreatment(value:boolean){sportTreatment=value},apply(p:AudioParameters,shift=false,time=ctx.currentTime){if(disposed)return;last=p;ramp(rykerOsc.frequency,Math.max(25,p.rpm/40),time);ramp(rykerGain.gain,p.powertrain==='cvt'?(.14+.27*p.load):0,time);if(p.reset&&shot){shot.stop(time);shot=undefined}for(const layer of p.layers){const loop=loops.find(x=>x.name===layer.name);if(!loop)continue;ramp(loop.gain.gain,layer.gain*(p.powertrain==='cvt'&&layer.name.startsWith('engine-')?0:1)*(sportTreatment&&/load|exhaust/i.test(layer.name)?1.08:1),time);ramp(loop.source.playbackRate,layer.rate,time)}const texture=loops.find(x=>x.name==='thermal-mid');if(texture){const blend=Math.max(0,1-Math.abs(p.rpm-3400)/600);ramp(texture.gain.gain,sportTreatment?blend*(.04+.12*p.load):0,time);ramp(texture.source.playbackRate,Math.max(.85,Math.min(1.18,p.rpm/3400)),time)}ramp(filter.frequency,p.cutoff*(sportTreatment?.9:1),time);ramp(master.gain,p.master,time);
 if(shift&&!p.reset&&p.master>0){if(shot)shot.stop(time);const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=bank.shift;gain.gain.setValueAtTime(p.shiftGain,time);source.connect(gain);gain.connect(filter);source.start(time);source.onended=()=>{source.disconnect();gain.disconnect();if(shot===source)shot=undefined};shot=source;shiftCount++}},
 inspect(){const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);return{engine:last?.powertrain==='cvt'?'three-cylinder procedural game sound':'authored engine beds',contextState:ctx.state,contextTime:ctx.currentTime,persistentLoops:loops.length,shiftCount,masterTarget:last?.master??0,rms:Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length),parameters:last}},
 dispose(){if(disposed)return;disposed=true;rykerOsc.stop();rykerOsc.disconnect();rykerGain.disconnect();for(const l of loops){l.source.stop();l.source.disconnect();l.gain.disconnect()}shot?.stop();filter.disconnect();master.disconnect();analyser.disconnect()}}
}
