import type {CourseRoute} from '../course/environment';
import type {VehicleTelemetry} from '../simulation';
/** The map is derived from the same route polyline as the race. No illustrative route. */
export class RouteAid {
 private marker:SVGCircleElement|null=null;private svg:SVGSVGElement|null=null;private peers=new Map<string,SVGCircleElement>();private minX=0;private minZ=0;private scale=1;private offsetX=0;private offsetY=0;private last=-1;
 constructor(root:HTMLElement,route?:CourseRoute){if(!route)return;const xs=route.centerline.map(p=>p[0]),zs=route.centerline.map(p=>p[1]);this.minX=Math.min(...xs);this.minZ=Math.min(...zs);const w=Math.max(...xs)-this.minX,h=Math.max(...zs)-this.minZ;this.scale=Math.min(162/Math.max(1,w),162/Math.max(1,h));this.offsetX=(220-w*this.scale)/2;this.offsetY=(220-h*this.scale)/2;const points=route.centerline.map(p=>this.project(p[0],p[1]));const aid=document.createElement('aside');aid.className='race-route-aid';aid.setAttribute('aria-label',route.name+' route map');aid.innerHTML=`<svg viewBox="0 0 220 220" aria-hidden="true"><circle class="map-boundary" cx="110" cy="110" r="106"/><path d="${points.map((p,i)=>(i?'L':'M')+p.map(v=>v.toFixed(1)).join(',')).join(' ')}Z"/><circle class="map-player" r="5"/></svg><span>${route.name}</span>`;root.append(aid);this.svg=aid.querySelector('svg');this.marker=aid.querySelector('.map-player')}
 updatePeers(field:Record<string,VehicleTelemetry>){if(!this.svg)return;for(const[id,t]of Object.entries(field)){if(id==='player')continue;let node=this.peers.get(id);if(!node){node=document.createElementNS('http://www.w3.org/2000/svg','circle');node.setAttribute('r','3.4');node.classList.add('map-peer','crew-'+id);this.svg.insertBefore(node,this.marker);this.peers.set(id,node)}const [x,y]=this.project(t.position.x,t.position.z);node.setAttribute('cx',String(x));node.setAttribute('cy',String(y))}}
 private marks?:SVGGElement;
 /** Collectible markers (SlingMods Points): small dots drawn under the cars; pass [] to clear. */
 setMarks(points:readonly {x:number;z:number;value:number}[]){if(!this.svg)return;if(!this.marks){this.marks=document.createElementNS('http://www.w3.org/2000/svg','g');this.marks.classList.add('map-marks');this.svg.insertBefore(this.marks,this.marker)}this.marks.innerHTML=points.map(p=>{const [x,y]=this.project(p.x,p.z);return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${p.value>=50?2.4:1.6}" class="map-token v${p.value}"/>`}).join('')}
 private project(x:number,z:number){return [(x-this.minX)*this.scale+this.offsetX,(z-this.minZ)*this.scale+this.offsetY]}
 update(t:VehicleTelemetry){if(!this.marker||!t.position||t.time>=this.last&&t.time-this.last<.1)return;this.last=t.time;const [x,y]=this.project(t.position.x,t.position.z);this.marker.setAttribute('cx',String(x));this.marker.setAttribute('cy',String(y))}
}
