/** Separate preview equipment; never aliases Slingshot retail IDs or career purchases. */
export type RykerPart='underglow'|'shocks'|'exhaust'|'body';
export type RykerBuild=Partial<Record<RykerPart,boolean>>;
export const RYKER_PRODUCTS=[
 {id:'underglow',category:'Lighting',brand:'TricLED',name:'RYKER CHASER LIGHTS',option:'Kit #1 · headlamps, grille & A-arms',sku:'SM-7227',url:'https://www.slingmods.com/canam-ryker-chaser-led-underglow-lighting-kit-1',fit:'Listing: 2019–2026 Ryker, Rally and Sport.',description:'Ryker-specific smoked LED strips. Preview uses a steady RGB color; remote chaser sequences and optional kits #2/#3 are not included.',view:'ryker-underglow'},
 {id:'shocks',category:'Suspension',brand:'Elka Suspension',name:'ELKA STAGE 3',option:'Front pair + rear · solo rider',sku:'SM-5475 + SM-8178',url:'https://www.slingmods.com/canam-ryker-front-shocks-coilovers-elka-suspension',rearUrl:'https://www.slingmods.com/canam-ryker-rear-shock-coilover-elka-suspension',fit:'Base 2019+, Rally 2019–2021, Sport 2022+. Rear Stage 3: solo riders only.',description:'Red springs, black damper bodies and reservoir assemblies. Visual preview only; shared game handling stays unchanged.',view:'ryker-shocks'},
 {id:'exhaust',category:'Exhaust',brand:'Treal Performance',name:'TREAL STREET EXHAUST',option:'Stainless steel · standard slash-cut tip',sku:'TRP-RKR-SES',url:'https://trealperformance.com/products/treal-performance-can-am-ryker-600-rally-900-exhaust-system',fit:'Manufacturer listing: 2019–2026 Ryker 600/900, Rally and Sport.',description:'Polished oval silencer, welded inlet and open slash-cut outlet. Visual preview; no horsepower bonus or claimed recording of the real exhaust.',view:'ryker-exhaust'},
 {id:'body',category:'Body Kit',brand:'Panther Customs',name:'PANTHER BODY KIT',option:'Two-piece front fascia & hood · satin black',sku:'SM-8167',url:'https://www.slingmods.com/canam-ryker-front-end-body-kit-panther-customs',fit:'Ryker 2019–2026, Rally 2019–2021, Sport 2022–2026. Excludes 2022+ Rally.',description:'Angular replacement front fascia and hood with recessed grille. Original game geometry modeled from product references; not manufacturer CAD.',view:'ryker-body'},
] as const;
export function validRykerBuild(value:unknown):value is RykerBuild{return !!value&&typeof value==='object'&&!Array.isArray(value)&&Object.entries(value).every(([k,v])=>RYKER_PRODUCTS.some(p=>p.id===k)&&typeof v==='boolean')}
export const RYKER_PRESETS=[{id:'ryker-night',name:'Redline Night',parts:{underglow:true,body:true}},{id:'ryker-street',name:'Panther Street',parts:{shocks:true,exhaust:true,body:true}},{id:'ryker-stock',name:'Factory Red',parts:{}}] as const;
