export type SpyderPart='throttle'|'front'|'rear'|'sway'|'underglow'|'wheels';
export type SpyderMode='Eco'|'City'|'Sport'|'Sport+';
export interface SpyderShock {preload:number;rebound:number;compression:number}
export interface SpyderBuild {parts:Partial<Record<SpyderPart,boolean>>;mode:SpyderMode;front:SpyderShock;rear:SpyderShock;pattern:'steady'|'pulse'}
export const freshSpyderBuild=():SpyderBuild=>({parts:{},mode:'City',front:{preload:0,rebound:.5,compression:.5},rear:{preload:0,rebound:.5,compression:.5},pattern:'steady'});
const base='https://www.slingmods.com/';
export const SPYDER_PRODUCTS=[
 {id:'throttle',sku:'SM-7386',brand:'Pedal Commander',name:'Throttle Response Controller',category:'Throttle',option:'2014–2023 connector · F3 2023 reference',url:base+'pedal-commander/canam-spyder-throttle-response-controller-pedal-commander',credits:550,description:'Eco, City, Sport and Sport+ response curves. Full throttle power stays unchanged.'},
 {id:'front',sku:'SM-20956 / 70003',brand:'Elka',name:'Stage 4 Front Pair',category:'Front Suspension',option:'F3 / F3-S · Stage 4 pair',url:base+'canam-spyder-f3-f3s-front-shocks-coilovers-elka-suspension',credits:1000,description:'Independent front preload, rebound and low-speed compression. Controls are normalized game estimates, not factory click counts. Game tuning: +1.5% grip.'},
 {id:'rear',sku:'SM-20957 / 70007',brand:'Elka',name:'Stage 4 Rear',category:'Rear Suspension',option:'F3 / F3-S · manual preload',url:base+'canam-spyder-f3-f3s-rear-shock-coilover-elka-suspension',credits:750,description:'Manual-preload rear shock. Independent rear rebound and low-speed compression; no hydraulic or high-speed adjustment. Game tuning: +1.5% grip.'},
 {id:'sway',sku:'SM-18320 + SM-18298',brand:'Baja Ron',name:'ULTRA Sway Bar',category:'Handling',option:'F3 bar + required aluminum end-link pair',url:base+'canam-spyder-f3-st-rs-ultra-performance-sway-bar-kit-baja-ron',credits:650,description:'One bundle includes both required links. Redistributes front support conservatively, plus +2% grip as game tuning (not a measured claim); no added power.'},
 {id:'underglow',sku:'SM-18631',brand:'TricLED',name:'F3 UnderGlow',category:'UnderGlow',option:'2023 F3 strip layout',url:base+'canam-spyder-f3-chaser-underglow-lighting-kit-tricled',credits:450,description:'Headlamp, side and underside strips. Steady / gentle pulse game subset. The 2024+ headlight exception remains excluded.'},
 {id:'wheels',sku:'SM-16776',brand:'TricLED',name:'Wheel Lights',category:'Wheel Lights',option:'Front pair · standalone controller',url:base+'canam-spyder-chaser-wheel-light-kit',credits:400,description:'Stationary Brembo-carrier mounting with custom-rim clearance checked in game. No handling effect.'},
] as const;
export const SPYDER_FIT='US 2023 base F3 reference only. Purchased custom model year unknown; game mounts are approximations, not physical fit certification.';
export function validSpyderBuild(raw:unknown):raw is SpyderBuild {if(!raw||typeof raw!=='object')return false;const r=raw as SpyderBuild;return !!r.parts&&typeof r.parts==='object'&&!Array.isArray(r.parts)&&Object.entries(r.parts).every(([k,v])=>SPYDER_PRODUCTS.some(p=>p.id===k)&&typeof v==='boolean')&&['Eco','City','Sport','Sport+'].includes(r.mode)&&['steady','pulse'].includes(r.pattern)&&[r.front,r.rear].every(s=>s&&Object.keys(s).length===3&&['preload','rebound','compression'].every(k=>Number.isFinite(s[k as keyof SpyderShock])&&s[k as keyof SpyderShock]>=0&&s[k as keyof SpyderShock]<=1))}
export function spyderThrottle(input:number,build:SpyderBuild){const x=Math.max(0,Math.min(1,input));if(!build.parts.throttle)return x;return x**({Eco:1.6,City:1,Sport:.78,'Sport+':.60}[build.mode])}
