import {driveTuneLabel,type DestinationLighting} from './config';
import './tokens.css';import './ui.css';
import {BuildMenuInput} from '../career/menu';
import {COLORS,type KitColor} from '../career/catalog';
import {streetSetup,suspensionParameters,type SuspensionSetup} from '../career/suspension';
import type {DeviceSample} from '../driving/input';
import {PRODUCTS,fits,type ProductId} from './catalog';
import {FINISHES,PRESETS,type BuildRecipe} from './config';
export interface SignatureState {recipe:BuildRecipe;destinationLighting?:DestinationLighting;pending:boolean;status:string;screen:'entry'|'build'|'events'|'shop';lighting:'studio'|'lights';driverVisible:boolean;compare:boolean;ignition?:boolean;reducedMotion?:boolean;canUndo?:boolean;savedRecipes?:readonly {id:string;name:string}[];ownedProductIds?:readonly string[];thumbs?:Record<string,string>;routePaths?:Record<string,string>;routeLengths?:Record<string,string>}
export interface SignatureHooks {onChange(recipe:BuildRecipe):void|Promise<void>;onAction(action:string,value?:string):void|Promise<void>;onSave(name:string):void|Promise<void>;onNavigate?():void}
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const categories=['Paint','Lighting','Suspension','Exhaust','Aero','Storage','Build Presets'];
const categoryIds:Record<string,ProductId>={Lighting:'SM-133',Suspension:'SM-3223',Exhaust:'SM-7720',Aero:'SM-26801',Storage:'SM-28919'};
const setupLabels:Record<keyof SuspensionSetup,string>={frontCompression:'Front compression',frontRebound:'Front rebound',rearCompression:'Rear compression',rearRebound:'Rear rebound',rideHeightMm:'Ride height'};
/** Presentation only. Scene owns validation, persistence, transactions and navigation. */
export class SignatureUI {
 readonly root=document.createElement('section');readonly menu:BuildMenuInput;private state!:SignatureState;private key='';private category='Paint';private resetOpen=false;private inspection='';private activeView='hero';private inspectorCollapsed=false;private advanced=false;private modalMenu?:BuildMenuInput;
 constructor(parent:Element,private hooks:SignatureHooks){
  this.root.className='signature-ui';this.root.id='signature-ui';this.root.setAttribute('aria-label','SlingMods showroom');parent.append(this.root);this.menu=new BuildMenuInput(this.root,()=>this.back(),'#game-audio');
  this.root.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLElement>('[data-action]');if(!b||this.state.pending||b.getAttribute('aria-disabled')==='true')return;void this.act(b.dataset.action!,b.dataset.value)});
  this.root.addEventListener('keydown',e=>{if(e.code==='Enter'&&e.target instanceof HTMLInputElement){e.preventDefault();if(!this.state.pending)void this.act('save')}else if(e.code==='Escape'){e.preventDefault();this.back()}else if(this.resetOpen&&e.code==='Tab'){const controls=[...this.root.querySelectorAll<HTMLElement>('.sig-confirm button')],i=controls.indexOf(document.activeElement as HTMLElement);e.preventDefault();controls[(i+(e.shiftKey?-1:1)+controls.length)%controls.length]?.focus()}else if(['ArrowUp','ArrowDown'].includes(e.code)&&!(e.target instanceof HTMLInputElement)){e.preventDefault();(this.modalMenu??this.menu).move(e.code==='ArrowUp'?-1:1)}});
 }
 private async act(action:string,value?:string){
  if(action==='inspector'){this.inspectorCollapsed=!this.inspectorCollapsed;this.key='';this.render();this.root.querySelector<HTMLElement>(this.inspectorCollapsed?'.sig-restore button':'.sig-detail-heading [data-action=inspector]')?.focus({preventScroll:true});return}
  if(action==='advanced'){this.advanced=!this.advanced;this.key='';this.render();return}
  if(action==='category'){if(this.category!==value)this.hooks.onNavigate?.();this.inspectorCollapsed=false;const wasInspecting=!!this.inspection;this.inspection='';this.category=value!;this.key='';this.render();if(wasInspecting)await this.hooks.onAction('view','hero');return}
  if(action==='reset'){this.resetOpen=true;this.key='';this.render();this.root.querySelector<HTMLButtonElement>('[data-action=cancel-reset]')!.focus();return}
  if(action==='cancel-reset'){this.closeReset();return}
  if(action==='confirm-reset'){this.resetOpen=false;action='reset'}
  const r=structuredClone(this.state.recipe);let change=true;
  if(action==='finish')r.finish=value as BuildRecipe['finish'];
  else if(action==='toggle'){const id=value as ProductId,p=PRODUCTS.find(p=>p.id===id)!;if(r.products[id])delete r.products[id];else if(fits(p,r).ok)r.products[id]=p.options[0].id;else return}
  else if(action==='option'){const [id,option]=value!.split('|');if(!fits(PRODUCTS.find(p=>p.id===id)!,r).ok)return;r.products[id as ProductId]=option}
  else if(action==='setup'){const [id,delta]=value!.split('|'),k=id as keyof SuspensionSetup;r.suspension[k]=Math.max(k==='rideHeightMm'?-20:0,Math.min(k==='rideHeightMm'?20:19,r.suspension[k]+Number(delta)))}
  else if(action==='street')r.suspension=streetSetup();
  else if(action==='light-color')r.lights.color=value as KitColor;
  else if(action==='light-brightness')r.lights.brightness=Math.max(.15,Math.min(.85,Math.round((r.lights.brightness+Number(value))*100)/100));
  else if(action==='light-enabled')r.lights.enabled=!r.lights.enabled;
  else change=false;
  if(change){await this.hooks.onChange(r);return}
  if(action==='save'){const input=this.root.querySelector<HTMLInputElement>('#signature-recipe-name')!,name=input.value.trim();if(!name){input.focus();input.setCustomValidity('Give this build a name.');input.reportValidity();return}input.setCustomValidity('');await this.hooks.onSave(name);return}
  if(action==='view'){this.activeView=value??'hero';this.inspection=value?.startsWith('SM-')?value:'';this.key='';this.render()}else if(['build','back','compare','reset','test-drive','race'].includes(action)){this.inspection=''}
  await this.hooks.onAction(action,value);
 }
 private closeReset(){this.resetOpen=false;this.key='';this.render();this.root.querySelector<HTMLElement>('[data-action=reset]')?.focus()}
 private back(){if(this.state.pending)return;if(this.resetOpen)this.closeReset();else void this.hooks.onAction('back')}
 update(state:SignatureState){this.state=state;this.render()}
 private button(label:string,action:string,value='',primary=false,disabled=false){return `<button data-action="${action}" data-value="${esc(value)}" ${disabled?'disabled':''} ${action==='view'?`aria-pressed="${this.activeView===value}"`:action==='ignition'?`aria-pressed="${!!this.state.ignition}"`:action==='advanced'?`aria-expanded="${this.advanced}"`:''} class="${primary?'sig-primary':''}">${label}</button>`}
 private render(){const s=this.state,key=JSON.stringify([s,this.category,this.resetOpen,this.inspection,this.inspectorCollapsed,this.advanced]);if(key===this.key)return;this.key=key;const focused=this.root.contains(document.activeElement)?document.activeElement as HTMLElement:null,focusKey=focused?.dataset.action+'|'+focused?.dataset.value,draft=this.root.querySelector<HTMLInputElement>('#signature-recipe-name')?.value;
  this.root.dataset.screen=s.screen;this.root.dataset.inspector=String(!this.inspectorCollapsed);this.root.dataset.inspection=String(!!this.inspection);this.root.dataset.reducedMotion=String(!!s.reducedMotion);this.root.setAttribute('aria-busy',String(s.pending));this.root.innerHTML=`<header class="sig-header"><button class="sig-brand" data-action="back" aria-label="SlingMods home"><img src="./assets/brand/slingmods-logo-main.png" alt="SlingMods"></button><span class="sig-game">THREE-WHEEL TOUR</span><div class="sig-context">2024 SLINGSHOT R <small>${s.screen==='entry'?'Development Preview · Desktop':s.screen==='events'?'CHOOSE YOUR DRIVE':'FREE CONFIGURATOR'}</small></div></header>${s.screen==='entry'?this.entry():s.screen==='events'?this.events():s.screen==='shop'?this.shop():this.build()}<p class="sig-status" role="status">${esc(s.pending?'Saving your build…':s.status)}</p>${this.resetOpen?'<div class="sig-modal"><section class="sig-confirm" role="alertdialog" aria-modal="true" aria-labelledby="reset-title"><span class="sig-eyebrow">PREVIEW BUILD</span><h2 id="reset-title">Restore starting build?</h2><p>Your saved recipes and career purchases stay safe. This restores the build you opened or last explicitly saved.</p>'+this.button('Keep my build','cancel-reset')+this.button('Restore preview','confirm-reset','',true)+'</section></div>':''}`;
  this.modalMenu=this.resetOpen?new BuildMenuInput(this.root.querySelector('.sig-confirm')!,()=>this.closeReset()):undefined;
  if(s.pending)for(const e of this.root.querySelectorAll<HTMLButtonElement|HTMLInputElement>('button,input'))e.disabled=true;
  if(this.resetOpen)for(const e of this.root.children)if(e instanceof HTMLElement&&!e.classList.contains('sig-modal'))e.inert=true;
  const input=this.root.querySelector<HTMLInputElement>('#signature-recipe-name');if(draft&&input)input.value=draft;
  if(focused)[...this.root.querySelectorAll<HTMLElement>('[data-action]')].find(e=>e.dataset.action+'|'+e.dataset.value===focusKey)?.focus({preventScroll:true});
 }
 private entry(){return `<main class="sig-entry"><span class="sig-eyebrow">YOUR SLINGSHOT. YOUR SIGNATURE.</span><h1>Make it yours.<br>Then make it move.</h1><p>Build your 2024 Slingshot R in the SlingMods showroom. Take your setup from the waterfront to the ridge.</p><div class="sig-entry-actions">${this.button('Build Your Slingshot <span>↗</span>','build','',true)}${this.button('Quick Race','quick-race')}${this.button('Continue Career','career')}</div><small>No credits needed to configure or test drive.</small></main><div class="sig-room-label"><span>THE SLINGMODS STUDIO</span><small>Real products. Your next build.</small></div>`}
 private build(){const s=this.state;return `<nav class="sig-categories" aria-label="Build categories">${categories.map((c,i)=>`<button data-action="category" data-value="${c}" aria-pressed="${this.category===c}"><span>0${i+1}</span>${c}</button>`).join('')}</nav><aside class="sig-detail" ${this.inspectorCollapsed?'hidden':''} aria-label="${esc(this.category)} configuration"><div class="sig-detail-heading"><span class="sig-eyebrow">${esc(this.category)}</span>${this.button('Hide panel','inspector')}</div>${this.inspection==='SM-28919'?'<p class="sig-inspection-note">Storage inspection · seats hidden and doors open. Full vehicle restores the exterior.</p>':''}${this.category==='Paint'?this.paint():this.category==='Build Presets'?this.presets():this.product(categoryIds[this.category])}</aside><div class="sig-view-tools" aria-label="Showroom view"><div class="sig-camera-rail"><span class="sig-tool-label">VIEW</span>${['Full vehicle','Front','Rear','Interior'].map((v,i)=>this.button(v,'view',['hero','front','rear','interior'][i])).join('')}${this.button(s.ignition?'Dash on ●':'Dash off ○','ignition',String(!s.ignition))}${this.button(this.advanced?'Less':'More','advanced')}</div>${this.advanced?`<div class="sig-advanced-rail">${this.button(s.lighting==='studio'?'Studio ✓':'Studio','lighting','studio')}${this.button(s.lighting==='lights'?'Lights ✓':'Lights','lighting','lights')}${this.button(s.driverVisible?'Driver on':'Driver off','driver',String(!s.driverVisible))}${this.button(s.reducedMotion?'Motion: Reduced':'Motion: Full','motion',String(!s.reducedMotion))}</div>`:''}</div>${this.inspectorCollapsed?`<div class="sig-restore">${this.button('Show '+this.category,'inspector')}</div>`:''}<footer class="sig-bottom"><div><strong>Preview build</strong><small>${driveTuneLabel(s.recipe.handlingProfile)} · No career spend</small></div><div class="sig-history">${this.button('Undo','undo','',false,!s.canUndo)}${this.button(s.compare?'Return to build':'Compare stock','compare')}${this.button('Reset','reset')}</div><div>${this.button('Shop This Build','shop')}${this.button('Destinations','quick-race')}${this.button('Test This Build ↗','test-drive','express',true)}</div></footer>`}
 private paint(){return `<h2>Choose your finish.</h2><p>Body and swingarm, in your signature palette.</p><div class="sig-finishes">${FINISHES.map(f=>`<button data-action="finish" data-value="${f.id}" aria-pressed="${this.state.recipe.finish===f.id}"><i style="--paint:${f.color};--accent:${f.accent}" aria-hidden="true"></i><span>${esc(f.name)}</span><b>${this.state.recipe.finish===f.id?'✓':''}</b></button>`).join('')}</div><details><summary>About these finishes</summary><p>Original game material combinations for the 2024 Slingshot R. Springs, brakes and trim retain their materials. These do not represent official paint availability.</p></details>`}
 private product(id:ProductId){const p=PRODUCTS.find(p=>p.id===id)!,s=this.state,selected=!!s.recipe.products[id],option=s.recipe.products[id]??p.options[0].id,owned=s.ownedProductIds?.includes(id),thumb=s.thumbs?.[id],fit=fits(p,s.recipe);return `<div class="sig-product-image">${thumb?`<img src="${esc(thumb)}" alt="${esc(p.name)} rendered asset preview">`:'<span>Inspect the mounted part in 3D</span>'}<span>${esc(p.brand)} / ${id}</span></div><h2>${esc(p.name)}</h2><p class="sig-fitment">${fit.ok?'Fits 2024 Slingshot R':esc(fit.reason)}<span>${selected?'Selected preview':'Not selected'}${owned?' · Career owned':''}</span></p><p>${esc(p.description)}</p><div class="sig-options" aria-label="Product option">${p.options.map(o=>`<button data-action="option" data-value="${id}|${esc(o.id)}" aria-pressed="${selected&&o.id===option}" ${!fit.ok?'disabled':''}>${esc(o.label)}</button>`).join('')}</div><div class="sig-product-actions">${selected?'<span class="sig-installed">✓ Installed</span>':''}${this.button(selected?'Remove':'Preview part','toggle',id,!selected,!selected&&!fit.ok)}${this.button('Inspect mount','view',id)}</div><a class="sig-external" href="${esc(p.shopUrl)}" target="_blank" rel="noopener noreferrer">View on SlingMods ↗</a>${id==='SM-133'&&selected?this.lightingControls():''}${id==='SM-3223'&&selected?this.setup():''}<details><summary>Details &amp; comparison</summary><p>${esc(p.effect)}</p><p>Preview selection is separate from career ownership. Removing a preview does not remove a purchased career part.</p></details>`}
 private lightingControls(){const l=this.state.recipe.lights;return `<section class="sig-setup"><h3>Set the mood</h3><div class="sig-options">${Object.entries(COLORS).map(([id,color])=>`<button data-action="light-color" data-value="${id}" aria-pressed="${l.color===id}"><i class="sig-color-dot" style="background:${color}" aria-hidden="true"></i>${id[0].toUpperCase()+id.slice(1)}</button>`).join('')}</div><div class="sig-stepper"><span>Brightness</span><button data-action="light-brightness" data-value="-.05" aria-label="Decrease brightness" ${l.brightness<=.15?'disabled':''}>−</button><output>${Math.round(l.brightness*100)}%</output><button data-action="light-brightness" data-value=".05" aria-label="Increase brightness" ${l.brightness>=.85?'disabled':''}>+</button></div>${this.button(l.enabled?'Turn LEDs off':'Turn LEDs on','light-enabled')}${this.button('See in Lights mode','lighting','lights')}</section>`}
 private setup(){const s=this.state.recipe.suspension,p=suspensionParameters(s);return `<section class="sig-setup"><div class="sig-setup-title"><h3>Find your balance</h3>${this.button('Street start','street')}</div><p>Independent compression and rebound. More clicks means firmer damping, not automatically faster.</p>${(Object.keys(setupLabels) as (keyof SuspensionSetup)[]).map(k=>`<div class="sig-stepper"><span>${setupLabels[k]}</span><button data-action="setup" data-value="${k}|-1" aria-label="Decrease ${setupLabels[k]}" ${s[k]===(k==='rideHeightMm'?-20:0)?'disabled':''}>−</button><output>${s[k]}${k==='rideHeightMm'?' mm':''}</output><button data-action="setup" data-value="${k}|1" aria-label="Increase ${setupLabels[k]}" ${s[k]===(k==='rideHeightMm'?20:19)?'disabled':''}>+</button></div>`).join('')}<details><summary>Calculated stock / selected damping</summary><table><thead><tr><th>N·s/m</th><th>Stock</th><th>Selected</th></tr></thead><tbody>${(['frontCompression','frontRebound','rearCompression','rearRebound'] as const).map(k=>`<tr><th>${setupLabels[k]}</th><td>${k.startsWith('front')?3800:6500}</td><td>${Math.round(p[k])}</td></tr>`).join('')}</tbody></table><p>Game estimates, not measured manufacturer curves. Clicks count from full soft. Ride height is a bounded game offset.</p></details></section>`}
 private presets(){return `<h2>A place to start.</h2><p>A few ideas for your next drive. Mix, change and make each one your own.</p><p>Drive tune: ${driveTuneLabel(this.state.recipe.handlingProfile)}</p><div>${this.state.recipe.handlingProfile!=='slingmods-sport-v3'?this.button('Use current driving','use-current-driving'):''}<details><summary>Historical reference tunes</summary>${this.button('Sport v2 · reference','handling','slingmods-sport-v2')}${this.button('Sport v1 · reference','handling','slingmods-sport-v1')}</details></div><div class="sig-presets">${PRESETS.map(p=>this.button(esc(p.name),'preset',p.id)).join('')}</div><form class="sig-save" onsubmit="return false"><label for="signature-recipe-name">Save your build recipe</label><input id="signature-recipe-name" maxlength="48" autocomplete="off" placeholder="Give your build a name">${this.button('Save build','save')}</form><div class="sig-recipes">${(this.state.savedRecipes??[]).map(r=>this.button(esc(r.name),'load-recipe',r.id)).join('')||'<p>No saved recipes yet.</p>'}</div>`}
 private events(){const s=this.state,night=s.destinationLighting==='night',routes=[{id:'harbor',name:'Original Harbor',type:'Technical waterfront',text:'Brake, turn and place the car through the original waterfront.'},{id:'express',name:'Harbor Express',type:'Open coastal road',text:'A longer waterfront run with room to accelerate.'},{id:'ridge',name:'Smoky Ridge',type:'Closed mountain circuit',text:'Climb through the trees, crest the overlook and follow the descent home.'}];return `<main class="sig-events"><span class="sig-eyebrow">MAKE IT MOVE</span><h1>Choose your drive.</h1><p>Every destination is free to explore with this exact preview build. Career progress and purchases stay separate.</p><div class="sig-event-grid sig-destinations">${routes.map(r=>`<article data-destination="${r.id}"><div class="sig-route-art">${r.id==='ridge'?'<img src="/assets/ridge/thumbnail.jpg" alt="Smoky Ridge mountain road captured in game" loading="lazy">':`<svg viewBox="0 0 240 130" aria-label="${r.name} route map"><path d="${esc(s.routePaths?.[r.id]??'')}"/></svg>`}</div><span class="sig-eyebrow">${r.type}</span><h2>${r.name}</h2><strong>1 lap · ${esc(s.routeLengths?.[r.id]??'')}${r.id==='ridge'?' · Physical elevation':' · Day'}</strong><p>${r.text}</p>${r.id==='ridge'?`<div class="sig-destination-light" role="group" aria-label="Smoky Ridge lighting"><button data-action="destination-lighting" data-value="day" aria-pressed="${!night}">Late afternoon</button><button data-action="destination-lighting" data-value="night" aria-pressed="${night}">Blue hour</button></div>`:'<small>Daylight waterfront drive</small>'}${this.button('Quick Race','race',r.id,true)}${this.button('Test Drive','test-drive',r.id)}</article>`).join('')}</div><div class="sig-destination-footer">${this.button('Back to showroom','build')}${this.button('Continue Career','career')}<span>Earned chapters: Build Matters · Own the Build · Ridge Run</span></div></main>`}
 private shop(){const selected=PRODUCTS.filter(p=>this.state.recipe.products[p.id]);return `<main class="sig-shop"><span class="sig-eyebrow">YOUR BUILD / REAL PRODUCTS</span><h1>Take a closer look.</h1><p>Open the individual product page you choose. Your preview stays here; no cart or checkout is created.</p><div class="sig-shop-list">${selected.map(p=>`<article><div><span>${p.id} · Fits 2024 Slingshot R</span><h2>${esc(p.name)}</h2><p>${esc(p.options.find(o=>o.id===this.state.recipe.products[p.id])?.label??'')}</p></div><a href="${esc(p.shopUrl)}" target="_blank" rel="noopener noreferrer">View on SlingMods ↗</a></article>`).join('')||'<p>Your build uses stock equipment. Preview an accessory to include it here.</p>'}</div>${this.button('Back to build','build','',true)}${this.button('Copy build summary','copy')}</main>`}
 frame(sample:DeviceSample){if(!this.state.pending)(this.modalMenu??this.menu).frame(sample)}
 inspect(){return {screen:this.state.screen,category:this.category,pending:this.state.pending,resetOpen:this.resetOpen}}
 dispose(){this.root.remove()}
}
