from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'assets/p11'
items=[('01 / Asphalt','../../public/assets/p11/race-asphalt/wet-baseColor.png','4K dry/wet PBR, detail normal, 25% puddle mask.'),('02 / Road decals','../../public/assets/p11/road-decals/baseColor.png','36 labelled UV cells, real-world sizes, normal/roughness/ORM companions.'),('03 / Harbor water','previews/water-day.png','Dual normal maps, foam, caustics, depth LUT and tested GLSL material.'),('04 / Ridge trees','previews/oak-wind.png','Three species, three LODs each, wind/backlight shader and eight-view imposters.'),('05 / Ground cover','../../public/assets/p11/ground-cover/cards-baseColor.png','Five scanned ground sets, 12 card clusters, six rock meshes and shoulder weights.'),('06 / Trackside kit','previews/armco-curved.png','22 prop variants, three LODs, shared 4K trim and route placement helper.'),('07 / Wooden sign','previews/sign-routed.png','Official logo, painted/routed versions, 2 LODs, tested 12% padding.'),('08 / HUD art','../../public/assets/p11/ui-hud/tachometer-arc@2x.png','45 SVG components with 2× PNG exports and embedded licensed typeface.'),('09 / VFX','../../public/assets/p11/vfx/tire-smoke.png','14 timed flipbooks plus particles, lens textures and a 64³ noise volume.'),('10 / Skies','previews/golden-hour-sky.png','Five 8K HDRs, 1K inputs, prefiltered EXRs and lighting metadata.'),('11 / Points token','previews/points-100.png','Four low-poly animated pickups and runtime scale/flash/shard animation.')]
cards=[]
for title,src,desc in items:
 media='<div class="sky">8K HDR + 1K PMREM<br><small>Golden / dusk / moon / rain / marine</small></div>' if src.endswith('.exr') else '<img loading="lazy" src="'+html.escape(src)+'">'
 cards.append('<article>'+media+'<h2>'+title+'</h2><p>'+desc+'</p></article>')
(OUT/'review.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>P11 Asset Review</title><style>body{margin:0;padding:48px;background:#121518;color:#edf0f2;font:16px/1.5 system-ui}header{max-width:1050px;margin-bottom:32px}h1{font-size:44px;margin:0}header b{color:#f04750}header p{color:#b0b9c1}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:24px}article{background:#20262b;padding:20px;border-top:2px solid #e0202a}img,.sky{width:100%;height:260px;object-fit:contain;background:#172027}.sky{display:flex;flex-direction:column;justify-content:center;align-items:center;background:linear-gradient(#28396a,#cf866f,#253b48);font-weight:800;font-size:28px}.sky small{font-size:13px}h2{font-size:23px}article p{color:#b0b9c1}a{color:#ff777d}</style><header><b>SLINGMODS / THREE-WHEEL TOUR</b><h1>P11 asset review</h1><p>All eleven kits have authored files. This is a standalone asset pack, not a deployed or fully integrated game update. AI card/decal artwork is upscaled from 1254px; scanned PBR maps are native resolution. Read STATUS.md for exact remaining acceptance checks.</p></header><main>'+''.join(cards)+'</main></html>', encoding="utf-8")
print('Wrote assets/p11/review.html')
