import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import{fileURLToPath}from'node:url';import{chromium}from'@playwright/test';
const root=path.resolve(fileURLToPath(new URL('../../',import.meta.url)));const evidence=path.join(root,'assets/p11/previews');await fs.mkdir(evidence,{recursive:true});
const html=`<!doctype html><html><style>body{margin:0}canvas{display:block}</style><script type="importmap">{"imports":{"three":"/node_modules/three/build/three.module.js","three/addons/":"/node_modules/three/examples/jsm/"}}</script><script type="module">
import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import{createHarborWater}from'/assets/p11/harbor-water/create-material.mjs';import{enableTreeWind}from'/assets/p11/ridge-trees/wind-material.mjs';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(900,700);renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);const errors=[];renderer.debug.onShaderError=(gl,p,v,f)=>errors.push([gl.getProgramInfoLog(p),gl.getShaderInfoLog(v),gl.getShaderInfoLog(f)].join('\\n'));
const camera=new T.PerspectiveCamera(45,900/700,.1,300);camera.position.set(0,3.5,7);camera.lookAt(0,0,0);const opaque=new T.Scene();opaque.background=new T.Color('#21333f');opaque.add(new T.HemisphereLight(0xc6dcf5,0x514431,3));const ground=new T.Mesh(new T.PlaneGeometry(30,30),new T.MeshStandardMaterial({color:0x847250}));ground.rotation.x=-Math.PI/2;ground.position.y=-3;opaque.add(ground);const quay=new T.Mesh(new T.BoxGeometry(4,1,9),new T.MeshStandardMaterial({color:0xa4a39a}));quay.position.set(-5,0,0);opaque.add(quay);
const rt=new T.WebGLRenderTarget(900,700);rt.depthTexture=new T.DepthTexture(900,700);renderer.setRenderTarget(rt);renderer.render(opaque,camera);renderer.setRenderTarget(null);
const faces=Array.from({length:6},(_,i)=>{const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d');ctx.fillStyle=['#91a9bc','#91a9bc','#c8dbe4','#415661','#9aadb9','#9aadb9'][i];ctx.fillRect(0,0,32,32);return c;});const cube=new T.CubeTexture(faces);cube.needsUpdate=true;
const water=await createHarborWater({sceneDepth:rt.depthTexture,environmentCube:cube,camera});const plane=new T.Mesh(new T.PlaneGeometry(30,30,128,128),water.material);plane.rotation.x=-Math.PI/2;opaque.add(plane);water.update(1);renderer.render(opaque,camera);window.report={waterShaderErrors:[...errors],opaqueDepthPass:true};window.ready=true;
window.night=()=>{water.material.uniforms.nightMix.value=1;water.material.uniforms.sunIntensity.value=.05;water.material.uniforms.nightLightPosition.value[0].set(0,5,-8);water.material.uniforms.nightLightColor.value[0].setRGB(1,.6,.2);renderer.render(opaque,camera);return [...errors];};
window.checkTree=async()=>{const gltf=await new GLTFLoader().loadAsync('/assets/p11/ridge-trees/oak-lod0.glb');const scene=new T.Scene();scene.background=new T.Color('#283139');scene.add(new T.HemisphereLight(0xd3e2ec,0x464531,3));const sun=new T.DirectionalLight(0xffd3a3,3);sun.position.set(5,10,-5);scene.add(sun);const time={value:1};gltf.scene.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])enableTreeWind(m,time);});scene.add(gltf.scene);const b=new T.Box3().setFromObject(gltf.scene),c=b.getCenter(new T.Vector3()),r=b.getSize(new T.Vector3()).length()*.5;camera.position.copy(c).add(new T.Vector3(r*.4,r*.3,r*3));camera.lookAt(c);renderer.render(scene,camera);const first=renderer.domElement.toDataURL();time.value=3;renderer.render(scene,camera);const second=renderer.domElement.toDataURL();return{shaderErrors:[...errors],windChangesRenderedPixels:first!==second};};
</script></html>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');if(u.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const relative=decodeURIComponent(u.pathname).slice(1);if(!relative.startsWith('assets/p11/')&&!relative.startsWith('node_modules/three/'))throw Error('Path denied');const base=relative.startsWith('node_modules/')?root:path.join(root,'public');const p=path.resolve(base,relative);if(!p.startsWith(base+path.sep))throw Error('Path denied');res.setHeader('Content-Type',/\.m?js$/.test(p)?'text/javascript':p.endsWith('.glsl')?'text/plain':'application/octet-stream');res.end(await fs.readFile(p));}catch(e){res.writeHead(500);res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});const page=await browser.newPage({viewport:{width:900,height:700}});page.on('pageerror',e=>console.error(e));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready,{},{timeout:60000});const report=await page.evaluate(()=>window.report);await page.screenshot({path:path.join(evidence,'water-day.png')});report.nightShaderErrors=await page.evaluate(()=>window.night());await page.screenshot({path:path.join(evidence,'water-night.png')});report.tree=await page.evaluate(()=>window.checkTree());await page.screenshot({path:path.join(evidence,'oak-wind.png')});await fs.writeFile(path.join(root,'assets/p11/shader-validation.json'),JSON.stringify(report,null,2));if(report.waterShaderErrors.length||report.nightShaderErrors.length||report.tree.shaderErrors.length||!report.tree.windChangesRenderedPixels)throw Error(JSON.stringify(report));console.log('Water/day/night and tree wind shaders compile and render; wind changes pixels.');}finally{await browser?.close();server.close();}
