import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from '@playwright/test';
const root=path.resolve(fileURLToPath(new URL('../../',import.meta.url))),out=path.join(root,'public/assets/p11');
const html=`<!doctype html><html><style>body{margin:0;background:#15191d}canvas{display:block}</style><script type="importmap">{"imports":{"three":"/node_modules/three/build/three.module.js","three/addons/":"/node_modules/three/examples/jsm/"}}</script><script type="module">
import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';import {EXRExporter} from 'three/addons/exporters/EXRExporter.js';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(900,700);renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);
const loader=new GLTFLoader();
window.renderAsset=async(url)=>{const gltf=await loader.loadAsync(url);const scene=new T.Scene();scene.background=new T.Color('#1c232b');scene.add(new T.HemisphereLight(0xd5e6ff,0x53483c,2.2));const sun=new T.DirectionalLight(0xffdfb5,3);sun.position.set(4,8,5);scene.add(sun);gltf.scene.traverse(o=>{if(o.isMesh){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.vertexColors=false;if(m.transparent){m.alphaTest=.35;m.transparent=false;}if(o.name.startsWith('LogoBounds_')){m.depthTest=false;m.depthWrite=false;o.renderOrder=100;}m.needsUpdate=true;}}});scene.add(gltf.scene);const box=new T.Box3().setFromObject(gltf.scene),size=box.getSize(new T.Vector3()),c=box.getCenter(new T.Vector3()),r=size.length()/2;const camera=new T.PerspectiveCamera(40,900/700,.01,1000);camera.position.copy(c).add(new T.Vector3(.9,.45,1.7).normalize().multiplyScalar(r*3.25));camera.lookAt(c);renderer.render(scene,camera);const stats={bounds:{min:box.min.toArray(),max:box.max.toArray()},triangles:renderer.info.render.triangles,animations:gltf.animations.map(a=>a.name)};gltf.scene.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});return stats;};
window.prefilter=async(name)=>{const hdr=await new RGBELoader().setDataType(T.FloatType).loadAsync('/assets/p11/skies/'+name+'-1k.hdr');let sourceMax=0;for(let i=0;i<hdr.image.data.length;i+=4)sourceMax=Math.max(sourceMax,hdr.image.data[i],hdr.image.data[i+1],hdr.image.data[i+2]);const prefilterScale=Math.min(1,128/sourceMax);for(let i=0;i<hdr.image.data.length;i+=4)for(let c=0;c<3;c++)hdr.image.data[i+c]*=prefilterScale;hdr.needsUpdate=true;const pmrem=new T.PMREMGenerator(renderer);const target=pmrem.fromEquirectangular(hdr);const data=await new EXRExporter().parse(renderer,target);await fetch('/write/'+name+'-pmrem.exr',{method:'POST',body:data});const pixels=hdr.image.data,w=hdr.image.width,h=hdr.image.height;let max=-1,idx=0;let horizon=[0,0,0],count=0;for(let y=0;y<h/2;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,l=pixels[i]*.2126+pixels[i+1]*.7152+pixels[i+2]*.0722;if(l>max){max=l;idx=y*w+x;}if(y>h*.46){for(let k=0;k<3;k++)horizon[k]+=pixels[i+k];count++;}}const y=Math.floor(idx/w),x=idx%w,theta=Math.PI*(y+.5)/h,phi=2*Math.PI*(x+.5)/w;const direction=[-Math.sin(theta)*Math.cos(phi),Math.cos(theta),Math.sin(theta)*Math.sin(phi)];const rgb=[pixels[idx*4],pixels[idx*4+1],pixels[idx*4+2]],peak=Math.max(...rgb);const result={preset:name,source:name+'-1k.hdr',prefiltered:name+'-pmrem.exr',layout:'Three.js CubeUVReflectionMapping',width:target.width,height:target.height,inputResolution:[w,h],direction,colorLinear:rgb.map(c=>c/peak),peakRadiance:rgb.map(c=>c/prefilterScale),peakLuminance:max/prefilterScale,prefilterRadianceScale:prefilterScale,environmentIntensityToRestoreRadiance:1/prefilterScale,fogColorLinear:horizon.map(c=>c/count/prefilterScale),directionMethod:'Brightest upper-hemisphere source texel; verify against full resolution before rig adoption',intensityUnits:'source relative radiance, not calibrated lux',colorTemperatureKelvin:null};target.dispose();pmrem.dispose();hdr.dispose();return result;};
window.ready=true;</script></html>`;
const types={'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.json':'application/json'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/author'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(req.method==='POST'&&/^\/write\/(golden-hour|dusk|clear-night|after-rain|marine-layer)-pmrem\.exr$/.test(url.pathname)){const chunks=[];for await(const c of req)chunks.push(c);await fs.writeFile(path.join(out,'skies',path.basename(url.pathname)),Buffer.concat(chunks));res.end('ok');return;}const rel=decodeURIComponent(url.pathname).replace(/^\//,'');if(!rel.startsWith('assets/p11/')&&!rel.startsWith('node_modules/three/')){res.writeHead(404);res.end();return;}const base=rel.startsWith('node_modules/')?root:path.join(root,'public');const p=path.resolve(base,rel);if(!p.startsWith(base+path.sep)){res.writeHead(403);res.end();return;}res.setHeader('Content-Type',types[path.extname(p)]??'application/octet-stream');res.end(await fs.readFile(p));}catch(e){res.writeHead(500);res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:900,height:700}});page.on('pageerror',e=>console.error(e));await page.goto(base+'/author');await page.waitForFunction(()=>window.ready);
await page.evaluate(url=>window.renderAsset(url),'/assets/p11/wooden-sign/sign-painted-lod0.glb');await page.screenshot({path:path.join(root,'assets/p11/previews/sign-depth-debug.png')});
}finally{await browser?.close();server.close();}
