import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath}from'node:url';import{Matrix4,Vector3,Quaternion,Box3}from'three';
const root=fileURLToPath(new URL('../../public/assets/p11/',import.meta.url));
function glb(file){const data=fs.readFileSync(path.join(root,file));assert.equal(data.readUInt32LE(0),0x46546c67);assert.equal(data.readUInt32LE(8),data.length);const n=data.readUInt32LE(12),json=JSON.parse(data.subarray(20,20+n)),bin=data.subarray(28+n);return{json,bin};}
function triangles(json){return json.meshes.reduce((s,m)=>s+m.primitives.reduce((a,p)=>a+(json.accessors[p.indices??p.attributes.POSITION].count/(p.indices===undefined?3:3)),0),0);}
function bounds(asset,predicate){const {json,bin}=asset,box=new Box3();let found=0;function walk(i,parent){const node=json.nodes[i],m=node.matrix?new Matrix4().fromArray(node.matrix):new Matrix4().compose(new Vector3().fromArray(node.translation??[0,0,0]),new Quaternion().fromArray(node.rotation??[0,0,0,1]),new Vector3().fromArray(node.scale??[1,1,1]));m.premultiply(parent);if(node.mesh!==undefined&&predicate(node.name)){found++;for(const p of json.meshes[node.mesh].primitives){const a=json.accessors[p.attributes.POSITION],v=json.bufferViews[a.bufferView];assert.equal(a.componentType,5126);for(let k=0;k<a.count;k++){const off=(v.byteOffset??0)+(a.byteOffset??0)+k*(v.byteStride??12);box.expandByPoint(new Vector3(bin.readFloatLE(off),bin.readFloatLE(off+4),bin.readFloatLE(off+8)).applyMatrix4(m));}}}for(const child of node.children??[])walk(child,m);}for(const i of json.scenes[json.scene??0].nodes)walk(i,new Matrix4());assert.ok(found);return box;}
test('official logo geometry remains within 12% padded board bounds in both variants and LODs',()=>{for(const variant of['painted','routed'])for(const lod of[0,1]){const a=glb(`wooden-sign/sign-${variant}-lod${lod}.glb`),board=bounds(a,n=>n.startsWith('cedar plank')),logo=bounds(a,n=>n.startsWith('LogoBounds_')),b=board.getSize(new Vector3()),l=logo.getSize(new Vector3());for(const axis of['x','y']){assert.ok(logo.min[axis]>=board.min[axis]+b[axis]*.12-1e-4,variant+axis+' lower');assert.ok(logo.max[axis]<=board.max[axis]-b[axis]*.12+1e-4,variant+axis+' upper');}const spec=JSON.parse(fs.readFileSync(path.join(root,'wooden-sign/logo-bounds.json')));assert.ok(Math.abs(l.x/l.y-spec.logo.sourceAspect)<.01);}});
test('tokens remain within 800 triangles and contain idle animation',()=>{for(const value of[10,25,50,100]){const {json}=glb(`points-token/points-${value}-lod0.glb`);assert.ok(triangles(json)<=800);assert.ok(json.animations?.some(a=>a.name.includes('Idle')));}});
test('tree LOD triangle budgets and wind channels survive export',()=>{for(const species of['oak','sycamore','eucalyptus'])for(const [lod,target]of[12000,3000,600].entries()){const{json}=glb(`ridge-trees/${species}-lod${lod}.glb`);assert.ok(Math.abs(triangles(json)-target)<=2,`${species} LOD${lod}`);for(const m of json.meshes)for(const p of m.primitives)assert.ok(p.attributes.COLOR_0!==undefined);}});
test('route placement uses arc length, finite inputs and lateral offsets',async()=>{const{placeAlongRoute}=await import('../../public/assets/p11/trackside-props/place-route.mjs');const p=placeAlongRoute([{x:0,y:0,z:0},{x:0,y:0,z:10},{x:10,y:0,z:10}],{spacing:5,offset:2});assert.deepEqual(p.map(x=>x.station),[0,5,10,15]);assert.deepEqual(p[0].position,[-2,0,0]);assert.deepEqual(p[2].position,[0,0,12]);assert.throws(()=>placeAlongRoute([{x:0,y:0,z:0},{x:0,y:2,z:0}]),/Vertical/);});
test('all shared GLB image dependencies resolve inside the asset pack',()=>{for(const dir of fs.readdirSync(root,{withFileTypes:true}).filter(e=>e.isDirectory()))for(const file of fs.readdirSync(path.join(root,dir.name)).filter(f=>f.endsWith('.glb'))){const{json}=glb(dir.name+'/'+file);for(const image of json.images??[]){if(!image.uri)continue;const p=path.resolve(root,dir.name,image.uri);assert.ok(p.startsWith(path.resolve(root)+path.sep));assert.ok(fs.existsSync(p),p);}}});
test('sky files retain HDR radiance and real prefiltered EXRs',()=>{const rigs=JSON.parse(fs.readFileSync(path.join(root,'skies/lighting-rigs.json'))).rigs;assert.equal(rigs.length,5);for(const r of rigs){const hdr=fs.readFileSync(path.join(root,'skies',r.preset+'-8k.hdr'));assert.match(hdr.subarray(0,400).toString(),/-Y 4096 \+X 8192/);const exr=fs.readFileSync(path.join(root,'skies',r.prefiltered));assert.equal(exr.readUInt32LE(0),20000630);assert.ok(Math.abs(Math.hypot(...r.direction)-1)<1e-5);}});
