"""Deterministic original Ridge district kit. Blender 4.5 background; no network/assets generated by AI.
Coordinate basis: authoring Z up; glTF exports Y up. Individual kit modules sit at local ground zero.
"""
import bpy, math, random, json
from mathutils import Vector
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'public/assets/ridge'; OUT.mkdir(parents=True,exist_ok=True)
EDIT=ROOT/'assets/blender/ridge'; EDIT.mkdir(parents=True,exist_ok=True)
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
def mat(name,color,rough=0.8,metal=0):
 m=bpy.data.materials.new(name);m.diffuse_color=(*color,1);m.use_nodes=True;n=m.node_tree.nodes.get('Principled BSDF');n.inputs['Base Color'].default_value=(*color,1);n.inputs['Roughness'].default_value=rough;n.inputs['Metallic'].default_value=metal;return m
bark=mat('Ridge_bark',(0.17,.115,.07));leaf=mat('Ridge_broadleaf',(0.17,.28,.065));rock=mat('Ridge_layered_stone',(.30,.31,.28));timber=mat('Ridge_warm_timber',(.28,.16,.075));metal=mat('Ridge_anthracite_metal',(.08,.095,.10),.6,.25);cream=mat('Ridge_warm_paint',(.76,.71,.59));seat=mat('Ridge_canvas',(.31,.35,.23))
attr=leaf.node_tree.nodes.new('ShaderNodeVertexColor');attr.layer_name='Color';leaf.node_tree.links.new(attr.outputs['Color'],leaf.node_tree.nodes.get('Principled BSDF').inputs['Base Color'])
def mesh(name,verts,faces,material,colors=None):
 me=bpy.data.meshes.new(name);me.from_pydata(verts,[],faces);me.update();o=bpy.data.objects.new(name,me);bpy.context.collection.objects.link(o);o.data.materials.append(material)
 if colors:
  a=me.color_attributes.new(name='Color',type='FLOAT_COLOR',domain='POINT')
  for i,c in enumerate(colors):a.data[i].color=(*c,1)
 return o
def tube(v,f,a,b,r0,r1,sides=7):
 a,b=Vector(a),Vector(b);d=(b-a).normalized();u=d.cross(Vector((0,1,0)))
 if u.length<.01:u=d.cross(Vector((1,0,0)))
 u.normalize();w=d.cross(u).normalized();base=len(v)
 for p,r in [(a,r0),(b,r1)]:
  for j in range(sides):v.append(tuple(p+r*(math.cos(j*math.tau/sides)*u+math.sin(j*math.tau/sides)*w)))
 for j in range(sides):f.append((base+j,base+(j+1)%sides,base+sides+(j+1)%sides,base+sides+j))
 f.append(tuple(base+sides+j for j in range(sides)))
for variant in range(4):
 for lod in ['near','far']:
  rng=random.Random(718+variant);v=[];f=[];lv=[];lf=[];colors=[];height=[15,19,12,17][variant];spread=[5.4,6.4,4.9,5.9][variant];trunk=[(0,0,0),(.13,-.07,height*.34),(-.12,.22,height*.64),(.48,.15,height*.91)]
  for j in range(3):tube(v,f,trunk[j],trunk[j+1],(.27-j*.065)*height/15,(.21-j*.063)*height/15,8 if lod=='near' else 5)
  clusters=[]
  for j in range(14):
   a=j*2.399+variant*.4;r=spread*(.45+.48*rng.random());z=height*(.55+.29*rng.random());end=(math.cos(a)*r,math.sin(a)*r,z);base=(0,0,height*(.33+j*.026));mid=(end[0]*.57,end[1]*.57,z-.5)
   tube(v,f,base,mid,.11,.05,6 if lod=='near' else 4);tube(v,f,mid,end,.05,.017,5 if lod=='near' else 3);clusters.append(end)
  clusters.append((.3,0,height*.9))
  for j,c in enumerate(clusters):
   for k in range(38 if lod=='near' else 10):
    a=rng.random()*math.tau;rr=math.sqrt(rng.random());cx=c[0]+math.cos(a)*rr*2.3;cy=c[1]+math.sin(a)*rr*2.0;cz=c[2]+rng.uniform(-.8,1.4);sz=rng.uniform(.26,.52) if lod=='near' else rng.uniform(.6,1.1);yaw=rng.random()*math.tau;tilt=rng.uniform(-.7,.7);base=len(lv)
    # Organic lobed clusters: non-coplanar pointed leaf fans, no billboard transparency.
    lv.append((cx,cy,cz+.08));col=(.11+rng.random()*.09,.19+rng.random()*.13,.045+rng.random()*.055);colors.append(col)
    for q in range(8):
     angle=q*math.tau/8+yaw;rad=sz*(1 if q%2 else .72);lv.append((cx+math.cos(angle)*rad,cy+math.sin(angle)*rad,cz+math.sin(angle)*tilt*rad));colors.append(col)
    for q in range(8):lf.append((base,base+1+q,base+1+(q+1)%8))
  mesh(f'ridge_tree{variant}_{lod}_bark',v,f,bark);mesh(f'ridge_tree{variant}_{lod}_leaf',lv,lf,leaf,colors)
def box(name,center,size,material):
 bpy.ops.mesh.primitive_cube_add(size=1,location=center);o=bpy.context.object;o.name=name;o.dimensions=size;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o.data.materials.append(material);return o
# Pavilion footprint 9x7 m, open front, metal pitched roof, timber posts, benches.
for x in [-4,4]:
 for y in [-3,3]:box('ridge_pavilion_post',(x,y,1.8),(.22,.22,3.6),timber)
box('ridge_pavilion_back',(0,3,1.8),(8.2,.16,3.5),timber)
for x in [-2.15,2.15]:
 o=box('ridge_pavilion_roof',(x,0,3.95),(4.55,7,.12),metal);o.rotation_euler.y=(-1 if x<0 else 1)*.19
for x in [-2.5,2.5]:
 box('ridge_pavilion_bench',(x,.5,.55),(2.4,.55,.14),timber)
 for dx in [-.9,.9]:box('ridge_pavilion_bench_leg',(x+dx,.5,.27),(.1,.4,.55),metal)
for x in [-7.5,7.5]:box('ridge_gantry_post',(x,0,3.0),(.34,.34,6),metal)
box('ridge_gantry_header',(0,0,6),(15.5,.5,1),timber)
# Painted plank sign board on the driver-facing (-Y) side of the header. The face texture already holds the
# official logo multiplied into the painted grain with 12% clear margin: scripts/build-ridge-gantry-sign.py.
SIGN=ROOT/'assets/source/ridge';sign=json.loads((SIGN/'gantry-sign.json').read_text());bw,bh=sign['boardMetres']
box('ridge_gantry_signboard',(0,-.31,6),(bw,.12,bh),timber)
# Steel hanger straps sit in the clear margin outside the artwork, in front of the painted face.
for x in [-bw*.46,bw*.46]:box('ridge_gantry_sign_strap',(x,-.39,6),(.09,.03,bh+.16),metal)
painted=bpy.data.materials.new('Ridge_gantry_sign_paint');painted.use_nodes=True;nt=painted.node_tree;pb=nt.nodes.get('Principled BSDF');pb.inputs['Metallic'].default_value=0
color=nt.nodes.new('ShaderNodeTexImage');color.image=bpy.data.images.load(str(SIGN/'gantry-sign-color.png'));color.image.pack();nt.links.new(color.outputs['Color'],pb.inputs['Base Color'])
orm=nt.nodes.new('ShaderNodeTexImage');orm.image=bpy.data.images.load(str(SIGN/'gantry-sign-orm.png'));orm.image.colorspace_settings.name='Non-Color';orm.image.pack();split=nt.nodes.new('ShaderNodeSeparateColor');nt.links.new(orm.outputs['Color'],split.inputs['Color']);nt.links.new(split.outputs['Green'],pb.inputs['Roughness'])
face=mesh('ridge_gantry_sign_face',[(-bw/2,-.374,6-bh/2),(bw/2,-.374,6-bh/2),(bw/2,-.374,6+bh/2),(-bw/2,-.374,6+bh/2)],[(0,1,2,3)],painted);uv=face.data.uv_layers.new(name='UVMap')
for loop,coord in zip(uv.data,[(0,0),(1,0),(1,1),(0,1)]):loop.uv=coord
for i in range(3):
 rng=random.Random(350+i);bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=2,radius=1);o=bpy.context.object;o.name=f'ridge_rock{i}'
 for p in o.data.vertices:p.co*=rng.uniform(.8,1.15);p.co.x*=4+i;p.co.y*=2.3;p.co.z=(p.co.z+1)*2.6
 o.data.materials.append(rock)
# Reusable picnic table and organized crate/canvas pit fixture.
box('ridge_table_top',(0,0,.85),(2.5,1.1,.12),timber)
for x in [-.9,.9]:box('ridge_table_leg',(x,0,.42),(.1,.8,.84),metal)
for y in [-.9,.9]:box('ridge_table_seat',(0,y,.47),(2.5,.35,.1),timber)
box('ridge_crate',(0,0,.4),(.9,.7,.8),timber)
box('ridge_crate_lid',(0,0,.84),(1,.8,.08),metal)
for o in bpy.context.scene.objects:
 if o.type=='MESH':o['author']='SlingMods rebuild P10A deterministic district kit';o['generator']='scripts/author-p10a-ridge.py'
bpy.ops.wm.save_as_mainfile(filepath=str(EDIT/'ridge-district-kit.blend'))
bpy.ops.export_scene.gltf(filepath=str(OUT/'ridge-kit.glb'),export_format='GLB',export_apply=True,export_yup=True,export_image_format='JPEG',export_jpeg_quality=90)
(OUT/'kit-manifest.json').write_text(json.dumps({'generator':'scripts/author-p10a-ridge.py','coordinateBasis':'Blender Z up -> glTF Y up','objects':len(bpy.context.scene.objects),'license':'Original project asset; no third-party model or reference photograph reused','treeLOD':'Four branched broadleaf variants, opaque nonplanar lobed foliage; near/far geometry explicitly switched in 100m spatial chunks'},indent=2),encoding='utf-8')
