import{chromium}from'@playwright/test';import fs from'node:fs/promises';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{spawn}from'node:child_process';import{once}from'node:events';
const out=process.env.REAR_DIR;assert.ok(out);await fs.mkdir(out,{recursive:false});const base=process.env.REAR_URL??'http://127.0.0.1:5187',sha=b=>createHash('sha256').update(b).digest('hex'),rig=JSON.parse(await fs.readFile('public/assets/vehicles/slingshot-p04a1-rear-rig.json','utf8'));let build;
if(process.env.VERIFY_BUILD==='1'){build=JSON.parse(await fs.readFile('dist/review-build.json','utf8'));for(const[p,h]of Object.entries(build.inputs))assert.equal(sha(await fs.readFile(p)),h,p)}
const report={runtimeCommit:build?.commit??'uncommitted development candidate',source:{},served:{},images:[],sweep:[],motion:[],modes:[],errors:[],method:'Isolated headless Chromium D3D11; daylight exported runtime. Explicit injected visual poses separate from actual simulation. No desktop/human/physical-controller proof. Rear motion and bay orbit SILENT.'};
for(const p of['public/assets/vehicles/slingshot-p04a1.glb','public/assets/vehicles/slingshot-p04a1-rear-rig.json','src/presentation/rear.ts'])report.source[p]=sha(await fs.readFile(p));
if(build)for(const p of ['dist/review-build.json','dist/index.html',...(await fs.readdir('dist/assets')).filter(f=>/\.(js|css)$/.test(f)).map(f=>'dist/assets/'+f)]){const r=await fetch(base+'/'+p.replace(/^dist\//,''));assert.equal(r.status,200,p);const h=sha(await fs.readFile(p));assert.equal(sha(Buffer.from(await r.arrayBuffer())),h,p);report.served[p]=h}
for(const p of Object.keys(report.source).filter(p=>p.startsWith('public/'))){const r=await fetch(base+'/'+p.slice(7));assert.equal(r.status,200);report.served[p]=sha(Buffer.from(await r.arrayBuffer()));assert.equal(report.served[p],report.source[p])}
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']});report.browser=browser.version();const ctx=await browser.newContext({viewport:{width:1280,height:720}}),page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));
let diagnosticT;
async function ready(scene){await page.goto(base+'/?scene='+scene+'&asset=p04a1&test=1&clock=controlled',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__TWT?.ready,null,{timeout:90000});if(build)assert.ok(build.commit.startsWith((await page.evaluate(()=>window.__TWT.inspect())).commit),'Served workbench build ref differs')}
async function label(text){await page.evaluate(text=>{let e=document.querySelector('#rear-capture-label');if(!e){e=document.createElement('div');e.id='rear-capture-label';e.style.cssText='position:fixed;top:12px;left:16px;right:16px;z-index:100;background:#101821ec;color:white;padding:9px 14px;font:13px system-ui;white-space:pre-line';document.body.append(e)}e.textContent=text},text)}
async function camera(position,target=[0,.58,.8]){await page.evaluate(({position,target})=>window.__TWT.referenceCamera(position,target,38),{position,target})}
async function still(name,description){const bytes=await page.screenshot();await fs.writeFile(out+'/'+name+'.png',bytes);report.images.push({name,description,sha256:sha(bytes),state:await page.evaluate(()=>window.__TWT.inspect())})}
function encoder(name){const p=spawn('ffmpeg',['-hide_banner','-loglevel','error','-f','image2pipe','-framerate','24','-i','pipe:0','-an','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p',out+'/'+name],{windowsHide:true});let error='';p.stderr.on('data',x=>error+=x);return{p,finish:async()=>{const done=once(p,'close');p.stdin.end();assert.equal((await done)[0],0,error)}}}
async function frame(e){const bytes=await page.screenshot({type:'jpeg',quality:90});if(!e.p.stdin.write(bytes))await once(e.p.stdin,'drain');return sha(bytes)}
try{
 await ready('vehicle');await page.evaluate(y=>window.__TWT.rearDiagnosticPose(y,0,false),rig.wheelCenter[1]);
 for(const[name,pos]of[['rear-left',[-3.7,1.2,1.25]],['rear-right',[3.7,1.2,1.25]],['rear-direct',[0,1.15,4.7]],['rear-threequarter',[3.2,1.8,4.5]],['rear-enclosed-low',[2.4,.15,3.8]]]){await camera(pos);await label('P04A1 · EXPORTED DAYLIGHT REST POSE · '+name);await still(name,'Normal opaque enclosed body; fixed physical wheel center')}
 await page.evaluate(()=>window.__TWT.rearOverlay(true));await label('DIAGNOSTIC OVERLAY · blue reserved storage volumes\ncyan wheel/hub · yellow arm pivot · magenta arm end · red upper shock · green lower shock');await still('rear-clearance-diagnostic','Same low camera/rest pose as rear-enclosed-low, labeled attachment/storage overlay; body remains opaque');await page.evaluate(()=>window.__TWT.rearOverlay(false));
 const[lo,hi]=rig.supportedHubY;
 for(let i=0;i<=80;i++){let matrices;for(const spin of[0,Math.PI/2,Math.PI,1.5*Math.PI]){const y=lo+(hi-lo)*i/80,state=await page.evaluate(({y,spin})=>window.__TWT.rearDiagnosticPose(y,spin,false),{y,spin}),r=state.rear;assert.ok(r.wheelCenterError<.001&&r.axleCenterError<.001&&r.armEndpointError<.001&&r.shockEndpointError<.001);if(matrices)assert.deepEqual(r.groups,matrices);matrices=r.groups;report.sweep.push({y,spin,rear:r})}}
 for(const mode of['bay','pad']){await ready(mode);const s=await page.evaluate(()=>window.__TWT.inspect());assert.ok(s.rear);if(mode==='pad')diagnosticT=structuredClone(s.telemetry);report.modes.push({mode,asset:await page.evaluate(()=>window.__TWT.asset),rear:s.rear})}
 await page.goto(base+'/?scene=harbor&test=1&clock=controlled',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__HARBOR?.ready,null,{timeout:90000});const hs=await page.evaluate(()=>window.__HARBOR.inspect());if(build)assert.ok(build.commit.startsWith(hs.commit));assert.equal(hs.asset,report.modes[0].asset);assert.ok(hs.rear.wheelCenterError<.001&&hs.rear.axleCenterError<.001);report.modes.push({mode:'harbor',asset:hs.asset,rear:hs.rear});
 await ready('vehicle');await camera([3.2,1.45,4.5]);const motion=encoder('rear-motion-silent.mp4');let simTick=-1;
 for(let f=0;f<432;f++){const time=f/24;let state,phase;
  if(time<10){if(f===48){diagnosticT.position={x:0,y:.27,z:0};diagnosticT.quaternion={x:0,y:0,z:0,w:1};await page.evaluate(t=>window.__TWT.diagnosticFrame(t),diagnosticT)}phase=time<2?'REST · ordinary authored pose':time<7?'INJECTED VISUAL TRAVEL · chassis raised0.27m to expose droop; no ground contact implied':'INJECTED WHEEL SPIN · raised chassis; suspension does not spin';let y=rig.wheelCenter[1],spin=0;if(time>=2&&time<7){const t=(time-2)/5,knots=[rig.wheelCenter[1],lo,hi,rig.wheelCenter[1]],s=t*3,k=Math.min(2,Math.floor(s)),a=(1-Math.cos((s-k)*Math.PI))/2;y=knots[k]+(knots[k+1]-knots[k])*a}if(time>=7)spin=(time-7)*Math.PI*3;state=await page.evaluate(({y,spin})=>window.__TWT.rearDiagnosticPose(y,spin,false),{y,spin});await camera([3.2,1.45+(time>=2?.27:0),4.5],[0,.58+(time>=2?.27:0),.8]);}
  else{if(f===240){await ready('pad');await page.evaluate(()=>window.__TWT.reset({x:0,z:35,y:.025}));}phase='NORMAL PAD SIMULATION · '+(time<14?'throttle':'braking')+' · fixed diagnostic rear camera';const end=Math.round((time-10)*120);state=await page.evaluate(({from,end})=>{let s;for(let i=from;i<=end;i++){window.__TWT.setDeviceSample({keys:i<24?[]:i<480?['KeyW']:['KeyS'],pads:[],focused:true});s=window.__TWT.normalFrame(i*1000/120,i===end)}return s},{from:simTick+1,end});simTick=end;const p=state.telemetry.position;await camera([p.x+3.2,p.y+1.45,p.z+3.7],[p.x,p.y+.55,p.z+.9]);}
  await label('REAR MOTION · SILENT · '+phase);const h=await frame(motion);report.motion.push({frame:f,time,phase,sha256:h,rear:state.rear,telemetry:time>=10?state.telemetry:null});
 }await motion.finish();
 await ready('bay');const orbit=encoder('rear-bay-orbit-silent.mp4');for(let f=0;f<192;f++){const angle=Math.PI*.55+f/191*Math.PI*.9;await page.evaluate(a=>window.__TWT.reviewOrbit(a),angle);await label('P04A1 · CURRENT BAY ORBIT · SILENT');await frame(orbit)}await orbit.finish();
 assert.deepEqual(report.errors,[]);for(const p of['rear-motion-silent.mp4','rear-bay-orbit-silent.mp4'])report.source[p]=sha(await fs.readFile(out+'/'+p));if(build)for(const[p,h]of Object.entries(build.inputs))assert.equal(sha(await fs.readFile(p)),h,p);await fs.writeFile(out+'/rear-capture.json',JSON.stringify(report,null,2));console.log('Rear capture PASS',report.sweep.length,'poses',report.motion.length,'motion frames');
}finally{await browser.close()}
