import {RaceRoad} from '../src/competition/road';
import type {CourseRoute} from '../src/course/environment';
import type {VehicleTelemetry,VehicleControl} from '../src/simulation';
import type {DeviceSample} from '../src/driving/input';
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
/** Evidence-only virtual player. Produces ordinary controls; never imported by the shipped game. */
export class CrewPlayerAgent {
 private road:RaceRoad;private segment?:number;private lane=2;private launched=false;private completed=false;private lastProgress=0;private passing:number|null=null;private passUntil=0;private time=0;
 constructor(route:CourseRoute){this.road=new RaceRoad(route)}
 control(v:VehicleTelemetry,peers:Record<string,VehicleTelemetry>={},dt=1/60):VehicleControl{
 const p=this.road.project(v.position.x,v.position.z,this.segment);this.segment=p.segment;if(this.launched&&p.progress<this.lastProgress-500)this.completed=true;if(p.progress>20&&p.progress<200)this.launched=true;this.lastProgress=p.progress;
 this.time+=dt;const lateral=(v.position.x-p.x)*-p.dz+(v.position.z-p.z)*p.dx,traffic=Object.entries(peers).filter(([id])=>id!=='player').map(([,o])=>{const dx=o.position.x-v.position.x,dz=o.position.z-v.position.z;return {ahead:dx*p.dx+dz*p.dz,lane:lateral+dx*-p.dz+dz*p.dx,speed:o.velocity.x*p.dx+o.velocity.z*p.dz}}).filter(o=>Math.abs(o.ahead)<65),front=traffic.filter(o=>o.ahead>0&&Math.abs(o.lane-lateral)<2.6).sort((a,b)=>a.ahead-b.ahead)[0];
 let targetLane=!this.completed&&(p.progress<170||p.progress>this.road.route.length-30)?3.65:0;if(this.passing===null&&front&&front.ahead<12+Math.abs(v.speed)*1.2){const lane=[3.65,-3.65].find(l=>Math.abs(l-front.lane)>2.6&&!traffic.some(o=>Math.abs(o.lane-l)<2.6&&o.ahead>-8&&o.ahead<16));if(lane!==undefined){this.passing=lane;this.passUntil=this.time+4}}if(this.passing!==null){targetLane=this.passing;if(this.time>this.passUntil&&!front&&!traffic.some(o=>Math.abs(o.lane)<2.6&&Math.abs(o.ahead)<12))this.passing=null}this.lane+=clamp(targetLane-this.lane,-1.2*dt,1.2*dt);
 const speed=Math.abs(v.speed),target=this.road.sample(p.progress+7+speed*.55),dx=target.x-target.dz*this.lane-v.position.x,dz=target.z+target.dx*this.lane-v.position.z,q=v.quaternion,yaw=Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z)),forward=-Math.sin(yaw)*dx-Math.cos(yaw)*dz,left=-Math.cos(yaw)*dx+Math.sin(yaw)*dz,angle=Math.atan2(left,forward),wheelbase=2.667,maxSteer=Math.min(.53/(1+speed*.037),Math.atan(5.4*wheelbase/Math.max(speed*speed,1))),desired=Math.atan2(2*wheelbase*Math.sin(angle),Math.hypot(dx,dz));
 let targetSpeed=23;for(let d=0;d<=70;d+=5){const a=this.road.sample(p.progress+d-7),b=this.road.sample(p.progress+d+7),curvature=Math.abs(Math.atan2(a.dx*b.dz-a.dz*b.dx,a.dx*b.dx+a.dz*b.dz))/14,corner=Math.sqrt(3.1/Math.max(curvature,.001));targetSpeed=Math.min(targetSpeed,Math.sqrt(corner*corner+2*3.6*Math.max(0,d-7)))}for(const o of traffic){if(o.ahead>0&&(Math.abs(o.lane-lateral)<2.6||Math.abs(o.lane-this.lane)<2.6)){const clearance=o.ahead-4.5;targetSpeed=Math.min(targetSpeed,Math.max(0,o.speed+(clearance-5-Math.abs(v.speed)*.9)*.7));if(clearance<2)targetSpeed=0}}const error=targetSpeed-v.speed;return {throttle:clamp(error*.36+.15,0,1),brake:clamp(-error*.22,0,1),steer:clamp(desired/maxSteer*1.12,-1,1),reverse:false,tractionControl:true};
 }
 sample(v:VehicleTelemetry,peers?:Record<string,VehicleTelemetry>,dt=1/60){return controlSample(this.control(v,peers,dt))}
}
export function controlSample(control:VehicleControl):DeviceSample {const axis=control.steer===0?0:-Math.sign(control.steer)*(.08+.92*Math.abs(control.steer)**(1/1.25)),buttons=Array.from({length:17},()=>({value:0,pressed:false}));buttons[7]={value:control.throttle,pressed:control.throttle>.5};buttons[6]={value:control.brake,pressed:control.brake>.5};return {keys:new Set(),focused:true,pads:[{index:0,id:'P05 explicitly labeled evidence-only virtual player',connected:true,mapping:'standard',axes:[axis,0,0,0],buttons}]}}
