from pathlib import Path
import json,hashlib,datetime,re
b=Path('director-kit/production/evidence/P05');build=json.loads((b/'build-inputs-verified.json').read_text());perf=json.loads((b/'performance-summary.json').read_text());assert len(perf['runs'])==5
testCount=int(re.search(r'tests (\d+)',(b/'tests-verified.log').read_text()).group(1));runtime=build['commit'];runs=perf['runs'];assert all(r['targetMet'] for r in runs);assert all(r['record']==False for r in runs)
for n,h in build['inputs'].items():assert hashlib.sha256(Path(n).read_bytes()).hexdigest()==h,n
proofs={1:['parity.json','tests-verified.log'],2:['tests-verified.log','performance-summary.json'],3:['tests-verified.log','support-check.json'],4:['tests-verified.log','ui-verified/report.json','video-verified/grid.png'],5:['competition-repaired/adversarial-physical.json','tests-verified.log'],6:['competition-repaired/podium-11.json','competition-repaired/field-player-97.json','performance-summary.json'],7:['competition-repaired/adversarial-physical.json','tests-verified.log'],8:['tests-verified.log','competition-repaired/rules-tests.log'],9:['tests-verified.log','competition-repaired/rules-tests.log'],10:['ui-verified/report.json','fresh-verified/fresh-flow.json'],11:['fresh-verified/fresh-flow.json','tests-verified.log'],12:['tests-verified.log','ui-verified/report.json'],13:['tests-verified.log','fresh-verified/fresh-flow.json'],14:['verified-scored-equipped1080/run.json','video-verified/contest.png','reviewer-competition-final.md'],15:['ui-verified/report.json','controller-verified/controller.json','solo-ui-verified/review-functional.json'],16:['audio-verified/audio.json','video-verified/video.json'],17:['performance-summary.json','preserved-foundation.json'],18:['performance-summary.json','performance-review.md'],19:['fresh-verified/fresh-flow.json','video-verified/run.json'],20:['reviewer-competition-final.md','reviewer-career-final.md','final-review.md']}
source=json.loads(Path('director-kit/director-addenda/review-09/ACCEPTANCE-CASES.json').read_text());out=[]
for i,c in enumerate(source['cases'],1):
 out.append({**c,'status':'locally_verified','evidence':proofs[i],'limits':{14:'Material/rig identity and resource isolation verified; final art approval held.',15:'Keyboard and virtual standard-controller only; no physical controller or foreground responsiveness claim.',16:'Actual signal/mixer/lifecycle tests. Continuous recording SILENT; no human audition.',18:'Only named isolated RTX4080 Chromium/D3D11 runs; OS/driver shader caches not cleared, broader hardware unavailable.',20:'Separate source reviewers plus lead runtime/media review; no G3/G4 or human-fun approval.'}.get(i,'See evidence method labels; deterministic tests are not native-RAF proof.')})
(b/'acceptance-results.json').write_text(json.dumps({'runtimeCommit':runtime,'scope':'P05 bounded local engineering/functional acceptance; director/human art/audio/fun and G3/G4 remain held. Executed local results, not edits to director requirements.','cases':out},indent=2))
lines=['# P05 native-RAF performance review','',perf['method'],'','| Run | Actual buffer | Valid races | Racing p95 / p99 / max ms | Programs | Target |','|---|---|---:|---|---|---|']
for r in runs:
 t=r['racingIntervals'];lines.append(f"| {r['name']} | {r['buffer']} | {len(r['results'])} | {t['p95']:.1f} / {t['p99']:.1f} / {t['max']:.1f} | {r['programCounts']} | {'met' if r['targetMet'] else 'missed'} |")
lines+=['','All raw ready/countdown/racing/finished rows remain in each run.json. Explicit preparation precedes event time; load includes preparation. One world step equals one session tick; four participants retained. Audio activated with real shared graphs; host output muted through Chromium flags. Recording is separate.','',f"Racing intervals: {sum(r['racingIntervals']['count'] for r in runs):,}. Racing intervals over100ms: {sum(r['racingIntervals']['over100'] for r in runs)}. All-phase intervals over100ms: {sum(r['allIntervals']['over100'] for r in runs)}.",'','See performance-summary.json for CPU control/physics/submission/collector timings, resource ranges, first/retry results and every >100ms row. No GPU timer or memory-byte claim. No lowered resolution labeled1080p. Partial earlier scored-equipped1080 was interrupted for a separately confirmed session-handoff repair, is not scored and remains local.']
(b/'performance-review.md').write_text('\n'.join(lines))
statePath=Path('director-kit/production/state.json');state=json.loads(statePath.read_text());state['as_of']=datetime.datetime.now(datetime.timezone.utc).isoformat();state['commit']=runtime;state['current_packet']='P05 First Night at the Harbor: integrated first chapter, local verification complete, awaiting Astra';state['next_action']='STOP after Astra-Review-10.zip. Await Astra; no unsupported G3/G4 advancement, new content, spending or deployment.'
state['P05']={'status':'locally_complete_awaiting_Astra','runtime_commit':runtime,'milestones':{k:'locally_complete'for k in ['I0','I1','I2','I3','I4','I5']},'acceptance':'production/evidence/P05/acceptance-results.json','review':'production/evidence/P05/final-review.md','performance':'production/evidence/P05/performance-summary.json','held':['G3','G4','final art and aural approval','human fun/playtest','physical-controller/foreground responsiveness','other hardware/mobile','full campaign and release']}
assert state['gates']['G3']['status']=='pending' and state['gates']['G4']['status']=='pending';statePath.write_text(json.dumps(state,indent=2)+'\n')
excerpt={k:state[k]for k in ['project','as_of','branch','commit','current_gate','current_packet','next_action','gates','P05']};excerpt['is_excerpt']=True;excerpt['source']='director-kit/production/state.json; full historical ledger retained in actual repository.';(b/'STATE-EXCERPT.json').write_text(json.dumps(excerpt,indent=2))
p=b/'milestones.md';s=p.read_text();s+='\n\nFinal I5 complete at '+runtime+'. '+str(testCount)+' source tests, exact4200-row parity, fresh/existing career flows, virtual controls, actual mixer signal/lifecycle and solo regressions pass. Five clean runs cover seven full-field races, plus separate continuous video. Local result awaits Astra; G3/G4 remain pending.\n';p.write_text(s)
print('Prepared local acceptance and ledger excerpt for',runtime)
