import fs from 'node:fs/promises';import{createHash}from'node:crypto';import{chromium}from'@playwright/test';
const dir=process.env.EVIDENCE_DIR;if(!dir)throw Error('Fresh EVIDENCE_DIR required');await fs.mkdir(dir,{recursive:false});
const original=await fs.readFile('public/assets/showcase/kit.glb'),n=original.readUInt32LE(12),g=JSON.parse(original.subarray(20,20+n).toString()),oldFilters=g.samplers.map(s=>s.minFilter??9987);g.samplers.forEach(s=>s.minFilter=9729);
let text=Buffer.from(JSON.stringify(g));const padded=Buffer.alloc(Math.ceil(text.length/4)*4,32);text.copy(padded);const tail=original.subarray(20+n),head=Buffer.alloc(20);original.subarray(0,12).copy(head);head.writeUInt32LE(20+padded.length+tail.length,8);head.writeUInt32LE(padded.length,12);head.writeUInt32LE(0x4e4f534a,16);const noMips=Buffer.concat([head,padded,tail]);
const hash=b=>createHash('sha256').update(b).digest('hex'),browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']}),rows=[];
try{for(const [name,bytes]of(process.env.PRODUCTION_ONLY==='1'?[['production-after',original]]:[['before',original],['no-mips-diagnostic',noMips]])){
 const context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/assets/showcase/kit.glb',r=>r.fulfill({contentType:'model/gltf-binary',body:bytes}));await page.goto('http://127.0.0.1:5187/?scene=bay&test=1&captureBuffer=1');await page.waitForFunction(()=>window.__TWT?.ready,null,{timeout:120000});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 await page.screenshot({path:dir+'/'+name+'.png'});rows.push({name,kitSha256:hash(bytes),inspection:await page.evaluate(()=>window.__TWT.inspect()),errors});await context.close();
 }await fs.writeFile(dir+'/material-isolation.json',JSON.stringify({method:'Actual isolated runtime bay. In diagnostic response ONLY glTF minification samplers changed to LINEAR(no mips), preserving BIN bytes, material values, geometry, UV, camera, lights and UI. Not a production fix or performance test.',sourceKitSHA256:hash(original),binBytesExact:original.subarray(20+n).equals(noMips.subarray(20+padded.length)),oldFilters,diagnosticFilter:9729,browser:browser.version(),rows},null,2));
}finally{await browser.close()}
