import {streetSetup} from '../src/career/suspension';import {HANDLING_PROFILES} from '../src/simulation/profile';
import fs from 'node:fs';import path from 'node:path';import {gzipSync} from 'node:zlib';
import {Simulation,steeringLimit,type HandlingProfileId} from '../src/simulation';import {InputResolver,type DeviceSample} from '../src/driving/input';import type {EnvironmentDefinition} from '../src/course/environment';
const dir=process.env.EVIDENCE_DIR??'director-kit/production/evidence/P08B/driving';fs.mkdirSync(dir,{recursive:true});
const asphalt:EnvironmentDefinition={ground:{center:[0,-.15,0],size:[3000,.3,3000]},obstacles:[],ramps:[],surfaceAt:(x)=>({id:Math.abs(x)>55?'grass':'asphalt',mu:Math.abs(x)>55?.52:1.05,rolling:Math.abs(x)>55?.065:.014})};
function sample(throttle=0,brake=0,steer=0):DeviceSample {const buttons=Array.from({length:17},()=>({value:0}));buttons[7].value=throttle;buttons[6].value=brake;return {keys:new Set(),focused:true,pads:[{index:0,id:'P08B diagnostic ordinary analog device values',mapping:'standard',connected:true,axes:[steer===0?0:-Math.sign(steer)*(.08+.92*Math.abs(steer)**(1/1.25)),0],buttons}]}}
const summary:any={method:'Fixed-step physics diagnostic using production InputResolver and supported controller samples. Not RAF performance or human driving proof.',profiles:{},tuning:HANDLING_PROFILES,build:process.env.BUILD??'stock'};
for(const id of ['legacy-p08a','slingmods-sport-v1']as HandlingProfileId[]){const cases:any={};for(const scenario of ['launch','brake','low-left','low-right','medium-left','medium-right','sweeper-left','sweeper-right','brake-turn-left','brake-turn-right','grass','bump','wall-reverse']){
 const environment=scenario==='wall-reverse'?{...asphalt,obstacles:[{id:'test-wall',center:[0,.5,10],size:[20,1,.5]}]}:scenario==='bump'?{...asphalt,obstacles:[{id:'test-bump',center:[0,.04,-20],size:[4,.08,1.2]}]}:asphalt;
 const sim=await Simulation.create(environment,id);if(process.env.BUILD==='street'||process.env.BUILD==='removed')sim.configureSuspension(streetSetup());if(process.env.BUILD==='modified')sim.configureSuspension({...streetSetup(),frontCompression:9,frontRebound:10,rearCompression:7,rearRebound:8,rideHeightMm:10});if(process.env.BUILD==='removed')sim.configureSuspension(null);sim.reset({x:scenario==='grass'?60:0,y:.025,z:scenario==='wall-reverse'?12:35});const input=new InputResolver(id);let now=0;input.poll(now,sample(),0);const rows:any[]=[];let to60:number|null=null,maxMph=0,brakeStart:any=null,stop:any=null;
 const duration=scenario==='launch'?22:scenario==='wall-reverse'?10:14;
 for(let i=0;i<duration*60;i++){const t=i/60,before=sim.telemetry();let device=sample();if(scenario==='launch')device=sample(1);else if(scenario==='wall-reverse')device=t<2?sample(.5):t<3?sample(0,1):t<3.6?sample():sample(0,.7);else if(scenario==='brake'){device=t<7?sample(1):sample(0,1);if(t>=7&&!brakeStart)brakeStart={time:t,z:before.position.z,speed:before.speed};if(brakeStart&&!stop&&Math.abs(before.speed)<.2)stop={time:t,z:before.position.z,distance:Math.abs(before.position.z-brakeStart.z)}}else{const sign=scenario.includes('right')?-1:1;const entry=scenario.startsWith('low')?2:scenario.startsWith('medium')?4:6;device=t<entry?sample(scenario.startsWith('low')?.25:.8):sample(scenario.startsWith('brake-turn')?0:.22,scenario.startsWith('brake-turn')?.65:0,scenario==='grass'?.2:scenario==='bump'?0:sign*(scenario.startsWith('sweeper')?.55:1))}
 const output=input.poll(now+=1000/60,device,before.speed);sim.step(output.control);const tele=sim.telemetry(),mph=tele.speed*2.2369362921;maxMph=Math.max(maxMph,mph);if(to60===null&&mph>=60)to60=(i+1)/60;rows.push({input:output.control,requestedSteering:output.control.steer*steeringLimit(before.speed,id),telemetry:tele});}
 const final=sim.telemetry();cases[scenario]={to60Seconds:to60,maxMph,braking:stop?{...stop,start:brakeStart}:null,finalPosition:final.position,finalYaw:Math.atan2(2*(final.quaternion.w*final.quaternion.y+final.quaternion.x*final.quaternion.z),1-2*(final.quaternion.y**2+final.quaternion.z**2)),maxRoll:Math.max(...rows.map(r=>Math.abs(Math.atan2(2*(r.telemetry.quaternion.w*r.telemetry.quaternion.z+r.telemetry.quaternion.x*r.telemetry.quaternion.y),1-2*(r.telemetry.quaternion.x**2+r.telemetry.quaternion.z**2))))),maxSlip:Math.max(...rows.flatMap(r=>r.telemetry.wheels.map((w:any)=>Math.abs(w.slipAngle)))),allFinite:rows.every(r=>Number.isFinite(r.telemetry.speed)&&Object.values(r.telemetry.position).every(Number.isFinite)),threeContactsFraction:rows.filter(r=>r.telemetry.wheels.every((w:any)=>w.contact)).length/rows.length};fs.writeFileSync(path.join(dir,id+'-'+scenario+'.json.gz'),gzipSync(JSON.stringify(rows)));sim.dispose();}
 summary.profiles[id]=cases;
}fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
