import fs from 'node:fs';import path from 'node:path';import {gzipSync} from 'node:zlib';import {Simulation,steeringRequest,steeringLimit,type HandlingProfileId,type VehicleControl} from '../src/simulation';import {InputResolver} from '../src/driving/input';import {toDevice} from './p08b-driving-evidence-agent';import {MOTION_PAD,clamp,yaw} from './p09c-motion-protocol';
const dir=process.env.EVIDENCE_DIR??'director-kit/production/evidence/P09C/transitions-01';fs.mkdirSync(dir,{recursive:true});const reports:any[]=[];
for(const profile of(process.env.PROFILES??'slingmods-sport-v1,slingmods-sport-v2,slingmods-sport-v3').split(',') as HandlingProfileId[])for(const scenario of['graduated-35','sweep-50','cross50-held','cross50-moving','coast-65','partial-brake-65','lane-90','lane-110','keyboard-tap-50','keyboard-hold-50','keyboard-hold-110'])for(const direction of[-1,1]){
 const sim=await Simulation.create(MOTION_PAD,profile),resolver=new InputResolver(profile),keyboard=new InputResolver(profile);sim.reset({x:0,y:.025,z:35});sim.enableDiagnostics();resolver.poll(0,{...toDevice(),keys:new Set()});keyboard.poll(0,{keys:new Set(),pads:[],focused:true});let entry:number|null=null;const initial=scenario.includes('35')||scenario.startsWith('cross')?35:scenario.includes('110')?110:scenario.includes('90')?90:scenario.includes('65')?65:50;const rows:any[]=[];
 for(let tick=0;tick<45*60;tick++){const previous=sim.telemetry();if(entry===null&&previous.speed>=initial*.44704-.05)entry=previous.time;const t=entry===null?-1:previous.time-entry;if(t>=14)break;let steer=0,brake=0,target=initial*.44704,throttle=1;const keys=new Set<string>();
  if(t>=0){
   if(scenario.startsWith('cross')){target=(t<7?70:35)*.44704;brake=t>=7&&previous.speed>target+.5?.35:0;steer=scenario.endsWith('held')?.25:.4*Math.sin(t*.7)}
   else if(scenario.startsWith('graduated'))steer=t<2?.15:t<4?.3:t<6?.45:t<8?.6:t<10?-.3:0;
   else if(scenario.startsWith('sweep')){target=(35+35*(.5-.5*Math.cos(t*.5)))*.44704;steer=.38*Math.sin(t*.5);brake=target<previous.speed-1?.2:0}
   else if(scenario.startsWith('lane'))steer=t<4?.32*Math.sin(t*Math.PI/2):0;
   else if(scenario.startsWith('keyboard'))steer=scenario.includes('tap')?(t<6&&t%1<.18?1:0):(t<2?1:t<4?-1:0);
   else {steer=t<8?.6:0;brake=scenario.startsWith('partial')&&t>=3&&t<6?.35:0}
   throttle=clamp(.22+(target-previous.speed)*.6,0,1);if(brake||scenario.startsWith('coast')&&t>=3&&t<6)throttle=0;
  }
  const desired:VehicleControl={throttle,brake,steer:steer*direction,reverse:false,tractionControl:true};let source='graduated standard-gamepad fixture';const device=toDevice(desired);
  if(scenario.startsWith('keyboard')&&t>=0){source='keyboard left/right event fixture with analog speed-hold pedal fixture';if(desired.steer>0)keys.add('KeyA');if(desired.steer<0)keys.add('KeyD');}
  // Steering keyboard checks use resolver with keyboard steering alone; pedal
  // speed maintenance is the same evidence-only analog control as other cases.
  let c=resolver.poll((tick+1)*1000/60,{...device,keys:new Set(device.keys)},previous.speed).control;
  if(scenario.startsWith('keyboard')&&t>=0){c={...c,steer:keyboard.poll((tick+1)*1000/60,{keys,pads:[],focused:true},previous.speed).control.steer}}
  sim.step(c);const current=sim.telemetry();rows.push({elapsed:t,source,input:c,targetMph:target/.44704,commandBeforeSpeed:c.steer*.6,commandBeforeBrake:c.steer*steeringLimit(previous.speed,profile),requested:steeringRequest(c.steer,previous.speed,profile,c.brake),visualHandWheel:current.steer*10,intervention:'none',telemetry:current,diagnostics:sim.diagnostics()});
 }
 const active=rows.filter(r=>r.elapsed>=0),qUp=(q:any)=>1-2*(q.x*q.x+q.z*q.z),report={profile,scenario,direction,entrySeconds:entry,samples:active.length,upMin:Math.min(...active.map(r=>qUp(r.telemetry.quaternion))),allContactFraction:active.filter(r=>r.telemetry.wheels.every((w:any)=>w.contact)).length/active.length,maxRoll:Math.max(...active.map(r=>Math.abs(Math.atan2(2*(r.telemetry.quaternion.w*r.telemetry.quaternion.z+r.telemetry.quaternion.x*r.telemetry.quaternion.y),1-2*(r.telemetry.quaternion.x**2+r.telemetry.quaternion.z**2))))),finalYaw:yaw(sim.telemetry().quaternion),maxAbsYawRate:Math.max(...active.map(r=>Math.abs(r.telemetry.angularVelocity.y))),forceBoundViolations:active.flatMap(r=>r.telemetry.wheels).filter(w=>Math.hypot(w.longitudinalForce,w.lateralForce)>w.gripLimit+1e-7).length,minSpeedMph:Math.min(...active.map(r=>r.telemetry.speed/.44704)),maxSpeedMph:Math.max(...active.map(r=>r.telemetry.speed/.44704))};reports.push(report);fs.writeFileSync(path.join(dir,`${profile}-${scenario}-${direction}.json.gz`),gzipSync(JSON.stringify(rows)));console.log(JSON.stringify(report));sim.dispose();
}fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify({method:'Matched 60Hz integrated control-only pad cases; exact normalized device inputs recorded, keyboard steering via real resolver, speed-hold test pedal driver. No pose/velocity writes after initial reset, no runtime assistance. Not native performance.',reports},null,2));
