import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {gzipSync} from 'node:zlib';import {Simulation} from '../src/simulation';import {createCourseEnvironment} from '../src/course/environment';import {EXPRESS_ROUTE} from '../src/express/route';const harbor=JSON.parse(fs.readFileSync('public/assets/harbor/route.json','utf8'));
const commit='63da7a0202a0216cea5e9a70bd55f63f5283cba4',dir=process.env.EVIDENCE_DIR,index='src/simulation/.p10a-historical-index.ts',profile='src/simulation/.p10a-historical-profile.ts';if(!dir)throw Error('Fresh EVIDENCE_DIR required; reviewed historical output and goldens are immutable');fs.mkdirSync(dir,{recursive:false});
if(fs.existsSync(index)||fs.existsSync(profile))throw Error('Historical temporary module already exists');
const oldIndex=execFileSync('git',['show',commit+':src/simulation/index.ts'],{encoding:'utf8'}),oldProfile=execFileSync('git',['show',commit+':src/simulation/profile.ts'],{encoding:'utf8'});
fs.writeFileSync(dir+'/index-baseline.txt',oldIndex);fs.writeFileSync(dir+'/profile-baseline.txt',oldProfile);
try{fs.writeFileSync(index,oldIndex.replaceAll("'./profile'","'./.p10a-historical-profile'"));fs.writeFileSync(profile,oldProfile);const {Simulation:Baseline}=await import('../src/simulation/.p10a-historical-index');const cases=[];
for(const scenario of['harbor','express']){const baseline=await Baseline.create(createCourseEnvironment(scenario==='harbor'?harbor:EXPRESS_ROUTE),'slingmods-sport-v3'),current=await Simulation.create(createCourseEnvironment(scenario==='harbor'?harbor:EXPRESS_ROUTE),'slingmods-sport-v3'),oldHash=createHash('sha256'),newHash=createHash('sha256'),rows=[];let mismatchTicks=0;for(let i=0;i<1800;i++){const t=i/60,c=scenario==='express'?{throttle:t<21?1:0,brake:t>=21?1:0,steer:0,reverse:false}:{throttle:t<10?.7:t<16?.2:0,brake:t>=18?.7:0,steer:t>5&&t<16?Math.sin(t)*.4:0,reverse:t>24};baseline.step(c);current.step(c);const a=baseline.telemetry(),b=current.telemetry(),sa=JSON.stringify(a)+'\n',sb=JSON.stringify(b)+'\n';oldHash.update(sa);newHash.update(sb);if(sa!==sb)mismatchTicks++;rows.push({input:c,baseline:a,current:b})}cases.push({scenario,profile:'slingmods-sport-v3',ticks:1800,mismatchTicks,telemetrySha256:oldHash.digest('hex'),currentSha256:newHash.digest('hex')});fs.writeFileSync(dir+'/'+scenario+'.json.gz',gzipSync(JSON.stringify(rows)));baseline.dispose();current.dispose()}
const report={baselineCommit:commit,baselineSource:'git show exact index.ts and profile.ts; unchanged drivetrain/suspension/contact-layout imports from checkout',cases,pass:cases.every(c=>c.mismatchTicks===0&&c.telemetrySha256===c.currentSha256)};fs.writeFileSync(dir+'/verification.json',JSON.stringify(report,null,2));console.log(report);if(!report.pass)process.exitCode=1;
}finally{fs.unlinkSync(index);fs.unlinkSync(profile)}
