import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import RAPIER from '@dimforge/rapier3d-compat';
import {RIDGE_ROUTE as route,RIDGE_STATIONS,RIDGE_SUPPORT_MESHES,RIDGE_SURFACES,ridgeCrossHeight} from '../src/ridge/route';import {sampleRoad,projectRoad,createCourseEnvironment} from '../src/course/environment';import {RaceWorld} from '../src/simulation';import {createCrewGrid} from '../src/competition/grid';
const dir=process.env.EVIDENCE_DIR;if(!dir)throw Error('Fresh EVIDENCE_DIR required');fs.mkdirSync(dir,{recursive:false});
const bounds=(vertices:number[])=>{const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<vertices.length;i++)min[i%3]=Math.min(min[i%3],vertices[i]),max[i%3]=Math.max(max[i%3],vertices[i]);return{min,max}};
const segments=route.centerline.map((a,i)=>{const b=route.centerline[(i+1)%route.centerline.length],prior=route.centerline[(i+route.centerline.length-1)%route.centerline.length],dx=b[0]-a[0],dz=b[1]-a[1],dy=route.elevations![(i+1)%route.centerline.length]-route.elevations![i],planar=Math.hypot(dx,dz),priorLength=Math.hypot(a[0]-prior[0],a[1]-prior[1]),turn=Math.atan2((a[0]-prior[0])*dz-(a[1]-prior[1])*dx,(a[0]-prior[0])*dx+(a[1]-prior[1])*dz),curvature=turn/((planar+priorLength)/2);return{segment:i,station:RIDGE_STATIONS[i],start:[a[0],route.elevations![i],a[1]],planar,length3D:Math.hypot(planar,dy),grade:dy/planar,curvature,radius:Math.abs(curvature)>1e-12?1/Math.abs(curvature):null}});
const meshes=RIDGE_SUPPORT_MESHES.map((mesh,index)=>{let minPlanArea=Infinity,minSurfaceArea=Infinity,maxSurfaceArea=0,downward=0;for(let i=0;i<mesh.indices.length;i+=3){const [a,b,c]=mesh.indices.slice(i,i+3).map(k=>mesh.vertices.slice(k*3,k*3+3)),u=b.map((x,j)=>x-a[j]),v=c.map((x,j)=>x-a[j]),normal=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],area=Math.hypot(...normal)/2;minPlanArea=Math.min(minPlanArea,normal[1]/2);minSurfaceArea=Math.min(minSurfaceArea,area);maxSurfaceArea=Math.max(maxSurfaceArea,area);downward+=Number(normal[1]<=0)}return{index,vertices:mesh.vertices.length/3,triangles:mesh.indices.length/3,bounds:bounds(mesh.vertices),minPlanArea,minSurfaceArea,maxSurfaceArea,downward,sha256:createHash('sha256').update(JSON.stringify(mesh)).digest('hex')}});
const world=await RaceWorld.create(createCourseEnvironment(route),'slingmods-sport-v3');world.world.step();
const ray=(x:number,z:number,y:number)=>{const hit=world.world.castRayAndGetNormal(new RAPIER.Ray({x,y:y+10,z},{x:0,y:-1,z:0}),20,true);return hit?{height:y+10-hit.timeOfImpact,normal:{...hit.normal}}:null};
const crosssections=[];for(let d=0;d<route.length;d+=10){const p=sampleRoad(route,d);for(const offset of[-8.9,-6,-3,0,3,6,8.9]){const x=p.x-p.dz*offset,z=p.z+p.dx*offset,expected=ridgeCrossHeight(d,offset),hit=ray(x,z,p.y!);crosssections.push({station:d,offset,x,z,expected,hit,error:hit?hit.height-expected:null})}}
const gates=route.checkpoints.map(g=>{const p=sampleRoad(route,g.distance),hit=ray(g.x,g.z,g.y!);return{id:g.id,station:g.distance,position:[g.x,g.y,g.z],halfWidth:g.halfWidth,sampleError:g.y!-p.y!,hit,physicalError:hit?hit.height-g.y!:null}});
const grids=Object.entries(createCrewGrid(route)).map(([id,pose])=>{const p=projectRoad(route,pose.x,pose.z),hit=ray(pose.x,pose.z,pose.y);return{id,pose,projection:p,hit,originClearance:hit?pose.y-hit.height:null}});
const widths=RIDGE_STATIONS.map((station,i)=>{const vertices=RIDGE_SURFACES.road.vertices,halfCount=(route.centerline.length+1)*2,li=i*6,ri=(halfCount+i*2+1)*3;return{station,pavedPlanWidth:Math.hypot(vertices[ri]-vertices[li],vertices[ri+2]-vertices[li+2]),outerSupportPlanWidth:Math.hypot(RIDGE_SURFACES.terrain[5].vertices[i*6+3]-RIDGE_SURFACES.terrain[0].vertices[i*6],RIDGE_SURFACES.terrain[5].vertices[i*6+5]-RIDGE_SURFACES.terrain[0].vertices[i*6+2])}});
const planeAbsent=world.world.castRay(new RAPIER.Ray({x:-600,y:200,z:0},{x:0,y:-1,z:0}),500,true)===null;world.dispose();
const maxCrossError=Math.max(...crosssections.map(r=>Math.abs(r.error??Infinity))),maxCenterError=Math.max(...crosssections.filter(r=>r.offset===0).map(r=>Math.abs(r.error??Infinity)));const report={source:'Derived from current authoritative arrays and actual Rapier queries, not copied design constants',stationConvention:'Planar metres, with separately measured 3D arc length',planarLength:segments.reduce((n,s)=>n+s.planar,0),length3D:segments.reduce((n,s)=>n+s.length3D,0),elevationMin:Math.min(...route.elevations!),elevationMax:Math.max(...route.elevations!),maxGrade:Math.max(...segments.map(s=>Math.abs(s.grade))),distanceAbove7Percent:segments.filter(s=>Math.abs(s.grade)>.07).reduce((n,s)=>n+s.planar,0),minRadius:Math.min(...segments.flatMap(s=>s.radius===null?[]:[s.radius])),centerlineBounds:bounds(route.centerline.flatMap((p,i)=>[p[0],route.elevations![i],p[1]])),supportBounds:bounds(RIDGE_SUPPORT_MESHES.flatMap(m=>m.vertices)),railBounds:bounds(route.colliders.flatMap(b=>{const values:number[]=[],pitch=b.pitch??0,yaw=b.yaw??0;for(const x of[-b.size[0]/2,b.size[0]/2])for(const y of[-b.size[1]/2,b.size[1]/2])for(const z of[-b.size[2]/2,b.size[2]/2]){const py=y*Math.cos(pitch)-z*Math.sin(pitch),pz=y*Math.sin(pitch)+z*Math.cos(pitch);values.push(b.center[0]+x*Math.cos(yaw)+pz*Math.sin(yaw),b.center[1]+py,b.center[2]-x*Math.sin(yaw)+pz*Math.cos(yaw))}return values})),railBoundsNote:'Exact world-axis bounds from all eight pitched/yawed corners of every authored collider box' ,meshes,maxCrossError,maxCenterError,planeAbsent,segments,crosssections,gates,grids,widths};fs.writeFileSync(dir+'/measurements.json',JSON.stringify(report,null,2));assert.ok(planeAbsent);assert.ok(meshes.every(m=>m.downward===0&&m.minSurfaceArea>0));assert.ok(maxCenterError<.003);assert.ok(maxCrossError<.08);assert.ok(gates.every(g=>g.hit&&Math.abs(g.sampleError)<1e-9&&Math.abs(g.physicalError!)<.003));assert.ok(grids.every(g=>g.hit&&g.originClearance!>0&&g.originClearance!<.04));assert.ok(widths.every(w=>Math.abs(w.pavedPlanWidth-12)<1e-8));fs.writeFileSync(dir+'/verification.json',JSON.stringify({pass:true,planarLength:report.planarLength,length3D:report.length3D,maxGrade:report.maxGrade,elevationRange:report.elevationMax-report.elevationMin,minRadius:report.minRadius,maxCrossError,maxCenterError,crosssections:crosssections.length,gateCount:gates.length,gridCount:grids.length,planeAbsent},null,2));console.log(fs.readFileSync(dir+'/verification.json','utf-8'));
