import fs from 'node:fs';import {gzipSync} from 'node:zlib';import assert from 'node:assert/strict';
import {RaceWorld,Simulation} from '../src/simulation';import {RIDGE_ROUTE as route,RIDGE_DESIGN,createRidgeEnvironment} from '../src/ridge/route';import {sampleRoad,projectRoad} from '../src/course/environment';import {createCrewGrid,CrewRace,RivalController} from '../src/competition';import {freeRecoveryPose,recoveryReason} from '../src/driving/recovery';
const dir=process.env.EVIDENCE_DIR;if(!dir)throw Error('Fresh EVIDENCE_DIR required');fs.mkdirSync(dir,{recursive:false});const summaries:any[]=[];
const roadPose=(station:number)=>{const p=sampleRoad(route,station);return{x:p.x,y:p.y!+.025,z:p.z,yaw:Math.atan2(-p.dx,-p.dz),pitch:Math.atan(p.dy!)}};
for(const [name,station,seconds]of[['ascent',350,20],['crest',1420,20],['descent-bends',2230,25]]as const){const sim=await Simulation.create(createRidgeEnvironment(),'slingmods-sport-v3');sim.reset(roadPose(station));sim.enableDiagnostics();const driver=new RivalController(route,'player',11,'slingmods-sport-v3'),rows=[];for(let i=0;i<seconds*60;i++){const old=sim.telemetry(),input=i<60?{throttle:0,brake:1,steer:0,reverse:false}:driver.control(old,{player:old});sim.step(input);rows.push({input,t:sim.telemetry(),forces:sim.diagnostics()})}const settled=rows.slice(90),contacts=settled.filter(r=>r.t.wheels.every(w=>w.contact)).length/settled.length,minUp=Math.min(...settled.map(r=>1-2*(r.t.quaternion.x**2+r.t.quaternion.z**2))),maxRoadError=Math.max(...settled.map(r=>projectRoad(route,r.t.position.x,r.t.position.z).distance));const report={name,contacts,minUp,maxRoadError,startY:rows[0].t.position.y,endY:rows.at(-1)!.t.position.y,pass:contacts>.98&&minUp>.9&&maxRoadError<5.8};summaries.push(report);fs.writeFileSync(dir+'/'+name+'.json.gz',gzipSync(JSON.stringify(rows)));console.log(report);sim.dispose()}
// Full actual four-car event. Controls only; shared tire forces, real ordered gates.
const world=await RaceWorld.create(createRidgeEnvironment(),'slingmods-sport-v3'),ids=['maya','jett','nico','player'],grid=createCrewGrid(route,ids);for(const id of ids)world.addVehicle(id,grid[id]);world.initialize();const race=new CrewRace(route,ids,'player',false,{eventId:'p10a-road-proof',laps:1,handlingProfileId:'slingmods-sport-v3'}),drivers=Object.fromEntries(ids.map(id=>[id,new RivalController(route,id,11,'slingmods-sport-v3')]));race.restart('p10a-road-proof');const rows=[];for(let i=0;i<300*60&&!race.snapshot().allFinished;i++){const before=world.telemetry(),inputs=Object.fromEntries(ids.map(id=>[id,race.control(id,drivers[id].control(before[id],before))]));world.step(inputs);const after=world.telemetry();race.tick(before,after,1/60);rows.push({inputs,field:after,race:race.snapshot()});if(i%3600===0)console.log('race',i/60,race.snapshot().standings.map(v=>[v.id,Math.round(v.progress),v.status]))}const result=race.snapshot();summaries.push({name:'four-car-real-lap',result,pass:result.allFinished&&result.standings.every(v=>v.status==='finished')});fs.writeFileSync(dir+'/four-car-lap.json.gz',gzipSync(JSON.stringify(rows)));world.dispose();
const recovery=[];for(const station of[500,1600,2200]){const sim=await Simulation.create(createRidgeEnvironment(),'slingmods-sport-v3');sim.reset({...roadPose(station),y:-20});const t=sim.telemetry(),reason=recoveryReason(t,route),pose=freeRecoveryPose(route,t);sim.reset(pose);const trace=[];for(let i=0;i<180;i++){sim.step({throttle:0,brake:1,steer:0,reverse:false});trace.push(sim.telemetry())}const last=trace.at(-1)!;recovery.push({station,reason,pose,last,pass:last.wheels.every(w=>w.contact)&&Math.abs(last.position.y-pose.y)<.2});fs.writeFileSync(dir+'/recovery-'+station+'.json.gz',gzipSync(JSON.stringify(trace)));sim.dispose()}summaries.push({name:'elevated-recovery',cases:recovery,pass:recovery.every(v=>v.pass)});
fs.writeFileSync(dir+'/summary.json',JSON.stringify({design:RIDGE_DESIGN,summaries,pass:summaries.every(v=>v.pass)},null,2));assert.ok(summaries.every(v=>v.pass),'Physical road proof failed; retained full evidence');
