import {chromium} from '@playwright/test';import {build} from 'vite';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const dir=process.env.EVIDENCE_DIR,fixture=process.env.FIXTURE,origin=process.env.BASE_URL||'http://127.0.0.1:5195';if(!dir||!fixture)throw Error('Fresh EVIDENCE_DIR and earned FIXTURE required');await fs.mkdir(dir,{recursive:false});const width=Number(process.env.WIDTH||1920),attempts=Number(process.env.RACES||2),equipped=process.env.SUSPENSION!=='stock',duel=process.env.EVENT==='duel';
const bundle=await build({configFile:false,logLevel:'silent',publicDir:false,build:{write:false,minify:false,lib:{entry:path.resolve('scripts/crew-evidence-agent.ts'),name:'CrewEvidence',formats:['iife']}}}),source=(Array.isArray(bundle)?bundle[0]:bundle).output.find(x=>x.type==='chunk').code;
const saved=JSON.parse(await fs.readFile(fixture,'utf8'));for(const o of saved.origins){o.origin=origin;for(const db of o.indexedDB??[])for(const store of db.stores)for(const row of store.records)if(row.value?.suspension)row.value.suspension.equipped=equipped}
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']}),c=await b.newContext({viewport:{width,height:width*9/16},deviceScaleFactor:1,storageState:saved}),p=await c.newPage(),errors=[],finals=[];p.on('pageerror',e=>errors.push(e.message));
try{await p.goto(origin+'/?scene=crew&test=1&profile=1&play=career&seed=11'+(duel?'&event=duel':''),{timeout:120000});await p.waitForFunction(()=>window.__CREW?.ready,null,{timeout:120000});await p.addScriptTag({content:source});await p.locator('#enable-sound').click();await p.waitForFunction(()=>window.__CREW.inspect().audio.enabled);
 const initial=await p.evaluate(()=>window.__CREW.inspect());await p.evaluate(()=>{window.__drive=true;window.__results=[];window.__trace=[];let attempt='',agent,lastTime=0,prior='ready',lastTick=0;function frame(){if(!window.__drive)return;const h=window.__CREW,s=h.lightweight();if(attempt!==s.attemptId){attempt=s.attemptId;agent=new window.CrewEvidence.EvidenceDriver(h.route);lastTime=0;lastTick=0}const dt=Math.max(0,s.telemetry.time-lastTime);lastTime=s.telemetry.time;h.setDeviceSample(s.race.phase==='running'?agent.sample(s.telemetry,s.field,dt):window.CrewEvidence.toDevice());if(s.race.phase==='finished'&&prior!=='finished')window.__results.push(s);if(s.ticks-lastTick>=60){lastTick=s.ticks;window.__trace.push(s)}prior=s.race.phase;requestAnimationFrame(frame)}requestAnimationFrame(frame)});
 await p.locator('#start-crew').click();await p.waitForTimeout(150);await p.locator('#start-crew').click();
 for(let i=0;i<attempts;i++){await p.waitForFunction(n=>window.__results.length>=n,i+1,{timeout:360000,polling:15000});await p.waitForFunction(()=>window.__CREW.lightweight().race.allFinished,null,{timeout:35000});await p.waitForFunction(()=>!window.__CREW.inspect().rewardPending);finals.push(await p.evaluate(()=>window.__CREW.inspect()));console.log(JSON.stringify({attempt:i+1,result:finals.at(-1).race.playerResult}));if(i+1<attempts)await p.locator('button[data-action="retry"]').click()}
 const raw=await p.evaluate(()=>{window.__drive=false;return {profile:window.__CREW.profile(),results:window.__results,trace:window.__trace}}),summary=raw.results.map((r,i)=>{const rows=raw.profile.rows.filter(v=>v[10]===2&&v[11]===i+1),times=rows.map(v=>v[1]).sort((a,b)=>a-b),pct=q=>times[Math.ceil(times.length*q)-1];return {attempt:i+1,samples:times.length,p95Ms:pct(.95),p99Ms:pct(.99),maxMs:times.at(-1),activeOver100Ms:times.filter(x=>x>100).length,pass:pct(.95)<=20&&pct(.99)<=33.4&&times.at(-1)<=100,result:r.race.playerResult,allFinishers:finals[i].race.standings.map(s=>({id:s.id,status:s.status,timeMs:s.timeMs,lap:s.lap})),memory:finals[i].memory}});
 const report={sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),browser:b.version(),width,height:width*9/16,equipped,duel,fixture,initial,finals,errors,...raw,method:'Native wall-clock RAF; existing control-only evidence driver; real rivals and shared simulation. No capture or screenshots during scored racing. Audio graph enabled, host output muted. Isolated browser, no desktop takeover.'};await fs.writeFile(dir+'/run.json',JSON.stringify(report));await fs.writeFile(dir+'/summary.json',JSON.stringify({sourceCommit:report.sourceCommit,renderer:raw.profile.renderer,browser:b.version(),width,equipped,duel,overflow:raw.profile.overflow,thresholds:{p95Ms:20,p99Ms:33.4,maxMs:100},attempts:summary,errors,method:report.method},null,2));console.log(JSON.stringify(summary));assert.deepEqual(errors,[]);assert.ok(summary.every(s=>s.result?.valid&&s.allFinishers.every(v=>v.status==='finished')));assert.equal(raw.profile.overflow,0);
}catch(e){await fs.writeFile(dir+'/failure.json',JSON.stringify({error:e.stack,errors,finals},null,2));throw e}finally{await c.close();await b.close()}
