import {chromium} from '@playwright/test';import {build} from 'vite';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR,base=process.env.BASE_URL||'http://127.0.0.1:5202';if(!out)throw Error('Fresh EVIDENCE_DIR required');await fs.mkdir(out,{recursive:false});
const bundle=await build({configFile:false,logLevel:'silent',publicDir:false,build:{write:false,minify:false,lib:{entry:path.resolve('scripts/p09a-career-driver.ts'),name:'Evidence',formats:['iife']}}}),source=(Array.isArray(bundle)?bundle[0]:bundle).output.find(x=>x.type==='chunk').code;
const fixture=JSON.parse(await fs.readFile('director-kit/production/evidence/P08A/loop-final-02/earned-career.json','utf8'));for(const o of fixture.origins)o.origin=base;
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']}),context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1,storageState:fixture,recordVideo:{dir:out+'/raw-video',size:{width:1280,height:720}}});
await context.addInitScript(()=>{const q=new URLSearchParams(location.search);q.set('test','1');q.set('profile','1');history.replaceState(null,'','?'+q+location.hash)});
// Capture-only sync flash mirror: native dialogs can obscure the game's ordinary DOM marker.
// Observe the real chirp-triggered flash and mirror it in the top layer for 240 ms.
// No game clock, audio samples, vehicle transforms or outcome is modified.
await context.addInitScript(()=>{new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(!(node instanceof HTMLElement)||!node.dataset.audioSync)continue;const flash=node.cloneNode(true);delete flash.dataset.audioSync;flash.dataset.evidenceSync=node.dataset.audioSync;flash.setAttribute('popover','manual');flash.style.cssText+=';inset:auto;margin:0;padding:0;border:0;left:0;top:0';document.body.append(flash);flash.showPopover();setTimeout(()=>flash.remove(),240)}}).observe(document,{childList:true,subtree:true})});
const p=await context.newPage(),errors=[],segments=[],shots=[];p.on('pageerror',e=>errors.push(e.message));
const wait=ms=>p.waitForTimeout(ms);async function ready(){await p.waitForFunction(()=>window.__SIGNATURE?.ready||window.__EXPRESS?.ready,null,{timeout:120000});await p.locator('[data-loading-stage]').waitFor({state:'detached',timeout:120000})}
async function shot(name){await p.screenshot({path:out+'/'+name+'.png'});shots.push(name)}
async function begin(name){await p.locator('#enable-sound').click();await p.waitForFunction(()=>((window.__SIGNATURE||window.__EXPRESS)?.inspect().audio??window.__CAREER_HUB?.audioInspect()).enabled);await p.evaluate(name=>{const h=window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB;h.startAudioCapture();(h.audioSync??h.audioMarker)(name+'-start');const label=document.createElement('div');label.textContent='REAL-SPEED GAME CAPTURE · AUTOMATED INPUT · ACTUAL GAME AUDIO';label.style.cssText='position:fixed;bottom:2px;left:50%;transform:translateX(-50%);font:10px Arial;background:#111d;color:#fff;padding:3px 8px;z-index:5000';document.body.append(label)},name);await wait(450)}
async function end(name){await p.evaluate(name=>{const h=window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB;(h.audioSync??h.audioMarker)(name+'-end')},name);await wait(400);const a=await p.evaluate(()=>(window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB).stopAudioCapture());await fs.writeFile(out+'/'+name+'-audio.webm',Buffer.from(a.base64,'base64'));delete a.base64;segments.push({name,...a});await fs.writeFile(out+'/audio-segments.json',JSON.stringify(segments,null,2))}
async function category(v){await p.locator('[data-action="category"][data-value="'+v+'"]').click();await wait(350)}async function action(a,v){await p.locator('[data-action="'+a+'"]'+(v?'[data-value="'+v+'"]':'')).first().click();if(await p.evaluate(()=>!!window.__SIGNATURE))await p.waitForFunction(()=>!window.__SIGNATURE.inspect().pending);await wait(350)}
async function driver(){await p.addScriptTag({content:source});await p.evaluate(()=>{window.__drive=true;window.__trace=[];window.__agent=new window.Evidence.EvidenceDriver(window.__EXPRESS.route);let last=0,record=0;function frame(){if(!window.__drive)return;const h=window.__EXPRESS,s=h.lightweight(),dt=Math.max(0,s.telemetry.time-last);last=s.telemetry.time;h.setDeviceSample(s.race.phase==='running'?window.__agent.sample(s.telemetry,s.field,dt):window.Evidence.toDevice());if(s.ticks-record>=30){record=s.ticks;window.__trace.push({wall:performance.now(),...s})}requestAnimationFrame(frame)}requestAnimationFrame(frame)})}

async function hub(){await p.waitForFunction(()=>window.__CAREER_HUB?.ready,null,{timeout:120000})}
try{
 await p.goto(base+'/?scene=signature');await ready();await begin('01-signature');await shot('01-entry');await wait(2500);await action('build');await action('finish','white-graphite');await wait(2500);await category('Lighting');await action('toggle','SM-133');await action('light-color','blue');await wait(2500);await p.locator('#game-audio summary').click();await wait(2200);await p.locator('#game-audio summary').click();await category('Build Presets');await action('preset','harbor-sport');await wait(2000);await category('Suspension');if((await p.evaluate(()=>window.__SIGNATURE.inspect())).recipe.products['SM-3223'])await action('toggle','SM-3223');await action('toggle','SM-3223');await shot('02-shocks');await wait(2200);await category('Storage');await action('toggle','SM-28919');await wait(1800);await category('Exhaust');if((await p.evaluate(()=>window.__SIGNATURE.inspect())).recipe.products['SM-7720'])await action('toggle','SM-7720');await action('toggle','SM-7720');await wait(2000);await action('view','SM-7720');await shot('03-thermal');await wait(2500);await action('view','interior');await action('ignition','false');await wait(1500);await action('ignition','true');await wait(2800);await shot('04-powered-display');await action('view','hero');await category('Build Presets');await p.locator('#signature-recipe-name').fill('Signature Finish / Touring');await action('save');await wait(1800);await category('Paint');await action('finish','white-graphite');await wait(2200);await action('advanced');const motion=p.locator('[data-action=motion][data-value=false]');if(await motion.count())await motion.click();await action('advanced');await wait(1500);
 await p.locator('[data-action=test-drive][data-value=express]').click();await p.waitForFunction(()=>window.__SIGNATURE?.inspect().departure?.elapsed>4.95);await p.locator('[data-departure=pause]').click();await shot('05-thermal-departure');await end('01-signature');await p.locator('[data-departure=pause]').click();await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:120000});await ready();
 await begin('02-drive');await p.locator('#start-crew').click();await wait(3500);await p.keyboard.down('w');await wait(6500);await p.keyboard.up('w');const fast=await p.evaluate(()=>window.__EXPRESS.inspect());await shot('06-running-engine');await p.keyboard.down('s');await wait(5000);await p.keyboard.up('s');await wait(600);const stopped=await p.evaluate(()=>window.__EXPRESS.inspect());assert(fast.telemetry.speed>26);assert(Math.abs(stopped.telemetry.speed)<.3);await p.keyboard.down('s');await wait(2000);await p.keyboard.up('s');await shot('07-reverse');const reverse=await p.evaluate(()=>window.__EXPRESS.inspect());assert(reverse.telemetry.gear<0);await p.keyboard.down('w');await wait(2500);await p.keyboard.up('w');await wait(500);await p.locator('#race-pause').click();await shot('08-pause-settings');await wait(1200);await fs.writeFile(out+'/driving.json',JSON.stringify({fast,stopped,reverse}));await end('02-drive');
 await p.goto(base+'/?scene=career&play=career');await hub();await begin('03-career-entry');await shot('09-career');await wait(1800);await p.locator('[data-action=event][data-value=open-it-up]').click();await wait(1800);await end('03-career-entry');await p.locator('[data-action=start]').click();await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:120000});await ready();await begin('04-earned-race');await driver();await p.locator('#start-crew').click();for(let i=0;i<160;i++){await wait(1000);const s=await p.evaluate(()=>window.__EXPRESS.inspect());if(i===22)await shot('10-race');if(s.race.playerResult?.valid&&!s.rewardPending&&s.career.state.receipts[s.attemptId])break;if(i===159)throw Error('Native career race timed out')}await wait(3000);await shot('11-earned-result');await fs.writeFile(out+'/earned-race.json',JSON.stringify(await p.evaluate(()=>({state:window.__EXPRESS.inspect(),trace:window.__trace}))));await end('04-earned-race');await p.locator('[data-action=bay]').click();await hub();await begin('05-earned-workshop');await p.locator('[data-product="SM-7720"]').scrollIntoViewIfNeeded();await wait(1800);await p.locator('[data-product="SM-7720"] [data-action=purchase]').click();await p.waitForFunction(()=>!window.__CAREER_HUB.inspect().pending);await wait(2000);await shot('12-earned-part');assert.equal((await p.evaluate(()=>window.__CAREER_HUB.inspect())).state.ownBuild.products['SM-7720'].owned,true);await p.locator('[data-product="SM-7720"] [data-action=equip]').click();await p.waitForFunction(()=>!window.__CAREER_HUB.inspect().pending);await wait(1000);await p.locator('[data-product="SM-7720"] [data-action=equip]').click();await p.waitForFunction(()=>!window.__CAREER_HUB.inspect().pending);await wait(1800);await end('05-earned-workshop');await p.locator('[data-product="SM-7720"] a').first().click();await ready();await begin('06-returned-build');await category('Exhaust');await action('view','SM-7720');await wait(3500);await action('view','hero');await wait(3000);await action('view','front');await wait(3500);await action('view','rear');await wait(3500);await action('view','hero');await wait(2500);await shot('13-returned-build');await end('06-returned-build');assert.deepEqual(errors,[]);
 await context.storageState({path:out+'/earned-career.json',indexedDB:true});await fs.writeFile(out+'/verification.json',JSON.stringify({pass:true,errors,shots,browser:browser.version(),segments:segments.map(s=>s.name),method:'Native wall-clock game, normal UI and keyboard; disclosed control-only career driver. Real earned P08A fixture, first new unlock earned by actual driving. Live game WebAudio synchronized with measured flash/chirp; career workshop records its live game audio graph, including successful transaction cues. Loading/navigation and sync markers cut, no replacement sound or speed changes.'},null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({error:e.stack,errors,segments},null,2));await shot('failure');throw e}finally{const video=p.video();await context.close();await fs.writeFile(out+'/video-path.json',JSON.stringify({path:await video.path()}));await browser.close()}
