import {chromium} from '@playwright/test';import {build} from 'vite';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR,base=process.env.BASE_URL||'http://127.0.0.1:5202';if(!out)throw Error('Fresh EVIDENCE_DIR required');await fs.mkdir(out,{recursive:false});
const bundle=await build({configFile:false,logLevel:'silent',publicDir:false,build:{write:false,minify:false,lib:{entry:path.resolve('scripts/p09c-career-driver.ts'),name:'Evidence',formats:['iife']}}}),source=(Array.isArray(bundle)?bundle[0]:bundle).output.find(x=>x.type==='chunk').code;

const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']}),context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1,recordVideo:{dir:out+'/raw-video',size:{width:1280,height:720}}});
await context.addInitScript(()=>{const q=new URLSearchParams(location.search);q.set('test','1');q.set('profile','1');history.replaceState(null,'','?'+q+location.hash)});
// Capture-only sync flash mirror: native dialogs can obscure the game's ordinary DOM marker.
// Observe the real chirp-triggered flash and mirror it in the top layer for 240 ms.
// No game clock, audio samples, vehicle transforms or outcome is modified.
await context.addInitScript(()=>{new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(!(node instanceof HTMLElement)||!node.dataset.audioSync)continue;const flash=node.cloneNode(true);delete flash.dataset.audioSync;flash.dataset.evidenceSync=node.dataset.audioSync;flash.setAttribute('popover','manual');flash.style.cssText+=';inset:auto;margin:0;padding:0;border:0;left:0;top:0';document.body.append(flash);flash.showPopover();setTimeout(()=>flash.remove(),240)}}).observe(document,{childList:true,subtree:true})});
const p=await context.newPage(),errors=[],segments=[],shots=[];p.on('pageerror',e=>errors.push(e.message));
const wait=ms=>p.waitForTimeout(ms);async function ready(){await p.waitForFunction(()=>window.__P09C_MOTION?.ready||window.__SIGNATURE?.ready||window.__EXPRESS?.ready,null,{timeout:120000});await p.locator('[data-loading-stage]').waitFor({state:'detached',timeout:120000})}
async function shot(name){await p.screenshot({path:out+'/'+name+'.png'});shots.push(name)}
async function begin(name){if(!await p.evaluate(()=>((window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS)?.inspect().audio??window.__CAREER_HUB?.audioInspect()).enabled)){try{await p.locator('#enable-sound').click({timeout:1500})}catch(error){if(!await p.evaluate(()=>((window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS)?.inspect().audio??window.__CAREER_HUB?.audioInspect()).enabled))throw error}}await p.waitForFunction(()=>((window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS)?.inspect().audio??window.__CAREER_HUB?.audioInspect()).enabled);assert.equal(await p.locator('#enable-sound').isVisible(),false,'Enabled audio must hide Enable sound');await p.evaluate(name=>{const h=window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB;h.startAudioCapture();(h.audioSync??h.audioMarker)(name+'-start');const label=document.createElement('div');label.textContent='REAL-SPEED GAME CAPTURE · AUTOMATED INPUT · ACTUAL GAME AUDIO';label.style.cssText='position:fixed;bottom:2px;left:50%;transform:translateX(-50%);font:10px Arial;background:#111d;color:#fff;padding:3px 8px;z-index:5000';document.body.append(label)},name);await wait(450)}
async function end(name){await p.evaluate(name=>{const h=window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB;(h.audioSync??h.audioMarker)(name+'-end')},name);await wait(400);const a=await p.evaluate(()=>(window.__P09C_MOTION||window.__SIGNATURE||window.__EXPRESS||window.__CAREER_HUB).stopAudioCapture());await fs.writeFile(out+'/'+name+'-audio.webm',Buffer.from(a.base64,'base64'));delete a.base64;segments.push({name,...a});await fs.writeFile(out+'/audio-segments.json',JSON.stringify(segments,null,2))}
async function category(v){await p.locator('[data-action="category"][data-value="'+v+'"]').click();await wait(350)}async function action(a,v){await p.locator('[data-action="'+a+'"]'+(v?'[data-value="'+v+'"]':'')).first().click();if(await p.evaluate(()=>!!window.__SIGNATURE))await p.waitForFunction(()=>!window.__SIGNATURE.inspect().pending);await wait(350)}
async function driver(){await p.addScriptTag({content:source});await p.evaluate(()=>{window.__drive=true;window.__trace=[];window.__agent=new window.Evidence.EvidenceDriver(window.__EXPRESS.route);let last=0,record=0,view=0;function frame(){if(!window.__drive)return;const h=window.__EXPRESS,s=h.lightweight(),dt=Math.max(0,s.telemetry.time-last);last=s.telemetry.time;const device=s.race.phase==='running'?window.__agent.sample(s.telemetry,s.field,dt):window.Evidence.toDevice();if(s.race.elapsedMs>([16000,17000,28000][view]??Infinity)){device.keys=['KeyC'];view++}h.setDeviceSample(device);if(s.ticks-record>=30){record=s.ticks;window.__trace.push({wall:performance.now(),...s})}requestAnimationFrame(frame)}requestAnimationFrame(frame)})}

async function hub(){await p.waitForFunction(()=>window.__CAREER_HUB?.ready,null,{timeout:120000})}
try{
 for(const mph of [50,65])for(const profile of ['slingmods-sport-v2','slingmods-sport-v3']){
  const name=String(segments.length+1).padStart(2,'0')+'-'+profile+'-'+mph;
  await p.goto((process.env.MOTION_URL||'http://127.0.0.1:5201')+'/scripts/p09c-motion-viewer.html?profile='+profile+'&mph='+mph);await ready();await begin(name);await p.locator('#start').click();await p.waitForFunction(()=>window.__P09C_MOTION.inspect().finished,null,{timeout:45000});await shot(name);await fs.writeFile(out+'/'+name+'-motion.json',JSON.stringify(await p.evaluate(()=>window.__P09C_MOTION.inspect())));await wait(1000);await end(name);
 }
 await p.goto(base+'/?scene=signature&screen=build');await ready();await category('Build Presets');await action('preset','harbor-sport');await category('Paint');await action('finish','white-graphite');await action('test-drive','express');await ready();
 await begin('05-keyboard-drive');await p.locator('#start-crew').click();await wait(1200);await p.keyboard.down('w');await wait(5200);await p.keyboard.down('a');await wait(300);await p.keyboard.up('a');await wait(500);await p.keyboard.down('d');await wait(280);await p.keyboard.up('d');await wait(700);await p.keyboard.up('w');await p.keyboard.down('s');await p.keyboard.down('a');await wait(300);await p.keyboard.up('a');await wait(4200);await p.keyboard.up('s');await wait(500);await p.keyboard.down('s');await wait(1800);await p.keyboard.up('s');await shot('05-reverse');await fs.writeFile(out+'/keyboard-before-reset.json',JSON.stringify(await p.evaluate(()=>window.__EXPRESS.inspect())));await p.keyboard.down('r');await wait(1300);await p.keyboard.up('r');await wait(1000);await shot('06-restarted');await end('05-keyboard-drive');
 await p.locator('[data-action=bay]').click();await ready();await action('back');await action('quick-race');await action('race','express');await ready();await begin('06-current-race');await driver();await p.locator('#start-crew').click();let done=false;for(let i=0;i<170;i++){await wait(1000);if(i===22)await shot('07-race-cockpit');const s=await p.evaluate(()=>window.__EXPRESS.inspect());if(s.race.playerResult?.valid){done=true;break}}assert(done,'Current race must finish valid');await wait(3000);await shot('08-race-result');await fs.writeFile(out+'/race.json',JSON.stringify(await p.evaluate(()=>({state:window.__EXPRESS.inspect(),trace:window.__trace}))));await end('06-current-race');
 await p.locator('[data-action=bay]').click();await ready();await begin('07-same-build');await action('view','front');await wait(3000);await action('view','rear');await wait(3000);await action('view','hero');await wait(3000);await shot('09-same-build');await end('07-same-build');
 assert.deepEqual(errors,[]);await fs.writeFile(out+'/verification.json',JSON.stringify({pass:true,errors,shots,browser:browser.version(),segments:segments.map(s=>s.name),method:'Native wall-clock actual simulation/game capture; same matched protocol at50/65mph for retainedv2/newv3. Diagnostic pad is explicitly labeled. UI keyboard and control-only actual race; actual post-limiter game master audio. R explicitly restarts, not a fabricated crash. Loading and sync markers cut only.'},null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({error:e.stack,errors,segments},null,2));await shot('failure');throw e}finally{const video=p.video();await context.close();await fs.writeFile(out+'/video-path.json',JSON.stringify({path:await video.path()}));await browser.close()}
