import {chromium} from '@playwright/test';import {build} from 'vite';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR,base=process.env.BASE_URL||'http://127.0.0.1:5202';if(!out)throw Error('Fresh EVIDENCE_DIR required');await fs.mkdir(out,{recursive:false});
const bundle=await build({configFile:false,logLevel:'silent',publicDir:false,build:{write:false,minify:false,lib:{entry:path.resolve('scripts/p09a-career-driver.ts'),name:'Evidence',formats:['iife']}}}),source=(Array.isArray(bundle)?bundle[0]:bundle).output.find(x=>x.type==='chunk').code;
const fixture=JSON.parse(await fs.readFile('director-kit/production/evidence/P08A/loop-final-02/earned-career.json','utf8'));for(const o of fixture.origins)o.origin=base;
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--mute-audio']}),context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1,storageState:fixture,recordVideo:{dir:out+'/raw-video',size:{width:1280,height:720}}});
await context.addInitScript(()=>{const q=new URLSearchParams(location.search);q.set('test','1');q.set('profile','1');history.replaceState(null,'','?'+q+location.hash)});
// Capture-only sync flash mirror: native dialogs can obscure the game's ordinary DOM marker.
// Observe the real chirp-triggered flash and mirror it in the top layer for 240 ms.
// No game clock, audio samples, vehicle transforms or outcome is modified.
await context.addInitScript(()=>{new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(!(node instanceof HTMLElement)||!node.dataset.audioSync)continue;const flash=node.cloneNode(true);delete flash.dataset.audioSync;flash.dataset.evidenceSync=node.dataset.audioSync;flash.setAttribute('popover','manual');flash.style.cssText+=';inset:auto;margin:0;padding:0;border:0;left:0;top:0';document.body.append(flash);flash.showPopover();setTimeout(()=>flash.remove(),240)}}).observe(document,{childList:true,subtree:true})});
const p=await context.newPage(),errors=[],segments=[],shots=[];p.on('pageerror',e=>errors.push(e.message));
const wait=ms=>p.waitForTimeout(ms);async function ready(){await p.waitForFunction(()=>window.__SIGNATURE?.ready||window.__EXPRESS?.ready,null,{timeout:120000});await p.locator('[data-loading-stage]').waitFor({state:'detached',timeout:120000})}
async function shot(name){await p.screenshot({path:out+'/'+name+'.png'});shots.push(name)}
async function begin(name){await p.locator('#enable-sound').click();await p.waitForFunction(()=>(window.__SIGNATURE||window.__EXPRESS).inspect().audio.enabled);await p.evaluate(name=>{const h=window.__SIGNATURE||window.__EXPRESS;h.startAudioCapture();h.audioSync(name+'-start');const label=document.createElement('div');label.textContent='REAL-SPEED GAME CAPTURE · AUTOMATED INPUT · ACTUAL GAME AUDIO';label.style.cssText='position:fixed;bottom:2px;left:50%;transform:translateX(-50%);font:10px Arial;background:#111d;color:#fff;padding:3px 8px;z-index:5000';document.body.append(label)},name);await wait(450)}
async function end(name){await p.evaluate(name=>(window.__SIGNATURE||window.__EXPRESS).audioSync(name+'-end'),name);await wait(400);const a=await p.evaluate(()=>(window.__SIGNATURE||window.__EXPRESS).stopAudioCapture());await fs.writeFile(out+'/'+name+'-audio.webm',Buffer.from(a.base64,'base64'));delete a.base64;segments.push({name,...a});await fs.writeFile(out+'/audio-segments.json',JSON.stringify(segments,null,2))}
async function category(v){await p.locator('[data-action="category"][data-value="'+v+'"]').click();await wait(350)}async function action(a,v){await p.locator('[data-action="'+a+'"]'+(v?'[data-value="'+v+'"]':'')).first().click();if(await p.evaluate(()=>!!window.__SIGNATURE))await p.waitForFunction(()=>!window.__SIGNATURE.inspect().pending);await wait(350)}
async function driver(){await p.addScriptTag({content:source});await p.evaluate(()=>{window.__drive=true;window.__trace=[];window.__agent=new window.Evidence.EvidenceDriver(window.__EXPRESS.route);let last=0,record=0;function frame(){if(!window.__drive)return;const h=window.__EXPRESS,s=h.lightweight(),dt=Math.max(0,s.telemetry.time-last);last=s.telemetry.time;h.setDeviceSample(s.race.phase==='running'?window.__agent.sample(s.telemetry,s.field,dt):window.Evidence.toDevice());if(s.ticks-record>=30){record=s.ticks;window.__trace.push({wall:performance.now(),...s})}requestAnimationFrame(frame)}requestAnimationFrame(frame)})}

async function hub(){await p.waitForFunction(()=>window.__CAREER_HUB?.ready,null,{timeout:120000})}
async function silentMark(){await p.evaluate(()=>{const n=document.createElement('div');n.setAttribute('popover','manual');n.style.cssText='position:fixed;inset:auto;left:0;top:0;margin:0;padding:0;border:0;width:64px;height:64px;background:rgb(255,0,255)';document.body.append(n);n.showPopover();setTimeout(()=>n.remove(),240)});await wait(450)}
async function silentBegin(){await silentMark()}async function silentEnd(name){await silentMark();segments.push({name,silent:true,reason:'Career workshop has no audio graph. Authentic UI silence retained.'});await fs.writeFile(out+'/audio-segments.json',JSON.stringify(segments,null,2))}
try{
 await p.goto(base+'/?scene=career&play=career');await hub();await silentBegin();await shot('01-locked-career');await wait(3500);await p.locator('[data-product="SM-7720"]').scrollIntoViewIfNeeded();await wait(4000);await shot('02-locked-exhaust');await silentEnd('01-locked-career');await p.locator('[data-product="SM-7720"] a').first().click();await ready();await begin('02-free-preview');await shot('03-free-exhaust');await action('view','SM-7720');await wait(5000);await action('view','hero');await action('finish','white-graphite');await wait(3500);await category('Build Presets');await shot('04-sport-v2');await wait(3500);await p.locator('[data-action=test-drive][data-value=express]').click();await p.waitForFunction(()=>window.__SIGNATURE?.inspect().departure?.elapsed>4.8);await p.locator('[data-departure=pause]').click();await shot('05-bay-exit');await end('02-free-preview');await p.locator('[data-departure=pause]').click();await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:120000});await ready();await begin('03-braking');await p.locator('#start-crew').click();await wait(3500);await p.keyboard.down('w');await wait(6300);await p.keyboard.up('w');await shot('06-fast-straight');const fast=await p.evaluate(()=>window.__EXPRESS.inspect());await p.keyboard.down('s');await wait(4700);await p.keyboard.up('s');await wait(700);await shot('07-braked');const stopped=await p.evaluate(()=>window.__EXPRESS.inspect());await fs.writeFile(out+'/braking.json',JSON.stringify({fast,stopped}));assert.ok(fast.telemetry.speed>26);assert.ok(Math.abs(stopped.telemetry.speed)<.3);await p.locator('#race-pause').click();await wait(1800);await end('03-braking');
 await p.goto(base+'/?scene=career&play=career');await hub();await p.locator('[data-action=event][data-value=open-it-up]').click();await p.locator('[data-action=start]').click();await p.waitForFunction(()=>window.__EXPRESS?.ready,null,{timeout:120000});await ready();await begin('04-earned-race');await driver();await p.locator('#start-crew').click();for(let i=0;i<160;i++){await wait(1000);const s=await p.evaluate(()=>window.__EXPRESS.inspect());if(i===22)await shot('08-brake-turn');if(i===67)await shot('09-coastline');if(s.race.playerResult?.valid&&!s.rewardPending&&s.career.state.receipts[s.attemptId])break;if(i===159)throw Error('Native career race timed out')}await wait(4000);await shot('10-earned-result');await fs.writeFile(out+'/earned-race.json',JSON.stringify(await p.evaluate(()=>({state:window.__EXPRESS.inspect(),trace:window.__trace}))));await end('04-earned-race');await p.locator('[data-action=bay]').click();await hub();await silentBegin();await p.locator('[data-product="SM-7720"]').scrollIntoViewIfNeeded();await shot('11-earned-exhaust');await wait(3000);await p.locator('[data-product="SM-7720"] [data-action=purchase]').click();await p.waitForFunction(()=>!window.__CAREER_HUB.inspect().pending);await wait(3500);await shot('12-purchased-installed');assert.equal((await p.evaluate(()=>window.__CAREER_HUB.inspect())).state.ownBuild.products['SM-7720'].owned,true);await silentEnd('05-earned-workshop');await p.locator('[data-product="SM-7720"] a').first().click();await ready();await begin('06-returned-build');await action('view','SM-7720');await wait(4500);await action('view','hero');await wait(4500);await shot('13-returned-build');await end('06-returned-build');assert.deepEqual(errors,[]);
 await context.storageState({path:out+'/earned-career.json',indexedDB:true});await fs.writeFile(out+'/verification.json',JSON.stringify({pass:true,errors,shots,browser:browser.version(),segments:segments.map(s=>s.name),method:'Native wall-clock game, normal UI and keyboard; disclosed control-only career driver. Real earned P08A fixture, first new unlock earned by actual driving. Live game WebAudio synchronized with measured flash/chirp; workshop UI is authentically silent and explicitly labeled. Loading/navigation and sync markers cut, no replacement sound or speed changes.'},null,2));
}catch(e){await fs.writeFile(out+'/failure.json',JSON.stringify({error:e.stack,errors,segments},null,2));await shot('failure');throw e}finally{const video=p.video();await context.close();await fs.writeFile(out+'/video-path.json',JSON.stringify({path:await video.path()}));await browser.close()}
