import {CrewPlayerAgent}from './crew-player-agent';
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID,createHash}from 'node:crypto';import {gzipSync}from 'node:zlib';
import routeData from '../public/assets/harbor/route.json';
import {createCourseEnvironment,type CourseRoute}from '../src/course/environment';
import {RaceWorld,FIXED_DT,type VehicleControl}from '../src/simulation';
import {CrewRace,RivalController,createCrewGrid}from '../src/competition';
const route=routeData as CourseRoute;
for(const seed of [11,97]){
 const order=seed===11?['maya','jett','nico','player']:['jett','nico','maya','player'],grid=createCrewGrid(route,order),world=await RaceWorld.create(createCourseEnvironment(route));for(const id of order)world.addVehicle(id,grid[id]);
 const playerAgent=new CrewPlayerAgent(route);const controllers=Object.fromEntries(order.map(id=>[id,new RivalController(route,id,seed)])),race=new CrewRace(route,order);race.restart(randomUUID());const rawFrames:string[]=[];let executed=0;const trace:unknown[]=[],changes:unknown[]=[];let lastOrder='';
 for(let tick=0;tick<60*300;tick++){const before=world.telemetry(),controls:Record<string,VehicleControl>={};for(const id of order){controls[id]=race.control(id,id==='player'&&process.env.PODIUM?playerAgent.control(before[id],before,FIXED_DT):controllers[id].control(before[id],before,FIXED_DT));const reason=controllers[id].inspect().retiredReason;if(reason)race.retire(id,reason)}world.step(controls,FIXED_DT);const now=world.telemetry();race.tick(before,now,FIXED_DT);executed++;rawFrames.push(JSON.stringify({tick,controls,telemetry:now}));if(tick%60===0){const snapshot=race.snapshot();trace.push({tick,snapshot,telemetry:now,controllers:Object.fromEntries(order.map(id=>[id,controllers[id].inspect()]))});const ids=snapshot.standings.map(s=>s.id).join();if(ids!==lastOrder){changes.push({tick,order:ids});lastOrder=ids}if(snapshot.allFinished)break}}
 const final=race.snapshot();assert.ok(final.allFinished);assert.ok(final.standings.every(s=>s.status==='finished'&&s.valid&&s.lap===2));assert.equal(world.steps,executed);assert.ok(Object.values(controllers).every(c=>c.inspect().recoveries===0&&c.inspect().retiredReason===null));if(process.env.PODIUM)assert.ok(final.playerResult!.place!<=3);const kind=process.env.PODIUM?'podium':'seed',rawPath=`director-kit/production/evidence/P05/competition/${kind}-${seed}-ticks.jsonl.gz`;fs.writeFileSync(rawPath,gzipSync(rawFrames.join('\n')));const files=['src/competition/race.ts','src/competition/rival.ts','src/competition/road.ts','src/competition/grid.ts','src/simulation/index.ts','src/simulation/drivetrain.ts','scripts/crew-player-agent.ts','scripts/test-competition-physics.ts','public/assets/harbor/route.json'];const inputHashes=Object.fromEntries(files.map(f=>[f,createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));const result={seed,inputHashes,environment:{runtime:process.version,platform:process.platform,clock:'deterministic1/60',rendered:false,player:process.env.PODIUM?'evidence-only CrewPlayerAgent':'production RivalController configured as QA player'},rawTelemetry:{path:rawPath,frames:rawFrames.length,sha256:createHash('sha256').update(fs.readFileSync(rawPath)).digest('hex')},grid,steps:world.steps,result:race.snapshot(),controllers:Object.fromEntries(order.map(id=>[id,controllers[id].inspect()])),changes,trace};fs.mkdirSync('director-kit/production/evidence/P05/competition',{recursive:true});fs.writeFileSync(`director-kit/production/evidence/P05/competition/${process.env.PODIUM?'podium':'seed'}-${seed}.json`,JSON.stringify(result));console.log(JSON.stringify({...result,trace:trace.length},null,2));world.dispose();
}
