import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {gzipSync} from 'node:zlib';import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation';import {streetSetup,type SuspensionSetup} from '../src/career/suspension';
const base='ed363b28ec6ba933dd82c576153bd73c80ea6619',dir=process.env.EVIDENCE_DIR;if(!dir)throw Error('EVIDENCE_DIR required');fs.mkdirSync(dir,{recursive:true});
const temp=path.resolve('.handoff-validation-p08a');fs.mkdirSync(temp,{recursive:true});
const original=execFileSync('git',['show',base+':src/simulation/index.ts'],{encoding:'utf8'}),source=original.replace("'../../public/assets/slingshot-contact-layout.json'","'../public/assets/slingshot-contact-layout.json'").replace("'../course/environment'","'../src/course/environment'").replace("'./drivetrain'","'../src/simulation/drivetrain'").replace("'./pad'","'../src/simulation/pad'");
fs.writeFileSync(path.join(temp,'baseline.ts'),source);const {Simulation:Baseline}=await import(pathToFileURL(path.join(temp,'baseline.ts')).href);
const sha=(data:string|Buffer)=>createHash('sha256').update(data).digest('hex');
async function trace(Factory:typeof Simulation,setup:SuspensionSetup|null|undefined|'removed'){const sim=await Factory.create();if(setup==='removed'){sim.configureSuspension({...streetSetup(),frontCompression:19,rideHeightMm:20});sim.configureSuspension(null)}else if(setup!==undefined)sim.configureSuspension(setup);const rows=[];
 for(let i=0;i<4200;i++){if(i===1400)sim.reset({x:0,z:35});if(i===2800)sim.reset({x:14,z:-66});sim.step({throttle:i%1400<900?.42:0,brake:i%1400>=900?.3:0,steer:i>=1400&&i<2800?Math.sin(i/180)*.16:0,reverse:false});rows.push(sim.telemetry())}sim.dispose();return rows}
const baseline=await trace(Baseline,undefined),stock=await trace(Simulation,null),street=await trace(Simulation,streetSetup());const removed=await trace(Simulation,'removed');assert.deepEqual(removed,baseline);assert.deepEqual(stock,baseline);assert.deepEqual(street,baseline);
const removal=await Simulation.create();removal.configureSuspension({...streetSetup(),frontCompression:19,rideHeightMm:20});removal.configureSuspension(null);removal.dispose();
async function response(setup:SuspensionSetup|null){const sim=await Simulation.create();sim.configureSuspension(setup);sim.reset({y:.20});const rows=[];for(let i=0;i<600;i++){sim.step({throttle:0,brake:1,steer:0,reverse:false});const t=sim.telemetry();rows.push({t:t.time,y:t.position.y,vy:t.velocity.y,loads:t.wheels.map(w=>w.load),travel:t.wheels.map(w=>w.travel)})}sim.dispose();return rows}
const responses={stock:await response(null),soft:await response({...streetSetup(),frontCompression:0,frontRebound:0,rearCompression:0,rearRebound:0}),firm:await response({...streetSetup(),frontCompression:19,frontRebound:19,rearCompression:19,rearRebound:19}),raised:await response({...streetSetup(),rideHeightMm:20}),lowered:await response({...streetSetup(),rideHeightMm:-20})};assert.notDeepEqual(responses.soft,responses.firm);assert.ok(responses.raised.at(-1)!.y-responses.lowered.at(-1)!.y>.035);
for(const [name,rows]of Object.entries({baseline,stock,street,removed}))fs.writeFileSync(path.join(dir,name+'-4200.json.gz'),gzipSync(JSON.stringify(rows)));
fs.writeFileSync(path.join(dir,'suspension-response.json'),JSON.stringify(responses));
const report={baselineCommit:base,baselineSourceSha256:sha(original),rowsPerTrace:4200,comparison:'Full telemetry deep equality: accepted baseline = new stock = installed street coefficients = removed product. Includes resets, turning, braking and severe curb diagnostic.',hashes:Object.fromEntries(Object.entries({baseline,stock,street,removed}).map(([k,v])=>[k,sha(JSON.stringify(v))])),response:Object.fromEntries(Object.entries(responses).map(([k,v])=>[k,{settledHeight:v.at(-1)!.y,peakVerticalSpeed:Math.max(...v.map(r=>Math.abs(r.vy))),maxLoad:Math.max(...v.flatMap(r=>r.loads))}])),limitations:'Drop/curb diagnostics quantify game parameters, not manufacturer performance. No claimed faster lap or general handling gain.'};fs.writeFileSync(path.join(dir,'physics-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
