import {chromium}from'@playwright/test';import fs from'node:fs/promises';import assert from'node:assert/strict';import{build}from'vite';import path from'node:path';
const dir=process.env.EVIDENCE_DIR;if(!dir)throw Error('EVIDENCE_DIR required');await fs.mkdir(dir,{recursive:false});await build({configFile:false,logLevel:'silent',publicDir:false,build:{outDir:path.resolve(dir+'/agent'),emptyOutDir:false,minify:false,lib:{entry:path.resolve('scripts/crew-evidence-agent.ts'),name:'CrewEvidence',formats:['iife'],fileName:()=> 'agent.js'}}});const source=await fs.readFile(dir+'/agent/agent.js','utf8'),saved=JSON.parse(await fs.readFile('director-kit/production/evidence/P04B2/fixtures/review08-earned.json','utf8'));
const b=await chromium.launch({headless:true,args:['--use-angle=d3d11']}),ctx=await b.newContext({viewport:{width:1280,height:720},storageState:saved}),p=await ctx.newPage(),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));let now=1000;
async function step(n=1,raster=true){const s=await p.evaluate(({now,n,raster})=>{let s;for(let i=0;i<n;i++)s=window.__CREW.normalFrame(now+i*1000/60,raster&&i===n-1);return s},{now,n,raster});now+=n*1000/60;return s}
try {await p.goto('http://127.0.0.1:5187/?scene=crew&test=1&clock=controlled&seed=11');await p.waitForFunction(()=>window.__CREW?.ready);await p.addScriptTag({content:source});const before=await p.evaluate(()=>window.__CREW.inspect());assert.equal(before.worldSteps,0);await step(60);assert.equal((await p.evaluate(()=>window.__CREW.inspect())).worldSteps,0);
await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await step();await p.locator('button[data-action="resume"]').click();await step();assert.equal((await p.evaluate(()=>window.__CREW.inspect())).race.paused,false);await p.locator('#start-crew').click();await step(30);assert.equal((await p.evaluate(()=>window.__CREW.inspect())).worldSteps,0);await p.locator('#start-crew').click();await step(200);checks.push('ready blur recovery and intro have zero world steps; synchronized countdown');
await p.keyboard.down('w');assert.equal((await step()).inputState.control.throttle,1);await p.locator('#race-pause').click();const paused=await step(20);const positions=JSON.stringify(paused.field);await step(20);assert.equal(JSON.stringify((await p.evaluate(()=>window.__CREW.inspect())).field),positions);await p.locator('button[data-action="resume"]').click();assert.equal((await step()).inputState.armed,false);await p.keyboard.up('w');await step();await p.keyboard.press('c');assert.equal((await step()).camera.mode,'far');await p.keyboard.press('c');assert.equal((await step()).camera.mode,'cockpit');await p.keyboard.down('b');assert.equal((await step()).camera.active,'rearward');await p.keyboard.up('b');assert.equal((await step()).camera.active,'cockpit');checks.push('all4 paused, heldW neutral rearm, native cameras and quick lookback');
await p.keyboard.press('c');await step();await p.locator('#race-pause').click();await step();await p.locator('button[data-action="resume"]').click();await step();
// Restart through held ordinary reset then drive a complete race via actual virtual device reader.
await p.keyboard.down('r');await step(70,false);await p.keyboard.up('r');await step();await p.evaluate(()=>{window.__qaDriver=new window.CrewEvidence.EvidenceDriver(window.__CREW.route,11);window.__qaLast=0});
let finish;for(let block=0;block<28;block++){const out=await p.evaluate(({now})=>{const h=window.__CREW;let state;for(let i=0;i<600;i++){const s=h.lightweight();const dt=Math.max(0,s.telemetry.time-window.__qaLast);window.__qaLast=s.telemetry.time;h.setDeviceSample(s.race.phase==='running'?window.__qaDriver.sample(s.telemetry,s.field,dt):window.CrewEvidence.toDevice());state=h.normalFrame(now+i*1000/60,i===599);if(state.race.playerResult)break}return state},{now});now+=10000;if(out.race.playerResult){finish=out;break}}
assert.ok(finish?.race.playerResult?.valid);assert.ok(finish.race.playerResult.place<=3);await p.waitForFunction(()=>!window.__CREW.inspect().rewardPending);await step();const result=await p.evaluate(()=>window.__CREW.inspect());assert.ok(result.career.crew.cleared);assert.equal(result.career.credits,300+({1:300,2:200,3:150}[result.race.playerResult.place])+400);checks.push('actual two-lap podium, real resultproof, placement + firstpodium persisted');await p.screenshot({path:dir+'/result.png'});
await p.locator('button[data-action="retry"]').click();const retry=await step();assert.notEqual(retry.attemptId,result.attemptId);assert.equal(retry.career.credits,result.career.credits);checks.push('immediate retry freshattempt no repeatedcredits');await p.locator('#race-pause').click();await step();await p.locator('button[data-action="bay"]').click();await p.waitForFunction(()=>window.__TWT?.ready);const returned=await p.evaluate(()=>window.__TWT.inspect());await p.reload();await p.waitForFunction(()=>window.__TWT?.ready);const reloaded=await p.evaluate(()=>window.__TWT.inspect());assert.deepEqual(reloaded.career,returned.career);assert.equal(reloaded.career.appearance.color,'cyan');checks.push('savedchapter and equippedcyan reload and return');await p.screenshot({path:dir+'/saved-bay.png'});
await fs.writeFile(dir+'/report.json',JSON.stringify({method:'Isolated Chromium D3D11; controlledclock for UI/deterministic functional QA, not performance',checks,errors,before,result,reloaded},null,2));assert.deepEqual(errors,[]);console.log(JSON.stringify(checks))
}finally{await b.close()}
