import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {loadTrackside,planTrackside,type TracksidePlan} from '../presentation/trackside';
import {loadRaceAsphalt} from '../presentation/race-asphalt';import {loadRoadDecals} from '../presentation/road-decals';
import {EXPRESS_ROUTE,EXPRESS_DESIGN} from './route';import {sampleRoad} from '../course/environment';
export type ExpressPlacement={module:string;x:number;z:number;yaw:number;scale:number};
/** Editable instance layout reuses current authored Harbor kit, not old route geometry. */
export const EXPRESS_PLACEMENTS:ExpressPlacement[]=[{module:'gantry',x:0,z:-24,yaw:0,scale:1.4},{module:'terminal',x:43,z:-35,yaw:-Math.PI/2,scale:1.2}];
for(let i=0;i<15;i++)EXPRESS_PLACEMENTS.push({module:'palm'+(i%3),x:18,z:-i*53-28,yaw:i*.83,scale:.85});
for(let i=0;i<8;i++){EXPRESS_PLACEMENTS.push({module:'dock',x:32,z:-i*94-70,yaw:Math.PI/2,scale:1},{module:'skiff',x:48,z:-i*94-76,yaw:Math.PI/2,scale:1},{module:'quay',x:24,z:-i*94-72,yaw:Math.PI/2,scale:1.2})}
for(let i=0;i<8;i++)EXPRESS_PLACEMENTS.push({module:'warehouse',x:-42,z:-58-i*94,yaw:Math.PI/2,scale:1.6},{module:'palm'+i%3,x:-18,z:-32-i*94,yaw:i*.73,scale:1.1});
for(let i=0;i<7;i++)EXPRESS_PLACEMENTS.push({module:'warehouse',x:-323,z:-i*91-185,yaw:Math.PI/2,scale:.85},{module:'palm'+i%3,x:-301,z:-i*93-205,yaw:i,scale:1});
for(let i=0;i<5;i++)EXPRESS_PLACEMENTS.push({module:'waterfrontHall'+i%3,x:-90-i*37,z:-975,yaw:0,scale:1},{module:'service',x:-245,z:-330-i*88,yaw:-Math.PI/2,scale:1});
EXPRESS_PLACEMENTS.push({module:'pavilion',x:-160,z:80,yaw:.2,scale:1.5},{module:'paddock',x:-245,z:35,yaw:-.6,scale:1.4});
export function buildExpressRibbon(inner:number,outer:number,height:number){if(inner>outer)[inner,outer]=[outer,inner];const route=EXPRESS_ROUTE,positions:number[]=[],uv:number[]=[],indices:number[]=[];let along=0;
 for(let i=0;i<=route.centerline.length;i++){const index=i%route.centerline.length,a=route.centerline[index],prior=route.centerline[(index-1+route.centerline.length)%route.centerline.length],next=route.centerline[(index+1)%route.centerline.length];let dx=next[0]-prior[0],dz=next[1]-prior[1],n=Math.hypot(dx,dz);dx/=n;dz/=n;if(i)along+=Math.hypot(a[0]-prior[0],a[1]-prior[1]);for(const offset of[inner,outer]){positions.push(a[0]-dz*offset,height,a[1]+dx*offset);uv.push(offset/6,along/6)}if(i<route.centerline.length){const k=i*2;indices.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g}
/** Roadside rhythm: barriers sit exactly on the collision rail line (11.2 m), so nothing here changes where the car can go. */
export const EXPRESS_TRACKSIDE:TracksidePlan={railOffset:EXPRESS_ROUTE.width/2+EXPRESS_ROUTE.runoff+.7,barrier:station=>station>560&&station<900?'jersey-red-white':'armco-straight',fence:(station,side)=>side<0?station>40&&station<560:station>780&&station<1150,lights:{spacing:40,offset:12.5},boards:{offset:9.6,scale:1.8}};
export async function loadExpressPresentation(scene:THREE.Scene,preset:'day'|'night'='day',renderer?:THREE.WebGLRenderer,lampsOn=preset==='night',wet=false){
 const root=new THREE.Group();root.name='Harbor_Express_layout_v1';const loader=new GLTFLoader(),textures=new THREE.TextureLoader();
 const [kit,logo,asphalt,normal,rough,grass]=await Promise.all([loader.loadAsync('/assets/showcase-quality/kit.glb'),loader.loadAsync('/assets/brand/slingmods-sign.glb'),textures.loadAsync('/assets/showcase-quality/textures/p06c_asphalt_Diffuse.jpg'),textures.loadAsync('/assets/showcase-quality/textures/p06c_asphalt_nor_gl.jpg'),textures.loadAsync('/assets/showcase-quality/textures/p06c_asphalt_Rough.jpg'),textures.loadAsync('/assets/showcase-quality/textures/leafy_grass_Diffuse.jpg')]);
 asphalt.colorSpace=grass.colorSpace=THREE.SRGBColorSpace;for(const t of[asphalt,normal,rough,grass]){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=4}grass.repeat.set(160,160);
 const materials={road:new THREE.MeshStandardMaterial({map:asphalt,normalMap:normal,roughnessMap:rough,roughness:.9,normalScale:new THREE.Vector2(.35,.35)}),runoff:new THREE.MeshStandardMaterial({color:'#aaa293',roughness:1}),white:new THREE.MeshStandardMaterial({color:'#ede4ca',roughness:.8}),red:new THREE.MeshStandardMaterial({color:'#a82620',roughness:.8}),ground:new THREE.MeshStandardMaterial({map:grass,color:'#747b60',roughness:1}),rail:new THREE.MeshStandardMaterial({color:'#afb5b6',metalness:.35,roughness:.6}),water:new THREE.MeshStandardMaterial({color: preset==='day'?'#426f7a':'#173442',metalness:.3,roughness:.32})};
 const add=(g:THREE.BufferGeometry,m:THREE.Material,name:string)=>{const mesh=new THREE.Mesh(g,m);mesh.name=name;mesh.receiveShadow=true;root.add(mesh);return mesh};
 const ground=add(new THREE.PlaneGeometry(1344,1550),materials.ground,'Express_land');ground.rotation.x=-Math.PI/2;ground.position.set(-650,-.01,-400);
 const water=add(new THREE.PlaneGeometry(1500,1600),materials.water,'Express_water');water.rotation.x=-Math.PI/2;water.position.set(772,-.07,-400);
 add(buildExpressRibbon(-10.5,10.5,.004),materials.runoff,'Express_runoff');const road=add(buildExpressRibbon(-7.5,7.5,.014),materials.road,'Express_road'),flatPaint:THREE.Mesh[]=[];for(const side of[-1,1]){flatPaint.push(add(buildExpressRibbon(side*7.3,side*7.42,.025),materials.white,'Express_edge'));add(buildExpressRibbon(side*7.55,side*8.1,.015),materials.red,'Express_curb')}
 const boxes=new THREE.BoxGeometry(1,1,1),rails=new THREE.InstancedMesh(boxes,materials.rail,EXPRESS_ROUTE.colliders.length),matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion();EXPRESS_ROUTE.colliders.forEach((b,i)=>{matrix.compose(new THREE.Vector3().fromArray(b.center as number[]),quaternion.setFromAxisAngle(THREE.Object3D.DEFAULT_UP,b.yaw??0),new THREE.Vector3().fromArray(b.size as number[]));rails.setMatrixAt(i,matrix)});rails.name='Express_rails_exact_collision_boxes';rails.computeBoundingSphere();rails.receiveShadow=true;root.add(rails);
 // P11 armco, barriers, lights, fence and countdown boards replace the plain rail boxes visually; the boxes remain the collision truth.
 // P11 surface: true-scale race asphalt (ribbon UVs are 6 m per unit) and one merged decal layer with worn paint in place of
 // the flat white markings. Any failure here leaves the previous road exactly as it was.
 const surface=renderer?await Promise.all([loadRaceAsphalt(renderer,6,{wet}),loadRoadDecals(renderer,EXPRESS_ROUTE,{halfWidth:7.5,y:.016,lanePaint:{edge:7.36,centreDash:[6,18]},gridStation:0,wet})]).catch(error=>{console.warn('P11 road surface unavailable; keeping the previous road.',error);return undefined}):undefined;
 // After rain the painted kerbs and the concrete run-off shine too (visual only; the simulation's grip is untouched).
 if(wet)for(const m of[materials.runoff,materials.red,materials.white])m.roughness=.3;
 if(surface){road.material=surface[0].material;root.add(surface[1].mesh);flatPaint.forEach(m=>m.visible=false)}
 const trackside=renderer?await loadTrackside(renderer,planTrackside(EXPRESS_ROUTE,EXPRESS_TRACKSIDE),lampsOn).catch(error=>{console.warn('P11 trackside unavailable; keeping the plain rails.',error);return undefined}):undefined;if(trackside){root.add(trackside.group);rails.visible=false}
 const dashes:THREE.BufferGeometry[]=[];for(let d=12;d<EXPRESS_ROUTE.length;d+=18){const p=sampleRoad(EXPRESS_ROUTE,d),g=new THREE.PlaneGeometry(.13,7);g.rotateX(-Math.PI/2);g.rotateY(Math.atan2(p.dx,p.dz));g.translate(p.x,.026,p.z);dashes.push(g)}flatPaint.push(add(mergeGeometries(dashes)!,materials.white,'Express_center_dashes'));dashes.forEach(g=>g.dispose());
 // Extract current kit primitives, join same materials and instance within 160m cells.
 kit.scene.updateMatrixWorld(true);const library=new Map<string,Map<THREE.Material,THREE.BufferGeometry[]>>();kit.scene.traverse(o=>{if(!(o instanceof THREE.Mesh)||!o.name.startsWith('kit_'))return;const module=o.name.slice(4).split('__')[0];if(!EXPRESS_PLACEMENTS.some(p=>p.module===module)||o.name==='kit_gantry__Quality_Painted_White')return;const material=(Array.isArray(o.material)?o.material[0]:o.material)as THREE.MeshStandardMaterial;if(material.name==='Showcase_Practical_Atlas')material.emissiveIntensity=preset==='night'?1.1:.12;const by=library.get(module)??new Map(),gs=by.get(material)??[];gs.push(o.geometry.clone().applyMatrix4(o.matrixWorld));by.set(material,gs);library.set(module,by)});
 let instanceGroups=0;for(const [module,by]of library){const cells=new Map<string,ExpressPlacement[]>();for(const p of EXPRESS_PLACEMENTS.filter(p=>p.module===module)){const key=Math.floor(p.x/160)+':'+Math.floor(p.z/160),list=cells.get(key)??[];list.push(p);cells.set(key,list)}for(const [material,gs]of by){const geometry=gs.length===1?gs[0]:mergeGeometries(gs)!;if(gs.length>1)gs.forEach(g=>g.dispose());for(const [cell,placements]of cells){const mesh=new THREE.InstancedMesh(geometry,material,placements.length);placements.forEach((p,i)=>{matrix.compose(new THREE.Vector3(p.x,0,p.z),quaternion.setFromAxisAngle(THREE.Object3D.DEFAULT_UP,p.yaw),new THREE.Vector3().setScalar(p.scale));mesh.setMatrixAt(i,matrix)});mesh.name='Express_'+module+'_'+cell;mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();root.add(mesh);instanceGroups++}}}
 // Fit the unit-width logo plane to the gantry header face: kit header is .75 m tall, centred 4.6 m up, front face +.3 m,
 // all times the module scale. 12% of the face stays clear above and below; the plane's own proportions carry the artwork aspect.
 const gantry=EXPRESS_PLACEMENTS[0],sign=logo.scene,art=new THREE.Box3().setFromObject(sign).getSize(new THREE.Vector3());sign.position.set(gantry.x,4.6*gantry.scale,gantry.z+.3*gantry.scale+.005);sign.scale.setScalar(.75*gantry.scale*(1-2*.12)*art.x/art.y);root.add(sign);
 for(const metres of[200,150,100,50]){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle='#f4ede1';c.fillRect(0,0,256,256);c.fillStyle='#bd3229';c.fillRect(0,0,256,22);c.fillStyle='#17212a';c.font='bold 96px sans-serif';c.textAlign='center';c.fillText(String(metres),128,145);c.font='bold 28px sans-serif';c.fillText('BRAKE',128,209);const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;const sign=add(new THREE.PlaneGeometry(2,2),new THREE.MeshStandardMaterial({map,roughness:.8,side:THREE.DoubleSide}),'Express_brake_'+metres);sign.position.set(-9,1.6,-800+metres);sign.visible=!trackside}
 scene.add(root);let disposed=false;return {root,roadY:.014,wetSurfaces:surface?.[0].wet?[surface[0].wet]:[],reflectable:trackside?[trackside.group]:[],update(camera:THREE.Vector3,_time:number){trackside?.update(camera)},inspect:()=>({route:EXPRESS_DESIGN,placements:EXPRESS_PLACEMENTS.length,instanceGroups,kit:'/assets/showcase-quality/kit.glb',collisionAlignment:'Visible rails consume exact route collision boxes',trackside:trackside?.inspect()??null,surface:surface?{asphalt:surface[0].inspect(),decals:surface[1].inspect()}:null,source:'src/express/route.ts and presentation.ts; kit editable source assets/blender/showcase-quality/built-waterfront.blend'}),dispose(){if(disposed)return;disposed=true;trackside?.dispose();surface?.forEach(v=>v.dispose());materials.road.dispose();root.removeFromParent();const geometries=new Set<THREE.BufferGeometry>(),mats=new Set<THREE.Material>(),maps=new Set<THREE.Texture>();for(const tree of[root,kit.scene])tree.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m)}});for(const g of geometries)g.dispose();for(const m of mats){for(const v of Object.values(m))if(v instanceof THREE.Texture)maps.add(v);m.dispose()}for(const t of maps)t.dispose()}};
}
