import {ResultCamera} from './presentation/safe-camera';
import {CURRENT_HANDLING_PROFILE} from './simulation/profile';
import {PresentationTelemetry} from './presentation/interpolate';
import {PoweredDisplay} from './presentation/powered-display';
import {RaceCues} from './audio/actions';
import {CrashRecovery} from './driving/recovery';
import {evidenceEnabled} from './demo/profile';
import {pageActive} from './demo/recovery';
import {createHarborRenderer,harborDepth} from './presentation/harbor-renderer';
import {loadShowcaseHarbor} from './presentation/showcase';
import './crew.css';
import {CrewUI} from './crew-ui';
import {CrewRace,createCrewGrid,RivalController} from './competition';
import {type CrewAwardProof} from './career/crew-result';
import {type DuelAwardProof} from './career/duel-result';
import {prepareRenderer,preparationVeil} from './presentation/prepare';
import {RuntimeProfile} from './presentation/runtime-profile';
import {careerClient,RAE} from './career/client';
import {SuspensionPresenter} from './presentation/suspension';
import {ProductPresenter} from './presentation/product';
import './career/build.css';
import {CURRENT_VEHICLE} from './presentation/vehicle-asset';
import './style.css';import './harbor.css';
import * as THREE from 'three';import {GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import {loadOutdoorEnvironment}from'./presentation/outdoor-environment';
import {RaceWorld,FIXED_DT,type VehicleControl,type VehicleTelemetry}from'./simulation';import{DrivingSession}from'./driving/session';import{KeyboardBuffer,type DeviceSample}from'./driving/input';
import{createCourseEnvironment,type CourseRoute,type CourseBox}from'./course/environment';import{RaceAttempt}from'./race/attempt';import{loadSave,writeSave,recordKey,saveBest,browserStorage}from'./save';
import{DrivingCamera,nextDrivingView,type DrivingView}from'./presentation/driving-camera';import{loadDrivingHero}from'./presentation/hero';import{harborLighting}from'./presentation/harbor-lighting';import{assetStatistics}from'./presentation/statistics';import{GameAudio,renderOfflineGameAudio}from'./audio/game-audio';import{type MenuAction}from'./harbor-ui';
const handlingProfile=CURRENT_HANDLING_PROFILE;
const params=new URLSearchParams(location.search),test=params.has('test'),controlled=test&&params.get('clock')==='controlled',preset='night' as const,quality=params.get('quality')==='low'?'low':'standard';
const duel=params.get('event')==='duel',rivalIds=duel?['maya']:['maya','jett','nico'];
const started=performance.now();const profile=new RuntimeProfile(params.has('profile'));document.body.className='harbor-race';const app=document.querySelector('#app')!;app.innerHTML='<div id="viewport"></div>';const veil=preparationVeil(app);let prepared=false;
const renderer=createHarborRenderer(params.has('captureBuffer'));renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?1:1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=preset==='night'?1.05:.95;app.querySelector('#viewport')!.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.06,1600),loader=new GLTFLoader();const outdoor=await loadOutdoorEnvironment(scene,renderer,preset);
const [route,world,hero]=await Promise.all([fetch('/assets/harbor/route.json').then(r=>r.json() as Promise<CourseRoute>),loader.loadAsync('/assets/harbor/harbor.glb'),loadDrivingHero(loader)]);
const career=await careerClient();if(!career.state.chapters.firstCompletion||!duel&&!career.state.buildMatters.legacyCrewAccess&&!career.state.buildMatters.duelCompleted){career.navigate('?scene=bay');await new Promise(()=>{})}const product=await ProductPresenter.load(loader,hero.root,scene);product.set(career.state.equipped,career.state.appearance);const unsubCareer=career.subscribe(()=>product.set(career.state.equipped,career.state.appearance));
scene.add(world.scene,hero.root);world.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.receiveShadow=true;o.castShadow=!(Array.isArray(o.material)?o.material:[o.material]).every(m=>/asphalt|ground|land|water|paint|runoff/i.test(m.name));for(const material of(Array.isArray(o.material)?o.material:[o.material])){const m=material as THREE.MeshStandardMaterial;if(m.map){m.map.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy())}if(m.emissive&&/lamp|lumin|emissive|light/i.test(m.name))m.emissiveIntensity=preset==='night'?2:.08}}});
const showcase=await loadShowcaseHarbor(scene,world.scene,preset,params.get('showcase')==='sample'?'sample':'full');
const worldStatistics=assetStatistics(showcase.root),gl=renderer.getContext(),rendererIdentity=gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info')?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);
const liveries:Record<string,[string,string]>={maya:['#d7dddd','#57bab7'],jett:['#6d161e','#aa3838'],nico:['#3c444c','#e9b454']};const rivals=Object.fromEntries(rivalIds.map(id=>[id,hero.cloneRival(...liveries[id])]));for(const r of Object.values(rivals))scene.add(r.root);
const suspension=await SuspensionPresenter.load(loader,hero.asset);suspension.set(career.state.suspension.equipped);
const lights=harborLighting(scene,hero.asset,route,preset,quality),physics=await RaceWorld.create(createCourseEnvironment(route),handlingProfile),save=loadSave(browserStorage()),race=new CrewRace(route,[...rivalIds,'player'],'player',duel,{handlingProfileId:handlingProfile}),grid=createCrewGrid(route,[...rivalIds,'player']);
for(const [id,pose]of Object.entries(grid))physics.addVehicle(id,pose);
physics.get('player').configureSuspension(career.state.suspension.equipped?career.state.suspension.setup:null);
let controllers=Object.fromEntries(rivalIds.map(id=>[id,new RivalController(route,id,Number(params.get('seed')??1),handlingProfile)]));
let previousField=physics.telemetry(),currentField=previousField,controlMs=0,physicsMs=0,attempt=0;const crewCosts:number[][]=[];let lastControlMs=0,lastPhysicsMs=0;
let introUntil:number|null=null,seenIntro=false;
const sim={telemetry:()=>physics.get('player').telemetry(),reset:()=>{for(const [id,pose]of Object.entries(grid))physics.get(id).reset(pose);controllers=Object.fromEntries(rivalIds.map(id=>[id,new RivalController(route,id,Number(params.get('seed')??1),handlingProfile)]));previousField=currentField=physics.telemetry()},step:(playerControl:VehicleControl,dt=FIXED_DT)=>{previousField=currentField;let begin=performance.now();const controls:Record<string,VehicleControl>={player:race.control('player',playerControl)};for(const [id,c]of Object.entries(controllers)){const r=race.snapshot(),standing=r.standings.find(s=>s.id===id)!,active=(r.phase==='running'||r.phase==='finished')&&(standing.status==='running'||standing.status==='finished'&&r.elapsedMs-standing.timeMs!<15000);controls[id]=race.control(id,active?c.control(currentField[id],currentField,dt):{throttle:0,brake:1,steer:0,reverse:false});if(active&&c.inspect().retiredReason)race.retire(id,c.inspect().retiredReason!)}controlMs+=performance.now()-begin;begin=performance.now();physics.step(controls,dt);currentField=physics.telemetry();physicsMs+=performance.now()-begin;race.tick(previousField,currentField,dt)}};
let attemptId:string|null=null,rewardPending=false,rewardText='',rewardStory='',rewardId:string|null=null;
let cameraMode:DrivingView=save.settings.camera,lookBack=false,virtual:DeviceSample|undefined,resetPresentation=true,committedAttempt=-1,persisted:boolean|null=null,confirmBlocked=false,debugVisible=false;const keyboard=new KeyboardBuffer(),menuEdges=new Set<string>(),releaseKeys=new Set<string>();
const display=new PoweredDisplay(hero.asset),raceCues=new RaceCues();display.snapshot(renderer,scene.environment,JSON.stringify(career.state.appearance));
const audio=new GameAudio(app),chase=new DrivingCamera(camera,handlingProfile);chase.eye.fromArray(hero.attachment.eye);chase.cockpitPitch=-.26;chase.cockpitFov=76;
const sourceSample=():DeviceSample=>{if(virtual)return virtual;const state=keyboard.read(),pressedKeys=new Set([...state.pressedKeys,...menuEdges]);menuEdges.clear();return{...state,keys:new Set([...state.keys,...releaseKeys]),pressedKeys,pads:typeof navigator.getGamepads==='function'?Array.from(navigator.getGamepads()):[],focused:document.hasFocus()&&!document.hidden}};
const resultCamera=new ResultCamera(camera,route.heightAt);const ui=new CrewUI(app,menuAction,duel,{route});if(!career.durable){const note=document.createElement('small');note.className='career-session';note.textContent='Session only — progress cannot be saved';app.append(note)}let sampled:DeviceSample={keys:new Set(),pads:[],focused:true};
const session=new DrivingSession(sim,()=>sampled,{profileId:handlingProfile,canReset:()=>!rewardPending,afterTick:()=>{const result=race.snapshot().playerResult;if(result?.valid&&result.timeMs&&attemptId&&rewardId!==attemptId){rewardId=attemptId;void awardFinish()}},onReset:()=>{attemptId=crypto.randomUUID();attempt++;rewardText='';rewardStory='';race.restart(attemptId);for(const k of keyboard.held)releaseKeys.add(k);keyboard.clear();resetPresentation=true;persisted=null},onPause:p=>race.setPaused(p)});
function menuAction(action:MenuAction){if(!prepared||rewardPending)return;profile.mark(action,{ticks:session.ticks});if(action==='bay'){race.abort();career.navigate('?scene=bay');return}if(action==='resume'){if(race.snapshot().phase==='ready'){session.input.paused=false;session.input.armed=false;race.setPaused(false);introUntil=null;return}session.input.paused=!session.input.paused;session.input.armed=false;race.setPaused(session.input.paused);audio.lifecycle(session.input.paused);confirmBlocked=true;return}
 if(!seenIntro&&introUntil===null){seenIntro=true;introUntil=performance.now()+6000;return}introUntil=null;session.input.paused=false;session.reset();confirmBlocked=true;committedAttempt=-1;}
const recovery=new CrashRecovery(app,route,false,()=>{if(!rewardPending){session.input.paused=false;session.reset();resetPresentation=true}});
physics.initialize();previousField=currentField=physics.telemetry();session.sync();
/** Ray against the same oriented boxes used by Rapier; decorative ground/water never blocks the camera. */
function obstruction(origin:THREE.Vector3,desired:THREE.Vector3){const delta=desired.clone().sub(origin),length=delta.length();if(length<1e-6)return;let nearest=Infinity;for(const box of route.colliders){if(box.size[1]<.1)continue;const yaw=box.yaw??0,c=Math.cos(yaw),s=Math.sin(yaw),dx=origin.x-box.center[0],dz=origin.z-box.center[2],o=[c*dx-s*dz,origin.y-box.center[1],s*dx+c*dz],d=[c*delta.x-s*delta.z,delta.y,s*delta.x+c*delta.z];let lo=0,hi=1;for(let i=0;i<3;i++){const half=box.size[i]/2;if(Math.abs(d[i])<1e-9){if(Math.abs(o[i])>half){lo=2;break}}else{const a=(-half-o[i])/d[i],b=(half-o[i])/d[i];lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b))}}if(lo<=hi&&lo>=0&&lo<=1)nearest=Math.min(nearest,lo*length)}return Number.isFinite(nearest)?nearest:undefined}
let lastInput:ReturnType<DrivingSession['frame']>|undefined,audioFrame:ReturnType<GameAudio['update']>|undefined;const frameTimes:number[]=[];let lastWall:number|undefined;
const presentationTelemetry=new PresentationTelemetry();
function present(dt:number,alpha:number,reset:boolean,raster:boolean){const t=presentationTelemetry.sample(session.previous,session.current,alpha);hero.pose(t,dt,cameraMode==='cockpit'&&!lookBack&&!(!!race.snapshot().playerResult&&!race.snapshot().paused),reset);chase.update(hero.root.position,hero.root.quaternion,session.current.speed,dt,cameraMode,lookBack,reset,obstruction);for(const [id,r]of Object.entries(rivals)){const t=structuredClone(currentField[id]),p=previousField[id];for(const k of ['x','y','z'] as const)t.position[k]=THREE.MathUtils.lerp(p.position[k],t.position[k],alpha);r.pose(t,dt,false,reset)}lights.update(hero.root.position,session.current.brake);suspension.update();product.update();audioFrame=audio.update(session.current,session.input.paused||race.snapshot().phase==='ready',cameraMode==='cockpit'&&!lookBack,reset);audio.updateOpponents(session.current,Object.fromEntries(Object.entries(currentField).filter(([id])=>id!=='player')));display.update(session.current,camera,performance.now());raceCues.update(race.snapshot(),id=>audio.cue(id));
 recovery.update(session.current,dt,race.snapshot().phase!=='ready'&&!race.snapshot().playerResult?.valid);
 showcase.update(camera.position,session.current.time);
 if(raster){const renderStart=performance.now();resultCamera.update(hero.root,!!race.snapshot().playerResult&&!race.snapshot().paused,innerWidth,innerHeight);renderer.render(scene,camera);profile.renderMs=performance.now()-renderStart;ui.setMapPeers(currentField);ui.update(race.snapshot(),session.current,session.input.armed,chase.activeView,introUntil,rewardText,rewardStory,rewardPending);renderReward();const heading=new THREE.Euler().setFromQuaternion(hero.root.quaternion,'YXZ').y,c=Math.cos(heading),sn=Math.sin(heading);ui.setProximity(Object.entries(currentField).filter(([id])=>id!=='player').map(([id,peer])=>{const dx=peer.position.x-session.current.position.x,dz=peer.position.z-session.current.position.z,p=new THREE.Vector3(peer.position.x,peer.position.y+.75,peer.position.z).project(camera);return{id,right:c*dx-sn*dz,forward:-sn*dx-c*dz,inView:p.z>-1&&p.z<1&&Math.abs(p.x)<.86&&Math.abs(p.y)<.8}}),chase.activeView);const debug=app.querySelector<HTMLElement>('#race-debug')!;debug.hidden=!debugVisible;if(debugVisible)debug.textContent=`${__BUILD_REF__} / ${preset} / ${quality}\n${renderer.info.render.calls} calls · ${renderer.info.render.triangles} submitted triangles\n${session.ticks} physics ticks · ${session.current.wheels.map(w=>w.surface).join('/')}`}}
function normalFrame(now:number,raster=true){sampled=sourceSample();ui.menuInput(sampled,race.snapshot());if(confirmBlocked){const held=sampled.pads.some(p=>p&&(p.buttons[0]?.value??0)>.5);if(!held)confirmBlocked=false;else sampled={...sampled,pads:sampled.pads.map(p=>p?{...p,buttons:p.buttons.map((b,i)=>i===0?{value:0,pressed:false}:b)}:p)}}
 if(introUntil!==null&&now>=introUntil)menuAction('start');
 if(race.snapshot().phase==='ready'){present(1/60,1,resetPresentation,raster);resetPresentation=false;return}
 lastInput=session.frame(now);if(lastInput.camera){cameraMode=nextDrivingView(cameraMode);const saved=loadSave(browserStorage());saved.settings.camera=cameraMode;writeSave(browserStorage(),saved)}lookBack=lastInput.lookBack;
 present(lastInput.dt,lastInput.alpha,resetPresentation||lastInput.reset,raster);resetPresentation=false;
}
function suspend(){keyboard.clear();ui.suspendInput();menuEdges.clear();session.input.suspend();race.setPaused(true);audio.lifecycle(true);ui.setMapPeers(currentField);ui.update(race.snapshot(),session.current,false,chase.activeView,introUntil,rewardText,rewardStory,rewardPending)}
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['Enter','Backspace'].includes(e.code)){if(e.target instanceof Element&&e.target.closest('button,a'))return;if(!e.repeat)menuEdges.add(e.code)}if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','Backspace'].includes(e.code))e.preventDefault();keyboard.down(e.code,performance.now(),e.repeat);if(evidenceEnabled()&&e.code==='KeyI'&&!e.repeat)debugVisible=!debugVisible});addEventListener('keyup',e=>{keyboard.up(e.code);releaseKeys.delete(e.code)});addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend()});addEventListener('gamepaddisconnected',()=>{session.input.disconnect();suspend()});
present(1/60,1,true,false);profile.mark('preparation-start',{ticks:session.ticks,race:race.snapshot()});
const preparation=await product.prepare(()=>prepareRenderer(renderer,scene,camera));
prepared=true;present(1/60,1,true,true);const loadMs=performance.now()-started;veil.remove();lastWall=undefined;profile.mark('preparation-end',{...preparation,ticks:session.ticks,race:race.snapshot()});
function animate(now:number){if(!pageActive())return;if(!controlled){const begin=performance.now();const d=lastWall===undefined?0:now-lastWall;lastWall=now;if(frameTimes.length<1800)frameTimes.push(d);normalFrame(now);profile.frame(now,d,performance.now()-begin,session.ticks,{...race.snapshot(),attempt},chase.activeView,renderer,scene);if(profile.enabled&&crewCosts.length<30000){const collect=performance.now();crewCosts.push([now,controlMs-lastControlMs,physicsMs-lastPhysicsMs,physics.steps,physics.participants.size,renderer.info.render.calls,renderer.info.render.triangles,renderer.info.memory.geometries,renderer.info.memory.textures,performance.now()-collect]);lastControlMs=controlMs;lastPhysicsMs=physicsMs}}requestAnimationFrame(animate)}requestAnimationFrame(animate);
profile.mark('load-ready',{loadMs});
const inspect=()=>({handlingProfile,profileContract:{simulation:physics.profileId,input:session.input.profileId},display:display.inspect(),simulationSuspension:physics.get('player').suspensionConfig(),renderDepth:harborDepth(renderer),showcase:showcase.inspect(),attemptId,career:career.state,careerDurable:career.durable,rewardPending,rewardText,suspension:suspension?.inspect(),product:product.inspect(),memory:{...renderer.info.memory},commit:__BUILD_REF__,preset,quality,telemetry:session.current,race:race.snapshot(),camera:{mode:cameraMode,active:chase.activeView,position:camera.position.toArray(),target:chase.target.toArray(),fov:camera.fov,aspect:camera.aspect},rear:hero.rear.inspect(),rivals:Object.fromEntries(Object.entries(rivals).map(([id,r])=>[id,{resources:r.resources,driver:r.driver.inspect(),rear:r.rear.inspect()}])),asset:CURRENT_VEHICLE,driver:hero.driver.inspect(),driverProjection:Object.fromEntries(Object.entries(hero.driver.inspect().arms??{}).map(([side,a])=>[side,new THREE.Vector3().fromArray((a as any).contact).project(camera).toArray()])),audio:audio.inspect(),audioFrame,lighting:lights.inspect(),lightBudget:lights.budget,ticks:session.ticks,inputState:lastInput?{...lastInput,current:undefined,previous:undefined}:null,field:currentField,worldSteps:physics.steps,participants:physics.participants.size,controllers:Object.fromEntries(Object.entries(controllers).map(([id,c])=>[id,c.inspect()])),persisted,renderInfo:{...renderer.info.render},frameTimes:[...frameTimes],loadMs,statistics:{...hero.statistics,world:worldStatistics},renderer:rendererIdentity});
if(evidenceEnabled())(window as any).__CREW={ready:true,inspect,lightweight:()=>({telemetry:session.current,race:race.snapshot(),ticks:session.ticks,attemptId,field:currentField}),profile:()=>({...profile.export(),crewCostColumns:['rafMs','controlMs','physicsMs','worldSteps','participants','calls','triangles','geometries','textures','collectorMs'],crewCosts,worldSteps:physics.steps,participants:physics.participants.size,controlMs,physicsMs,loadMs,preparation,buffer:renderer.getContext().getContextAttributes(),size:renderer.getDrawingBufferSize(new THREE.Vector2()).toArray(),dpr:renderer.getPixelRatio(),renderer:rendererIdentity}),normalFrame:(now:number,raster=true)=>{if(!controlled)throw Error('Controlled test clock required');normalFrame(now,raster);return inspect()},setDeviceSample:(sample:any)=>{if(!test)throw Error('Isolated test context required');virtual=sample?{...sample,keys:new Set(sample.keys)}:undefined},startAudioCapture:()=>{if(!test)throw Error('Isolated test context required');return audio.startEvidenceCapture()},audioSync:(id:string)=>{if(!test)throw Error('Isolated test context required');return audio.evidenceMarker(id)},stopAudioCapture:()=>{if(!test)throw Error('Isolated test context required');return audio.stopEvidenceCapture()},renderOfflineAudio:(timeline:Parameters<typeof renderOfflineGameAudio>[0],duration:number)=>{if(!test)throw Error('Test context required');return renderOfflineGameAudio(timeline,duration)},referenceCamera:(position:number[],target:number[],fov=45)=>{if(!test)throw Error('Test context required');scene.fog=null;camera.position.fromArray(position);camera.fov=fov;camera.updateProjectionMatrix();camera.lookAt(new THREE.Vector3().fromArray(target));renderer.render(scene,camera)},route};
addEventListener('resize',()=>{if(!pageActive())return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);present(0,lastInput?.alpha??1,false,true)});addEventListener('pagehide',()=>{display.dispose();recovery.dispose();unsubCareer();career.close();suspension.dispose();product.dispose();audio.dispose();Object.values(rivals).forEach(r=>r.dispose());physics.dispose();showcase.dispose();lights.dispose();outdoor.dispose();renderer.dispose()});

async function awardFinish(){if(rewardPending)return;const result=race.snapshot().playerResult;if(!result?.valid)return;rewardPending=true;rewardText='Saving crew credits…';try{const proof=race.awardProof();if(!proof)throw Error('No certified race result');const r=await career.execute(duel?{type:'duel-award',result:proof as DuelAwardProof,handlingProfile}:{type:'crew-award',result:proof as CrewAwardProof,handlingProfile});if(r.changed&&r.receipt)audio.cue('career.unlock','award:'+attemptId);rewardText=r.receipt?`+${r.receipt.amount-(r.receipt.chapterBonus??0)} placement + ${r.receipt.chapterBonus??0} ${duel?'first clean duel':'first podium'} = ${r.receipt.amount} game credits · Balance ${r.state.credits}`:'Result already recorded';rewardStory=r.story?RAE[r.story]:''}catch(e){rewardText='Credits could not be saved. Retry saving or return without this award.'}finally{rewardPending=false}}
function renderReward(){const menu=app.querySelector<HTMLElement>('#race-menu');if(!menu||!rewardText.startsWith('Credits could not')||menu.querySelector('#crew-retry-save'))return;const retry=document.createElement('button');retry.id='crew-retry-save';retry.textContent='Retry saving credits';retry.onclick=()=>void awardFinish();menu.append(retry)}
