import {RaceInstruments,raceHeader,tachMarkup,displayedGear} from './signature/race-instruments';
import {nudgeMenuControl} from './career/menu';
import type {CourseRoute} from './course/environment';
import {RouteAid} from './signature/route-aid';
import {installRaceMenuFocus} from './signature/race-accessibility';
import {activeProfile,sceneHref} from './demo/profile';
import type{CrewRace}from './competition';import type{VehicleTelemetry}from './simulation';import type{DeviceSample}from './driving/input';import {raceTime,type MenuAction}from './harbor-ui';
import {proximityCues,type NearbyVehicle}from './crew-proximity';
export interface CrewUIOptions {title?:string;subtitle?:string;preview?:boolean;career?:boolean;freeDrive?:boolean;trial?:boolean;route?:CourseRoute}
type State=ReturnType<CrewRace['snapshot']>;
const names:Record<string,string>={player:'YOU',maya:'MAYA',jett:'JETT',nico:'NICO'};
export class CrewUI {
 readonly root=document.createElement('div');private key='';private confirm=false;private back=false;private armed=false;private padKey='';private orderKey='';private proximityKey='';private pending=false;private routeAid:RouteAid;private navHeld=[false,false];private horizontalHeld=[false,false];private nodes=new Map<string,HTMLElement>();private values=new Map<string,string>();private displayTime=-Infinity;private instruments:RaceInstruments;
 private node(selector:string){let n=this.nodes.get(selector);if(!n){n=this.root.querySelector<HTMLElement>(selector)!;this.nodes.set(selector,n)}return n}
 private text(selector:string,value:string){if(this.values.get(selector)===value)return;this.values.set(selector,value);this.node(selector).textContent=value}
 constructor(parent:Element,private action:(a:MenuAction)=>void,private duel=false,private options:CrewUIOptions={}){this.root.id='harbor-ui';this.root.innerHTML=raceHeader(this.options.title??(this.duel?'MAYA DUEL':'HARBOR CREW'))+'<details id="crew-order" aria-label="Race order"><summary>Standings</summary><div class="crew-rows"></div></details><aside id="crew-proximity" aria-label="Nearby traffic" hidden></aside><div id="race-banner" aria-live="polite"></div><aside class="race-gauges">'+tachMarkup()+'</aside><section id="race-menu" aria-label="Crew race menu"></section><div id="race-debug" hidden></div>';this.instruments=new RaceInstruments(this.root);if(this.options.title)this.root.querySelector('.race-label')!.textContent=this.options.title.toUpperCase();if(this.duel)this.root.querySelector('.race-label')!.textContent='SLINGMODS / MAYA DUEL';parent.append(this.root);installRaceMenuFocus(this.root);this.routeAid=new RouteAid(this.root,options.route);this.root.querySelector('#race-pause')!.addEventListener('click',()=>this.action('resume'));this.root.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button[data-action]');if(b&&!b.disabled&&!this.pending)this.action(b.dataset.action as MenuAction)})}
 update(s:State,t:VehicleTelemetry,armed:boolean,view:string,intro:number|null,reward:string,story:string,pending:boolean){this.pending=pending;this.routeAid.update(t);this.instruments.update(t);const find=(s:string)=>this.node(s);const p=s.standings.find(x=>x.id==='player')!;const now=performance.now();if(now-this.displayTime>=100||s.phase!=='running'||s.paused){this.displayTime=now;this.text('#race-time',raceTime(s.playerResult?.timeMs??s.elapsedMs));this.text('#race-position',String(p.place));this.text('#race-field',String(s.standings.length));this.text('#race-lap',String(Math.min(s.laps,p.lap)));this.text('#race-laps',String(s.laps));this.text('#race-progress',this.options.freeDrive?'TEST DRIVE · NO CAREER REWARDS':'');this.text('#race-speed',String(Math.round(Math.abs(t.speed)*2.23694)));this.text('#race-gear',displayedGear(t.gear,t.powertrain));const reverse=t.gear<0;if(find('.race-gauges').classList.contains('is-reverse')!==reverse)find('.race-gauges').classList.toggle('is-reverse',reverse);this.text('#race-rpm',String(Math.round(t.rpm)))}find('#crew-order').hidden=!!this.options.freeDrive;const ahead=s.standings.find(x=>x.place===p.place-1);this.text('#crew-order summary',ahead?`${names[ahead.id]} AHEAD · STANDINGS`:'LEADING · STANDINGS');const orderKey=s.standings.map(x=>[x.id,x.place,x.status,x.lap,x.timeMs].join(':')).join('/');if(orderKey!==this.orderKey){this.orderKey=orderKey;find('#crew-order .crew-rows').innerHTML=s.standings.map(x=>`<div class="crew-${x.id}"><b><i>${x.place}</i> ${names[x.id]}</b><span>${x.status==='finished'?raceTime(x.timeMs!):x.status==='running'?`L${Math.min(s.laps,x.lap)}`:x.status==='invalid'?'INVALID':x.status.toUpperCase()}</span></div>`).join('')}find('#race-banner').classList.toggle('notice',!armed&&s.phase==='running'&&!s.paused);this.text('#race-banner',intro!==null?'':s.phase==='countdown'?String(Math.ceil(s.countdown)):s.phase==='running'&&s.elapsedMs<1000?'GO':!armed&&s.phase==='running'&&!s.paused?'Release controls to continue':'');
 const key=[s.phase,s.paused,intro!==null,s.playerResult?.status,s.allFinished,reward,story,pending].join('/');if(key===this.key)return;this.key=key;const menu=find('#race-menu'),shown=s.phase==='ready'||s.phase==='finished'||s.paused;menu.hidden=!shown;document.body.classList.toggle('race-menu-open',shown);document.body.classList.toggle('race-results-open',!!s.playerResult&&!s.paused);if(!shown)return;
 let title='First Night at the Harbor',lead='Two laps after dark. Finish in the top three to earn your place. Your stock build is welcome.',button='Meet the grid',action='start';
 if(this.options.preview||this.options.career){title=this.options.title??'Harbor Express';lead=this.options.subtitle??'Your preview build. One waterfront lap. No career credits are spent or earned.';button=this.options.career?'Start career event':this.options.freeDrive?'Start Test Drive':this.options.trial?'Start Time Attack':'Start Quick Race'}
 if(this.duel){title='Maya / Find your line';lead='One clean lap beside Maya earns 500 first-duel credits + 150 finish / 250 win. Fund your suspension, then meet the full crew.';button='Meet Maya'}
 if(intro!==null&&!this.options.preview){title='Maya. Jett. Nico. You.';lead='JETT: Hope you saved some speed for the corners.<br>MAYA: He says that right before braking too late.';button='Start race';if(this.duel){title='Precision before pace';lead='MAYA: Brake once. Turn once. Leave room for both of us.<br>RAE: Bring it back clean and the workshop fund is yours.'}button='Skip dialogue · Start race';}
 else if(s.paused){title='Take a breath';lead='Every car and the clock are paused. Release controls before continuing.';button='Continue';action='resume'}else if(s.playerResult){const r=s.playerResult;title=r.valid?'Race complete':'This run will not count';lead=r.valid?`<strong class="result-time">${raceTime(r.timeMs!)}</strong>${reward||'Checking result…'}<small>${story}</small>`:`${r.invalidReason??r.status}. No crew credits.<small>RAE: That one won’t count. Reset, take a breath, and give me a clean run.</small>`;button='Race again';action='retry'}
 if(this.options.preview&&s.playerResult){const r=s.playerResult;title=r.valid?(this.options.freeDrive?'Test drive complete':'Race complete'):'Practice complete';lead=`<strong class="result-time">${raceTime(r.timeMs??s.elapsedMs)}</strong>No career rewards · Free preview build<small>${r.valid?'Your build is ready for another run.':'Try again for a clean run.'}</small>`;button=this.options.freeDrive?'Drive again':this.options.trial?'Retry':'Race again';action='retry'}
 menu.dataset.phase=s.playerResult?'result':s.paused?'pause':'ready';document.body.classList.toggle('race-results-open',!!s.playerResult&&!s.paused);menu.dataset.place=s.playerResult?.valid?String(s.playerResult.place):'—';menu.innerHTML=`<span class="race-label">${this.options.career?(s.event.startsWith('p10a-')?'CHAPTER 03 / RIDGE RUN':s.event.startsWith('p09a-')?'CHAPTER 02 / OWN THE BUILD':'CHAPTER 01 / BUILD MATTERS'):this.options.preview?'SLINGMODS / FREE PREVIEW':activeProfile()==='demo'?'PREPARED DEMO / HARBOR CREW':'CHAPTER 01 / FIRST NIGHT'}</span><span class="result-numeral" aria-hidden="true">${s.playerResult?.valid?s.playerResult.place:'—'}<small>${s.playerResult?.valid?'PLACE':'NOT CLASSIFIED'}</small></span><h1>${title}</h1><p>${lead}</p>${s.playerResult?this.resultRows(s):''}<div class="menu-actions"><button class="primary" data-action="${action}" id="start-crew" ${pending?'disabled':''}>${button}</button><button data-action="bay" ${pending?'disabled':''}>Back to Showroom</button>${!pending?'<a class="shop-build-route" href="?scene=signature&amp;screen=events">Change Event</a>':''}${s.playerResult&&!pending&&!this.options.preview&&!this.options.career?`<a class="shop-build-route" href="${sceneHref('bay','&shop=build')}">Shop This Build</a>`:''}</div><details class="race-help" ${s.phase==='ready'&&activeProfile()==='demo'?'open':''}><summary>Controls &amp; race rules</summary><p>W / S pedals · A / D steering · C camera · hold B look back · Esc pause · X reverse / drive · hold R one second to restart.</p><p>Controller: RT / LT pedals · left stick steering · top face camera · hold LB look back · right face reverse / drive · Menu pause.</p><p>${this.options.freeDrive?'Explore freely. No lap validation or finish requirement.':(s.laps===1?'One clean lap':'Two clean laps')+' through every checkpoint.'} Stay within the course. ${this.options.preview?'No career rewards in free preview.':'Credits are awarded only for a valid finish.'}</p><p><strong>Reverse:</strong> Brake to stop. Release pedals, then press S / LT again to reverse. W / RT brakes reverse; release and press again for forward. Holding the brake never selects reverse. X / right face selects direction directly.</p><small>Enter / bottom face confirm · Backspace / right face showroom</small></details>`;
 }
 setMapPeers(field:Record<string,VehicleTelemetry>){this.routeAid.updatePeers(field)}
 private resultRows(s:State){const leader=s.standings.find(x=>x.place===1&&x.status==='finished');return `<div class="result-standings" aria-label="Final standings">${s.standings.map(x=>`<div class="crew-${x.id}"><b>${x.place}</b><span>${names[x.id]}</span><strong>${x.status==='finished'?(x.place===1?raceTime(x.timeMs!):leader?`+${((x.timeMs!-leader.timeMs!)/1000).toFixed(3)}`:raceTime(x.timeMs!)):x.status==='running'?'Finishing…':x.status.toUpperCase()}</strong></div>`).join('')}</div>`}
 setProximity(peers:readonly NearbyVehicle[],view:string){const cues=proximityCues(peers,view),key=cues.map(c=>c.side+':'+c.id).sort().join('/');if(key===this.proximityKey)return;this.proximityKey=key;const root=this.root.querySelector<HTMLElement>('#crew-proximity')!;root.hidden=!cues.length;root.innerHTML=cues.map(c=>`<span class="nearby-${c.side} crew-${c.id}"><i aria-hidden="true">${c.side==='left'?'‹':c.side==='right'?'›':'⌄'}</i>${names[c.id]} <small>${c.side==='rear'?'BEHIND':c.side.toUpperCase()}</small></span>`).join('')}
 suspendInput(){this.armed=false;this.padKey='';this.confirm=false;this.back=false}
 menuInput(sample:DeviceSample,s:State){
  if(typeof document!=='undefined'&&document.body?.dataset.gxModal){this.armed=false;this.confirm=true;this.back=true;return}
  const p=sample.pads.find(x=>x?.connected&&x.mapping==='standard'),key=p?`${p.index}:${p.id}`:'';
  if(!sample.focused||!p||key!==this.padKey)this.armed=false;this.padKey=key;
  if(sample.focused&&p&&p.buttons.every(b=>b.value<.02)&&p.axes.every(a=>Math.abs(a)<.15))this.armed=true;
  const active=document.activeElement,interactive=active instanceof Element&&active.closest('button,a,input,select,summary');
  const confirm=(!interactive&&sample.keys.has('Enter'))||(this.armed&&(p?.buttons[0]?.value??0)>.5),back=sample.keys.has('Backspace')||(this.armed&&(p?.buttons[1]?.value??0)>.5);
  const nav=[this.armed&&((p?.buttons[12]?.value??0)>.5||(p?.buttons[14]?.value??0)>.5||(p?.axes[1]??0)<-.6),this.armed&&((p?.buttons[13]?.value??0)>.5||(p?.buttons[15]?.value??0)>.5||(p?.axes[1]??0)>.6)];
  if(!this.pending&&sample.focused&&(s.phase==='ready'||s.phase==='finished'||s.paused)){
   const scope=this.root?.querySelector<HTMLElement>('#race-menu');const horizontal=[this.armed&&(p?.buttons[14]?.value??0)>.5,this.armed&&(p?.buttons[15]?.value??0)>.5],direction=horizontal[0]&&!this.horizontalHeld[0]?-1:horizontal[1]&&!this.horizontalHeld[1]?1:0;this.horizontalHeld=horizontal;const adjusted=!!direction&&nudgeMenuControl(direction);
   if(adjusted){}else if(scope&&nav.some((held,i)=>held&&!this.navHeld?.[i])){const options=[...scope.querySelectorAll<HTMLElement>('button:not(:disabled),a,summary'),...document.querySelectorAll<HTMLElement>('#game-audio button:not(:disabled),#game-audio input,#game-audio summary')].filter(e=>!e.hidden&&!!e.getClientRects().length),index=options.indexOf(active as HTMLElement),direction=nav[0]?-1:1;if(options.length)options[(index+direction+options.length)%options.length].focus()}
   else if((!interactive&&sample.pressedKeys?.has('Enter'))||confirm&&!this.confirm){if(interactive&&(scope?.contains(active)||active?.closest('#game-audio'))&&active instanceof HTMLElement)active.click();else this.action(s.paused?'resume':s.phase==='finished'?'retry':'start')}
   else if(sample.pressedKeys?.has('Backspace')||back&&!this.back)this.action('bay');
  }
  this.confirm=confirm;this.back=back;this.navHeld=nav;
 }

}
