import type{CrewRace}from './competition';import type{VehicleTelemetry}from './simulation';import type{DeviceSample}from './driving/input';import {raceTime,type MenuAction}from './harbor-ui';
type State=ReturnType<CrewRace['snapshot']>;
const names:Record<string,string>={player:'YOU',maya:'MAYA',jett:'JETT',nico:'NICO'};
export class CrewUI {
 readonly root=document.createElement('div');private key='';private confirm=false;private back=false;private armed=false;private padKey='';
 constructor(parent:Element,private action:(a:MenuAction)=>void){this.root.id='harbor-ui';this.root.innerHTML='<div class="race-top"><div><span class="race-label">FIRST NIGHT / HARBOR CREW</span><strong id="race-time"></strong><span id="race-progress"></span></div><button id="race-pause" aria-label="Pause">Ⅱ</button></div><aside id="crew-order"></aside><div id="race-banner" aria-live="polite"></div><aside class="race-gauges"><strong id="race-speed">0</strong><span>MPH</span><div><b id="race-gear"></b> GEAR <b id="race-rpm"></b> RPM</div></aside><section id="race-menu"></section><div id="race-debug" hidden></div>';parent.append(this.root);this.root.querySelector('#race-pause')!.addEventListener('click',()=>this.action('resume'));this.root.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button[data-action]');if(b&&!b.disabled)this.action(b.dataset.action as MenuAction)})}
 update(s:State,t:VehicleTelemetry,armed:boolean,view:string,intro:number|null,reward:string,story:string,pending:boolean){const find=(s:string)=>this.root.querySelector<HTMLElement>(s)!;const p=s.standings.find(x=>x.id==='player')!;find('#race-time').textContent=raceTime(s.playerResult?.timeMs??s.elapsedMs);find('#race-progress').textContent=`${p.place}/4 POSITION · LAP ${p.lap}/2 · ${view.toUpperCase()}`;find('#race-speed').textContent=String(Math.round(Math.abs(t.speed)*2.23694));find('#race-gear').textContent=t.gear<0?'R':String(t.gear);find('#race-rpm').textContent=String(Math.round(t.rpm));find('#crew-order').innerHTML=s.standings.map(x=>`<div class="crew-${x.id}"><b>${x.place} ${names[x.id]}</b><span>${x.status==='finished'?raceTime(x.timeMs!):x.status==='running'?`LAP ${x.lap}`:x.status.toUpperCase()}</span></div>`).join('');find('#race-banner').textContent=intro!==null?'':s.phase==='countdown'?String(Math.ceil(s.countdown)):s.phase==='running'&&s.elapsedMs<1000?'GO':!armed&&s.phase==='running'&&!s.paused?'Release controls to continue':'';
 const key=[s.phase,s.paused,intro!==null,s.playerResult?.status,reward,story,pending].join('/');if(key===this.key)return;this.key=key;const menu=find('#race-menu'),shown=s.phase==='ready'||s.phase==='finished'||s.paused;menu.hidden=!shown;document.body.classList.toggle('race-menu-open',shown);if(!shown)return;
 let title='First Night at the Harbor',lead='Two laps. Three rivals. Finish in the top three to earn your place. Stock builds are welcome.',button='Meet the grid',action='start';
 if(intro!==null){title='Maya. Jett. Nico. You.';lead='JETT: Hope you saved some speed for the corners.<br>MAYA: He says that right before braking too late.<small>Text exchange · grid introduction · 6 seconds</small>';button='Skip intro · Start';}
 else if(s.paused){title='Take a breath';lead='All four cars and the clock are paused. Release controls before continuing.';button='Continue';action='resume'}else if(s.playerResult){const r=s.playerResult;title=r.valid?`${r.place}${r.place===1?'st':r.place===2?'nd':r.place===3?'rd':'th'} place · Race complete`:'This run will not count';lead=r.valid?`<strong class="result-time">${raceTime(r.timeMs!)}</strong>${reward||'Checking result…'}<small>${story}</small>`:`${r.invalidReason??r.status}. No crew credits.<small>RAE: That one won’t count. Reset, take a breath, and give me a clean run.</small>`;button='Retry race';action='retry'}
 menu.innerHTML=`<span class="race-label">CHAPTER 01 / TWO-LAP NIGHT RACE</span><h1>${title}</h1><p>${lead}</p><div class="menu-actions"><button class="primary" data-action="${action}" id="start-crew" ${pending?'disabled':''}>${button}</button><button data-action="bay" ${pending?'disabled':''}>Return to bay</button></div><small>W/S pedals · A/D steering · C camera · hold B look back · Esc pause<br>Controller: RT/LT pedals · left stick · top face camera · LB look back<br>Enter / bottom face confirm · Backspace / right face bay</small>`;
 }
 suspendInput(){this.armed=false;this.padKey='';this.confirm=false;this.back=false}
 menuInput(sample:DeviceSample,s:State){const p=sample.pads.find(x=>x?.connected&&x.mapping==='standard'),key=p?`${p.index}:${p.id}`:'';if(!sample.focused||!p||key!==this.padKey)this.armed=false;this.padKey=key;if(sample.focused&&p&&p.buttons.every(b=>b.value<.02)&&p.axes.every(a=>Math.abs(a)<.15))this.armed=true;const confirm=(!(document.activeElement instanceof Element&&document.activeElement.closest('button,a,input,select'))&&sample.keys.has('Enter'))||(this.armed&&(p?.buttons[0]?.value??0)>.5),back=sample.keys.has('Backspace')||(this.armed&&(p?.buttons[1]?.value??0)>.5);if(sample.focused&&(s.phase==='ready'||s.phase==='finished'||s.paused)){if(sample.pressedKeys?.has('Enter')||confirm&&!this.confirm)this.action(s.paused?'resume':s.phase==='finished'?'retry':'start');else if(sample.pressedKeys?.has('Backspace')||back&&!this.back)this.action('bay')}this.confirm=confirm;this.back=back}
}
