import {loadSurfaceMaterials} from './presentation/surface-materials';
import {VehicleMirrors} from './presentation/vehicle-mirrors';
import {CURRENT_VEHICLE_CONTEXT} from './presentation/vehicle-asset';
import {ResultCamera} from './presentation/safe-camera';
import RAPIER from '@dimforge/rapier3d-compat';
import {PresentationTelemetry} from './presentation/interpolate';
import {PoweredDisplay} from './presentation/powered-display';
import {RaceCues} from './audio/actions';
import {SceneLifetime,disposeGraph} from './presentation/scene-lifetime';
import {CrashRecovery,freeRecoveryPose} from './driving/recovery';
import {VehicleEffects} from './presentation/vehicle-effects';
import {effectContacts} from './presentation/effect-contacts';
import {DrivingContact,contactGround} from './presentation/driving-contact';
import {ShakedownRace,SHAKEDOWN_EVENT} from './career-experience/chapter-one-race';
import {RAE} from './career/client';
import {openCareerRace} from './career-experience/race-adapter';
import {readCareerContext} from './career/context';
import {EntryTrace} from './presentation/entry-trace';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {EXPRESS_ROUTE,EXPRESS_DESIGN,loadExpressPresentation} from './express/index';
import {createCourseEnvironment,type CourseRoute} from './course/environment';
import {CrewRace,createCrewGrid,RivalController} from './competition';
import {RaceWorld,FIXED_DT,type VehicleControl,type VehicleTelemetry} from './simulation';
import {DrivingSession} from './driving/session';
import {KeyboardBuffer,type DeviceSample} from './driving/input';
import {DrivingCamera,nextDrivingView,type DrivingView} from './presentation/driving-camera';
import {SpeedFeel,motionReduced} from './presentation/speed-feel';import {RenderPipeline,DEFAULT_BLOOM,NIGHT_BLOOM} from './presentation/render-pipeline';import {loadGraphicsQuality,GRAPHICS_PRESETS} from './presentation/graphics-settings';import {installGraphicsControl} from './presentation/graphics-control';import {resolveLook,rememberLook,LOOKS,type TimeOfDay} from './presentation/time-of-day';import {WetReflection} from './presentation/wet-reflection';import type {WetRoadUniforms} from './presentation/race-asphalt';
import {loadDrivingHero} from './presentation/hero';import {trimSmallCasters} from './presentation/shadows';import {TransparentHalves} from './presentation/transparent-halves';import {perfLegacy,setPerfLegacy} from './presentation/perf-switches';
import {SignatureFinishPresenter,SignatureProducts} from './presentation/signature-art';
import {ProductPresenter} from './presentation/product';
import {SuspensionPresenter} from './presentation/suspension';
import {createHarborRenderer} from './presentation/harbor-renderer';
import {loadOutdoorEnvironment} from './presentation/outdoor-environment';
import {loadShowcaseHarbor} from './presentation/showcase';
import {harborLighting} from './presentation/harbor-lighting';
import {prepareRenderer,preparationVeil} from './presentation/prepare';
import {RuntimeProfile} from './presentation/runtime-profile';
import {GameAudio} from './audio/game-audio';
import {CrewUI} from './crew-ui';
import {buildRepository,fragmentRecipe,recipeFragment,previewSnapshot} from './signature/config';
import {loadSave,writeSave,browserStorage} from './save';
import {pageActive} from './demo/recovery';
import {evidenceEnabled} from './demo/profile';
import './style.css';import './harbor.css';import './crew.css';

const entryTrace=new EntryTrace(),lifetime=new SceneLifetime();
const params=new URLSearchParams(location.search),test=params.has('test'),controlled=test&&params.get('clock')==='controlled',started=performance.now();
const careerRace=await openCareerRace(params);if(careerRace)lifetime.own(careerRace,v=>v.close());
// Free drives never touch the career. A temporary (storage-less) career only rides through this tab and back out.
const carrier=careerRace?undefined:lifetime.own(await readCareerContext({saved:false}),v=>v.dispose());
const previewFrom=params.get('back')==='garage'?'bay':params.get('from')==='career'||params.get('from')==='bay'?params.get('from'):null;
const previewReturn=(screen:'build'|'events',build:string)=>params.get('back')==='garage'&&screen==='build'?'?scene=bay&play=career&shop=build':`?scene=signature&screen=${screen}${previewFrom?'&from='+previewFrom:''}${build}`;
const requestedRoute=params.get('route')==='ridge'||params.get('scene')==='ridge'?'ridge':params.get('route')==='harbor'?'harbor':'express';
const storage=buildRepository(),savedSnapshot=careerRace?{recipe:careerRace.recipe,route:careerRace.route,mode:'race' as const,returnTo:careerRace.returnTo,lighting:careerRace.preset}:fragmentRecipe(location.hash)?previewSnapshot(fragmentRecipe(location.hash)!,params.get('route')==='ridge'||params.get('scene')==='ridge'?'ridge':params.get('route')==='harbor'?'harbor':'express',params.get('mode')==='race'?'race':'test',params.get('lighting')==='night'?'night':'day'):storage.store.drive(params.get('route')==='ridge'||params.get('scene')==='ridge'?'ridge':params.get('route')==='harbor'?'harbor':'express',params.get('mode')==='race'?'race':'test'),snapshot=careerRace?savedSnapshot:{...savedSnapshot,...(params.has('route')||params.get('scene')==='ridge'?{route:requestedRoute}:{}),...(params.has('mode')?{mode:params.get('mode')==='race'?'race' as const:'test' as const}:{})},recipe=snapshot.recipe,free=snapshot.mode==='test',express=snapshot.route==='express',ridge=snapshot.route==='ridge',requestedPreset=(careerRace?.preset??(ridge&&params.has('lighting')?(params.get('lighting')==='night'?'night':'day'):snapshot.lighting??'day')),
 // Time-of-day look (presentation only). `preset` stays one of the two validated bases, which records, saves, lamps and optics key on.
 look=resolveLook({route:snapshot.route as 'express'|'harbor'|'ridge',career:!!careerRace,requested:requestedPreset,explicitLighting:careerRace?.fixedLighting??(params.has('lighting')||snapshot.lighting==='night')}),preset=look.base,graphics=params.get('quality')==='low'?'low':loadGraphicsQuality(),quality=GRAPHICS_PRESETS[graphics].lighting,handlingProfile=recipe.handlingProfile;
document.body.className='harbor-race signature-race';const app=document.querySelector('#app')!;app.innerHTML='<div id="viewport"></div>';const veil=preparationVeil(app,{destination:ridge?'Smoky Ridge':express?'Harbor Express':'Original Harbor'}),profile=new RuntimeProfile(params.has('profile'));
const renderer=lifetime.own(createHarborRenderer(params.has('captureBuffer')),v=>v.dispose());renderer.setPixelRatio(Math.min(devicePixelRatio,GRAPHICS_PRESETS[graphics].pixelRatioCap));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;app.querySelector('#viewport')!.append(renderer.domElement);
let activeLook=look;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.06,2200),loader=new GLTFLoader();const parseGLTF=loader.parse.bind(loader);loader.parse=(data,path,onLoad,onError)=>{const at=performance.now();parseGLTF(data,path,g=>{entryTrace.record('gltf-decode-construct:'+path,at);onLoad(g)},onError)};const ridgePresentation=ridge?await import('./ridge/presentation'):null;const [outdoor,hero]=await Promise.all([entryTrace.measure('sky-fetch-decode-probe',()=>lifetime.load(Promise.resolve(ridgePresentation?ridgePresentation.loadRidgeAtmosphere(scene,renderer,preset):loadOutdoorEnvironment(scene,renderer,preset,look).catch(error=>{console.warn('Look sky unavailable; using the base sky.',error);activeLook=LOOKS[preset];return loadOutdoorEnvironment(scene,renderer,preset)})),v=>v.dispose())),entryTrace.measure('vehicle-fetch-decode-bind',()=>lifetime.load(loadDrivingHero(loader),v=>disposeGraph(v.root)))]);
const ridgeModule=ridge?await import('./ridge/route'):null;
const route:CourseRoute=ridgeModule?ridgeModule.RIDGE_ROUTE:express?EXPRESS_ROUTE:await(await fetch('/assets/harbor/route.json')).json();scene.add(hero.root);
let sceneryRoot:THREE.Object3D|undefined;
let updateWorld:(camera:THREE.Vector3,time:number)=>void=()=>{},inspectWorld:()=>unknown=()=>undefined;
// A wet look hands back the road's wet uniforms, its height and what should appear in its puddles.
let wetRoad:{roadY:number;wetSurfaces:WetRoadUniforms[];reflectable:THREE.Object3D[]}|undefined;
if(ridge){const {loadRidgePresentation}=await import('./ridge/presentation');const presentation=await entryTrace.measure('ridge-fetch-decode-build',()=>lifetime.load(loadRidgePresentation(scene,preset,{renderer,enabled:params.get('forest')!=='off'}),v=>v.dispose()));sceneryRoot=presentation.root;updateWorld=(p,t)=>presentation.update(p,t,pipeline.quality,motionReduced());inspectWorld=()=>presentation.inspect()}else if(express){const presentation=await entryTrace.measure('express-fetch-decode-build',()=>lifetime.load(loadExpressPresentation(scene,preset,renderer,activeLook.lampsOn,activeLook.wet),v=>v.dispose()));sceneryRoot=presentation.root;wetRoad=presentation;updateWorld=(p,t)=>presentation.update?.(p,t);inspectWorld=()=>presentation.inspect()}else{const original=await lifetime.load(loader.loadAsync('/assets/harbor/harbor.glb'),v=>disposeGraph(v.scene));scene.add(original.scene);const presentation=await lifetime.load(loadShowcaseHarbor(scene,original.scene,preset,'full',{renderer,lamps:route.lamps,lampsOn:activeLook.lampsOn,swell:GRAPHICS_PRESETS[graphics].waterSwell,motion:!motionReduced()}),v=>v.dispose());const {loadHarborSpeedDressing}=await import('./presentation/harbor-speed-dressing'),dressing=await lifetime.load(loadHarborSpeedDressing(renderer,scene,route,activeLook.lampsOn,activeLook.wet).catch(error=>{console.warn('P11 harbor dressing unavailable; keeping the previous road.',error);return undefined}),v=>v?.dispose());sceneryRoot=presentation.root;wetRoad=dressing;updateWorld=(p,t)=>{presentation.update(p,t);dressing?.update(p)};inspectWorld=()=>presentation.inspect()}
const surfaceFinish=await lifetime.load(loadSurfaceMaterials(renderer,sceneryRoot!,params.get('surfaces')!=='off'),v=>v.dispose());
const colors:Record<string,[string,string]>={maya:['#d7dddd','#57bab7'],jett:['#6d161e','#aa3838'],nico:['#3c444c','#e9b454']};const peers=Object.fromEntries((careerRace?careerRace.participants.filter(id=>id!=='player'):free?[]:['maya','jett','nico']).map(id=>[id,hero.cloneRival(...colors[id],preset)]));for(const p of Object.values(peers))scene.add(p.root);const casters=[hero,...Object.values(peers)].map(car=>trimSmallCasters(car.root));
const mirrors=lifetime.own(new VehicleMirrors(hero.root,hero.asset),v=>v.dispose());
const finishes=lifetime.own(new SignatureFinishPresenter(hero.asset),v=>v.dispose());await entryTrace.measure('finish-fetch-decode',()=>finishes.set(recipe.finish));
const [under,shocks,accessories]=await entryTrace.measure('products-fetch-decode-bind',()=>Promise.all([lifetime.load(ProductPresenter.load(loader,hero.root,scene),v=>v.dispose()),lifetime.load(SuspensionPresenter.load(loader,hero.asset),v=>v.dispose()),lifetime.load(SignatureProducts.load(loader,hero.asset),v=>v.dispose())]));under.set(hero.asset.getObjectByName('ryker_foundation')?!!recipe.ryker?.underglow:!!recipe.products['SM-133'],recipe.lights);shocks.set(!!recipe.products['SM-3223']);accessories.set(Object.keys(recipe.products),recipe.ryker);
const ids=careerRace?careerRace.participants:free?['player']:['maya','jett','nico','player'],rivalIds=ids.filter(id=>id!=='player'),grid=careerRace?.eventId===SHAKEDOWN_EVENT?{player:route.start}:createCrewGrid(route,ids),world=await lifetime.load(RaceWorld.create(createCourseEnvironment(route),handlingProfile),v=>v.dispose());
for(const id of ids)world.addVehicle(id,grid[id]);world.get('player').configureSuspension(recipe.products['SM-3223']?recipe.suspension:null);
const eventId=careerRace?.eventId??(ridge?'smoky-ridge':express?'harbor-express':'harbor-preview')+(free?'-test-v1':'-quick-race-v1'),race=careerRace?.eventId===SHAKEDOWN_EVENT?new ShakedownRace(route,preset,handlingProfile):new CrewRace(route,ids,'player',ids.length===2,careerRace?.kind==='chapter-one'?{handlingProfileId:handlingProfile}:{eventId,laps:careerRace?.laps??1,handlingProfileId:handlingProfile,freeDrive:free,timeTrial:!!careerRace&&ids.length===1});

let rivals=Object.fromEntries(rivalIds.map(id=>[id,new RivalController(route,id,11,handlingProfile)]));world.initialize();let currentField=world.telemetry(),previousField=currentField,attemptId:string|null=null,attempt=0,prepared=false,confirmBlocked=false;
const resultCamera=new ResultCamera(camera,route.heightAt,false);const keyboard=new KeyboardBuffer(),releaseKeys=new Set<string>();let virtual:DeviceSample|undefined,sampled:DeviceSample={keys:new Set(),pads:[],focused:true},cameraMode:DrivingView=loadSave(browserStorage()).settings.camera,lookBack=false,resetPresentation=true;
const display=new PoweredDisplay(hero.asset),raceCues=new RaceCues();display.snapshot(renderer,scene.environment,JSON.stringify(recipe));
const audio=lifetime.own(new GameAudio(app),v=>v.dispose()),chase=new DrivingCamera(camera,handlingProfile);
// Every view renders through the pipeline (Low = direct, as before Phase 2). Reduced motion keeps every LOOK and removes
// only motion: SpeedFeel then leaves the camera alone and asks for no edge blur.
const speedFeel=new SpeedFeel(),pipeline=lifetime.own(new RenderPipeline(renderer,graphics),v=>v.dispose());pipeline.onViewTarget(target=>{mirrors.viewTarget=target});
const contact=lifetime.own(new DrivingContact(scene,ids,contactGround(world),params.get('contact')!=='off'),v=>v.dispose());
const effects=lifetime.own(new VehicleEffects(scene,[{id:'player',root:hero.root,exhaust:!!recipe.products['SM-7720']},...Object.entries(peers).map(([id,peer])=>({id,root:peer.root,exhaust:false}))],effectContacts(world),params.get('effects')!=='off'),v=>v.dispose());void effects.loadTextures(renderer);
// Wet road reflections (High/Ultra): cars, underglow and trackside lamps mirrored in the puddles; never the live mirror faces.
const wetReflection=activeLook.wet&&wetRoad?.wetSurfaces.length?lifetime.own(new WetReflection(renderer,wetRoad.roadY,wetRoad.wetSurfaces),v=>v.dispose()):undefined;wetReflection?.reflect([hero.root,...Object.values(peers).map(p=>p.root),...wetRoad!.reflectable],[mirrors.group]);
let wetFrame=0;const renderWetRoad=(force=false)=>{if(!wetReflection||!wetRoad)return;const every=GRAPHICS_PRESETS[pipeline.quality].wetReflections;for(const surface of wetRoad.wetSurfaces)surface.planar.value=every?1:0;if(every&&(force||wetReflection.passes===0||++wetFrame%every===0))wetReflection.render(scene,camera)};
// Ridge keeps its own atmospheres; elsewhere the look supplies bloom. Changing the look needs a fresh scene, so it restarts
// only from the start menu and otherwise waits for the next drive.
const frameBloom=ridge?(preset==='night'?NIGHT_BLOOM:DEFAULT_BLOOM):activeLook.bloom;
lifetime.own(installGraphicsControl(app,renderer,pipeline,quality,careerRace||ridge?undefined:{current:activeLook.id,choose:(id:TimeOfDay)=>{rememberLook(snapshot.route as 'express'|'harbor',id);if(race.snapshot().phase!=='ready')return'Applies on your next drive.';const next=new URL(location.href);next.searchParams.set('look',id);next.searchParams.delete('lighting');location.replace(carrier?carrier.relay(next.href):next.href);return''}}),v=>v.dispose());
audio.setExhaustTreatment(!!recipe.products['SM-7720']);chase.eye.fromArray(hero.attachment.eye);
lifetime.own(display,v=>v.dispose());
const lights=lifetime.own(harborLighting(scene,hero.asset,route,preset,quality,ridge?undefined:activeLook),v=>v.dispose());ridgePresentation?.configureRidgeLighting(scene,preset);
const sim={telemetry:()=>world.get('player').telemetry(),reset:()=>{for(const[id,pose]of Object.entries(grid))world.get(id).reset(pose);rivals=Object.fromEntries(rivalIds.map(id=>[id,new RivalController(route,id,11,handlingProfile)]));previousField=currentField=world.telemetry()},step:(control:VehicleControl,dt=FIXED_DT)=>{previousField=currentField;const controls:Record<string,VehicleControl>={player:race.control('player',control)};for(const[id,rival]of Object.entries(rivals)){controls[id]=race.control(id,rival.control(currentField[id],currentField,dt));if(rival.inspect().retiredReason)race.retire(id,rival.inspect().retiredReason!)}world.step(controls,dt);currentField=world.telemetry();race.tick(previousField,currentField,dt)}};
const ui=new CrewUI(app,menuAction,false,{title:careerRace?.title??(ridge?'Smoky Ridge':express?'Harbor Express':'Original Harbor'),subtitle:careerRace?.subtitle??(free?'Unscored build test':'Quick race / 1 lap')+' / '+(ridge?(preset==='day'?'Late afternoon':'Blue hour'):activeLook.label),preview:!careerRace,career:!!careerRace,freeDrive:free,route});
let rewardPending=false,rewardText='',rewardStory='',rewardId='',resetPermit=false;
const session=new DrivingSession(sim,()=>sampled,{profileId:handlingProfile,canReset:()=>{if(careerRace&&race.snapshot().playerResult?.valid){if(rewardId)careerRace.client.navigate(careerRace.returnTo);return false}if(resetPermit)return true;if(rewardPending)return false;if(careerRace&&!resetPermit){void restartCareer();return false}return true},onReset:()=>{attemptId=careerRace?.attempt.id??crypto.randomUUID();rewardText='';rewardStory='';rewardId='';attempt++;race.restart(attemptId);for(const k of keyboard.held)releaseKeys.add(k);keyboard.clear();resetPresentation=true},onPause:p=>race.setPaused(p)});session.sync();
const recovery=new CrashRecovery(app,route,free,()=>{if(rewardPending)return;if(free){world.get('player').reset(freeRecoveryPose(route,session.current));previousField=currentField=world.telemetry();session.input.reset();session.input.paused=false;race.setPaused(false);session.sync();for(const k of keyboard.held)releaseKeys.add(k);keyboard.clear();resetPresentation=true;audio.lifecycle(false)}else menuAction('restart')});
async function restartCareer(){if(!careerRace||rewardPending)return;rewardPending=true;try{if(attemptId)await careerRace.restart();resetPermit=true;session.input.paused=false;session.reset()}catch(e){rewardText='Could not start this entry. Return to career to resume.'}finally{resetPermit=false;rewardPending=false}}
async function saveCareerResult(){if(!careerRace||rewardPending)return;rewardPending=true;try{const result=await careerRace.commit(race);if(result.changed&&result.receipt)audio.cue('career.unlock','award:'+attemptId);rewardText=`+${result.receipt?.amount??0} game credits · Balance ${result.state.credits} · ${careerRace.client.durable?'Saved':'Session only'}`;if(race instanceof ShakedownRace){const lap=race.snapshot().standingLap.result;if(lap?.bestMs)rewardText+=` · ${lap.newBest?'Personal best':'Best'} ${(lap.bestMs/1000).toFixed(2)}s`;if(careerRace.kind==='chapter-one'&&!careerRace.bestPersisted)rewardText+=' · Lap time could not be saved'};rewardStory='story' in result&&result.story?RAE[result.story as keyof typeof RAE]:'';rewardId=attemptId??''}catch(e){rewardText='Result save interrupted. Retry saving before leaving.'}finally{rewardPending=false}}
function menuAction(action:string){if(!prepared||rewardPending)return;if(careerRace&&race.snapshot().playerResult?.valid&&!rewardId&&action!=='save-result'&&action!=='leave-unsaved'&&action!=='resume')return;if(action==='leave-unsaved'&&careerRace){careerRace.client.navigate(careerRace.returnTo);return}if(action==='save-result'){void saveCareerResult();return}if(careerRace&&(action==='bay'||action==='events'||action==='retry'&&race.snapshot().playerResult?.valid)){careerRace.client.navigate(careerRace.returnTo);return}profile.mark(action,{ticks:session.ticks});if(action==='bay'||action==='events'){const href=previewReturn(action==='events'?'events':'build',recipeFragment(recipe));location.assign(carrier?carrier.relay(href):href);return}if(action==='resume'){session.input.paused=!session.input.paused;session.input.armed=false;race.setPaused(session.input.paused);audio.lifecycle(session.input.paused);confirmBlocked=true;return}session.input.paused=false;session.reset();confirmBlocked=true}
function source():DeviceSample{if(virtual)return virtual;const state=keyboard.read();return {...state,keys:new Set([...state.keys,...releaseKeys]),pads:Array.from(navigator.getGamepads?.()??[]),focused:document.hasFocus()&&!document.hidden}}
let lastInput:ReturnType<DrivingSession['frame']>|undefined,lastWall:number|undefined;
const presentationTelemetry=new PresentationTelemetry();
// Query actual fixed geometry, including road, terrain and rails; does not alter vehicle motion.
function ridgeCameraObstruction(target:THREE.Vector3,desired:THREE.Vector3){const delta=desired.clone().sub(target),length=delta.length();if(length<1e-6)return;delta.divideScalar(length);const hit=world.world.castRay(new RAPIER.Ray(target,delta),length,true,undefined,undefined,undefined,undefined,c=>!c.parent()&&!c.isSensor());return hit?.timeOfImpact}

function present(dt:number,alpha:number,reset:boolean,raster:boolean){
 const t=presentationTelemetry.sample(session.previous,session.current,alpha);hero.pose(t,dt,cameraMode==='cockpit'&&!lookBack&&!(!!race.snapshot().playerResult&&!race.snapshot().paused),reset);chase.update(hero.root.position,hero.root.quaternion,t.speed,dt,cameraMode,lookBack,reset,ridge?ridgeCameraObstruction:undefined);
 const finished=!!race.snapshot().playerResult&&!race.snapshot().paused;if(finished)speedFeel.edgeBlur=0;else speedFeel.apply(camera,chase.target,t,chase.activeView,dt,innerHeight,reset,ridge?ridgeCameraObstruction:undefined);
 for(const[id,peer]of Object.entries(peers))peer.pose(currentField[id],dt,false,reset);lights.update(hero.root.position,t.brake,camera.position,pipeline.quality);contact.update(currentField,t);shocks.update();under.update();audio.update(session.current,session.input.paused||race.snapshot().phase==='ready',cameraMode==='cockpit'&&!lookBack,reset);audio.updateOpponents(session.current,Object.fromEntries(Object.entries(currentField).filter(([id])=>id!=='player')));display.update(session.current,camera,performance.now());raceCues.update(race.snapshot(),id=>audio.cue(id));updateWorld(camera.position,session.current.time);
 effects.update(currentField,camera,innerHeight*renderer.getPixelRatio(),pipeline.quality,activeLook.wet,activeLook.lampsOn,speedFeel.reducedMotion,reset);
 if(careerRace&&race.snapshot().playerResult?.valid&&race.snapshot().allFinished&&!rewardId&&!rewardPending&&!rewardText.startsWith('Result save interrupted'))void saveCareerResult();
 recovery.update(session.current,dt,race.snapshot().phase!=='ready'&&!race.snapshot().playerResult?.valid);
 // Nothing moves between this frame's passes (mirrors, wet road, view), so the scene's transforms are resolved once here;
 // three would otherwise walk all ~2000 objects again for every render call.
 if(raster){const begin=performance.now();resultCamera.update(hero.root,!!race.snapshot().playerResult&&!race.snapshot().paused,innerWidth,innerHeight);mirrors.update(camera,innerHeight,chase.activeView==='near'||chase.activeView==='cockpit',chase.activeView==='near');if(!perfLegacy('matrix')){scene.updateMatrixWorld();scene.matrixWorldAutoUpdate=false}try{mirrors.render(renderer,scene,camera);renderWetRoad();pipeline.render(scene,camera,{edgeBlur:speedFeel.edgeBlur,focus:chase.target,bloom:frameBloom,grade:activeLook.grade,heatHaze:effects.heatHaze,effectTime:session.current.time});}finally{scene.matrixWorldAutoUpdate=true}profile.renderMs=performance.now()-begin;ui.setMapPeers(currentField);ui.update(race.snapshot(),session.current,session.input.armed,chase.activeView,null,careerRace?rewardText:'Preview drive / no career credits',rewardStory,rewardPending);if(careerRace){const primary=app.querySelector<HTMLButtonElement>('#start-crew');if(primary&&race.snapshot().playerResult?.valid&&!race.snapshot().paused){primary.textContent='Continue chapter';primary.disabled=!rewardId;}const back=app.querySelector<HTMLButtonElement>('[data-action=bay]');if(back){back.textContent='Back to career';back.disabled=!!race.snapshot().playerResult?.valid&&!rewardId;}if(!rewardId&&race.snapshot().playerResult?.valid&&!rewardText)rewardText='Waiting for the rest of the field before saving.';if(rewardText.startsWith('Result save interrupted')&&!app.querySelector('[data-action=save-result]')){const b=document.createElement('button');b.dataset.action='save-result';b.textContent='Retry saving result';app.querySelector('#race-menu .menu-actions')?.append(b);const leave=document.createElement('button');leave.dataset.action='leave-unsaved';leave.textContent='Leave without this reward';app.querySelector('#race-menu .menu-actions')?.append(leave)}};if(!careerRace&&params.get('back')==='garage'){const back=app.querySelector<HTMLButtonElement>('[data-action=bay]');if(back&&back.textContent!=='Back to career garage')back.textContent='Back to career garage'}const events=app.querySelector<HTMLAnchorElement>('a.shop-build-route');if(events){events.href=careerRace?careerRace.returnTo:previewReturn('events',recipeFragment(recipe));events.hidden=!!careerRace&&!!race.snapshot().playerResult?.valid&&!rewardId}}
}
function normalFrame(now:number,raster=true){sampled=source();ui.menuInput(sampled,race.snapshot());if(confirmBlocked){const held=sampled.pads.some(p=>p&&(p.buttons[0]?.value??0)>.5);if(!held)confirmBlocked=false;else sampled={...sampled,pads:sampled.pads.map(p=>p?{...p,buttons:p.buttons.map((b,i)=>i===0?{value:0,pressed:false}:b)}:p)}}
 if(race.snapshot().phase==='ready'){present(1/60,1,resetPresentation,raster);resetPresentation=false;return}
 lastInput=session.frame(now);if(race.snapshot().phase==='running')entryTrace.driving();if(lastInput.camera){cameraMode=nextDrivingView(cameraMode);const saved=loadSave(browserStorage());saved.settings.camera=cameraMode;writeSave(browserStorage(),saved)}lookBack=lastInput.lookBack;present(lastInput.dt,lastInput.alpha,resetPresentation||lastInput.reset,raster);resetPresentation=false;
}
function suspend(){keyboard.clear();releaseKeys.clear();ui.suspendInput();session.input.suspend();race.setPaused(true);audio.lifecycle(true)}
addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('input,textarea,select'))return;keyboard.down(e.code,performance.now(),e.repeat);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>{keyboard.up(e.code);releaseKeys.delete(e.code)});addEventListener('blur',suspend);addEventListener('visibilitychange',()=>{if(document.hidden)suspend()});
addEventListener('gamepaddisconnected',()=>{session.input.disconnect();suspend()});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,GRAPHICS_PRESETS[pipeline.quality].pixelRatioCap));renderer.setSize(innerWidth,innerHeight);pipeline.resize();wetReflection?.resize()});
// Transparent two-sided vehicle parts: the same two draws through one shader program instead of two (transparent-halves.ts).
const halves=new TransparentHalves(),vehicleRoots=()=>[hero.root,...Object.values(peers).map(p=>p.root)];if(!perfLegacy('transparency'))halves.apply(vehicleRoots());
await entryTrace.measure('initial-present',()=>present(0,1,true,false));effects.prepare();const preparation=await entryTrace.measure('graphics-preparation',()=>prepareRenderer(renderer,scene,camera,()=>{renderWetRoad(true);pipeline.render(scene,camera)}));present(0,1,true,true);veil.remove();prepared=true;entryTrace.ready();const loadMs=performance.now()-started;
function frame(now:number){if(!pageActive())return;if(!controlled){const begin=performance.now();normalFrame(now);profile.frame(now,lastWall===undefined?0:now-lastWall,performance.now()-begin,session.ticks,{...race.snapshot(),attempt},cameraMode,renderer,scene,pipeline.resolution.scale);lastWall=now}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function inspect(){const gl=renderer.getContext();return {surfaceFinish:surfaceFinish.inspect(),transparentHalves:halves.inspect(),contact:contact.inspect(),effects:effects.inspect(),look:{id:activeLook.id,base:preset,requested:look.id,wet:activeLook.wet},wetReflection:wetReflection?.inspect()??null,speedFeel:speedFeel.inspect(),pipeline:pipeline.inspect(),camera:{fov:camera.fov,position:camera.position.toArray(),view:chase.activeView},world:inspectWorld(),shadowCasters:casters,rivalMerge:Object.values(peers)[0]?.resources.merge,mirrors:mirrors.inspect(),vehicleContext:CURRENT_VEHICLE_CONTEXT,visual:hero.inspectVisual(),rivals:Object.fromEntries(Object.entries(peers).map(([id,p])=>[id,{visual:p.inspectVisual(),optics:p.inspectOptics()}])),optics:lights.inspect(),display:display.inspect(),recovery:recovery.inspect(),entry:entryTrace.inspect(),build:__BUILD_REF__,handlingProfile,profileContract:{simulation:world.profileId,input:session.input.profileId,field:world.profileId},eventId,preview:!careerRace,career:careerRace?{attempt:careerRace.attempt,state:careerRace.client.state}:null,free,recipe:structuredClone(recipe),race:race.snapshot(),telemetry:session.current,field:currentField,ticks:session.ticks,attemptId,rewardPending,rewardText,careerTouched:!!careerRace,route:{id:route.id,version:route.version,length:route.length},design:ridgeModule?ridgeModule.RIDGE_DESIGN:express?EXPRESS_DESIGN:null,lighting:preset,suspension:shocks.inspect(),simulationSuspension:world.get('player').suspensionConfig(),products:accessories.inspect?.(),input:lastInput,audio:audio.inspect(),memory:{...renderer.info.memory},renderer:gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info')?.UNMASKED_RENDERER_WEBGL??gl.RENDERER),size:renderer.getDrawingBufferSize(new THREE.Vector2()).toArray(),dpr:renderer.getPixelRatio(),loadMs,preparation}}
if(evidenceEnabled())(window as any).__EXPRESS={ready:true,inspect,route,setPerf:(value:string)=>{const legacy=setPerfLegacy(value);if(legacy.includes('transparency'))halves.restore();else halves.apply(vehicleRoots());return legacy},effectFixture:(field:Record<string,VehicleTelemetry>,reset=false)=>{if(!test||!controlled)throw Error('Isolated controlled visual fixture required');hero.pose(field.player,1/60,false,reset);for(const [id,peer] of Object.entries(peers))if(field[id])peer.pose(field[id],1/60,false,reset);contact.update(field);effects.update(field,camera,innerHeight*renderer.getPixelRatio(),pipeline.quality,activeLook.wet,activeLook.lampsOn,speedFeel.reducedMotion,reset);pipeline.render(scene,camera,{bloom:frameBloom,grade:activeLook.grade,heatHaze:effects.heatHaze,effectTime:field.player.time});return effects.inspect()},referenceCamera:(id:string,position:number[],target:number[])=>{if(!test)throw Error('Isolated test required');const car=id==='player'?hero.root:peers[id]?.root;if(!car)throw Error('Unknown car');car.updateWorldMatrix(true,true);camera.position.copy(car.localToWorld(new THREE.Vector3().fromArray(position)));camera.lookAt(car.localToWorld(new THREE.Vector3().fromArray(target)));updateWorld(camera.position,session.current.time);lights.update(camera.position,0,camera.position,pipeline.quality);renderWetRoad(true);pipeline.render(scene,camera,{bloom:frameBloom,grade:activeLook.grade});return renderer.domElement.toDataURL()},lightweight:()=>({telemetry:session.current,race:race.snapshot(),field:currentField,ticks:session.ticks,attemptId}),profile:()=>({...profile.export(),loadMs,preparation,handlingProfile,route:route.id}),normalFrame:(now:number,raster=true)=>{if(!controlled)throw Error('Controlled test context required');normalFrame(now,raster);return inspect()},setDeviceSample:(v:any)=>{if(!test)throw Error('Isolated test required');virtual=v?{...v,keys:new Set(v.keys)}:undefined},startAudioCapture:()=>audio.startEvidenceCapture(),audioSync:(id:string)=>audio.evidenceMarker(id),stopAudioCapture:()=>audio.stopEvidenceCapture(),drawCensus:async(renders=40)=>{const {watchPasses,census}=await import('./presentation/draw-census');return{passes:await watchPasses(renderer,renders),branches:census(scene,camera)}}};
lifetime.own(recovery,v=>v.dispose());lifetime.own(scene,disposeGraph);addEventListener('pagehide',suspend,{once:true});
