import {createHarborRenderer,harborDepth} from './presentation/harbor-renderer';
import {loadShowcaseHarbor} from './presentation/showcase';
import {prepareRenderer,preparationVeil} from './presentation/prepare';
import {RuntimeProfile} from './presentation/runtime-profile';
import {careerClient,RAE} from './career/client';
import {ProductPresenter} from './presentation/product';
import './career/build.css';
import {CURRENT_VEHICLE} from './presentation/vehicle-asset';
import './style.css';import './harbor.css';
import * as THREE from 'three';import {GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import {loadOutdoorEnvironment}from'./presentation/outdoor-environment';
import {Simulation,type VehicleTelemetry}from'./simulation';import{DrivingSession}from'./driving/session';import{KeyboardBuffer,type DeviceSample}from'./driving/input';
import{createCourseEnvironment,type CourseRoute,type CourseBox}from'./course/environment';import{RaceAttempt}from'./race/attempt';import{loadSave,writeSave,recordKey,saveBest,browserStorage}from'./save';
import{DrivingCamera,nextDrivingView,type DrivingView}from'./presentation/driving-camera';import{loadDrivingHero}from'./presentation/hero';import{harborLighting}from'./presentation/harbor-lighting';import{assetStatistics}from'./presentation/statistics';import{GameAudio,renderOfflineGameAudio}from'./audio/game-audio';import{HarborUI,type MenuAction}from'./harbor-ui';
const params=new URLSearchParams(location.search),test=params.has('test'),controlled=test&&params.get('clock')==='controlled',preset=params.get('preset')==='night'?'night':'day',quality=params.get('quality')==='low'?'low':'standard';
const started=performance.now();const profile=new RuntimeProfile(params.has('profile'));document.body.className='harbor-race';const app=document.querySelector('#app')!;app.innerHTML='<div id="viewport"></div>';const veil=preparationVeil(app);let prepared=false;
const renderer=createHarborRenderer(params.has('captureBuffer'));renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?1:1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=preset==='night'?1.05:.95;app.querySelector('#viewport')!.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.06,1600),loader=new GLTFLoader();const outdoor=await loadOutdoorEnvironment(scene,renderer,preset);
const [route,world,hero]=await Promise.all([fetch('/assets/harbor/route.json').then(r=>r.json() as Promise<CourseRoute>),loader.loadAsync('/assets/harbor/harbor.glb'),loadDrivingHero(loader)]);
const career=await careerClient(),product=await ProductPresenter.load(loader,hero.root,scene);product.set(career.state.equipped,career.state.appearance);const unsubCareer=career.subscribe(()=>product.set(career.state.equipped,career.state.appearance));
scene.add(world.scene,hero.root);world.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.receiveShadow=true;o.castShadow=!(Array.isArray(o.material)?o.material:[o.material]).every(m=>/asphalt|ground|land|water|paint|runoff/i.test(m.name));for(const material of(Array.isArray(o.material)?o.material:[o.material])){const m=material as THREE.MeshStandardMaterial;if(m.map){m.map.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy())}if(m.emissive&&/lamp|lumin|emissive|light/i.test(m.name))m.emissiveIntensity=preset==='night'?2:.08}}});
const showcase=await loadShowcaseHarbor(scene,world.scene,preset,params.get('showcase')==='sample'?'sample':'full');
const worldStatistics=assetStatistics(showcase.root),gl=renderer.getContext(),rendererIdentity=gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info')?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);
const lights=harborLighting(scene,hero.asset,route,preset,quality),sim=await Simulation.create(createCourseEnvironment(route)),save=loadSave(browserStorage()),key=recordKey(route,preset),race=new RaceAttempt(route,preset,save.records[key]?.timeMs??null);
let attemptId:string|null=null,rewardPending=false,rewardText='',rewardStory='',rewardId:string|null=null;
let cameraMode:DrivingView=save.settings.camera,lookBack=false,virtual:DeviceSample|undefined,resetPresentation=true,committedAttempt=-1,persisted:boolean|null=null,confirmBlocked=false,debugVisible=false;const keyboard=new KeyboardBuffer(),menuEdges=new Set<string>(),releaseKeys=new Set<string>();
const audio=new GameAudio(app),chase=new DrivingCamera(camera);chase.eye.fromArray(hero.attachment.eye);chase.cockpitPitch=-.26;chase.cockpitFov=76;
const sourceSample=():DeviceSample=>{if(virtual)return virtual;const state=keyboard.read(),pressedKeys=new Set([...state.pressedKeys,...menuEdges]);menuEdges.clear();return{...state,keys:new Set([...state.keys,...releaseKeys]),pressedKeys,pads:typeof navigator.getGamepads==='function'?Array.from(navigator.getGamepads()):[],focused:document.hasFocus()&&!document.hidden}};
const ui=new HarborUI(app,preset,menuAction);if(!career.durable){const note=document.createElement('small');note.className='career-session';note.textContent='Session only — progress cannot be saved';app.append(note)}let sampled:DeviceSample={keys:new Set(),pads:[],focused:true};
const session=new DrivingSession(sim,()=>sampled,{resetPose:route.start,beforeTick:c=>race.control(c),afterTick:(a,b,dt)=>{race.tick(a,b,dt);const result=race.snapshot().result;if(result&&result.valid&&attemptId&&rewardId!==attemptId){rewardId=attemptId;void awardFinish(attemptId,result.timeMs)}},onReset:()=>{attemptId=crypto.randomUUID();rewardText='';rewardStory='';race.restart();for(const k of keyboard.held)releaseKeys.add(k);keyboard.clear();resetPresentation=true;persisted=null},onPause:p=>race.setPaused(p)});
function menuAction(action:MenuAction){if(!prepared||rewardPending)return;profile.mark(action==='start'?'countdown':action,{ticks:session.ticks});if(action==='bay'){career.navigate('?scene=bay');return}if(action==='resume'){session.input.paused=!session.input.paused;session.input.armed=false;race.setPaused(session.input.paused);audio.lifecycle(session.input.paused);confirmBlocked=true;return}session.input.paused=false;session.reset();confirmBlocked=true;committedAttempt=-1}
sim.reset(route.start);for(let i=0;i<120;i++)sim.step({throttle:0,brake:1,steer:0,reverse:false});session.sync();
/** Ray against the same oriented boxes used by Rapier; decorative ground/water never blocks the camera. */
function obstruction(origin:THREE.Vector3,desired:THREE.Vector3){const delta=desired.clone().sub(origin),length=delta.length();if(length<1e-6)return;let nearest=Infinity;for(const box of route.colliders){if(box.size[1]<.1)continue;const yaw=box.yaw??0,c=Math.cos(yaw),s=Math.sin(yaw),dx=origin.x-box.center[0],dz=origin.z-box.center[2],o=[c*dx-s*dz,origin.y-box.center[1],s*dx+c*dz],d=[c*delta.x-s*delta.z,delta.y,s*delta.x+c*delta.z];let lo=0,hi=1;for(let i=0;i<3;i++){const half=box.size[i]/2;if(Math.abs(d[i])<1e-9){if(Math.abs(o[i])>half){lo=2;break}}else{const a=(-half-o[i])/d[i],b=(half-o[i])/d[i];lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b))}}if(lo<=hi&&lo>=0&&lo<=1)nearest=Math.min(nearest,lo*length)}return Number.isFinite(nearest)?nearest:undefined}
let lastInput:ReturnType<DrivingSession['frame']>|undefined,audioFrame:ReturnType<GameAudio['update']>|undefined;const frameTimes:number[]=[];let lastWall:number|undefined;
function present(dt:number,alpha:number,reset:boolean,raster:boolean){const t=structuredClone(session.current),prev=session.previous;for(const k of['x','y','z']as const)t.position[k]=THREE.MathUtils.lerp(prev.position[k],t.position[k],alpha);const q=new THREE.Quaternion(prev.quaternion.x,prev.quaternion.y,prev.quaternion.z,prev.quaternion.w).slerp(new THREE.Quaternion(t.quaternion.x,t.quaternion.y,t.quaternion.z,t.quaternion.w),alpha);Object.assign(t.quaternion,{x:q.x,y:q.y,z:q.z,w:q.w});hero.pose(t,dt,cameraMode==='cockpit'&&!lookBack,reset);chase.update(hero.root.position,hero.root.quaternion,session.current.speed,dt,cameraMode,lookBack,reset,obstruction);lights.update(hero.root.position,session.current.brake);product.update();audioFrame=audio.update(session.current,session.input.paused,cameraMode==='cockpit'&&!lookBack,reset);
 showcase.update(camera.position,session.current.time);
 if(raster){const renderStart=performance.now();renderer.render(scene,camera);profile.renderMs=performance.now()-renderStart;ui.update(race.snapshot(),session.current,session.input.armed,chase.activeView,persisted);renderReward();const debug=app.querySelector<HTMLElement>('#race-debug')!;debug.hidden=!debugVisible;if(debugVisible)debug.textContent=`${__BUILD_REF__} / ${preset} / ${quality}\n${renderer.info.render.calls} calls · ${renderer.info.render.triangles} submitted triangles\n${session.ticks} physics ticks · ${session.current.wheels.map(w=>w.surface).join('/')}`}}
function normalFrame(now:number,raster=true){sampled=sourceSample();ui.menuInput(sampled,race.snapshot());if(confirmBlocked){const held=sampled.pads.some(p=>p&&(p.buttons[0]?.value??0)>.5);if(!held)confirmBlocked=false;else sampled={...sampled,pads:sampled.pads.map(p=>p?{...p,buttons:p.buttons.map((b,i)=>i===0?{value:0,pressed:false}:b)}:p)}}
 lastInput=session.frame(now);if(lastInput.camera){cameraMode=nextDrivingView(cameraMode);const saved=loadSave(browserStorage());saved.settings.camera=cameraMode;writeSave(browserStorage(),saved)}lookBack=lastInput.lookBack;
 const state=race.snapshot();if(state.result&&committedAttempt!==state.attempt){committedAttempt=state.attempt;if(state.result.valid)persisted=saveBest(browserStorage(),key,state.result.timeMs).persisted}
 present(lastInput.dt,lastInput.alpha,resetPresentation||lastInput.reset,raster);resetPresentation=false;
}
function suspend(){keyboard.clear();menuEdges.clear();session.input.suspend();race.setPaused(true);audio.lifecycle(true);ui.update(race.snapshot(),session.current,false,chase.activeView,persisted)}
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['Enter','Backspace'].includes(e.code)){if(e.target instanceof Element&&e.target.closest('button,a'))return;if(!e.repeat)menuEdges.add(e.code)}if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','Backspace'].includes(e.code))e.preventDefault();keyboard.down(e.code,performance.now(),e.repeat);if(e.code==='KeyI'&&!e.repeat)debugVisible=!debugVisible});addEventListener('keyup',e=>{keyboard.up(e.code);releaseKeys.delete(e.code)});addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend()});addEventListener('gamepaddisconnected',()=>{session.input.disconnect();suspend()});
present(1/60,1,true,false);profile.mark('preparation-start',{ticks:session.ticks,race:race.snapshot()});
const preparation=await product.prepare(()=>prepareRenderer(renderer,scene,camera));
prepared=true;present(1/60,1,true,true);const loadMs=performance.now()-started;veil.remove();lastWall=undefined;profile.mark('preparation-end',{...preparation,ticks:session.ticks,race:race.snapshot()});
function animate(now:number){if(!controlled){const begin=performance.now();const d=lastWall===undefined?0:now-lastWall;lastWall=now;if(frameTimes.length<1800)frameTimes.push(d);normalFrame(now);profile.frame(now,d,performance.now()-begin,session.ticks,race.snapshot(),chase.activeView,renderer,scene)}requestAnimationFrame(animate)}requestAnimationFrame(animate);
profile.mark('load-ready',{loadMs});
const inspect=()=>({renderDepth:harborDepth(renderer),showcase:showcase.inspect(),attemptId,career:career.state,careerDurable:career.durable,rewardPending,rewardText,product:product.inspect(),memory:{...renderer.info.memory},commit:__BUILD_REF__,preset,quality,telemetry:session.current,race:race.snapshot(),camera:{mode:cameraMode,active:chase.activeView,position:camera.position.toArray(),target:chase.target.toArray(),fov:camera.fov,aspect:camera.aspect},rear:hero.rear.inspect(),asset:CURRENT_VEHICLE,driver:hero.driver.inspect(),driverProjection:Object.fromEntries(Object.entries(hero.driver.inspect().arms??{}).map(([side,a])=>[side,new THREE.Vector3().fromArray((a as any).contact).project(camera).toArray()])),audio:audio.inspect(),audioFrame,lighting:lights.inspect(),lightBudget:lights.budget,ticks:session.ticks,inputState:lastInput?{...lastInput,current:undefined,previous:undefined}:null,record:loadSave(browserStorage()).records[key]??null,persisted,renderInfo:{...renderer.info.render},frameTimes:[...frameTimes],loadMs,statistics:{...hero.statistics,world:worldStatistics},renderer:rendererIdentity});
(window as any).__HARBOR={ready:true,inspect,lightingDiagnostic:(t:VehicleTelemetry,view:DrivingView,equipped:boolean,color:'red'|'cyan',nits?:number)=>{if(!controlled)throw Error('Controlled diagnostic context required');hero.pose(t,0,view==='cockpit',true);lights.update(hero.root.position,t.brake);product.set(equipped,{...career.state.appearance,color,brightness:.6,enabled:true});product.update();if(nits!==undefined){if(nits<0||nits>1800)throw Error('Bounded diagnostic luminance');scene.traverse(o=>{if(o instanceof THREE.RectAreaLight)o.intensity=equipped?nits:0})}chase.update(hero.root.position,hero.root.quaternion,t.speed,1/60,view,false,true,obstruction);renderer.render(scene,camera);return{product:product.inspect(),lighting:lights.inspect(),camera:{position:camera.position.toArray(),target:chase.target.toArray()},exposure:renderer.toneMappingExposure}},lightweight:()=>({telemetry:session.current,race:race.snapshot(),ticks:session.ticks,attemptId}),profile:()=>({...profile.export(),loadMs,preparation,buffer:renderer.getContext().getContextAttributes(),size:renderer.getDrawingBufferSize(new THREE.Vector2()).toArray(),dpr:renderer.getPixelRatio(),renderer:rendererIdentity}),normalFrame:(now:number,raster=true)=>{if(!controlled)throw Error('Controlled test clock required');normalFrame(now,raster);return inspect()},setDeviceSample:(sample:any)=>{if(!test)throw Error('Isolated test context required');virtual=sample?{...sample,keys:new Set(sample.keys)}:undefined},startAudioCapture:()=>{if(!test)throw Error('Isolated test context required');return audio.startEvidenceCapture()},audioSync:(id:string)=>{if(!test)throw Error('Isolated test context required');return audio.evidenceMarker(id)},stopAudioCapture:()=>{if(!test)throw Error('Isolated test context required');return audio.stopEvidenceCapture()},renderOfflineAudio:(timeline:Parameters<typeof renderOfflineGameAudio>[0],duration:number)=>{if(!test)throw Error('Test context required');return renderOfflineGameAudio(timeline,duration)},referenceCamera:(position:number[],target:number[],fov=45)=>{if(!test)throw Error('Test context required');scene.fog=null;camera.position.fromArray(position);camera.fov=fov;camera.updateProjectionMatrix();camera.lookAt(new THREE.Vector3().fromArray(target));renderer.render(scene,camera)},route};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);present(0,lastInput?.alpha??1,false,true)});addEventListener('pagehide',()=>{unsubCareer();career.close();product.dispose();audio.dispose();sim.dispose();showcase.dispose();lights.dispose();outdoor.dispose();renderer.dispose()});

async function awardFinish(id:string,timeMs:number){rewardPending=true;rewardText='Saving workshop credits…';try{const r=await career.execute({type:'award',id,valid:true,timeMs,event:'harbor'});rewardText=r.receipt?`+${r.changed?r.receipt.amount:0} game credits · Balance ${r.state.credits}`:'Reward already recorded';rewardStory=r.story?RAE[r.story]:''}catch(e){rewardText='Credits could not be saved. Retry saving before leaving.'}finally{rewardPending=false;renderReward()}}
function renderReward(){
 const menu=app.querySelector<HTMLElement>('#race-menu');if(!menu)return;let box=menu.querySelector<HTMLElement>('#career-reward');if(race.snapshot().phase!=='finished'){box?.remove();return}if(!box){box=document.createElement('div');box.id='career-reward';menu.querySelector('.menu-actions')?.before(box)}
 const text=rewardText||'No credits for an invalid attempt.';if(box.dataset.value!==text+rewardStory){box.replaceChildren();const strong=document.createElement('strong');strong.textContent=text;box.append(strong);if(rewardStory){const small=document.createElement('small');small.textContent='RAE: '+rewardStory;const dismiss=document.createElement('button');dismiss.textContent='Got it';dismiss.onclick=()=>{rewardStory='';renderReward()};box.append(small,dismiss)}if(!career.durable){const small=document.createElement('small');small.textContent='Session only — progress cannot be saved';box.append(small)}if(text.startsWith('Credits could not')){const retry=document.createElement('button');retry.textContent='Retry saving credits';retry.onclick=()=>{const r=race.snapshot().result;if(attemptId&&r?.valid)void awardFinish(attemptId,r.timeMs)};box.append(retry)}box.dataset.value=text+rewardStory}
 for(const b of menu.querySelectorAll<HTMLButtonElement>('button[data-action]'))b.disabled=rewardPending;
}
