import {RaceInstruments,raceHeader,tachMarkup,displayedGear} from './signature/race-instruments';
import type {CourseRoute} from './course/environment';
import {RouteAid} from './signature/route-aid';
import {installRaceMenuFocus} from './signature/race-accessibility';
import {BuildMenuInput} from './career/menu';
import {activeProfile,sceneHref} from './demo/profile';
import type {RaceSnapshot} from './race/attempt';
import type {VehicleTelemetry} from './simulation';
import type {DeviceSample} from './driving/input';
export const raceTime=(ms:number)=>`${Math.floor(ms/60000)}:${((ms%60000)/1000).toFixed(3).padStart(6,'0')}`;
export type MenuAction='start'|'retry'|'resume'|'bay';
export class HarborUI {
 readonly root=document.createElement('div');private key='';private priorConfirm=false;private priorBack=false;
 private routeAid:RouteAid;private menuControl:BuildMenuInput;private menu:HTMLElement;private clock:HTMLElement;private progress:HTMLElement;private speed:HTMLElement;private gear:HTMLElement;private rpm:HTMLElement;private banner:HTMLElement;private instruments:RaceInstruments;
 constructor(parent:Element,readonly preset:'day'|'night',readonly action:(a:MenuAction)=>void,route?:CourseRoute){
 this.root.id='harbor-ui';this.root.innerHTML=raceHeader('ORIGINAL HARBOR',true)+'<div id="race-banner" aria-live="polite"></div><aside class="race-gauges">'+tachMarkup()+'</aside><section id="race-menu" aria-label="Time trial menu"></section><div id="race-debug" hidden></div>';this.instruments=new RaceInstruments(this.root);parent.append(this.root);installRaceMenuFocus(this.root);this.routeAid=new RouteAid(this.root,route);
 this.menu=this.root.querySelector('#race-menu')!;this.menuControl=new BuildMenuInput(this.menu,()=>this.action('bay'));this.clock=this.root.querySelector('#race-time')!;this.progress=this.root.querySelector('#race-progress')!;this.speed=this.root.querySelector('#race-speed')!;this.gear=this.root.querySelector('#race-gear')!;this.rpm=this.root.querySelector('#race-rpm')!;this.banner=this.root.querySelector('#race-banner')!;
 this.root.querySelector('#race-pause')!.addEventListener('click',()=>this.action('resume'));this.menu.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button[data-action]');if(b)this.action(b.dataset.action as MenuAction)});
 }
 update(s:RaceSnapshot,t:VehicleTelemetry,armed:boolean,view:string,persisted:boolean|null){
 this.routeAid.update(t);this.instruments.update(t);this.root.querySelector('#race-position')!.textContent=String(s.checkpoint);this.root.querySelector('#race-field')!.textContent=String(s.total);this.root.querySelector('#race-lap')!.textContent='TT';this.root.querySelector('#race-laps')!.textContent='SOLO';this.clock.textContent=raceTime(s.result?.timeMs??s.elapsedMs);this.progress.textContent=`${s.checkpoint} / ${s.total} CHECKPOINTS`;this.speed.textContent=String(Math.round(Math.abs(t.speed)*2.23694));this.gear.textContent=displayedGear(t.gear,t.powertrain);this.gear.closest('.race-gauges')!.classList.toggle('is-reverse',t.gear<0);this.rpm.textContent=String(Math.round(t.rpm));
 this.banner.textContent=s.phase==='countdown'?String(Math.ceil(s.countdown)):s.invalidReason?'Invalid lap — retry for a record':s.phase==='running'&&s.elapsedMs<1000?'GO':!armed&&s.phase==='running'&&!s.paused?'Release controls to continue':'';this.banner.classList.toggle('invalid',!!s.invalidReason);this.banner.classList.toggle('notice',!armed&&s.phase==='running'&&!s.paused);
 const key=[s.phase,s.paused,s.result?.timeMs,persisted].join('/');if(key===this.key)return;this.key=key;
 const shown=s.phase==='ready'||s.phase==='finished'||s.paused;this.menu.hidden=!shown;document.body.classList.toggle('race-menu-open',shown);document.body.classList.toggle('race-results-open',!!s.result&&!s.paused);if(!shown)return;
 let title='Ready on the grid',lead='One standing-start lap. Find your braking points and bring it back clean.',buttons='<button class="primary" data-action="start" id="start-lap">Start lap</button>';
 if(s.paused){title='Take a breath';lead='Paused. The lap clock is stopped. Release driving controls before continuing.';buttons='<button class="primary" data-action="resume" id="resume-lap">Continue</button><button data-action="retry">Restart attempt</button>'}
 else if(s.phase==='finished'&&s.result){const r=s.result;title=r.valid?'Lap complete':'Practice complete';lead=r.valid?`${r.newBest?'PERSONAL BEST':'VALID LAP'} <strong class="result-time">${raceTime(r.timeMs)}</strong>${r.firstRecord?'First record':r.previousBestMs!==null?`Previous best ${raceTime(r.previousBestMs)} · ${r.differenceMs!>=0?'+':'−'}${(Math.abs(r.differenceMs!)/1000).toFixed(3)} s`:''}${persisted===false?'<small>Storage unavailable — record kept for this session only.</small>':''}`:`Invalid lap — ${r.invalidReason}. <strong class="result-time">${raceTime(r.timeMs)}</strong>Retry for a record.`;buttons='<button class="primary" data-action="retry" id="retry-lap">Race Again</button>'}
 this.menu.dataset.phase=s.result?'result':s.paused?'pause':'ready';document.body.classList.toggle('race-results-open',!!s.result&&!s.paused);this.menu.innerHTML=`<span class="race-label">${activeProfile()==='demo'?'DEVELOPMENT PREVIEW / DEMO · ':'HARBOR SHAKEDOWN · '}${this.preset.toUpperCase()}</span><span class="result-numeral" aria-hidden="true">${s.result?.valid?'TT':'—'}</span><h1>${title}</h1><p>${lead}</p><div class="menu-actions">${buttons}<button data-action="bay">Back to Showroom</button><a class="shop-build-route" href="?scene=signature&amp;screen=events">Change Event</a>${s.phase==='finished'?`<a class="shop-build-route" href="${sceneHref('bay','&shop=build')}">Shop This Build</a>`:''}</div>${s.phase!=='finished'?'<details '+(activeProfile()==='demo'?'open':'')+'><summary>Driving controls & lap rules</summary><p>W/S or arrows throttle/brake · A/D steer · C camera · hold B rearward · X reverse / drive · hold R restart · Esc pause.<br>Controller: RT/LT pedals, left stick, top face camera, LB rearward, bottom face hold restart, right face reverse / drive, Menu pause.</p><p><strong>Reverse:</strong> Brake to stop. Release pedals, then press S / LT again to reverse. W / RT brakes reverse; release and press again for forward. Holding the brake never selects reverse. X / right face selects direction directly.</p><p>Visit each checkpoint in order. More than 0.35 s with two tires beyond runoff invalidates the record. Reset starts a fresh attempt. Dry grip is identical day and night.</p></details>':''}<small>Enter / bottom face: ${s.phase==='finished'?'retry':s.paused?'continue':'start'} · Backspace / right face: bay</small>`;
 }
 menuInput(sample:DeviceSample,s:RaceSnapshot){if(!(s.phase==='ready'||s.phase==='finished'||s.paused)){this.menuControl.reset();return}this.menuControl.frame(sample);const active=document.activeElement,interactive=active instanceof Element&&active.closest('button,a,input,select,summary');if(sample.focused&&!interactive&&sample.pressedKeys?.has('Enter'))this.action(s.paused?'resume':s.phase==='finished'?'retry':'start');if(sample.focused&&sample.pressedKeys?.has('Backspace'))this.action('bay')}
}
