import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const base=process.env.BASE_URL||'http://127.0.0.1:5188',out=path.resolve(process.env.OUT||`director-kit/production/evidence/P07A/hardening-${new Date().toISOString().replaceAll(':','-')}`);
await fs.mkdir(out,{recursive:false});
const candidate=JSON.parse(await fs.readFile('demo-current.json','utf8'));
const toolSHA256=createHash('sha256').update(await fs.readFile(new URL(import.meta.url))).digest('hex');
const selected=(process.env.CASES||'').split(',').filter(Boolean);const contexts=new Set();
const report={candidate,base,toolSHA256,browserArgs:['--use-angle=d3d11'],selected,startedAt:new Date().toISOString(),method:'Isolated headless Chromium against the exact local static demo output. Native links/keys except declared failure injection, graphics extension and inspection hooks. Not performance scoring.',cases:[],complete:false};
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});
async function run(name,work){if(selected.length&&!selected.some(part=>name.includes(part)))return;const entry={name,startedAt:new Date().toISOString(),pass:false};report.cases.push(entry);try{Object.assign(entry,await work());entry.pass=true;console.log('PASS',name)}catch(error){entry.error=String(error?.stack||error);console.log('FAIL',name,entry.error)}finally{for(const c of contexts)await c.close().catch(()=>{});contexts.clear();entry.finishedAt=new Date().toISOString();await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2))}}
async function context(options={}){const c=await browser.newContext({viewport:{width:1280,height:720},...options});contexts.add(c);await c.addInitScript(()=>{window.__documentIdentity=crypto.randomUUID();window.__pageShows=[];addEventListener('pageshow',event=>window.__pageShows.push({persisted:event.persisted,at:performance.now()}))});return c}
async function ready(page,scene='bay'){await page.waitForFunction(scene=>scene==='bay'?!!document.querySelector('#chapter-panel'):!!document.querySelector('#race-menu'),scene,{timeout:120000});await page.waitForFunction(()=>!document.querySelector('.preview-loading-exit'),null,{timeout:120000})}
async function recovery(page){await page.waitForSelector('.preview-recovery',{timeout:120000});const facts=await page.evaluate(()=>({text:document.querySelector('.preview-recovery').innerText,appInert:document.querySelector('#app').inert,modal:document.querySelector('.preview-recovery').getAttribute('aria-modal'),focus:document.activeElement?.id,canvasCount:document.querySelectorAll('canvas').length}));assert.equal(facts.appInert,true);assert.equal(facts.modal,'true');assert.equal(facts.focus,'retry-loading');const focus=[];for(let i=0;i<6;i++){await page.keyboard.press('Tab');focus.push(await page.evaluate(()=>({text:document.activeElement?.textContent,inDialog:!!document.activeElement?.closest('.preview-recovery')})))}assert.ok(focus.every(x=>x.inDialog));assert.doesNotMatch(facts.text,/C:\\|OneDrive|file:\/\/|stack/i);return{...facts,tabCycle:focus}}
try{
 await run('ordinary entry and historical selector rejection',async()=>{const c=await context(),page=await c.newPage(),requests=[];page.on('request',request=>requests.push(new URL(request.url()).pathname));await page.goto(base);await page.waitForSelector('#demo-race');const entry=await page.evaluate(()=>({title:document.querySelector('h1').innerText,links:[...document.querySelectorAll('.preview-actions a')].map(a=>({text:a.textContent,href:a.getAttribute('href')})),controls:document.querySelector('.preview-controls').innerText,globals:[typeof window.__TWT,typeof window.__CREW,typeof window.__HARBOR]}));assert.equal(entry.links.length,4);assert.ok(entry.controls.includes('Hold one second to restart'));assert.deepEqual(entry.globals,['undefined','undefined','undefined']);assert.ok(!requests.some(x=>/\.glb$|\.hdr$/.test(x)));await page.goto(base+'/?scene=vehicle&asset=p01&diagnostic=shape&neutral=1&play=demo');await page.waitForSelector('#demo-race');assert.equal(new URL(page.url()).search,'?play=demo');await c.close();return{entry,requests,historicalRejected:true}});
 for(const scenario of [
  {name:'missing current vehicle',asset:'/assets/vehicles/slingshot-p04a1.glb',scene:'bay'},
  {name:'missing required branding model',asset:'/assets/brand/slingmods-sign.glb',scene:'bay'},
  {name:'missing required daylight HDR',asset:'/assets/showcase-quality/sky/day-puresky-2k.hdr',scene:'harbor'},
  {name:'missing shared runtime JavaScript with embedded physics WASM',pattern:/\/assets\/game-audio-[^/]+\.js$/,scene:'crew'},
  {name:'missing lazy crew JavaScript',pattern:/\/assets\/crew-[^/]+\.js$/,scene:'crew'},
 ])await run(scenario.name,async()=>{const c=await context(),page=await c.newPage();let blocked=null;const matcher=url=>scenario.asset?new URL(url).pathname===scenario.asset:scenario.pattern.test(new URL(url).pathname);const handler=route=>{blocked=route.request().url();return route.fulfill({status:404,contentType:'text/plain',body:'Injected required-asset failure'})};await c.route(matcher,handler);await page.goto(base+`/?scene=${scenario.scene}&play=demo`);const failure=await recovery(page);assert.ok(blocked,'Targeted required dependency must actually be requested');await page.screenshot({path:path.join(out,scenario.name.replaceAll(' ','-')+'.jpg'),type:'jpeg',quality:83});await c.unroute(matcher,handler);await page.getByRole('button',{name:'Retry page',exact:true}).click();await ready(page,scenario.scene);const retry={url:page.url(),canvases:await page.locator('canvas').count(),dialogGone:await page.locator('.preview-recovery').count()===0};assert.equal(retry.canvases,1);assert.equal(retry.dialogGone,true);await c.close();return{injected404:blocked,failure,retry}});
 await run('slow required dependency has a visible ordinary exit',async()=>{const c=await context(),page=await c.newPage();let held;await c.route('**/assets/vehicles/slingshot-p04a1.glb',route=>new Promise(resolve=>{held={route,resolve}}));await page.goto(base+'/?scene=bay&play=demo',{waitUntil:'commit'});await page.waitForSelector('.preview-loading-exit');const exit=page.locator('.preview-loading-exit');assert.equal(await exit.isVisible(),true);await exit.click();await page.waitForSelector('#demo-race');if(held){await held.route.abort().catch(()=>{});held.resolve()}await c.close();return{exitVisible:true,returnedToEntry:true,method:'Required model request held until normal exit navigation, then request aborted; no replacement asset'}});
 await run('WebGL disabled with browser launch flag',async()=>{const disabled=await chromium.launch({headless:true,args:['--disable-webgl']}),c=await disabled.newContext(),page=await c.newPage();try{await page.goto(base+'/?scene=bay&play=demo');const facts=await recovery(page);assert.match(facts.text,/WebGL 2 is unavailable/);assert.equal(await page.evaluate(()=>document.createElement('canvas').getContext('webgl2')===null),true);return{launchFlag:'--disable-webgl',facts}}finally{await c.close();await disabled.close()}});
 await run('actual context loss pauses race audio and contains recovery focus',async()=>{const c=await context(),page=await c.newPage();await page.goto(base+'/?scene=crew&play=demo&test=1&profile=1');await page.waitForFunction(()=>window.__CREW?.ready,null,{timeout:120000});await page.locator('#enable-sound').click();await page.waitForFunction(()=>window.__CREW.inspect().audio.enabled);await page.locator('#start-crew').click();await page.waitForTimeout(500);await page.locator('#start-crew').click();await page.waitForFunction(()=>window.__CREW.inspect().race.phase==='running',null,{timeout:20000});await page.keyboard.down('KeyW');await page.waitForTimeout(450);const before=await page.evaluate(()=>window.__CREW.inspect());const lost=await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2'),extension=gl.getExtension('WEBGL_lose_context');if(!extension)return false;extension.loseContext();return true});assert.equal(lost,true);const panel=await recovery(page);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>window.__CREW.inspect());await page.waitForTimeout(350);const later=await page.evaluate(()=>window.__CREW.inspect());assert.equal(after.race.paused,true);assert.equal(after.audio.life.paused,true);assert.equal(after.ticks,later.ticks);await page.screenshot({path:path.join(out,'context-loss-recovery.jpg'),type:'jpeg',quality:83});await page.locator('#retry-loading').click();await page.waitForFunction(()=>window.__CREW?.ready,null,{timeout:120000});const reloaded=await page.evaluate(()=>({state:window.__CREW.inspect(),canvasCount:document.querySelectorAll('canvas').length,audioUIs:document.querySelectorAll('#game-audio').length}));assert.equal(reloaded.canvasCount,1);assert.equal(reloaded.audioUIs,1);assert.equal(reloaded.state.race.phase,'ready');assert.equal(reloaded.state.audio.enabled,false);await c.close();return{injection:'WEBGL_lose_context.loseContext() on actual renderer',renderer:before.renderer,before:{ticks:before.ticks,race:before.race,audio:before.audio.life,input:before.inputState},after:{ticks:after.ticks,race:after.race,audio:after.audio.life},laterTicks:later.ticks,panel,reloaded:{ticks:reloaded.state.ticks,phase:reloaded.state.race.phase,canvasCount:reloaded.canvasCount,audioUIs:reloaded.audioUIs,audioEnabled:reloaded.state.audio.enabled},limit:'Inspection retains the previous completed frame inputState; suspension is evidenced by stopped ticks, paused race/audio, and a fresh neutral page on retry.'}});
 await run('native back navigation and persisted-page restoration create one fresh scene',async()=>{const c=await context(),page=await c.newPage();await page.goto(base);await page.locator('#demo-garage').click();await ready(page);const before=await page.evaluate(()=>({id:window.__documentIdentity,events:window.__pageShows,canvases:document.querySelectorAll('canvas').length}));await page.locator('.preview-return').click();await page.waitForSelector('#demo-race');await page.goBack();await ready(page);const nativeBack=await page.evaluate(()=>({id:window.__documentIdentity,events:window.__pageShows,canvases:document.querySelectorAll('canvas').length}));assert.equal(nativeBack.canvases,1);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForFunction(id=>window.__documentIdentity!==id,nativeBack.id,{timeout:20000});await ready(page);const restored=await page.evaluate(()=>({id:window.__documentIdentity,canvases:document.querySelectorAll('canvas').length,loadingExits:document.querySelectorAll('.preview-loading-exit').length}));assert.equal(restored.canvases,1);assert.equal(restored.loadingExits,0);await c.close();return{before,nativeBack,simulatedPersistedEvent:restored,limit:'Native back records actual browser pageshow events. The persisted=true branch is separately dispatched to prove full reload; this is not a claim that native BFCache was used.'}});
 report.complete=report.cases.every(x=>x.pass);report.finishedAt=new Date().toISOString();await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,pass:report.cases.filter(x=>x.pass).length,total:report.cases.length,complete:report.complete}));if(!report.complete)process.exitCode=1;
}finally{await browser.close()}
